### ISSUE TITLE
Acillary/temp parrot files errors in source taball in OSX

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1002]
When unpacking the source tarball generated by autobuild in cclmac00, I get:

tar: copyfile unpack (cctools-e42bca65-source/parrot/test/fixtures/a/b/c/_acl) failed: No such file or directory
tar: copyfile unpack (cctools-e42bca65-source/parrot/test/fixtures/a/b/_acl) failed: No such file or directory
tar: copyfile unpack (cctools-e42bca65-source/parrot/test/fixtures/a/_acl) failed: No such file or directory
tar: copyfile unpack (cctools-e42bca65-source/parrot/test/fixtures/_acl) failed: No such file or directory

**Comment by batrick** [comment]
@nhazekam I'm gifting this to you.

**Comment by btovar** [comment]
@nhazekam, taking this from you.

**Comment by btovar** [comment]
@batrick: Are we using the .__acl for anything in the parrot tests? They cause conflicts when unpacking the tar in OSX, unless the user says:

COPYFILE_DISABLE=true tar zxpf cctools-e51ad7ff-source.tar.gz

The error messages themselves are harmless, but I rather remove the .__acl if they are not necessary.

**Comment by batrick** [comment]
It is used by the parrot chirp search test. I think the .__acl files can be removed if a default acl is used in the chirp server.

**Comment by btovar** [comment]
The acl's in question are pretty generic: unix: lrw. 

Thanks Patrick, I'll check the chirp tests.
