### ISSUE TITLE
makeflow should not access struct work_queue directly

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1005]
The most glaring example is q->fast_abort. WQ's API function does some checking and prints a debug message, which does not happen when using fast abort with work queue. Ideally, makeflow should not access WQ structures directly.

(@nhazekam: we talked about this one before, I am just making an official record.)

**Comment by btovar** [comment]
@nhazekam: I believe this one is fixed, right?

**Comment by nhazekam** [comment]
@btovar Yes, this is fixed. fast_abort is now set through batch_queue_set_option.
