### ISSUE TITLE
"exit" and "release" have the same meaning at worker

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1009]
I would like to keep "release" with the current meaning: worker simply disconnect from master, and turn "exit" into terminating the worker.

From the master, shut down workers when queue exits should use exit, as "release" is implied.

(Funny story: I incorrectly set worker's timeout to 30 hours. condor_rm sent all my jobs to X state, and I had no way to kill the workers.)

@dthain, @nhazekam

**Comment by dthain** [comment]
Ok here
