### ISSUE TITLE
Option to disable following chdir in the resource monitor

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1017]
@matz-e case: Some forked processes chdir to /cvmfs, which does not give an useful measurement ot the task usage.

I would like to add an option to the monitor to specifically ask to follow chdirs, or to specifically track directories given at the command line.

**Comment by dthain** [comment]
I think the way to go here is for the resource monitor to track the name of a directory given on the command line.  Whoever is invoking the command has some idea of the zone that they want tracked...
