### ISSUE TITLE
makeflow does not compile on RedHat 7

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1024]
makeflow_log.c:296:26: error: comparison between 'makeflow_clean_depth' and 'enum <anonymous>' [-Werror=e│num-compare]
   int silent = clean_mode != MAKEFLOW_GC_NONE;

**Comment by btovar** [comment]
All all the centos.

**Comment by nhazekam** [comment]
I will be right on this. Overlooked those errors.

**Comment by nhazekam** [comment]
Fixed in #1025
