### ISSUE TITLE
Support for file:// and data:// URL schemas

### ISSUE THREAD

**Issue by Baguage** [cooperative-computing-lab/cctools#1035]
This is low priority request obviously, but is it possible to add support for file:// and data:// (https://tools.ietf.org/html/rfc2397) URL schemas? This may be useful for generating umbrella specifications programmatically among other things.

**Comment by Baguage** [comment]
This related to Umbrella tool

**Comment by hmeng-19** [comment]
@Baguage , that is an interesting idea.
As we discussed, currently, I would first add support for local files `file:///tmp/output/f1` into umbrella specs. When you have an example of dataURL, I would be happy to give it a try.

**Comment by Baguage** [comment]
Here is an example of data url that encodes "Umbrella" string:
data:text/plain;charset=utf-8;base64,VW1icmVsbGE=
