### ISSUE TITLE
Makeflow should communicate the task categories to work queue

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1042]
See #1041.

@nhazekam, suggestions, glaring should nots?

**Comment by nhazekam** [comment]
It looks good to me. I think will be great for using fast abort more as we can now have the abort specific categories of tasks. Helpful when you have only a couple long running compared to a chunk of short running.

I know you are still thinking about the Makeflow integration, but do you plan on still accepting it as a command line option/environment variable or do you plan on pushing more for it to be done in labeling?

**Comment by btovar** [comment]
As option/environment that is communicated to work queue.

**Comment by nhazekam** [comment]
That sounds good. Do we care that category would now have a different definition between Makeflow and WQ, aka a category in Makeflow also contains cores/memory/etc but in WQ it just a class of tasks, the fast abort multiplier, and some stats?

**Comment by btovar** [comment]
Ah no, that's the idea. I need to add cores/memory/disk etc to the categories in work queue.

**Comment by nhazekam** [comment]
OK, awesome. That makes sense to me as well. I know this is getting farther into the weeds but would you allow the user to still specify cores/memory/disk in the task or move entirely to categories even if it was relatively generic?

**Comment by btovar** [comment]
Both, using category as the fallback. Also, we would add a mode in which you specify the size of the largest worker (per resource), and then we automatically compute the sizes of the tasks, based on history, our first allocation algorithm, etc.

**Comment by nhazekam** [comment]
Great, well this looks like the right base level for categories to be built up with, especially since wq_stat has a lot of info we can add a use with it.

**Comment by btovar** [comment]
Solved in #1141
