### ISSUE TITLE
Duplicate output name error at worker

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1049]
Situation:

1) Task 1 and 2 both have as output fileA. (issue 1, this breaks semantics of wq)
2) Both tasks fall in the same worker, and complete successfully.
3) Say task 1 finish first, then task 2 overwrites fileA.  (issue 2, silent overwrite)
4) When master gets the results, fileA is returned for task 1, and task 2 fails, as fileA is deleted in the meanwhile (issue 3, output was correctly generated, but removed when task 1 is cleaned up)

All issues are avoided if work_queue_task_specify_file checks whether two tasks have the same output. I propose to make this a fatal error.

(BTW, this is why I was getting the problems with errno and rename.)

@dthain, @nhazekam

**Comment by nhazekam** [comment]
Sounds plausible, but are we worried about how much added work it is to check the filenames? Would we want to have a table of filenames?

Also, following a task finishing would we allow filenames in that task to be used again?

**Comment by btovar** [comment]
There will be some overhead, but we already check for repeated remote names, thus the O() would not change.

Also, the check would be for "active" tasks. Once a task is returned to the user, it is removed from the work queue tables. This means that once a task is returned, that output name is available again.

**Comment by dthain** [comment]
Folks, I'm going to veto this feature request.

While I understand that the situation can come about, it seems to me that the problem is not limited to WQ (you have it in every kind of concurrent system) and its adding to our ever growing list of cross-functional constraints.  The cost-benefit just isn't there...
