### ISSUE TITLE
umbrella support for local resources file:/// 

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#1050]
Problem:
Currently, the data dependencies of Umbrella may come from http, https, git, or cvmfs. However, in some cases, the user may want to test the data or software from his local file system. 

Solution:
Add support for local resources in the format of `file:///...`, such as `file:///data/file1` or `file:///software/povray`.

**Comment by hmeng-19** [comment]
@Baguage , here is the issue. Let me know if more information is needed.

**Comment by Baguage** [comment]
As discussed with @hmeng-19 , we will update url_download and replace wget program call with urllib2 (standard python library). urllib2 does support file://, ftp://, http:// and https:// out of the shelf, and  custom protocol handlers can be added too. @cwilli34 will send a pull request for review when we are ready.

**Comment by hmeng-19** [comment]
Fixed by #1064
