### ISSUE TITLE
cores as a float

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1051]
Right now we keep cores as an integer. I would like to change it to a double, so that the following makes more sense:

cores = cpu_time/wall_time

Right now the resource monitor does:

cores = ceil(cpu_time/wall_time)     // with the appropriate double casts.

Does anybody see any drawback?

**Comment by dthain** [comment]
No complaints here.

Although we did have an odd problem in AWE this summer, related to floats/cores.
What happened is that the task was producing a resource report in which cores had
a float type, but an integral value.  The code for parsing the resource reports in the
master examined the type of each *value* before examining the name.

The result was that when cores had the literal value of "1", the resource monitor
flagged that as "unknown field" b/c "cores" was not in the integer section.

Something to take a look at...

**Comment by btovar** [comment]
Not needed anymore.
