### ISSUE TITLE
no-worker-for-task policy

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1052]
If a task cannot be dispatched given its resource requirements (i.e., there is not a worker big enough connected to the master), what should we do?

We need to communicate with the user somehow. We cannot cancel the task right away, as a worker may be in the process of connecting. I propose to have calls such as:

work_queue_cancel_task_on_memory(q, N);
in which tasks which use N memory or more, are cancelled.

Also:
r = work_queue_missing_resources(q);
in which r is a summary struct with the maximum resources missing. If no resource is missing, r is NULL.

@dthain, @nhazekam

**Comment by nhazekam** [comment]
In what circumstances would you foresee the user adding work_queue_cancel_task_on_memory?

I can definitely see work_queue_missing_resources being useful for a user to figure out why they are making progress and need more resources. Is that what you had in mind?

**Comment by btovar** [comment]
Imagine work_queue_missing_resource returns a resource size that your pool cannot fulfill. You would like that task cancelled. This could happen if tasks are automatically labeled (say labels come from an archive, but those labels where found in a pool of workers that you do not have).

**Comment by nhazekam** [comment]
Cool, though in that case I agree with your above statement that we need to communicate whats happening to the users, so in cases of task cancellation they are aware it was removed.

**Comment by btovar** [comment]
See #2771
