### ISSUE TITLE
Umbrella passes UnboundLocalError after run

### ISSUE THREAD

**Issue by cwilli34** [cooperative-computing-lab/cctools#1053]
Following error occurs on line 773  /cctools/bin/umbrella:

`UnboundLocalError: local variable 'host_linux_distro' referenced before assignment`

Adding `host_linux_distro = None` before the if statement takes care of this error.

**Comment by hmeng-19** [comment]
@cwilli34 , thanks for pointing out the mistake.

BTW, I think we are working on two different versions of umbrella,  here are the content from line 754 - line 765 from the master branch of https://github.com/cooperative-computing-lab/cctools/blob/master/umbrella/src/umbrella.py.  

    if arch_index != -1:
        host_linux_distro = 'arch'
    else:
        redhat_index = uname_list[2].find('el')
        centos_index = uname_list[2].find('centos')
        if redhat_index != -1:
            dist_version = uname_list[2][redhat_index + 2]
            if centos_index != -1 or dist_list[0].lower() == 'centos':
                host_linux_distro = 'centos' + dist_version
            else:
                host_linux_distro = 'redhat' + dist_version
    logging.debug("The OS distribution information of the local machine: %s", host_linux_distro)

Is this where you are talking about?

**Comment by cwilli34** [comment]
Yes, this is where I was talking about.  My version is only different because I also added changes tot he url_download method.

**Comment by hmeng-19** [comment]
Cool. Glad to know we are on the same page. 
Do you want me to make a tiny pull request to fix the problem first? or you already fix it in your branch?

**Comment by cwilli34** [comment]
I think we have it fixed in ours and will probably be delivering a pull request soon.  Thank you though!

**Comment by hmeng-19** [comment]
Fixed by #1064
