### ISSUE TITLE
Umbrella - Checksum validation - case sensitive

### ISSUE THREAD

**Issue by Baguage** [cooperative-computing-lab/cctools#1054]
Ran into this problem when creating a new umbrella spec
Used online service to compute MD5 checksum and got 76A94fff405EA493D04C5C3CD97B6409
Umbrella did not like that, because although checksum was correct it expected it in lower case: 76a94fff405ea493d04c5c3cd97b6409. I believe it should not be case sensitive and should accept AAAA, aaaa, AAaa and so on.

**Comment by hmeng-19** [comment]
@Baguage , you are right. I plan to make a tiny pull request to fix this problem. Is that okay for you? Or you already fixed it in your branch?

**Comment by Baguage** [comment]
not yet, I wanted to get your approval first

**Comment by hmeng-19** [comment]
Go ahead. I have no problem with it. Thanks.

**Comment by hmeng-19** [comment]
Fixed by #1157 .
