### ISSUE TITLE
Parrot should implement `getgroups` and `setgroups` for `--fake-setuid`

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#1063]
This is necessary to resolve #981.

Just to summarize some implementation details:

* If Linux returns the primary group id with the supplemental group ids, we should too.
* Just use a statically sized array of `gid_t` in the pfs_process struct, no dynamic list.

**Comment by tommasoboccali** [comment]
thanks! no big hurry, in the other way (condor outside parrot) it works ;)

tom

**Comment by batrick** [comment]
Fixed by #1067.
