### ISSUE TITLE
Feature Request:  Minimum slot size in Work Queue Factory

### ISSUE THREAD

**Issue by klannon** [cooperative-computing-lab/cctools#1083]
In the mode of using Work Queue Factory where it tries to grab the biggest possible slots, it would be great if you could specify a minimum slot size to keep the factory from making workers that are too small to serve any of your tasks.

**Comment by dthain** [comment]
Now that I look more closely, I see that `condor_submit_workers` has the `--autosize` option, but
`work_queue_factory` does not.  So that's part of the missing piece.

**Comment by btovar** [comment]
It is more than that. I've just modified condor_submit_workers so that it takes a minimum too, something like:
cores="ifThenElse($cores > TotalSlotCpus, $cores, TotalSlotCpus)"
