### ISSUE TITLE
Some environment variables override CLI switches in Parrot

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#1092]
Some environment variables would overwrite the CLI switches.
    
This was privately reported by Rodney Walker. The alien cache was being initialized to "" after the command switches causing the switch to do nothing. Only the PARROT_CVMFS_ALIEN_CACHE environment variable worked.
    
Introduced by 1b64779f7a0cbd6c2db6d70254de0c6beaa9970a.

**Comment by dthain** [comment]
FYI, very early versions of parrot tried to make an environment variable to correspond to every command line switch. 

In retrospect, I'm not sure this is a good idea, except in cases where the environment variable is a well known sort of thing across tools (like HTTP PROXY)

Is it still necessary to support this?

**Comment by batrick** [comment]
I think a lot of people are relying on it so yes I think we need to support at least the current ones.
