### ISSUE TITLE
Makeflow: Large DAGs Load Slowly on Lustre

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1094]
(Nick, I know you are already working on this, just making a record of it.)

Per our discussion today, add a switch to makeflow that skips the initial stat of files when the user gives a `--skip-file-check` argument (or something to that effect.)

Then part: Set an alarm in the consistency checking code, so that if it takes more than a reasonable amount of time (say, 15 seconds) print an informational message and suggest the use of the option.

Also @btovar

**Comment by btovar** [comment]
CJ reported that #1095 works for him.
