### ISSUE TITLE
Ability to drain a Work Queue Factory

### ISSUE THREAD

**Issue by klannon** [cooperative-computing-lab/cctools#1099]
I'm not sure if this is even a sensible request, but it would be really nice if you could "drain" a work queue factory--in other words, tell a factory that it should reduce the number of connected workers, but only by removing workers after they complete their current tasks.

**Comment by dthain** [comment]
That is a great idea!

**Comment by klannon** [comment]
You can probably even guess why it occurred to me.  :)

**Comment by dthain** [comment]
@charleszheng44 please add a new capability to `work_queue_factory` so that if `drain:true` is set in the configuration file, then workers are allowed to exit, but are not actively removed.  Put that together with `max-workers:0` and you get a system that will shut itself down slowly without killing jobs...

**Comment by charleszheng44** [comment]
Did you mean that in order to slowly decreased the number of workers, we keep decrease the value of max-workers to 0?

**Comment by btovar** [comment]
Look at work_queue_shut_down_workers(q, n);
It releases at most n workers, but it does not release a worker if it is running a task.

Call work_queue_shut_down_workers in(q, n); in work_queue_factory when drain is true, and max-workers is smaller than the current active workers.

**Comment by dthain** [comment]
Er, Ben, I think you are confused: `work_queue_shutdown_workers` is at the master program, not in the factory.

**Comment by btovar** [comment]
Ah, indeed. 

The behavior that you describe is already there, without the need of drain: true. Simply set max_workers and min_workers to 0, workers are not regenerated, and the idle out as the master sends less work.

However, if you do not like the waiting for the idling out, then I do not see how we can do this from work_queue_factory alone.

**Comment by klannon** [comment]
This is not quite what I had in mind.  Currently, I have let's say 2k 
workers in a factory.  I'm told by the university that I'm breaking the 
internet and I need to scale back.  So, I'd like to go to 1k workers 
with the least amount of wasted work, but as quickly as possible.  
Currently, it seems that if I set max workers to 1k, the factory doesn't 
launch any new jobs, but the workers only seem to be removed by 
eviction.  To have them terminate faster, but still not lose any work, 
it would be nice if the factory could tell them, "please disconnect 
after you finish your next task."  (And of course, only tell this to 
enough workers that I go from 2k running to 1k running.  Note, for me, 
it would be fine if it got close to 1k but not quite--i.e. when it's 
removing workers, if it accidentally remove a few too many, I wouldn't 
be upset.)  So, the master keeps sending work, but we shrink the pool of 
running workers managed by the factory.

**Comment by charleszheng44** [comment]
It sounds like that you want the WorkQueue to gradually decrease the size of the worker pool instead of immediately evict running workers after the value of max_workers is reset.

**Comment by klannon** [comment]
Yes, but without ever interrupting a running task in progress.

**Comment by dthain** [comment]
@klannon, I'm sorry, but I accidentally deleted your long comment via my fat fingers.

**Comment by klannon** [comment]
Here's what I'd previously wrote:
>This is not quite what I had in mind.  Currently, I have let's say 2k workers in a factory.  I'm told by the university that I'm breaking the internet and I need to scale back.  So, I'd like to go to 1k workers with the least amount of wasted work, but as quickly as possible.  Currently, it seems that if I set max workers to 1k, the factory doesn't launch any new jobs, but the workers only seem to be removed by eviction.  To have them terminate faster, but still not lose any work, it would be nice if the factory could tell them, "please disconnect after you finish your next task."  (And of course, only tell this to enough workers that I go from 2k running to 1k running.  Note, for me, it would be fine if it got close to 1k but not quite--i.e. when it's removing workers, if it accidentally remove a few too many, I wouldn't be upset.)  So, the master keeps sending work, but we shrink the pool of running workers managed by the factory. 

If your goal was to get me to write shorter comments, I've foiled you this time...

**Comment by btovar** [comment]
The factory currently does not know which workers are running tasks, and does not communicate with the master. Also, the master does not read from the catalog, thus we would have to make some changes in several parts. 

We can shorten the idle-out-time of workers by implement this with lobster:

1) First, set the number of desired workers in the conf. file of the factory.
2) while main loop in lobster:

s = q.stats
desired_workers = n
current_workers =  s.total_workers_connected
delta_workers = desired_workers - current_workers
q.shutdown_workers(delta_workers)

This will not shutdown more than delta_workers, and it will only shutdown workers without a task.

However, if all the workers are busy, this will not have any impact. I am still thinking on how to give you a general solution as clean as possible.

**Comment by klannon** [comment]
So, maybe this is the difference between a "pool" and a "factory."  It seems like the missing link is that once the factory makes the workers, the connection between workers and their factory is lost (or at least not very strong).  If I'm understanding correctly, in the current design, management of created workers is really left up to the master.

I think where I see this falling into trouble is that factories tend to be associated with specific resources (e.g. where you run the factory) and there are times when you might want to manage the workers on a per resource basis (e.g. gracefully shutting down workers specifically running on a particular resource).  In this case, it would be nice if the factory still had enough of a connection with its workers to be able to manage them a little bit (e.g. instruct them to stop taking new work and shutdown once their current task has finished).

Of course, I have no idea how easy it would be actually to implement that...

**Comment by btovar** [comment]
@klannon: You are correct. The situation here is that by design, the worker only talks to the master, and the master and the factory do not talk to each other.

@dthain: Here is an idea:

1) Add label to a worker to indicate from which pool it came from. This would be simply a string given as a command line argument. The master also knows from which pool a worker came (a new message in the protocol).

2) The factory writes to the catalog to indicate if draining is needed, and in what proportion.

3) Using a long time out, masters read from the catalog, and select workers to drain in the proportion specified by the pool.

**Comment by dthain** [comment]
That's the simplest idea I have heard so far.

And I like it b/c it doesn't involve creating a new communication channel between the factory and the workers.

Let's chew on it some more before writing code.

**Comment by dthain** [comment]
After chewing on this (for two years!) I have a better and simpler idea.

1 - Modify the work_queue_worker to trap the SIGTERM signal, and in that case, allow current tasks to end, and then exit.
2 - Modify the batch_job interface to have a "gentle remove" method, which uses `condor_vacate_job` instead of `condor_rm` in the HTCondor implementation.  This will cause the worker to receive SIGTERM and have a brief interval of time before SIGKILL.
3 - Modify the the work_queue_factory to use "gentle remove" instead of "hard remove" when downsizing.

**Comment by btovar** [comment]
Completed in #2912

**Comment by btovar** [comment]
Some older issues have also been kind of completed, but in taskvine, not wq.
