### ISSUE TITLE
work_queue_factory and arbitrary condor requirements

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1103]
In condor_submit_workers we have '-r', that allows a user to specify arbitrary condor requirements. We want the option --condor-requirements='...'  in work_queue_factory to have the same functionality.

@charleszheng44: Please add --condor-requirements to work_queue_factory. You want to communicate the requirements via batch_set_option, and modify batch_submit_condor_job in batch_job_condor.c accordingly.

Also, make condor-requirements an option in the factory configuration file.

**Comment by charleszheng44** [comment]
I am working on it.
