### ISSUE TITLE
jx.h is not installed, needed by work_queue.h

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#1111]
`work_queue.h` includes `rmsummary.h` which includes `jx.h`. @charleszheng44 found this while trying to build the work queue example.

**Comment by dthain** [comment]
Good thing for @charleszheng44 to work on.

This points to a flaw in our testing scheme -- we run tests on the built code, rather than on an installed copy, so we miss problems with installation.

**Comment by batrick** [comment]
Resolved in #1113.
