### ISSUE TITLE
Makeflow should have an example workflow for shipping local executables

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#1149]
We should expand on `makeflow/example/example.categories.makeflow` to also package up the submission site's `convert` and `curl` (`curl` is also necessary for `-T chirp`). Then, each rule should add dependencies for these executables. This is something we tell our users to do so we need to set a good example.

This issue came from discussion in #1146 and #1147.

**Comment by dthain** [comment]
Good to have an example like this.

I suspect few people see the examples in makeflow/examples, but would be more likely to see it if it is discussed clearly in the manual.

**Comment by dthain** [comment]
After playing around with this, I have come to the conclusion that `convert` is not a great tool to use in our default example workflow.  It has many sub-components installed all over the filesystem and so cannot be easily deployed to remote machines.

A really good example would use `starch` to create a portable executable and then send it along.

**Comment by dthain** [comment]
Added to makeflow examples.
