### ISSUE TITLE
`string_wrap_command` concatenates commands by default

### ISSUE THREAD

**Issue by trshaffer** [cooperative-computing-lab/cctools#1164]
When applying wrappers in Makeflow, this behavior allows commands to trivially (and likely accidentally) step out of the wrapper by using a semicolon and a second command. Code for quoting and escaping is already present, however it seems that command quoting and escaping is only performed when substituting `[]`, otherwise commands are simply concatenated. I doubt this is what users would expect when using the wrapper functionality. Is there a compatibility issue, or are some users known to *depend on* wrappers working by concatenation? If not, I would prefer `string_wrap_command` to quote and escape commands by default.

**Comment by dthain** [comment]
The wrapper concept is a relatively new development for which we don't have a lot of users yet.
(I would like to see it used more once the wrinkles are figured out.)

At this point, I think you should change it to get the more consistent behavior, and not worry too much about how it is already used.

**Comment by batrick** [comment]
The original intent of wrappers was to make simple transformations on the command, perhaps prefixing some environment variables:

`makeflow --wrapper='export FOO=1; {}'`

I use this regularly in Makeflow+Chirp to save stdout and stderr:

`makeflow --wrapper=$'{\n{}\n} > stdout.%% 2> stderr.%%' --wrapper-output='stdout.%%' --wrapper-output='stderr.%%'`

The `[]` escaping for commands is a recent change to allow escaping commands to be passed as an argument to another program. For example, one could strace all recipes using:

`makeflow --wrapper='strace -f -o strace-%%.debug -- /bin/sh -c []'`

To my knowledge, the current use-cases for `[]` is the resource monitor and the disk allocator.

**Comment by trshaffer** [comment]
@batrick, would you be opposed to a change in syntax? Since unquoted substitution needs to be done carefully, I think we should make it available on request. If we're exposing wrappers as a user feature, it would make sense that

- `{}` does quoting and escaping
- `[]` does simple string substitution, no quoting/escaping
- no placeholder is equivalent to trailing `{}`

We also need to update the documentation, as it doesn't mention quoting/escaping.

**Comment by batrick** [comment]
Let me suggest a different approach that only involves changing the default when there is no placeholder used in the wrapper string. For the default, let's append `/bin/sh -c []` wrapper. Appending `[]` as the default (the escaped command) is not useful as it will require the user to
always put `/bin/sh -c` at the end of their wrapper to get it to work. They might as well put `/bin/sh -c []` at the end of their wrapper and not use the default.

The other advantage of using `/bin/sh -c []` as the default is that it also works for current use cases (e.g. all the ones I previously mentioned). Additionally, command wrappers like `strace` now correctly work for the entire command (which may have multiple statements; e.g. `echo hello; echo bye;`) without the user making extra effort.

**Comment by trshaffer** [comment]
After looking over the examples in the documentation, I started thinking about including `/bin/sh -c`. I like this default case approach; I'll put in a pull request with the change, and updated docs.

**Comment by batrick** [comment]
Fixed by #1166.
