### ISSUE TITLE
Treat CORES as an alias to OMP_NUM_THREADS

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1165]
@akahs  found the following error while running makeflow -Tlocal:
 
libgomp: Thread creation failed: Resource temporarily unavailable
Thread creation failed: Resource temporarily unavailable

The problem is that both makeflow and the task executable (/usr/bin/convert) try to use all the cores in the machine. makeflow sets CORES=1, but convert respects OMP_NUM_THREADS. For n cores, nxn processes are created and this exhausted the maximum number of concurrent processes allowed.

This is a really nice example on how different applications respect/ignore resources limits. Note that  adding OMP_NUM_THREADS would not solve the problem in general, as the executable may ignore its value, or use some other framework (e.g., MPI).

**Comment by dthain** [comment]
@charleszheng44 please take this one.

First verify that you can reproduce the bug on student00.cse.nd.edu.

The issue here is that convert tries to use all of the cores available, and when makeflow tries to run four at once, it exceeds the per-user limits on the machine.
