### ISSUE TITLE
Project: Failover Catalog Server

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1187]
Establish a fail-over scheme for the catalog server, so that the outage of one machine doesn't bring everything to a halt.

Step 1 - Allow the environment variable CATALOG_HOST to contain a list of hostnames.  Let the default value be "catalog.cse.nd.edu;backup-catalog.cse.nd.edu"  Factor out the various places where we update a single catalog via datagram_send into a common module that will send the same packet to a list of servers.

Step 2 - Update catalog_query_create to accept a list of servers, and then query them in order.  If the first one doesn't respond in a reasonable time, move on to the second one.

Step 3 - Optimize the failover case -- if the first one is not responding quickly, then continue to use the backup instead of always retrying the primary.  (Until the backup fails.)

**Comment by dthain** [comment]
@trshaffer do you want to take a try at this one?

**Comment by trshaffer** [comment]
Will all catalog servers in the list need to use the same port?

**Comment by dthain** [comment]
Seems to me that the might each have different ports.
We may need to clean up the API...

**Comment by trshaffer** [comment]
It seems like I've been running into trouble with the networking APIs lately. For this one, it would be also be nice to fall back to other addresses returned by DNS, which I think would tie into some of the IPv6 discussion with @batrick.

**Comment by dthain** [comment]
What sort of trouble?

**Comment by trshaffer** [comment]
Oh, just the host:port a bit ago, and the internal API here will be a little awkward. Should I be looking at minimal changes to make this work, or thinking about e.g. API changes for IPv6 integration?

**Comment by dthain** [comment]
Short answer: only change the API where really necessary.
Let's talk about it today.

**Comment by dthain** [comment]
I think this one is done, right?

**Comment by trshaffer** [comment]
As far as I know
