### ISSUE TITLE
Extremely long line

### ISSUE THREAD

**Issue by trshaffer** [cooperative-computing-lab/cctools#1195]
I was wondering why my text editor was getting laggy in `dag_visitors.c`. As it happens, one of the lines is 248879 characters long. It appears to be a large XML file with newlines stripped out. I don't think a single `fprintf` statement is the correct place for this kind of data.

https://github.com/cooperative-computing-lab/cctools/blame/8196aab6913de56eb155de4315ed063f0a2ff2d8/makeflow/src/dag_visitors.c#L487

**Comment by btovar** [comment]
Since this mode is not used very often, we can move it to a file somewhere in INSTALL_PATH, and read it when needed. Alternatively, perhaps there is a cytoscape style that is not 200kB.
