### ISSUE TITLE
Documentation for Makeflow linker needs to be updated

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#1198]
The documentation for Makeflow linker requires to be updated:
http://ccl.cse.nd.edu/software/manuals/makeflow.html#linking
It seems `-b` option has been removed from `makeflow`.

**Comment by dthain** [comment]
Go right ahead!

**Comment by hmeng-19** [comment]
@dthain , I do not think any current options of Makeflow aims to collect the dependencies of a given makeflow into a dir, as described http://ccl.cse.nd.edu/software/manuals/makeflow.html#linking .

**Comment by hmeng-19** [comment]
@dthain , we can either close the issue for now, or remove http://ccl.cse.nd.edu/software/manuals/makeflow.html#linking from the Makeflow user manual page.

**Comment by hmeng-19** [comment]
Fixed by 1435.
