### ISSUE TITLE
Parrot should use mechanism other than env var to detect nested executions

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#1203]
Rodney Walker reported an issue with a script he wrote that may be run inside or outside of Parrot. He was trying to detect nested executions of Parrot using `ps | grep parrot_run` and only run `parrot_run` if not already inside Parrot. This was his example script:

````
ps | grep parrot_run
if [ $? -eq 1 ];then
   MYHOST=`hostname -f`
   echo No parrot on $MYHOST
   unset PARROT_ENABLED
  /home/hpc/pr58be/ri32buz2/software/cvmfs_parrot/cctools/bin/parrot_run
ls /cvmfs/atlas.cern.ch
else
  MYHOST=`hostname -f`
  echo Should be in parrot already on $MYHOST
  ps | grep parrot_run
  echo $MYHOST $?
  echo PARROT_ENABLED: $MYHOST $PARROT_ENABLED
  ls /cvmfs/atlas.cern.ch/repo
fi
````

It seems the need to for using `ps` is due to this script being part of a job submission framework which passes environment variables to jobs. So a job would begin with PARROT_ENABLED set even though it is not running Parrot.

I suggest Parrot use another mechanism like a failure from `ptrace` to detect nesting or perhaps a custom Parrot system call.

**Comment by dthain** [comment]
+1 on custom system call

**Comment by batrick** [comment]
I would also suggest the nested Parrot just execute the program normally so users don't need to test anything.

**Comment by batrick** [comment]
Thinking about it more, an option would be necessary if we want to have the nested Parrot execute the program normally. The options may conflict (e.g. mount options) so the program may fail unexpectedly.

**Comment by dthain** [comment]
This could be done, but the various policy controls in parrot would have to be consolidated into a structure which represents the current "container" in which the process executes.

And then make sure that the policies given on the command line are a proper subset of those already in effect.

Interesting!
