### ISSUE TITLE
Specify Location of Resource Monitor Output Files Per Task in Work Queue

### ISSUE THREAD

**Issue by klannon** [cooperative-computing-lab/cctools#1211]
Would it be possible to have the resource monitor output files go into a directory specified independently for each task, in a similar way to the way the task output file local locations can be specified?  For example, something like:

`task.specify_monitoring_dir(local)`

**Comment by btovar** [comment]
Yes. We can make it so that the default is split per category. Which use case were you thinking of?

**Comment by klannon** [comment]
Personally, I'd like to be able to specify a unique location for the output of each task.  Right now, all the other task related files we generate (i.e. the job outputs) go into a directory structure where each task gets its own directory.  I would like to be able to ask WQ to put the resource monitoring file in that same directory so that it's easy to associate resource usage with the rest of the task outputs (log files, etc.)  Would that be possible?
