### ISSUE TITLE
space and tab magic in makefile

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#1215]
(1) I copied the example makeflow from http://ccl.cse.nd.edu/software/manuals/makeflow.html#language into a local file `example.makeflow`, and `makeflow example.makeflow` works perfectly. Even if each rule line starts with 8 spaces.
    
    hmeng@daspos2 ~/work/makeflow$ cat example.makeflow
    CURL=/usr/bin/curl
    CONVERT=/usr/bin/convert
    URL=http://ccl.cse.nd.edu/images/capitol.jpg
    
    capitol.montage.gif: capitol.jpg capitol.90.jpg capitol.180.jpg capitol.270.jpg capitol.360.jpg $CONVERT
            LOCAL $CONVERT -delay 10 -loop 0 capitol.jpg capitol.90.jpg capitol.180.jpg capitol.270.jpg capitol.360.jpg capitol.270.jpg capitol.180.jpg capitol.90.jpg capitol.montage.gif
    
    capitol.90.jpg: capitol.jpg $CONVERT
            $CONVERT -swirl 90 capitol.jpg capitol.90.jpg
    
    capitol.180.jpg: capitol.jpg $CONVERT
            $CONVERT -swirl 180 capitol.jpg capitol.180.jpg
    
    capitol.270.jpg: capitol.jpg $CONVERT
            $CONVERT -swirl 270 capitol.jpg capitol.270.jpg
    
    capitol.360.jpg: capitol.jpg $CONVERT
            $CONVERT -swirl 360 capitol.jpg capitol.360.jpg
    
    capitol.jpg: $CURL
            LOCAL $CURL -o capitol.jpg $URL
 
(2) Then I tried to remove the three environment variable settings (CURL, CONVERT, URL) at the beginning of `example.makeflow` and replace them with their real values. The result makefile is `1.mf`.
Notice: each rule line still starts with 8 spaces.
    
    hmeng@daspos2 ~/work/makeflow$ cat 1.mf
    capitol.montage.gif: capitol.jpg capitol.90.jpg capitol.180.jpg capitol.270.jpg capitol.360.jpg /usr/bin/convert
            LOCAL /usr/bin/convert -delay 10 -loop 0 capitol.jpg capitol.90.jpg capitol.180.jpg capitol.270.jpg capitol.360.jpg capitol.270.jpg capitol.180.jpg capitol.90.jpg capitol.montage.gif
    
    capitol.90.jpg: capitol.jpg /usr/bin/convert
            /usr/bin/convert -swirl 90 capitol.jpg capitol.90.jpg
    
    capitol.180.jpg: capitol.jpg /usr/bin/convert
            /usr/bin/convert -swirl 180 capitol.jpg capitol.180.jpg
    
    capitol.270.jpg: capitol.jpg /usr/bin/convert
            /usr/bin/convert -swirl 270 capitol.jpg capitol.270.jpg
    
    capitol.360.jpg: capitol.jpg /usr/bin/convert
            /usr/bin/convert -swirl 360 capitol.jpg capitol.360.jpg
    
    capitol.jpg: /usr/bin/curl
            LOCAL /usr/bin/curl -o capitol.jpg http://ccl.cse.nd.edu/images/capitol.jpg
 
However, `makeflow 1.mf` fails for the following reason:
 
    hmeng@daspos2 ~/work/makeflow$ makeflow 1.mf
    parsing 1.mf...
    2016/03/18 17:36:18.84 makeflow[141707] fatal: Expecting a filename. line: 17 column: 29
    Terminated
 
(3) To fix the problem, I accepted Nick's suggestion, and replace the 8 spaces at the start of each rule line with a tab, and got `2.mf`. Then `makeflow 2.mf` works perfectly.
    
    hmeng@daspos2 ~/work/makeflow$ cat 2.mf
    capitol.montage.gif: capitol.jpg capitol.90.jpg capitol.180.jpg capitol.270.jpg capitol.360.jpg /usr/bin/convert
            LOCAL /usr/bin/convert -delay 10 -loop 0 capitol.jpg capitol.90.jpg capitol.180.jpg capitol.270.jpg capitol.360.jpg capitol.270.jpg capitol.180.jpg capitol.90.jpg capitol.montage.gif
    
    capitol.90.jpg: capitol.jpg /usr/bin/convert
            /usr/bin/convert -swirl 90 capitol.jpg capitol.90.jpg
    
    capitol.180.jpg: capitol.jpg /usr/bin/convert
            /usr/bin/convert -swirl 180 capitol.jpg capitol.180.jpg
    
    capitol.270.jpg: capitol.jpg /usr/bin/convert
            /usr/bin/convert -swirl 270 capitol.jpg capitol.270.jpg
    
    capitol.360.jpg: capitol.jpg /usr/bin/convert
            /usr/bin/convert -swirl 360 capitol.jpg capitol.360.jpg
    
    capitol.jpg: /usr/bin/curl
            LOCAL /usr/bin/curl -o capitol.jpg http://ccl.cse.nd.edu/images/capitol.jpg

**Comment by hmeng-19** [comment]
Just to be clear, there is no empty line at the beginning of all these three makefiles, and there is no empty line at the end of all these three makefiles.

**Comment by nkremerh** [comment]
Just curious, has this been resolved? @nhazekam

**Comment by hmeng-19** [comment]
@nhazekam , I have the same question as @nkremerh .

**Comment by nhazekam** [comment]
This was a reproducible error at the time of raising the issue. However after trying the three above described makeflows, none had any errors parsing. I also tried a makeflow provided previously that had the issue, and there is no longer an error. I am in favor of closing this as it appears the issue was remedied in master. @hmeng-19 let me know your thoughts before this is closed.

**Comment by hmeng-19** [comment]
@nhazekam , I just retried the three makefiles mentioned in this PR, and they all worked well.
I guess some updates to Makeflow recently may fix the problem somehow.
I will close this issue, thanks for looking into it.
