### ISSUE TITLE
Resource Monitor Delay

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1220]
Our automatic tests have gotten rather slow lately -- it takes quite a while to get through all of the makeflow tests, which used to finish in a fraction of a second.

The culprit seems to be that the category feature is enabling the resource monitor in the WQ worker, and then the RM main loop seems to make the minimum task execution time a couple of seconds.  This will have an outside impact on workflows that consist of a large number of rapid tasks.

Is there any way to improve the resource monitor so that it exits rapidly after the child completes?

**Comment by btovar** [comment]
That sounds like a bug. The monitor should not take a couple of seconds to return. Let me check what's going on.

**Comment by dthain** [comment]
Nice, thanks.

**Comment by dthain** [comment]
Hmm, I'm still seeing huge delays in the simple test makeflows, can you look some more:
or example:
http://ccl.cse.nd.edu/a/1218bae7/1218bae7.x86_64-redhat5.log

```
--- Testing makeflow/test/TR_makeflow_001_dirs_01.sh ...          success 45s
--- Testing makeflow/test/TR_makeflow_001_dirs_02.sh ...          success 42s
--- Testing makeflow/test/TR_makeflow_001_dirs_03.sh ...          success 42s
--- Testing makeflow/test/TR_makeflow_001_dirs_04.sh ...          success 42s
--- Testing makeflow/test/TR_makeflow_001_dirs_05.sh ...          success 42s
--- Testing makeflow/test/TR_makeflow_001_dirs_06.sh ...          success 42s
--- Testing makeflow/test/TR_makeflow_001_dirs_07.sh ...          success 62s
--- Testing makeflow/test/TR_makeflow_001_dirs_08.sh ...          success 42s
--- Testing makeflow/test/TR_makeflow_001_dirs_09.sh ...          success 43s
--- Testing makeflow/test/TR_makeflow_001_dirs_10.sh ...          success 42s
--- Testing makeflow/test/TR_makeflow_001_dirs_11.sh ...          success 82s
```

**Comment by btovar** [comment]
RH5 still is slow... with #1225. Checking....

**Comment by dthain** [comment]
I think there is a second issue here -

I don't think we want the RM enabled unless the user has specifically asked for it, or a feature requested that requires it.   Is there a reason that it seems to be enabled for the base makeflow test cases?

**Comment by btovar** [comment]
You are correct. work queue is activating monitoring in makeflow when it should not, and the monitor had a bug in the exit handler for RH5.

It is the way we send the limits from makeflow to work queue. There are no limits (all are -1), but work queue sees that the limits structure is defined, and activates monitoring per category.

**Comment by btovar** [comment]
The issue was that there was some left over functionality from when categories where only in work queue. Now that makeflow has categories too for all the batch systems, I simply removed setting the limits per category for wq. Makeflow communicates to wq limits per task, when appropriate.

**Comment by btovar** [comment]
This was a happy issue where bugs help discover each other... If one of the bugs did not exist, it would have take longer to fix the other.

**Comment by btovar** [comment]
http://ccl.cse.nd.edu/a/5c43f368/5c43f368.x86_64-redhat5.log 

--- Testing makeflow/test/TR_makeflow_001_dirs_01.sh ...          success 5s
--- Testing makeflow/test/TR_makeflow_001_dirs_02.sh ...          success 2s
--- Testing makeflow/test/TR_makeflow_001_dirs_03.sh ...          success 2s
--- Testing makeflow/test/TR_makeflow_001_dirs_04.sh ...          success 3s
--- Testing makeflow/test/TR_makeflow_001_dirs_05.sh ...          success 2s
--- Testing makeflow/test/TR_makeflow_001_dirs_06.sh ...          success 2s
--- Testing makeflow/test/TR_makeflow_001_dirs_07.sh ...          success 2s
--- Testing makeflow/test/TR_makeflow_001_dirs_08.sh ...          success 1s
--- Testing makeflow/test/TR_makeflow_001_dirs_09.sh ...          success 1s
--- Testing makeflow/test/TR_makeflow_001_dirs_10.sh ...          success 1s
--- Testing makeflow/test/TR_makeflow_001_dirs_11.sh ...          success 1s
