### ISSUE TITLE
#1180 (jx expressions) breaks resource monitor tools

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1231]
Before #1180, we could have many json objects per file. This was not proper json, but it did allow the monitor tools to process the resource summaries quite fast. I could force the many objects in a file to be in an array, but then the whole array would need to be read before the first object can be processed. A single file may contain thousands of summaries, so this is undesirable.

Any thoughts?

**Comment by dthain** [comment]
That sounds like a reasonable use case, and it's pretty similar to the test case `TR_jx.sh` which expects to parse and return one item at a time.  Can you put in a test that breaks?

(The only parsing wrinkle here is that `[a][x]` could indicate two array literals, each containing one item, or an array literal `[a]` followed by an array lookup of item in position x.  This is solved by the hack of adding a semicolon between the two.)

**Comment by dthain** [comment]
Is this one solved?

**Comment by trshaffer** [comment]
The above test is passing. As far as I know, this is working in @btovar's use case
