### ISSUE TITLE
chirp server busy waiting

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1233]
The CRC is reporting a trickle of continuous load from chirp_servers, which may be having some impact on how condor is computing local load average.

When I strace an idle chirp server, I see a busy-wait of the following form:

```
wait4(-1, 0x7fff141cdec4, WNOHANG, NULL) = -1 ECHILD (No child processes)
select(7, [4 6], NULL, NULL, {0, 5000}) = 0 (Timeout)
wait4(-1, 0x7fff141cdec4, WNOHANG, NULL) = -1 ECHILD (No child processes)
select(7, [4 6], NULL, NULL, {0, 5000}) = 0 (Timeout)
wait4(-1, 0x7fff141cdec4, WNOHANG, NULL) = -1 ECHILD (No child processes)
select(7, [4 6], NULL, NULL, {0, 5000}) = 0 (Timeout)
wait4(-1, 0x7fff141cdec4, WNOHANG, NULL) = -1 ECHILD (No child processes)
select(7, [4 6], NULL, NULL, {0, 5000}) = 0 (Timeout)
wait4(-1, 0x7fff141cdec4, WNOHANG, NULL) = -1 ECHILD (No child processes)
. . .
```

Ok, it's not *exactly* busy-waiting, since the select sleeps for 5000 usec, but an idle process really ought to be idle.

@batrick please take a look.  Can we do better than this?

**Comment by batrick** [comment]
That's this block of code:

https://github.com/cooperative-computing-lab/cctools/blob/8964e7239df0dd1117536bb96cb9fd97a921f457/chirp/src/chirp_server.c#L2277-L2313

I think it would be safe to increase that select to a second. I'll do some tests to be sure.
