### ISSUE TITLE
JX library failure

### ISSUE THREAD

**Issue by trshaffer** [cooperative-computing-lab/cctools#1250]
While trying to run `chirp_status`, on the current master I get an error.

    [tshaffe1@cclws19 src]$ ./chirp_status  -d all
    2016/04/11 12:35:48.31 chirp_status[28267] debug: ./chirp_status version 6.0.0 [master:8b2b9d1c] (released 2016-04-11 08:00:51 -0400)
    2016/04/11 12:35:48.31 chirp_status[28267] debug: Built by tshaffe1@cclws19 on 2016-04-11 12:26:11 -0400
    2016/04/11 12:35:48.31 chirp_status[28267] debug: System: Linux cclws19 2.6.32-431.17.1.el6.x86_64 #1 SMP Fri Apr 11 17:27:00 EDT 2014 x86_64 GNU/Linux
    2016/04/11 12:35:48.31 chirp_status[28267] debug: Configuration: --strict
    2016/04/11 12:35:48.31 chirp_status[28267] http: connect catalog.cse.nd.edu port 9097
    2016/04/11 12:35:48.31 chirp_status[28267] dns: looking up name catalog.cse.nd.edu
    2016/04/11 12:35:48.31 chirp_status[28267] dns: catalog.cse.nd.edu is 129.74.152.166
    2016/04/11 12:35:48.31 chirp_status[28267] tcp: connecting to 129.74.152.166:9097
    2016/04/11 12:35:48.31 chirp_status[28267] tcp: made connection to 129.74.152.166:9097
    2016/04/11 12:35:48.31 chirp_status[28267] http: GET http://catalog.cse.nd.edu:9097/query.json HTTP/1.1
    Connection: close
    Host: catalog.cse.nd.edu
    User-Agent: Mozilla/5.0 (compatible; CCTools 6.0.0 [master:8b2b9d1c] Parrot; http://ccl.cse.nd.edu/)
    2016/04/11 12:35:48.32 chirp_status[28267] http: HTTP/1.1 200 OK
    2016/04/11 12:35:48.32 chirp_status[28267] http: Date: Mon Apr 11 12:35:48 2016
    2016/04/11 12:35:48.32 chirp_status[28267] http: Server: catalog_server
    2016/04/11 12:35:48.32 chirp_status[28267] http: Connection: close
    2016/04/11 12:35:48.32 chirp_status[28267] http: Access-Control-Allow-Origin: *
    2016/04/11 12:35:48.32 chirp_status[28267] http: Content-type: text/plain
    2016/04/11 12:35:48.32 chirp_status[28267] http:
    2016/04/11 12:35:48.40 chirp_status[28267] tcp: disconnected from 129.74.152.166:9097
    2016/04/11 12:35:48.40 chirp_status[28267] debug: query result failed to parse as JSON
    couldn't query catalog: Resource temporarily unavailable

There appears to be a parsing failure in the JX library. @nhazekam confirmed this issue on his workstation

**Comment by dthain** [comment]
Please post the raw output of curl from the catalog server, so we can see what's not working...

**Comment by trshaffer** [comment]
[parse_failure.txt](https://github.com/cooperative-computing-lab/cctools/files/213614/parse_failure.txt)

**Comment by dthain** [comment]
@btovar can you take a look?

**Comment by btovar** [comment]
I am not getting an error from my workstation. I'll investigate more.

**Comment by trshaffer** [comment]
Same here, `chirp_status` seems to be working again. I checked that I was getting the error when I grabbed that catalog output posted above. I'll post another one for comparison, now that it's working

[ok.txt](https://github.com/cooperative-computing-lab/cctools/files/213725/ok.txt)

**Comment by btovar** [comment]
All right, thanks Tim.

**Comment by btovar** [comment]
I can test Tim's files with the executable for testing jx_count_obj_test. parse_failure.txt produces a segfault.

**Comment by btovar** [comment]
There seems to be two issues. On error, jx_parser_delete may be called twice, which produces a double free. The error, though, is a malformed array that comes from chirp_status.

**Comment by btovar** [comment]
The double free comes from jx_parser_yield (so unrelated to chirp_status). On error, yield deletes the parser. I'll remove that, so that the calling code does the cleaning on error.

**Comment by btovar** [comment]
The problem is not related to chirp at all. My pull request #1257 sent a malformed work queue status to the catalog. It would be nice if the parsing skipped malformed entries, though.

**Comment by btovar** [comment]
On further inspection, the catalog update rejects malformed entries. Investigating further.

**Comment by trshaffer** [comment]
It looks like the culprit is on line 466 of that failing paste. One of the values is a float in E notation. It seems JX doesn't handle this syntax, so `2.9e-05` gets parsed as an invalid expression.

**Comment by btovar** [comment]
Tim, for me it fails much earlier, in line 34.

**Comment by btovar** [comment]
I can confirm it also fails at line 466.

**Comment by trshaffer** [comment]
Huh, my little test program parses that line OK. If I give it line 466, I get

    invalid expression: key-value pairs missing a comma or closing brace

which makes sense if it doesn't recognize `e` as part of a number.

**Comment by btovar** [comment]
Mmm, line 34 is parsing now for me too. Probably my mistake in the way I set the test.

But yes, if I test  1e-1 by itself, it fails. Thanks Tim  for the pointer. I'll work on this right away.
