### ISSUE TITLE
Long commands cause " No buffer space available" errors in work queue

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1277]
Per Matt Bomhoff:

I am seeing this error message in the debug log followed by WorkQueue halting:

2016/04/20 15:54:31.22 work_queue_python[12242] fatal: [buffer.c:84]: No buffer space available

The full snippet below shows the submission of a job with a very long command-line (> 4096 chars) followed by the many file transfers and finally the buffer error.  Submitting the same job with fewer files and thus a shorter command-line (< 4096 chars) and fewer file transfers finishes successfully. 

I appreciate any help you can provide with debugging this issue.

Thanks!
Matt

Matt Bomhoff, CoGe Lead Software Developer, Lyons Lab, University of Arizona
http://genomevolution.org

04/20/2016 03:54:30 yerba.workqueue:91[INFO] ######### WORKQUEUE SCHEDULING ##########
04/20/2016 03:54:30 yerba.workqueue:93[INFO] WORKQUEUE coge-main: The workflow 38628 is scheduling job perl /opt/apache/coge/scripts/load_genome.pl  -user_name mbomhoff -wid 38628 -name "" -desc "" -link "" -version 1 -restricted 1 -source_name 'Matt Bomhoff' -organism_id 32977 -type_id 1 -staging_dir ./load_genome -fasta_files /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa01.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa02.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa03.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa04.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa05.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa06.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa07.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa08.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa09.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa10.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa11.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa12.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa13.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa14.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa15.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa16.fna.gz,/storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa17.fna.gz -irods_files '' -config /opt/apache2/coge/coge.conf
2016/04/20 15:54:30.42 work_queue_python[12242] wq: Task 20 state change: unknown (0) to ready (1)
04/20/2016 03:54:30 yerba.workqueue:142[INFO] WORKQUEUE coge-main: Task has been submited and assigned [id 20]
04/20/2016 03:54:30 yerba.workqueue:146[INFO] ######### WORKQUEUE END SCHEDULING ##########
04/20/2016 03:54:30 yerba.workqueue:182[INFO] ######### WORKQUEUE END UPDATING ##########
2016/04/20 15:54:30.48 work_queue_python[12242] wq: Task 20 state change: ready (1) to running (2)
2016/04/20 15:54:30.48 work_queue_python[12242] wq: workers status -- total: 10, active: 10, available: 9.
2016/04/20 15:54:30.48 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa01.fna.gz bytes 0:42541161 as 'file-0-304b3940e461322112f5f9808828b0d2-chrssa01.fna.gz'
2016/04/20 15:54:30.48 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 518.87 MB/s
2016/04/20 15:54:30.48 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 42.54 MB file.
2016/04/20 15:54:30.48 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-304b3940e461322112f5f9808828b0d2-chrssa01.fna.gz 42541161 0644 1
2016/04/20 15:54:30.54 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 42.54 MB in 0.05s (774.09s MB/s) average 774.09s MB/s
2016/04/20 15:54:30.54 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa02.fna.gz bytes 0:18156792 as 'file-0-6e139429b2c3ae37eef4a49f7ea1195b-chrssa02.fna.gz'
2016/04/20 15:54:30.54 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 522.26 MB/s
2016/04/20 15:54:30.54 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 18.16 MB file.
2016/04/20 15:54:30.54 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-6e139429b2c3ae37eef4a49f7ea1195b-chrssa02.fna.gz 18156792 0644 1
2016/04/20 15:54:30.57 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 18.16 MB in 0.03s (575.91s MB/s) average 701.85s MB/s
2016/04/20 15:54:30.57 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa03.fna.gz bytes 0:23724311 as 'file-0-e6918cb9111df24f9900adadebd9ad76-chrssa03.fna.gz'
2016/04/20 15:54:30.57 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 522.50 MB/s
2016/04/20 15:54:30.57 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 23.72 MB file.
2016/04/20 15:54:30.57 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-e6918cb9111df24f9900adadebd9ad76-chrssa03.fna.gz 23724311 0644 1
2016/04/20 15:54:30.61 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 23.72 MB in 0.04s (593.00s MB/s) average 667.42s MB/s
2016/04/20 15:54:30.61 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa04.fna.gz bytes 0:21814527 as 'file-0-f28c03e5ca73b4465491728642ec5a46-chrssa04.fna.gz'
2016/04/20 15:54:30.61 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 522.97 MB/s
2016/04/20 15:54:30.61 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 21.81 MB file.
2016/04/20 15:54:30.61 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-f28c03e5ca73b4465491728642ec5a46-chrssa04.fna.gz 21814527 0644 1
2016/04/20 15:54:30.65 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 21.81 MB in 0.04s (582.72s MB/s) average 648.08s MB/s
2016/04/20 15:54:30.65 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa05.fna.gz bytes 0:20078423 as 'file-0-4404044d087e96f7fb9c5c67325daeae-chrssa05.fna.gz'
2016/04/20 15:54:30.65 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 523.31 MB/s
2016/04/20 15:54:30.65 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 20.08 MB file.
2016/04/20 15:54:30.65 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-4404044d087e96f7fb9c5c67325daeae-chrssa05.fna.gz 20078423 0644 1
2016/04/20 15:54:30.68 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 20.08 MB in 0.04s (551.57s MB/s) average 630.54s MB/s
2016/04/20 15:54:30.68 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa06.fna.gz bytes 0:21635033 as 'file-0-54bb9762cb97531095a606328ef93dae-chrssa06.fna.gz'
2016/04/20 15:54:30.68 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 523.34 MB/s
2016/04/20 15:54:30.68 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 21.64 MB file.
2016/04/20 15:54:30.68 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-54bb9762cb97531095a606328ef93dae-chrssa06.fna.gz 21635033 0644 1
2016/04/20 15:54:30.72 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 21.64 MB in 0.04s (565.05s MB/s) average 620.03s MB/s
2016/04/20 15:54:30.72 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa07.fna.gz bytes 0:14859980 as 'file-0-f6b27bd03401519545f86476928ae11c-chrssa07.fna.gz'
2016/04/20 15:54:30.72 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 523.49 MB/s
2016/04/20 15:54:30.72 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 14.86 MB file.
2016/04/20 15:54:30.72 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-f6b27bd03401519545f86476928ae11c-chrssa07.fna.gz 14859980 0644 1
2016/04/20 15:54:30.75 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 14.86 MB in 0.03s (590.74s MB/s) average 617.24s MB/s
2016/04/20 15:54:30.75 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa08.fna.gz bytes 0:6617166 as 'file-0-9dc8655a690c724c23af702ef4e6fcb7-chrssa08.fna.gz'
2016/04/20 15:54:30.75 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 523.76 MB/s
2016/04/20 15:54:30.75 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 6.62 MB file.
2016/04/20 15:54:30.75 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-9dc8655a690c724c23af702ef4e6fcb7-chrssa08.fna.gz 6617166 0644 1
2016/04/20 15:54:30.76 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 6.62 MB in 0.01s (540.84s MB/s) average 613.85s MB/s
2016/04/20 15:54:30.76 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa09.fna.gz bytes 0:36480667 as 'file-0-d9a23789a686819a35006fe66aadf804-chrssa09.fna.gz'
2016/04/20 15:54:30.76 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 523.73 MB/s
2016/04/20 15:54:30.76 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 36.48 MB file.
2016/04/20 15:54:30.76 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-d9a23789a686819a35006fe66aadf804-chrssa09.fna.gz 36480667 0644 1
2016/04/20 15:54:30.82 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 36.48 MB in 0.06s (594.70s MB/s) average 610.37s MB/s
2016/04/20 15:54:30.82 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa10.fna.gz bytes 0:31381559 as 'file-0-4e956cc2d918934f8c655e8382b741d0-chrssa10.fna.gz'
2016/04/20 15:54:30.82 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 524.43 MB/s
2016/04/20 15:54:30.82 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 31.38 MB file.
2016/04/20 15:54:30.82 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-4e956cc2d918934f8c655e8382b741d0-chrssa10.fna.gz 31381559 0644 1
2016/04/20 15:54:30.88 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 31.38 MB in 0.06s (515.11s MB/s) average 595.80s MB/s
2016/04/20 15:54:30.88 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa11.fna.gz bytes 0:24087900 as 'file-0-ea05909e6fa70056cb153aaeaff421a6-chrssa11.fna.gz'
2016/04/20 15:54:30.88 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 523.91 MB/s
2016/04/20 15:54:30.88 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 24.09 MB file.
2016/04/20 15:54:30.88 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-ea05909e6fa70056cb153aaeaff421a6-chrssa11.fna.gz 24087900 0644 1
2016/04/20 15:54:30.93 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 24.09 MB in 0.05s (492.87s MB/s) average 584.55s MB/s
2016/04/20 15:54:30.93 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa12.fna.gz bytes 0:23677740 as 'file-0-93c2808185cc2a1a925a30c8d385472a-chrssa12.fna.gz'
2016/04/20 15:54:30.93 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 523.24 MB/s
2016/04/20 15:54:30.93 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 23.68 MB file.
2016/04/20 15:54:30.93 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-93c2808185cc2a1a925a30c8d385472a-chrssa12.fna.gz 23677740 0644 1
2016/04/20 15:54:30.98 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 23.68 MB in 0.05s (482.39s MB/s) average 574.44s MB/s
2016/04/20 15:54:30.98 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa13.fna.gz bytes 0:29062328 as 'file-0-4849169b5838ed3b146d388fde1c71b1-chrssa13.fna.gz'
2016/04/20 15:54:30.98 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 522.47 MB/s
2016/04/20 15:54:30.98 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 29.06 MB file.
2016/04/20 15:54:30.98 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-4849169b5838ed3b146d388fde1c71b1-chrssa13.fna.gz 29062328 0644 1
2016/04/20 15:54:31.04 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 29.06 MB in 0.06s (468.46s MB/s) average 562.67s MB/s
2016/04/20 15:54:31.04 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa14.fna.gz bytes 0:24506060 as 'file-0-aeff82024cea6b79d6d1eab0ffc4d72c-chrssa14.fna.gz'
2016/04/20 15:54:31.04 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 521.31 MB/s
2016/04/20 15:54:31.04 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 24.51 MB file.
2016/04/20 15:54:31.04 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-aeff82024cea6b79d6d1eab0ffc4d72c-chrssa14.fna.gz 24506060 0644 1
2016/04/20 15:54:31.09 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 24.51 MB in 0.05s (495.83s MB/s) average 557.23s MB/s
2016/04/20 15:54:31.09 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa15.fna.gz bytes 0:26846682 as 'file-0-a21384cfd253ad44f2099f9e22b59ee8-chrssa15.fna.gz'
2016/04/20 15:54:31.09 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 520.73 MB/s
2016/04/20 15:54:31.09 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 26.85 MB file.
2016/04/20 15:54:31.09 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-a21384cfd253ad44f2099f9e22b59ee8-chrssa15.fna.gz 26846682 0644 1
2016/04/20 15:54:31.15 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 26.85 MB in 0.06s (474.79s MB/s) average 550.21s MB/s
2016/04/20 15:54:31.15 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa16.fna.gz bytes 0:22688590 as 'file-0-d7827b981dc13ea695940b864813225c-chrssa16.fna.gz'
2016/04/20 15:54:31.15 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 519.80 MB/s
2016/04/20 15:54:31.15 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 22.69 MB file.
2016/04/20 15:54:31.15 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-d7827b981dc13ea695940b864813225c-chrssa16.fna.gz 22688590 0644 1
2016/04/20 15:54:31.19 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 22.69 MB in 0.05s (485.00s MB/s) average 545.92s MB/s
2016/04/20 15:54:31.19 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) needs file /storage2/coge/tmp/uploads/mbomhoff/6201817E074911E69FB0EC554C3FE610/ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrssa17.fna.gz bytes 0:13849602 as 'file-0-b44f7c49460138dd06fad229758ddf30-chrssa17.fna.gz'
2016/04/20 15:54:31.19 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) using overall queue average transfer rate of 519.17 MB/s
2016/04/20 15:54:31.19 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) will try up to 10 seconds to transfer this 13.85 MB file.
2016/04/20 15:54:31.19 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): put file-0-b44f7c49460138dd06fad229758ddf30-chrssa17.fna.gz 13849602 0644 1
2016/04/20 15:54:31.22 work_queue_python[12242] wq: geco.iplantcollaborative.org (127.0.0.1:41327) received 13.85 MB in 0.03s (514.80s MB/s) average 544.79s MB/s
2016/04/20 15:54:31.22 work_queue_python[12242] wq: tx to geco.iplantcollaborative.org (127.0.0.1:41327): task 20
2016/04/20 15:54:31.22 work_queue_python[12242] fatal: [buffer.c:84]: No buffer space available
Could not open '/dev/tty' for immediate error reporting.
2016/04/20 15:54:31.33 work_queue_python[14046] tcp: listening on port 1025
2016/04/20 15:54:31.33 work_queue_python[14046] wq: Using default fast abort multiplier for 'default'.
2016/04/20 15:54:31.33 work_queue_python[14046] wq: Work Queue is listening on port 1025.
2016/04/20 15:54:31.33 work_queue_python[14046] wq: workers status -- total: 0, active: 0, available: 0.
2016/04/20 15:54:31.33 work_queue_python[14046] wq: log enabled and is being written to /opt/Yerba/log/workqueue.log
04/20/2016 03:54:31 yerba.workqueue:74[INFO] WORKQUEUE coge-main: Starting work queue on port 1025

**Comment by btovar** [comment]
The error comes because we set a maximum of WORK_QUEUE_LINE_MAX for messages to the worker. For command lines, this may be overkill, as buffer may grow as needed, and we send the size of the command line in the message.

I am looking for other places where the command line is assumed to be WORK_QUEUE_LINE_MAX.

**Comment by btovar** [comment]
I'm going to send the command line in a different message. "cmd %d\n" will send the length, with the command line sent via link_write. This avoids the WORK_QUEUE_LINE_MAX buffer limit of send_worker_message.  The worker does not rely on WORK_QUEUE_LINE_MAX for the size of the command line.

I still need to check that the monitor summaries do not have such assumptions.

**Comment by dthain** [comment]
This will fix the problem, but looks like it will break backwards compatibility.  Two suggestions:

- If you want to keep backwards compatibility, you could detect long command lines and turn them into `"sh longcmd.sh"` and then add a new input buffer that delivers the long command line in the file `longcmd.sh`  That could be done silently in the library without changing the protocol.

- If you are going to break the protocol, then I think it's time to bite the bullet and send the task in JSON format!

**Comment by btovar** [comment]
I don't believe the protocol would be broken. We would be changing:

send_worker_msg("cmd %d\n%s", n, command);

into:

send_worker_msg("cmd %d\n", n);
link_write(.... cmd ....);

**Comment by dthain** [comment]
Ah, I misunderstood.  Sounds good!
