### ISSUE TITLE
Look into using GCC's memory leak detection during build tests

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#1286]
Added in [GCC v4.8](https://gcc.gnu.org/gcc-4.8/changes.html). See also this [blog post](http://lemire.me/blog/2016/04/20/no-more-leaks-with-sanitize-flags-in-gcc-and-clang/).

**Comment by trshaffer** [comment]
Once I fixed a small leak in `resource_monitor/src/piggybacker.c`, I could compile cctools with those checks. For `makeflow example.makeflow`

    =================================================================
    ==10039==ERROR: LeakSanitizer: detected memory leaks

    Direct leak of 192 byte(s) in 6 object(s) allocated from:
        #0 0x7f72f836449a in __interceptor_malloc /build/gcc/src/gcc-5-20160209/libsanitizer/asan/asan_malloc_linux.cc:38
        #1 0x4faeb4 in cctools_list_create cctools/dttools/src/list.c:16
        #2 0x4fdf8c in list_duplicate cctools/dttools/src/list.c:375
        #3 0x404f9b in makeflow_generate_output_files cctools/makeflow/src/makeflow.c:152
        #4 0x40885a in makeflow_node_complete cctools/makeflow/src/makeflow.c:647
        #5 0x40a5c2 in makeflow_run cctools/makeflow/src/makeflow.c:830
        #6 0x40e012 in main cctools/makeflow/src/makeflow.c:1590
        #7 0x7f72f701e70f in __libc_start_main (/usr/lib/libc.so.6+0x2070f)

    Direct leak of 192 byte(s) in 6 object(s) allocated from:
        #0 0x7f72f836449a in __interceptor_malloc /build/gcc/src/gcc-5-20160209/libsanitizer/asan/asan_malloc_linux.cc:38
        #1 0x4fbd02 in new_node cctools/dttools/src/list.c:120
        #2 0x4fc79c in cctools_list_push_tail cctools/dttools/src/list.c:190
        #3 0x4fe042 in list_duplicate cctools/dttools/src/list.c:378
        #4 0x404f9b in makeflow_generate_output_files cctools/makeflow/src/makeflow.c:152
        #5 0x4074b1 in makeflow_node_submit cctools/makeflow/src/makeflow.c:474
        #6 0x407e8d in makeflow_dispatch_ready_jobs cctools/makeflow/src/makeflow.c:574
        #7 0x40a43c in makeflow_run cctools/makeflow/src/makeflow.c:817
        #8 0x40e012 in main cctools/makeflow/src/makeflow.c:1590
        #9 0x7f72f701e70f in __libc_start_main (/usr/lib/libc.so.6+0x2070f)

    Direct leak of 128 byte(s) in 4 object(s) allocated from:
        #0 0x7f72f836449a in __interceptor_malloc /build/gcc/src/gcc-5-20160209/libsanitizer/asan/asan_malloc_linux.cc:38
        #1 0x4fbd02 in new_node cctools/dttools/src/list.c:120
        #2 0x4fc79c in cctools_list_push_tail cctools/dttools/src/list.c:190
        #3 0x4fe042 in list_duplicate cctools/dttools/src/list.c:378
        #4 0x404dc6 in makeflow_generate_input_files cctools/makeflow/src/makeflow.c:137
        #5 0x40748a in makeflow_node_submit cctools/makeflow/src/makeflow.c:473
        #6 0x407e8d in makeflow_dispatch_ready_jobs cctools/makeflow/src/makeflow.c:574
        #7 0x40a43c in makeflow_run cctools/makeflow/src/makeflow.c:817
        #8 0x40e012 in main cctools/makeflow/src/makeflow.c:1590
        #9 0x7f72f701e70f in __libc_start_main (/usr/lib/libc.so.6+0x2070f)

    Indirect leak of 192 byte(s) in 6 object(s) allocated from:
        #0 0x7f72f836449a in __interceptor_malloc /build/gcc/src/gcc-5-20160209/libsanitizer/asan/asan_malloc_linux.cc:38
        #1 0x4fbd02 in new_node cctools/dttools/src/list.c:120
        #2 0x4fc79c in cctools_list_push_tail cctools/dttools/src/list.c:190
        #3 0x4fe042 in list_duplicate cctools/dttools/src/list.c:378
        #4 0x404f9b in makeflow_generate_output_files cctools/makeflow/src/makeflow.c:152
        #5 0x40885a in makeflow_node_complete cctools/makeflow/src/makeflow.c:647
        #6 0x40a5c2 in makeflow_run cctools/makeflow/src/makeflow.c:830
        #7 0x40e012 in main cctools/makeflow/src/makeflow.c:1590
        #8 0x7f72f701e70f in __libc_start_main (/usr/lib/libc.so.6+0x2070f)

    Indirect leak of 160 byte(s) in 5 object(s) allocated from:
        #0 0x7f72f836449a in __interceptor_malloc /build/gcc/src/gcc-5-20160209/libsanitizer/asan/asan_malloc_linux.cc:38
        #1 0x4fbd02 in new_node cctools/dttools/src/list.c:120
        #2 0x4fc79c in cctools_list_push_tail cctools/dttools/src/list.c:190
        #3 0x4fe042 in list_duplicate cctools/dttools/src/list.c:378
        #4 0x404dc6 in makeflow_generate_input_files cctools/makeflow/src/makeflow.c:137
        #5 0x40748a in makeflow_node_submit cctools/makeflow/src/makeflow.c:473
        #6 0x407e8d in makeflow_dispatch_ready_jobs cctools/makeflow/src/makeflow.c:574
        #7 0x40a43c in makeflow_run cctools/makeflow/src/makeflow.c:817
        #8 0x40e012 in main cctools/makeflow/src/makeflow.c:1590
        #9 0x7f72f701e70f in __libc_start_main (/usr/lib/libc.so.6+0x2070f)

    SUMMARY: AddressSanitizer: 864 byte(s) leaked in 27 allocation(s).

If @nhazekam has some larger Makeflows, I'm curious to see how it does



I tried running the tests, and got 73 leaks. Since these options require some linker flags, the tests that compile their own code were complaining about missing symbols, so the number of leaks might actually be higher.

**Comment by trshaffer** [comment]
Once I modify those test scripts to run with the checks, it looks like we're leaking 8.54 MiB over the course of the tests. Since the leak checks cause non-zero exit status on *any* leak, all the leaks would need to be fixed before using this in the build tests. Right now, we would have a lot of red

    ./run_all_tests.sh
    --- Testing dttools/test/TR_b64.sh ...                            success 0s
    --- Testing dttools/test/TR_buffer.sh ...                         failure 0s
    --- Testing dttools/test/TR_chunk_test.sh ...                     failure 1s
    --- Testing dttools/test/TR_data_struct_set.sh ...                failure 0s
    --- Testing dttools/test/TR_hmac_test.sh ...                      success 0s
    --- Testing dttools/test/TR_jx_count.sh ...                       success 0s
    --- Testing dttools/test/TR_jx.sh ...                             failure 0s
    --- Testing dttools/test/TR_path_basename.sh ...                  success 0s
    --- Testing dttools/test/TR_path_collapse.sh ...                  success 0s
    --- Testing dttools/test/TR_path_dirname.sh ...                   success 0s
    --- Testing dttools/test/TR_path_extension.sh ...                 success 1s
    --- Testing dttools/test/TR_path_remove_trailing_slashes.sh ...   success 0s
    --- Testing dttools/test/TR_pattern.sh ...                        success 0s
    --- Testing dttools/test/TR_stringtools.sh ...                    success 0s
    --- Testing dttools/test/TR_umr.sh ...                            success 0s
    --- Testing makeflow/test/TR_makeflow_001_dirs_01.sh ...          failure 1s
    --- Testing makeflow/test/TR_makeflow_001_dirs_02.sh ...          failure 2s
    --- Testing makeflow/test/TR_makeflow_001_dirs_03.sh ...          failure 1s
    --- Testing makeflow/test/TR_makeflow_001_dirs_04.sh ...          failure 1s
    --- Testing makeflow/test/TR_makeflow_001_dirs_05.sh ...          failure 1s
    --- Testing makeflow/test/TR_makeflow_001_dirs_06.sh ...          failure 2s
    --- Testing makeflow/test/TR_makeflow_001_dirs_07.sh ...          failure 1s
    --- Testing makeflow/test/TR_makeflow_001_dirs_08.sh ...          failure 1s
    --- Testing makeflow/test/TR_makeflow_001_dirs_09.sh ...          failure 1s
    --- Testing makeflow/test/TR_makeflow_001_dirs_10.sh ...          failure 2s
    --- Testing makeflow/test/TR_makeflow_001_dirs_11.sh ...          failure 1s
    --- Testing makeflow/test/TR_makeflow_020_line_continuation.sh ... failure 0s
    --- Testing makeflow/test/TR_makeflow_020_syntax_default.sh ...   failure 0s
    --- Testing makeflow/test/TR_makeflow_020_syntax_long_line_test.sh ... failure 2s
    --- Testing makeflow/test/TR_makeflow_020_syntax_meta2.sh ...     failure 0s
    --- Testing makeflow/test/TR_makeflow_020_syntax_meta.sh ...      failure 0s
    --- Testing makeflow/test/TR_makeflow_020_syntax_test.sh ...      failure 0s
    --- Testing makeflow/test/TR_makeflow_020_syntax_typo.sh ...      failure 0s
    --- Testing makeflow/test/TR_makeflow_020_syntax_variable_issues.sh ... success 1s
    --- Testing makeflow/test/TR_makeflow_020_syntax_variable_scope.sh ... failure 0s
    --- Testing makeflow/test/TR_makeflow_021_export.sh ...           failure 0s
    --- Testing makeflow/test/TR_makeflow_022_export.sh ...           success 0s
    --- Testing makeflow/test/TR_makeflow_023_export_wq.sh ...        failure 1s
    --- Testing makeflow/test/TR_makeflow_030_gc_none.sh ...          failure 0s
    --- Testing makeflow/test/TR_makeflow_030_gc_on_demand.sh ...     failure 1s
    --- Testing makeflow/test/TR_makeflow_030_gc_ref_count.sh ...     failure 0s
    --- Testing makeflow/test/TR_makeflow_040_recursive.sh ...        failure 0s
    --- Testing makeflow/test/TR_makeflow_linker_001.sh ...           failure 0s
    --- Testing makeflow/test/TR_makeflow_linker_abs.sh ...           failure 0s
    --- Testing makeflow/test/TR_makeflow_linker_collision.sh ...     failure 1s
    --- Testing makeflow/test/TR_makeflow_linker_complex.sh ...       failure 0s
    --- Testing makeflow/test/TR_makeflow_linker_deps.sh ...          failure 0s
    --- Testing makeflow/test/TR_makeflow_linker_dirs.sh ...          failure 0s
    --- Testing makeflow/test/TR_makeflow_linker_simp.sh ...          success 0s
    --- Testing makeflow/test/TR_makeflow_remote_naming.sh ...        failure 1s
    --- Testing makeflow/test/TR_makeflow_src_example.sh ...          failure 1s
    --- Testing makeflow/test/TR_makeflow_viz.sh ...                  failure 1s
    --- Testing makeflow/test/TR_starch_date_config.sh ...            success 0s
    --- Testing makeflow/test/TR_starch_date.sh ...                   success 0s
    --- Testing makeflow/test/TR_starch_example.sh ...                success 3s
    --- Testing makeflow/test/TR_starch_extract_and_remove.sh ...     success 1s
    --- Testing work_queue/test/TR_work_queue_foreman.sh ...          failure 16s
    --- Testing work_queue/test/TR_work_queue_multicore.sh ...        failure 2s
    --- Testing work_queue/test/TR_work_queue_single.sh ...           failure 1s
    --- Testing sand/test/TR_filter_verification.sh ...               failure 1s
    --- Testing sand/test/TR_sanity.sh ...                            failure 1s
    --- Testing allpairs/test/TR_allpairs_bitwise.sh ...              failure 1s
    --- Testing allpairs/test/TR_allpairs_composite.sh ...            failure 1s
    --- Testing wavefront/test/TR_wavefront_001_sum_test.sh ...       success 1s
    --- Testing wavefront/test/TR_wavefront_master_001_sum_test.sh ... failure 1s
    --- Testing parrot/test/TR_parrot_bind.sh ...                     failure 0s
    --- Testing parrot/test/TR_parrot_cloexec.sh ...                  failure 0s
    --- Testing parrot/test/TR_parrot_clone.sh ...                    success 1s
    --- Testing parrot/test/TR_parrot_clone_untraced.sh ...           success 0s
    --- Testing parrot/test/TR_parrot_cvmfs_access.sh ...             success 0s
    --- Testing parrot/test/TR_parrot_cvmfs_alien_cache.sh ...        success 0s
    --- Testing parrot/test/TR_parrot_dir.sh ...                      failure 0s
    --- Testing parrot/test/TR_parrot_exec_cache.sh ...               failure 3s
    --- Testing parrot/test/TR_parrot_execve.sh ...                   failure 1s
    --- Testing parrot/test/TR_parrot_fake_setuid.sh ...              failure 0s
    --- Testing parrot/test/TR_parrot_mmap.sh ...                     failure 2s
    --- Testing parrot/test/TR_parrot_msg_fd.sh ...                   failure 0s
    --- Testing parrot/test/TR_parrot_permissions.sh ...              failure 1s
    --- Testing parrot/test/TR_parrot_personality.sh ...              failure 0s
    --- Testing parrot/test/TR_parrot_procexe.sh ...                  failure 0s
    --- Testing parrot/test/TR_parrot_search_chirp.sh ...             failure 0s
    --- Testing parrot/test/TR_parrot_search.sh ...                   failure 1s
    --- Testing parrot/test/TR_parrot_thread_fd.sh ...                failure 15s
    --- Testing resource_monitor/test/TR_librmonitor_poll.sh ...      success 2s
    --- Testing chirp/test/TR_chirp_acl.sh ...                        success 1s
    --- Testing chirp/test/TR_chirp_alloc.sh ...                      success 2s
    --- Testing chirp/test/TR_chirp_benchmark.sh ...                  success 1s
    --- Testing chirp/test/TR_chirp_hdfs.sh ...                       success 1s
    --- Testing chirp/test/TR_chirp_job_python.sh ...                 skipped 0s
    --- Testing chirp/test/TR_chirp_job.sh ...                        success 3s
    --- Testing chirp/test/TR_chirp_multi.sh ...                      failure 1s
    --- Testing chirp/test/TR_chirp_ops.sh ...                        success 0s
    --- Testing chirp/test/TR_chirp_perl.sh ...                       skipped 0s
    --- Testing chirp/test/TR_chirp_proxy.sh ...                      success 4s
    --- Testing chirp/test/TR_chirp_python.sh ...                     skipped 0s
    --- Testing chirp/test/TR_chirp_rmall.sh ...                      success 0s
    --- Testing chirp/test/TR_chirp_search.sh ...                     success 1s
    --- Testing chirp/test/TR_chirp_symlinks.sh ...                   failure 0s
    --- Testing chirp/test/TR_chirp_thirdput.sh ...                   success 4s
    --- Testing chirp/test/TR_chirp_tickets.sh ...                    success 0s

    Test Results: 62 of 94 tests failed (3 skipped) in 98 seconds.

**Comment by dthain** [comment]
Any sense on how many of these are true leaks (e.g. memory increases over time) as opposed to singleton object leaks?

**Comment by nhazekam** [comment]
The ones mentioned above for Makeflow are possibly leaks where a filename isn't freed. I can not attest to any other issues, but I am working out a pull request for the makeflow issues.

**Comment by trshaffer** [comment]
I suspect that a lot of these are memory we freed by exiting. To find real leaks, we ought to e.g. run Makeflows of varying size to see how the numbers change. A PR to compile with these options is forthcoming
