### ISSUE TITLE
Make Catalog More Responsive

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1303]
Under certain conditions, the catalog server gets blocked up and doesn't respond to queries.  here is what's going on:

The catalog server works by accepting updates via udp, which is fast and non blocking.  For queries, it forks to service the request.  This makes it easy to give the client a snapshot of the catalog state as it existed when the query arrived, since we don't have to worry about updates.   However, we don't want an infinite number of catalog processes running at once, so the server has an upper limit of 50 query processes running.  When that limit is reached, it stops accepting connections.  As a result, queries are delayed until another one finishes.

Now, what's happening is that we are getting a bunch of queries from off campus.  For whatever reason, the queries are issued, but then are slow reading all of the data off of the TCP stream.  So, the catalog server process sits there, trying to fulfill the request, and the next thing you know, we have 50 blocked processes.

Currently, the catalog server tries forever to service the request.  What we need to do in the query handler is to set an alarm for, say, 15 seconds.  If the client cannot pull the data off the stream and give up.

Also, for debugging purposes, it would be nice if the catalog server would change its process title to "catalog_server [128.x.y.z]" so we can see which process is handling which client.  (See change_process_title.h)

**Comment by dthain** [comment]
I think this one is done, right?

**Comment by trshaffer** [comment]
Yep, this was already implemented
