### ISSUE TITLE
List of backup catalogs should be quoted.

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1313]
This was a fun one to find...

Workers from the wq_factory suddenly started to send "cores 1" to the master, which is the default. Here is the line that condor executes:

./work_queue_worker -M crustacean.* -t 300 -C catalog.cse.nd.edu;backup-catalog.cse.nd.edu:9097 --cores 4 --memory 256 --disk 1024

Of course, given the semicolon, only this executes:

./work_queue_worker -M crustacean.* -t 300 -C catalog.cse.nd.edu

**Comment by btovar** [comment]
Bobby Tables, et. al.

**Comment by batrick** [comment]
Why didn't we use a comma for a separator?

**Comment by btovar** [comment]
Since this is a recent pr, a comma should be easy to change without disturbing any current uses.

**Comment by dthain** [comment]
Discuss with @trshaffer ...
