### ISSUE TITLE
Project: Viz Work Queue

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1368]
Create a simple javascript visualization that pulls down json from the catalog server and displays vital statistics about each work queue master: host, port, project, and simple bar graphs of resources and performance.

**Comment by dthain** [comment]
Done!

http://ccl.cse.nd.edu/software/workqueue/status

**Comment by hmeng-19** [comment]
Not sure it is my chrome's problem, it looks each item is described as a
block occupying 5 lines.
Do you think using a single line for each item would be better, because
more items can be seen without scrolling?

**Comment by dthain** [comment]
@nkremerh can you check?

**Comment by nkremerh** [comment]
@dthain In Chrome, it appears as it was intended. If there are other perspectives on how the data is presented, we can have a conversation about that via email.

**Comment by hmeng-19** [comment]
@Nate, I saved my screen into a pdf, please take a look.

**Comment by hmeng-19** [comment]
I just retried it using a different wifi and it worked (just took some time
to load all the beautiful pictures for the first time).
It was probably the network I used this afternoon at RedHat was too slow,
and all those pictures can not be loaded (I waited at least 5 minutes
there).
