### ISSUE TITLE
Makeflow Directives

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1383]
Directives is the name of special variables that direct the execution of nodes. This is a manner of expressing information that is different from normal variables. The need for this comes from wanting to inform a dag/node about information relevant to execution such as filesizes, resources, and mounts.

Prior to this nodes were able to specify resources using variables as each resource had a single value, CORES=4, MEMORY=1024... 

However, in the case of filesizes and mounts there is additional information that needs to pulled from the line.

The proposal is to add .NAME directives so that this information can be parsed in the manner appropriate with the type of directive.

examples:
.SIZE filename size
.MOUNT source target
.CORES number  --or-- .RESOURCES CORES number

@dthain @btovar Thoughts?

**Comment by btovar** [comment]
I like .RESOURCES CORES X

**Comment by nhazekam** [comment]
This is now implemented in #1399

**Comment by nhazekam** [comment]
This is implemented and merged in #1399.
