### ISSUE TITLE
Have factory autosize workers based on category requirements

### ISSUE THREAD

**Issue by annawoodard** [cooperative-computing-lab/cctools#1392]
I know that we've discussed this idea in the past, but I don't see it in the issue tracker yet-- please close if I've missed it.

We have a number of undergrads doing HEP research this summer and using Lobster + WQ for the first time. With the fantastic progress made by the cctools team on the resource monitor, it's easier and faster than ever to spot resource allocated-vs-utilized inefficiencies. I am observing, however, that a big stumbling block for new users is determining the optimal factory configuration. The benefit of automatically adjusting the requested resources per-task is lost if the user has the per-worker factory request too low. More advanced users can spot this almost immediately with the (awesome!) `work_queue_status -A` option, but new users are often confused about why they don't have any able workers. The whole picture is complicated by certain workflows that have the ratio of various categories running changing over time. It seems that the factory resource specification itself is redundant, since the resource monitor already knows what it SHOULD be. Would it be possible to have an automatic flag that would instruct the factory to submit workers with either 1) a given multiple of the necessary resources per category or a fancier variation 2) the maximum multiple of the necessary resources per category in order to pack optimally into available slots?

I realize that added complexity comes at a cost and is not always an improvement, but in this case I think there is a potential for a huge increase in user friendliness.

@klannon @matz-e @WenzhaoLi

**Comment by Nekel-Seyew** [comment]
@btovar @nhazekam Is this still an idea we should keep, or has it been addressed? It seems like it's mostly solved via training and documentation.

**Comment by klannon** [comment]
If by "solved" you mean my problem instead of yours, then I suppose that's true, but this remains probably the biggest struggle for new users who are not used to the worker-task model as opposed to just submitting batch jobs.  They struggle to understand the distinction between worker and task resource specifications and don't understand why they should be different (or maybe I should say, when they should be different).  It would be great if worker size could be autocalculated from task size somehow (or even just guessed with some hints from user).

**Comment by dthain** [comment]
Definitely still an open problem.  It's not only about the relationship between tasks and workers, but also between workers and the batch system that they run on.  (e.g. Will I get better service asking for 20 4-core workers, or 10 8-core workers)

**Comment by Nekel-Seyew** [comment]
Oh, sorry! I didn't think about it from a more worker+task level. I was thinking more of a fit-from-largest-task perspective. But that does seem to be an open question then, comparing service performance from differently sized worker partitions.

It could be interesting to try and tie in the capacity feature on the factory as well. That way the factory and the master could communicate with one another, and the factory can get the right-sized workers created to handle most of the jobs while not overwhelming the master with too many workers.

**Comment by dthain** [comment]
Closing out old but good ideas that didn't make it into the funnel...
