### ISSUE TITLE
Feature: Modify Makeflow to send catalog updates.

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1396]
Modify Makeflow to send its own periodic updates to the catalog server, indicating the number of jobs that are blocked, ready, running, failed, and complete, with a report type of "makeflow". 

Note that this report is distinct from the WQ level report, which only sees things relevant to WQ.  The Makeflow level report should be sent whenever the -N option is given, regardless of whether WQ is enabled.  So, the options "-N projectname -T condor" would indicate that jobs should be sent to condor, while makeflow level reports are sent to the catalog.

**Comment by Nekel-Seyew** [comment]
Implemented, and created a pull request to merge my working copy with repo.
