### ISSUE TITLE
Catalog Server duplicate field error for Chirp Servers

### ISSUE THREAD

**Issue by Nekel-Seyew** [cooperative-computing-lab/cctools#1407]
In the internal Catalog list for ND (http://catalog.cse.nd.edu:9097/) Chirp servers have two fields stored: "name" and "name" which sometimes are different, and the first is probably an IP name resolution of the second. Internally, this isn't a problem, but this causes an error when retrieving the information as a JSON file, as the second instance of "name" overwrites the value of the first instance of "name".

**Comment by dthain** [comment]
Good catch!  As it turns out, I fixed this a few days ago in PR #1395 .
The fixed version hasn't been deployed yet, so the catalog server is still reporting duplicates.
