### ISSUE TITLE
[Parrot] Parrot_run fails with full IceCube simulation

### ISSUE THREAD

**Issue by bgharper** [cooperative-computing-lab/cctools#1410]
@dthain @hmeng-19 

It seems to occur fairly randomly, as sometimes it will successfully run and trace (as it did when I created the package). 

```

sh-4.1$ ./fullSimulation.py 
2016/07/20 15:05:15.71 parrot_run[506691] <child:506871> fatal: cannot run application which does not allow tracing (CLONE_UNTRACED)
2016/07/20 15:05:15.71 parrot_run[506691] <child:506871> notice: received signal 15 (Terminated), killing all my children...
2016/07/20 15:05:15.71 parrot_run[506691] <child:506871> notice: sending myself 15 (Terminated), good
bye!
 Terminated
```

Attached is a zip of the fullSimulation.py script, although it requires an icecube setup on CVMFS. [Here](https://drive.google.com/open?id=0B9jyC8sqxSFpLVZVOFdERlFuemM) is a link to the package I created in one of the successful runs (~250mb/650mb uncompressed). I recommend running as root to avoid any gid/uid issues. 

[fullSimulation.zip](https://github.com/cooperative-computing-lab/cctools/files/374598/fullSimulation.zip)

**Comment by dthain** [comment]
Ok, the first thing we need to do here is understand what application is setting `CLONE_UNTRACED`, which is an unusual request to make in the first place...

**Comment by bgharper** [comment]
Dumping an strace of a regular run shows the following calls to clone:
`clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f207cde49d0) = 508235
`
(repeated twelve times because num cpus = 12, with same flags, just different addresses and PIDs)

Where it doesn't look like it's being set by any of them by default. Dumping an strace on a (failed) parrot_run shows:

```
[billobob@uc3-c007 icecube]$ cat strace.parrot | grep -C 3 CLONE
open("/tmp/parrot.53362/parrot-instance.3c4sPk/parrot-fd.cLib53", O_RDONLY|O_DIRECTORY) = 5
dup2(5, 4094)                           = 4094
close(5)                                = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7ff64374dab0) = 509874
wait4(509874, [{WIFSTOPPED(s) && WSTOPSIG(s) == SIGSTOP}], WSTOPPED, NULL) = 509874
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_STOPPED, si_pid=509874, si_status=SIGSTOP, si_utime=0, si_stime=0} ---
kill(509874, SIGCONT)                   = 0
--
readlink("/home/billobob/stash/icecube", 0x7ffca7cb1610, 1023) = -1 EINVAL (Invalid argument)
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x391be326a0}, {SIG_DFL, [], 0}, 8) = 0
pipe([14, 22])                          = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7ff64374dab0) = 509953
close(22)                               = 0
wait4(509953, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 509953
read(14, "/stash/user/billobob/icecube", 1024) = 28
--
wait4(-1, 0x7ffca7cc8444, WNOHANG|WSTOPPED|__WALL, 0x7ffca7cc8448) = 0
ptrace(PTRACE_GETREGS, 509969, 0, 0x27d1020) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3543, ...}) = 0
write(2, "2016/07/20 16:09:49.72 parrot_ru"..., 1332016/07/20 16:09:49.72 parrot_run[509873] <child:509969> fatal: cannot run application which does not allow tracing (CLONE_UNTRACED)
) = 133
ioctl(2, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0x7ffca7ca3120) = -1 ENOTTY (Inappropriate ioctl for device)
write(4, "2016/07/20 16:09:49.72 parrot_ru"..., 133) = 133
```

**Comment by batrick** [comment]
Oops, I think the problem is that parrot is checking a flags argument for clone when fork/vfork syscalls take no argument. @bgharper, are there fork syscalls?

**Comment by bgharper** [comment]
Yes, in fact the last thing the parrot debug log shows before crashing is a vfork call

`2016/07/21 12:02:35.18 parrot_run[530916] <child:531012> syscall: vfork
2016/07/21 12:02:35.18 parrot_run[530916] <child:531012> debug: flags = 0x65D16EF4
2016/07/21 12:02:35.18 parrot_run[530916] <child:531012> fatal: cannot run application which does not allow tracing (CLONE_UNTRACED)
2016/07/21 12:02:35.18 parrot_run[530916] <child:531012> process: killing pid 531012`

**Comment by dthain** [comment]
Yup, @batrick has the right idea, and I think #1413 should fix it.
@bgharper please try the latest build (as soon as it completes):
http://ccl.cse.nd.edu/software/autobuild

**Comment by bgharper** [comment]
Indeed, that seemed to do the trick. Working fine now.

**Comment by dthain** [comment]
Glad to hear it, and please thank @batrick
