### ISSUE TITLE
Update Parrot to New libcvmfs

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1415]
Update `pfs_service_cvmfs.cc` to use the new cvmfs API:
https://github.com/cvmfs/cvmfs/pull/1634

Key bit: Set up a way to pass in arbitrary cvmfs options from the command line

**Comment by dthain** [comment]
FYI @trshaffer @btovar @jblomer

**Comment by trshaffer** [comment]
My preference would be to use JSON to pass CVMFS options into Parrot as key/value pairs. This would fit well with the v2 API, and avoid parsing and manipulating large option strings. Could we deprecate most of Parrot's CVMFS-related options and use the v2 API if it's available and the user gives a JSON config, else fall back to the existing config syntax? This should maintain backwards compatibility and encourage users to switch to JSON config

**Comment by dthain** [comment]
That works for me.

**Comment by dthain** [comment]
Finished some time ago.
