### ISSUE TITLE
work_queue_factory needs to take batch options

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1426]
Currently work_queue_factory does not take batch options from the command line. I also do not believe that it takes them from the config file either. We should have some method of adding batch options to the workers as they are submitted.

**Comment by btovar** [comment]
You can use -E to pass options to the workers, though.

**Comment by nhazekam** [comment]
The -E options tells the worker info, like cores etc... But to instruct the batch system where to/how to run is a submission side specification.

**Comment by btovar** [comment]
Correct. Your problem description seems to insinuate options to workers, rather than batch systems.

**Comment by nhazekam** [comment]
Sorry, to clarify, we need an option such as -B is used in Makeflow that specifies options for batch system work_queue_factory submits to. It should be as simple as taking an option "-B" and setting the value to batch_job with batch_job_set_option(queue, "batch-options", value)

**Comment by dthain** [comment]
@Nekel-Seyew please handle this one.

**Comment by dthain** [comment]
Whoops, I see Nick assigned himself.  Nick, did you want to handle this?

**Comment by nhazekam** [comment]
Yes. I think this is a minor fix that Ben and I are pushing through kind of
quickly.

**Comment by nhazekam** [comment]
@btovar addressed this in 5.4.19. We should also make sure to carry this over to master as it is a useful/necessary feature.
