### ISSUE TITLE
add a new field into an umbrella spec to mark the necessity of archiving it

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#1431]
Currently, `umbrella upload` uploads all the dependencies specified in an  Umbrella specification into OSF or S3. 

However, sometimes the user may want to only archive some deps with `umbrella upload`. 

Proposed plan:
Add a new optional field, named `upload`, into each dependency object to mark whether that dependency is needed to be archived or not. 
The `upload` field can be set to `true` (the default value) or `false`.

**Comment by hmeng-19** [comment]
@dthain , PTAL.

**Comment by dthain** [comment]
Ok with me

**Comment by hmeng-19** [comment]
Fixed by #1441 .
