### ISSUE TITLE
Add support for CWL to Makeflow

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1437]
Add to Makeflow the ability to input and output the Common Workflow Language:
https://github.com/common-workflow-language

**Comment by dthain** [comment]
@trshaffer since you are already working on this.

**Comment by dthain** [comment]
@trshaffer Where did the code for cwl <-> makeflow conversions end up?

**Comment by trshaffer** [comment]
I still have it, but I am **not** confident it's suitable for any kind of production use. Getting CWL to behave within Makeflow's model feels really forced, and I ended up partially reimplementing a lot of CWL's logic. It also requires the reference CWL implementation to be installed/built on all workers.

If we're just interested in running CWL through CCTools, it would be much cleaner to connect CWL to Work Queue. CC @nhazekam

**Comment by dthain** [comment]
Ok, where is the code located, so we can see?

**Comment by dthain** [comment]
After many rounds, we decided this is not the way to go.
