### ISSUE TITLE
Feature: Parrot Sterile Mode

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1449]
To facilitate expriments in reproducibility, add a new "sterile" mode to Parrot that eliminates incidental variations between runs:

- Always report the system time as 12:01, January 1st, 2000
- Always report a fixed user and group id.
- Always report the same machine and os version
- Other aspects?

Obviously, this mode would cause confusing results for system software.  But, it could be very effective at eliminating differences in simulation codes, where times and user ids are often used (improperly) to seed random number generators and the like.

**Comment by btovar** [comment]
(sorry, hit wrong button)

**Comment by dthain** [comment]
#1459 addresses the time issue.

**Comment by dthain** [comment]
@pivie If you try out the new pull request, you should be able to play around with these settings:
```
$ ./parrot_run --time-stop --uid 0 --hostname earth -- bash
[root@earth src]# 
```
Going even farther, you could map /dev/urandom to consistent values with `--mount /dev/urandom /tmp/junk`

**Comment by dthain** [comment]
Fixed and in use.
