### ISSUE TITLE
Work Queue Cache Recovery

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#145]
Lee-Ping would like a mode in which the worker does not delete its cache directory, since the worker may be evicted but return to the node later.

Upon restart, the worker would connect to the master, then iterate over the contents of the cache directory, verifying that each file present matches what the master has, deleting those that do not match.

This would allow the master to stage very large expensive files once, and not re-transmit them in the event of a transient failure.

**Comment by Nekel-Seyew** [comment]
@btovar I don't know if I would recommend closing this issue from 4 years ago. It's a good idea that someone hopefully should get around to doing, but if I'm not mistaken, this is going to be covered in WorkQueue 2 no?

**Comment by dthain** [comment]
@leeping It is my pleasure to inform you that this issue has been fulfilled (after 10 years!) in our new system, [TaskVine](http://ccl.cse.nd.edu/software/taskvine).  Would be happy to work with you to on migrating your applications!
