### ISSUE TITLE
On resource exhaustion, makeflow should not delete the resource summary file

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1451]
When a rule fails, it deletes all of its outputs. This includes the resource summary file. This is not advantageous, as the summary provides information about the failure (e.g., which resources where exhausted).

**Comment by dthain** [comment]
I seem to recall running into this issue before -- you can't debug a job at all if its outputs are deleted.

But, we don't want the (presumed bad) output files to confuse Makeflow when determining how to resume.

Maybe all of the outputs of a failed job should be moved into a specific directory `makeflow.failed.${JOBID}` so that the user can examine them in isolation?

**Comment by btovar** [comment]
That sounds like a good idea. In addition, it would not treat the summary file in any special way.

**Comment by nhazekam** [comment]
I think that approach sounds reasonable and also provides a clear manner
for users to inspect failed tasks.

**Comment by floreal797** [comment]
This is a big problem for me. As said before, it's impossible to debug without output. I see it was deleted from milestone 6.1... this problem will be solved? In near future?

**Comment by dthain** [comment]
@floreal797 Sorry, I think we overlooked the importance of this since the github issue didn't reflect that you were waiting on it.

@trshaffer Please fix this one ASAP.  Let's have makeflow tell the user that job X failed and its outputs can be found in directory `makeflow.failed.XXXXX`

**Comment by floreal797** [comment]
I try with the master branch, as a solution was committed. The makeflow.failed.0 is created but is empty. But there were some outputs created (declared in the Makeflow file). They are still lost.

This is my Makeflow file:
/home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/BuildPop_default/logs.stdout /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/BuildPop_default/logs.stderr /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/BuildPop_default/pop/INDIV_1_100_300_1.fq.gz /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/BuildPop_default/pop/INDIV_2_100_300_1.fq.gz /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/BuildPop_default/pop/INDIV_1_100_300_2.fq.gz /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/BuildPop_default/pop/INDIV_2_100_300_2.fq.gz: /home/fcabanettes/jflow_results/cnvreferenceprepare/wf000516/GstripFinalOutputs_default/reference.fasta /home/fcabanettes/jflow_results/cnvreferenceprepare/wf000516/GstripFinalOutputs_default/reference.Nstretch.bed /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/.working/e749bdb633/_Stash/0/0/0/w0000000
@SYMBOL="BuildPop.default"
        /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/.working/e749bdb633/_Stash/0/0/0/w0000000 /home/fcabanettes/jflow_results/cnvreferenceprepare/wf000516/GstripFinalOutputs_default/reference.fasta /home/fcabanettes/jflow_results/cnvreferenceprepare/wf000516/GstripFinalOutputs_default/reference.Nstretch.bed None 2 15 0 0 1e-06 100 300 30 20 8 /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/BuildPop_default/logs.stdout /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/BuildPop_default/logs.stderr /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/BuildPop_default/pop/INDIV_1_100_300_1.fq.gz /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/BuildPop_default/pop/INDIV_2_100_300_1.fq.gz /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/BuildPop_default/pop/INDIV_1_100_300_2.fq.gz /home/fcabanettes/jflow-work/work/cnvsimpop/wf000074/BuildPop_default/pop/INDIV_2_100_300_2.fq.gz

**Comment by dthain** [comment]
@trshaffer please work with @floreal797 on this.

**Comment by trshaffer** [comment]
@floreal797 could you send me your Makeflow file via email (tshaffe1@nd.edu)? Github's comment box isn't rendering it well. Also, are you using a batch system like Condor, or Work Queue?

**Comment by floreal797** [comment]
I send you a mail just now. In my test I don't use any batch system (makeflow -T local). I will also use it with SGE batch system in the future, but I don't have tested it yet.

**Comment by nhazekam** [comment]
I am reopening, auto closed with the merging of the last branch. Let us know if this resolves the issue.

**Comment by floreal797** [comment]
Yeah, it solved the problem, now I have the outputs in the directory! Thank you so much for the fix!

**Comment by nhazekam** [comment]
Glad to hear! Thanks @trshaffer.
