### ISSUE TITLE
chirp server freezes when backend processes are not terminated

### ISSUE THREAD

**Issue by khurtado** [cooperative-computing-lab/cctools#1457]
When a chirp server is started, it triggers backend processes like the one below and is eventually terminated. Sometimes, such backend processes are not terminated and stay hanging there (below and example of one of the processes authenticated with x509 proxies)...

```
uscms01  1020529  0.0  0.0  54168  3572 ?        S    Aug30   0:32 chirp_server
uscms01  3173912  185  0.6 19771872 410500 ?     Sl   08:07   0:07 chirp_server [10.32.82.9:54186] [globus:/DC=ch/DC=cern/OU=Organic_Units/OU=Users/CN=lannon/CN=490792/CN=Kevin_Patrick_Lannon]
```

At that point, all the server does is to send TCP RST signals to client requests and the server can't be restarted by killing just the PID of the server. All backend processes have to be killed by hand, otherwise chirp says the following:

```
2016/08/30 07:26:37.28 chirp_server[865823] notice: * /afs/crc.nd.edu/group/ccl/software/cctools/x86_64/redhat6/bin/chirp_server starting at Tue Aug 30 07:26:37 2016
2016/08/30 07:26:39.42 chirp_server[865823] fatal: couldn't listen on port 9094: Address already in use

```

Below are some details about the parameters used to run the chirp server

[Chirpd server details]
The chirp server is running as a user with the following parameters:

```
daemon --pidfile $CHIRP_PID --user uscms01 $CHIRP_BIN --inherit-default-acl --root=hdfs://${CHIRP_HDFS_HOST}:${CHIRP_HDFS_PORT}${CHIRP_HDFS_LOCATION} -A $CHIRP_DEFAULT_ACL -p $CHIRP_PORT -b -d "$CHIRP_DEBUG_LEVEL" -a globus -o $CHIRP_LOG -O $CHIRP_MAX_ROTATE -M $CHIRP_MAX_CLIENTS -B $CHIRP_PID
```

with:

```
CHIRP_DEFAULT_ACL=/etc/chirp_acl
CHIRP_LOG=/var/log/chirp/log.debug
CHIRP_PORT=9094
CHIRP_MAX_CLIENTS=600
CHIRP_MAX_ROTATE=0
CHIRP_DEBUG_LEVEL='auth'
CHIRP_HDFS_PORT=19000
CHIRP_HDFS_LOCATION='/'
CHIRP_HDFS_HOST='eddie.crc.nd.edu'
```

**Comment by batrick** [comment]
There are two problems here:

* The `chirp_server` children serving a client are keeping the listening socket open (the one listening on 9094). The children should `link_close` that socket here:

https://github.com/cooperative-computing-lab/cctools/blob/2e7ea7ec69dfd8cb2959155e122c8c3ccc34a2c1/chirp/src/chirp_server.c#L2315-L2316

* The `chirp_server` process is not properly cleaning up its children on signal. That's also documented in this issue: https://github.com/cooperative-computing-lab/cctools/issues/602

**Comment by dthain** [comment]
@batrick I'm not sure I follow your explanation -- in the child process `chirp_receive` uses the link and then calls `_exit(0)` which will close the socket when the process terminates.  In the other cases following `fork`, the link gets closed.  Am I missing something?

**Comment by dthain** [comment]
Aha, you are quite right -- thanks.

**Comment by dthain** [comment]
I think we have fixed as much as we know how to fix on this one.
