### ISSUE TITLE
Work Queue Temporary Files

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#146]
Per Lee-Ping, add a mode to Work Queue to optimize the case of a large file that is generated by one task and then consumed by another, but is not necessary to return back to the submission point.

This can be done by adding a flag WORK_QUEUE_TEMPORARY to a file, which indicates that the master should remember its presence, but not transfer it back.  A task that indicates the same file as an input dependency must then be matched to the worker that has the file.

Complication: What happens if a worker storing a temporary file crashes and loses the file?

**Comment by Nekel-Seyew** [comment]
@btovar I think the primary requested functionality of this is handled by the request of #145 and a shared file system. This can probably be closed.

**Comment by dthain** [comment]
@leeping and likewise here, [TaskVine](http://ccl.cse.nd.edu/software/taskvine) has the ability to manage temporary files on workers that are not brought back to the manager.
