### ISSUE TITLE
WQ Filename Sanitation 

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1463]
When using WQ-MAKER we are running into an issue where the directory structure created by MAKER doesn't get handled correctly. The directory name is:

 LNKV01_iso11.1.fsa_nt_Shomeocarpa_genome_assembly_DNA.maker.output/|961591432|gb|LNKV01000257.1|        LNKV01_iso11.1.fsa_nt_Shomeocarpa_genome_assembly_DNA_datastore/45/CE

The issue seems to be that |s and spaces aren't being handled correctly and it complains that the file doesn't exist.

2016/09/05 20:00:21.25 [10353] notice: Cannot stat file LNKV01_iso11.1.fsa_nt_Shomeocarpa_genome_assembly_DNA.maker.output/|961591432|gb|LNKV01000257.1|        LNKV01_iso11.1.fsa_nt_Shomeocarpa_genome_assembly_DNA_datastore/45/CE: No such file or directory

@btovar thoughts.

**Comment by btovar** [comment]
I'm not sure this is a work queue problem. 
For example:

my $name = "LNKV01_iso11.1.fsa_nt_Shomeocarpa_genome_assembly_DNA.maker.output/|961591432|gb|LNKV01000257.1| LNKV01_iso11.1.fsa_nt_Shomeocarpa_genome_assembly_DNA_datastore/45/CE";

# This works fine:

my $t = Work_Queue::Task->new(qq(mkdir -p "$name" && touch "$name/hello")); 
$t->specify_output_file("$name/hello");

# This does not (not that the names are not quoted in the command line given):

my $t = Work_Queue::Task->new(qq(mkdir -p $name && touch $name/hello)); 
$t->specify_output_file("$name/hello");

From wq-maker perspective, I wonder if you have to: qq($some_name) every filename in a command line.

**Comment by btovar** [comment]
@nhazekam: is this a wq issue?

**Comment by nhazekam** [comment]
I think that we determined that it was a MAKER/filesystem issue, not wq.
