### ISSUE TITLE
Makeflow- Umbrella : When umbrella wrapper is used locally, the umbrella.log is left behind

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1468]
We should log this, allow the user to specify a pattern to be used for each tasks logs, and clean this when it is done. By default it should either always be collected with a name such as umbrella_%%.log, or it should be disable. @hmeng-19 I will leave this up to you for the next pull request on Umbrella in Makeflow.

**Comment by hmeng-19** [comment]
@nhazekam , PTAL.
#1491 should fix this.

**Comment by hmeng-19** [comment]
@nhazekam , for testing this feature, `cctools/makeflow/example/makeflow_umbrella` will be a good example.

**Comment by nhazekam** [comment]
Fixed in #1491 .
