### ISSUE TITLE
parrot error with RH7, tar and symbolic links

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1476]
Per David Schultz:

I'm having a problem that seems specific to the RHEL7 build of cctools.  I've tested with the last few releases with the same result.

If I have a directory with symlinks, where the symlinks appear before the file they are linked to:

[dschultz@dyn-12-232 ~]$ ls -al test
total 4
drwxrwxr-x. 2 dschultz dschultz   65 Sep 15 17:21 .
drwx------. 8 dschultz dschultz 4096 Sep 15 17:21 ..
lrwxrwxrwx. 1 dschultz dschultz   16 Sep 15 17:21 libtest.so -> libtest.so.1.0.0
lrwxrwxrwx. 1 dschultz dschultz   16 Sep 15 17:21 libtest.so.1 -> libtest.so.1.0.0
-rw-rw-r--. 1 dschultz dschultz    0 Sep 15 17:21 libtest.so.1.0.0

I can create a tarball without error, but when trying to untar while inside parrot_run, it gives these errors:

[dschultz@dyn-12-232 ~]$ cctools-6.0.0-x86_64-redhat7/bin/parrot_run tar -zxf test.tar.gz
tar: test/libtest.so: Cannot utime: No such file or directory
tar: test/libtest.so.1: Cannot utime: No such file or directory
tar: Exiting with failure status due to previous errors

It works just fine if parrot_run is not used.  Any ideas?

(I was able to reproduce it on cclvm05.crc.nd.edu-- Ben)

**Comment by trshaffer** [comment]
There's a typo in Parrot's `lutimens` implementation, such that it tries to follow symlinks and change the time on the target. Depending on the order `tar` does things, the target might not have been created, hence the `ENOENT`. Newer builds (that support the `*at` family) go down this code path, hence the RHEL7 specificity. I just submitted a PR to fix this

**Comment by btovar** [comment]
Excellent, thanks Tim!
