### ISSUE TITLE
Chirp Server Crashes on Ticket Auth

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1477]
This succeeds: `chirp -a hostname disc02.crc.nd.edu`

This fails: `chirp -a ticket -a hostname disc02.crc.nd.edu` b/c the chirp server crashes after accepting the ticket authentication method, but having no tickets to deal with.

This is a high priority to fix, since the default configuration (no -a options) tries the ticket method and causes the crash, even when the user does nothing special.

**Comment by btovar** [comment]
On it.
