### ISSUE TITLE
missing implementations of several dag funcs

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#1489]
I noticed that `dag.h` includes the prototypes of `dag_input_lookup_or_create` and `dag_output_lookup_or_create`, however, I can not find their imeplementations in `dag.c`.

**Comment by hmeng-19** [comment]
@nhazekam , @btovar , @dthain , PTAL.

**Comment by dthain** [comment]
Dead code should be removed!  Haiyan, please fix it and make a pull request.

**Comment by hmeng-19** [comment]
@dthain , just want to make it clear. 
Your point is that makeflow no longer provides these interfaces. Right?

**Comment by dthain** [comment]
If the prototype serves no purpose, remove it.

**Comment by hmeng-19** [comment]
#1490  should fix this.
@dthain , PTAL.

**Comment by hmeng-19** [comment]
Fixed by #1490 .
