### ISSUE TITLE
wq_factory only works with project names

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1504]
Explicit host names are needed when makeflow is run with --work-queue-preferred-connection=by-ip

As reported by @bbockelm.

**Comment by bbockelm** [comment]
Actually, I don't think it's a `makeflow` issue.  I want to be able to manage the hostname `work_queue_factory` utilizes.  For example, from my cluster headnode, I get:

```
$ work_queue_factory -T slurm -N project-bbockelm
2016/10/19 09:40:11: |submitted: 0 |needed: 8 |waiting connection: 0 |requested: 5 
PROJECT            HOST                   PORT WAITING RUNNING COMPLETE WORKERS 
masters:
project-bbockelm   external.example.com         9001       4       0        0       0 
```

Where `external.example.com` is the external hostname and firewalled off.  However, if I run the `hostname` command itself, it returns `internal.example.com`.

I should be able to override the hostname used explicitly - and it might be better to default the hostname used by the catalog server to be the same as the output of `gethostname()`.  It seems the catalog server uses the default hostname from the address returned by `getpeername()` on the TCP connection.

**Comment by btovar** [comment]
You are correct. I mentioned that makeflow option to eliminate 'just use a project name' solution.

Thanks for the extra info...
