### ISSUE TITLE
string_cookie has crummy randomness

### ISSUE THREAD

**Issue by bbockelm** [cooperative-computing-lab/cctools#1506]
I noticed `string_cookie` (whose random string is used `link_auth_password`) has really poor entropy.  It's actually based on `rand` (yuck!).  It weakens the handshake for the authentication.

It seems that `random_hex` could be a drop-in replacement for this usage.

Note that `random_hex` and friends still don't meet cryptographic standards for generating key material, but might be OK in this case.

**Comment by dthain** [comment]
@trshaffer please take a look at this one.
