### ISSUE TITLE
Ability to ask workers to report metric

### ISSUE THREAD

**Issue by niravmerchant** [cooperative-computing-lab/cctools#1507]
Hi Ben @btovar per our conversation, I am filling this feature request.
It would be good if the master could request:
1. Run commands like uptime, df -h , ps etc to see activity and metrics on a worker. Currently we do a lot of that using ansible, but doing it natively will be great (from master)
2. It would be great to connect master and worker using public private key (allow workers to be submitted with public keys), this also will make #1 more secure.

Let me know if you need more specifics.

Regards,
Nirav

**Comment by dthain** [comment]
Closing out some stale issues -

1 - Is partially available in TaskVine via top level resource monitoring.
2 - SSL connection has been supported for some time in both WQ and TaskVine.
