### ISSUE TITLE
jx fails to parse integers as doubles.

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1511]
Example from work_queue_factory:

This works:

"tasks-per-worker": 4.0

This does not:

"tasks-per-worker":4

I propose for jx_double to accept numbers without a decimal point.

**Comment by dthain** [comment]
The problem isn't quite clear to me.

The parser will interpret the former as `jx_pair(jx_string("tasks-per-worker"),jx_double(4.0))` and the latter as `jx_pair(jx_string("tasks-per-worker"),jx_integer(4))`

JX distinguishes between integer and floating point numbers b/c they have rather different arithmentic properties, and some odd things can happen if you represent integer division with floating division.

Perhaps we just need a helper method to cast either case of a number of the desired type?

**Comment by btovar** [comment]
Indeed. I was trying to fix the wrong thing. See #1514.
