### ISSUE TITLE
parrot packaging tool fails on some python3 programs

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#1512]
Problem:
Last week Tim showed me that he failed to reproduce a python program using
parrot packaging tool on his Arch Linux. After some testings, we realized that
parrot packaging tool can still reproduce python2 applications on his machine,
however, cannot reproduce python3. I also sufferred the same problem on my own
Arch Linux.

Cause:
Since python3.2, `__pycache__` was introduced into python to hold the bytecode
files (i.e., .pyc files) potentially for multiple python versions to save the
loading time, and the import mechanism was changed since then.  The first time
a module is loaded, a corresponding pyc file will be added into the
`__pycache__` dir.  

Let us say we have a python module: `/usr/lib/python3.5/codecs.py`, the python
bytecode: `/usr/lib/python3.5/__pycache__/codecs.cpython-35.pyc` (which
includes the modification time of `/usr/lib/python3.5/codecs.py` to determine
whether the bytecode is stale or not) will be created the first time this
module is loaded.

When we try to load the `codecs` module, the python runtime first does an
`stat` syscall on `/usr/lib/python3.5/codecs.py` to get the modification time,
then read `/usr/lib/python3.5/__pycache__/codecs.cpython-35.pyc` to see whether
it is stale or not.  If the pyc file is latest, then the .py file will not be
opened.

You can find the PEP doc for this change: https://www.python.org/dev/peps/pep-3147/ 
You can find the new module load float chat here: https://www.python.org/dev/peps/pep-3147/#flow-chart

When we use parrot package tool to preserve a python3 program, lots of python
modules may have already been compiled and their .pyc files already exists and
are not stale. Therefore parrot pacakging tool will mark the .py file as
metadata copy, and only create an empty file with the metadata info (permission
mode and modification time and access time) inside the created package.

Notice: currently, the metadata info parrot packaging tool copies from the
original files does not include the `st_size` info due to some wierd behavior on
AFS. 

Now, when we rerun a python3 program inside the package created by parrot
packaging tool, we run into an edge case the PEP does not mention (I take a
guess here and justify my guess by some testings): the python runtime `stat` the
.py file, and then `open` the .pyc file, `read` the modification time of the .py
file from it, determine it matches the .py file inside the package, however,
the st_size field of the .py file inside the package is 0.  The python runtime
becomes skeptical, and thinks the .pyc is stale. And then the python runtime
tries to recompile the .py file and replace the .pyc file.  However, the .py
file is empty, this recompiling attempt can only fail.

To verify my guess that the ignoring setting the st_size field for metadata
copy is the root cause, I modified the parrot packaging tool by using
`truncate` to set the size of the metadata-copy files (including .py files
mentioned above), and now the python3 program can be reproduced using our
parrot packaging tool.

However, I am not 100% sure that this is the ultimate solution to this problem.
We should ask ourselves, do we intend to preserve these .pyc files or not?

I also found out that you can disable creating .pyc files by setting some
specific environment variables (`export PYTHONDONTWRITEBYTECODE=True`),
however, this disabling only stops creating new .pyc files. The old .pyc files
which have already existed on your system will still have their influence. In
lots of cases, non-root users can not delete the .pyc files under system dirs like
`/usr/lib/python3.5`.

**Comment by hmeng-19** [comment]
@dthain , @trshaffer , PTAL.

**Comment by dthain** [comment]
This is #1513 right?

**Comment by hmeng-19** [comment]
@dthain , yes. 
I did not refer #1513 here, because I am not sure #1513 is the eventually thing I want to do. 
This issue speaks a bigger problem than #1513 tries to solve.

**Comment by hmeng-19** [comment]
Fixed by #1513.
