### ISSUE TITLE
Script for RH6/RH7 Auto-Select

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1520]
@Nekel-Seyew please work up a little script that will allow the user to run an arbitrary program on RHEL6 or RHEL7, running it natively if possible, and deploying Singularity only if needed.  Something like this:

```
runos rhel6 myprogram x y z ...
runos rhel7 myprogram x y z
```

The CRC is already deploying a mix of RHEL6 and RHEL7 machines, and we have cases where 7 code needs to run on a 6 machine, and vice versa.  If you get this going quickly, there will be lots of people using it...

@klannon

**Comment by dthain** [comment]
The condor matrix shows a big sea of green, mainly because we have a large number of machines running RH7, so the need for this is very high right now...

http://condor.cse.nd.edu/condor_matrix.cgi

**Comment by Nekel-Seyew** [comment]
I have a script and 2 Images, one running CentOS6 and one running CentOS7, simply running the task through singularity, and assuming that Singularity v2.2 is available on the machine.

I'm still working on a solution if Singularity isn't available for the system.

**Comment by dthain** [comment]
We aren't concerned about the case where singularity isn't installed at this point.

The main point is to either exec `singularity image command` if the os doesn't match, or just `command` if the os does match...

**Comment by dthain** [comment]
Deployed in `/afs/crc.nd.edu/group/ccl/software/runos`
