### ISSUE TITLE
Show the resource usage of Work Queue worke

### ISSUE THREAD

**Issue by charleszheng44** [cooperative-computing-lab/cctools#1528]
Can we make `work_queue_status -A HOST PORT` show resource usage information, when running Makeflow `wq` mode with resource monitor? The current output looks like,
```
CATEGORY        RUNNING    WAITING  FIT-WORKERS  MAX-CORES MAX-MEMORY   MAX-DISK 
default           52        948           52        ???        ???        ??? 
```

**Comment by dthain** [comment]
My understanding is that this information gets filled in as tasks complete.
But it won't be observed while the task is running.
Is this still a problem?

**Comment by dthain** [comment]
@btovar I believe that resource reporting works as intended now, yes?
