### ISSUE TITLE
Take advantage of shared filesystems with Makeflow

### ISSUE THREAD

**Issue by annawoodard** [cooperative-computing-lab/cctools#1541]
This is a feature request. I am running an HEP analysis with Makeflow+WQ+Condor. Part of my workflow runs over a large collection of input files which are several gigabytes each, stored in an HDFS filesystem which is accessible to all machines in our cluster. I would like to be able to tell Makeflow about these files by specifying them as inputs, so I can take advantage of nice Makeflow features like re-running downstream rules if one if its input files are modified. Running over this collection of inputs is an "embarrassingly parallel" problem, but parallelization is broken because absolute paths are forbidden-- WQ+condor must be run in transfer mode, so the input files are transferred in series. @dthain suggested you might be able to add a command line switch which would allow me to tell WQ that any file under a given path is globally accessible to the workers and does not need to be transferred. His idea has the advantage that it preserves the status of the Makeflow script as a complete description of the workflow which is independent of the batch system.

In case it's helpful, you can find an example Makeflow script for the workflow I'm referring to here: `/afs/crc.nd.edu/user/a/awoodard/www/ttV/6/1/1/Makeflow`.

**Comment by annawoodard** [comment]
@hmeng-19 see the path above in case it is useful for the Umbrella test. Ping me if I can be helpful in any way.

**Comment by hmeng-19** [comment]
@annawoodard , thanks. I will give it a try.

**Comment by dthain** [comment]
What we need here is a command line argument like this:

```
makeflow -T condor --shared-fs /afs --shared-fs /hadoop
```

The effect of the argument will be quite simple: files inside directories that are indicated as shared filesystems will not be added to the input or output lists of a batch job, when it is constructed from a `dag_node`.  The effect is that makeflow will still "manage" the file at the DAG level, but not pass it down to the batch level.

**Comment by dthain** [comment]
@trshaffer please take a look at this one, I think it is a quick fix and will have a big impact on Anna's work.

**Comment by dthain** [comment]
@trshaffer please add to the manual and man pages, and discuss with @annawoodard to see if it meets her needs...
