### ISSUE TITLE
Allow wrappers to apply to groups of Makeflow rules

### ISSUE THREAD

**Issue by annawoodard** [cooperative-computing-lab/cctools#1542]
This is a feature request. In a demonstration of just how convoluted my workflow is, I need different wrappers for various rules in my Makeflow script. After discussion with @hmeng-19 we decided a wrapper was the right tool for the job here rather than umbrella because I'm just setting up environment variables. It would be convenient to be able to specify different wrappers for groups of rules in the Makeflow script, in an analogous way to how umbrella specifications are handled.

**Comment by dthain** [comment]
Out of curiosity, are you using some kind of script to generate your Makeflow?

**Comment by annawoodard** [comment]
@dthain: Yes.

**Comment by dthain** [comment]
Closing out old ideas that didn't make the funnel.

This isn't feasible without major changes to the Makeflow architecture.

**Comment by dthain** [comment]
Closing out old but good ideas that didn't make the funnel...
