### ISSUE TITLE
an issue about the http timeout setting in makeflow mount module 

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#1550]
Currently, the http timeout value in the makeflow mount module (used via the `--mounts` option) is hard-coded as 300 seconds, which is too short if a dependency is huge or the user runs multiple instances of a makeflow concurrently.

**Comment by hmeng-19** [comment]
@btovar , @dthain , 
Currently, the mount module depends on `http_fetch_to_file`, and does not support https deps (I do not think `dttools` includes any library for fetching files via https.)
I have two options: libcurl and wget.
Using libcurl we need to either assume the machine has libcurl installed in a standard path or import libcurl into cctools somehow.
Using wget we need to assume `wget` is available on the machine.
Currently, I plan to use the `wget`. Let me know if you have any thoughts on this.

**Comment by dthain** [comment]
Or possible `curl`.  Is one used more widely than the other?

**Comment by hmeng-19** [comment]
@dthain , take a look at here https://daniel.haxx.se/docs/curl-vs-wget.html

**Comment by hmeng-19** [comment]
@dthain , the thing I would like go with `wget` is:
"Its ability to recover from a prematurely broken transfer and continue downloading has no counterpart in curl."

**Comment by dthain** [comment]
Ok, that's fine with me.
