### ISSUE TITLE
Resource monitor greatly overestimated number of cores

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1554]
20 cores were measured for a task, which seems unlikely.﻿⁠⁠⁠⁠

Logs:

earth:/tmpscratch/users/klannon/mcprod_ttW_alpha1273_filtered/v0/

As reported by @klannon

**Comment by matz-e** [comment]
I'm seeing this too… Requires resetting the master to finish processing, as the number of cores will exceed any worker connected (ever).

**Comment by btovar** [comment]
On it.

**Comment by btovar** [comment]
Was your master running on earth?

**Comment by matz-e** [comment]
Yes…
