### ISSUE TITLE
Parrot doesn't know about magic symlinks under /proc/*/ns/

### ISSUE THREAD

**Issue by trshaffer** [cooperative-computing-lab/cctools#1559]
On recent kernels, the process namespaces are visible as symlinks, for example on my RHEL6 workstation

    [tshaffe1@cclws19 ~]$ ll /proc/self/ns/
    total 0
    dr-x--x--x. 2 tshaffe1 dip 0 Dec  1 13:14 .
    dr-xr-xr-x. 8 tshaffe1 dip 0 Dec  1 13:14 ..
    lrwxrwxrwx. 1 tshaffe1 dip 0 Dec  1 13:14 ipc -> ipc:[4026531839]
    lrwxrwxrwx. 1 tshaffe1 dip 0 Dec  1 13:14 mnt -> mnt:[4026531840]
    lrwxrwxrwx. 1 tshaffe1 dip 0 Dec  1 13:14 net -> net:[4026531954]
    lrwxrwxrwx. 1 tshaffe1 dip 0 Dec  1 13:14 pid -> pid:[4026531836]
    lrwxrwxrwx. 1 tshaffe1 dip 0 Dec  1 13:14 uts -> uts:[4026531838]

These symlinks don't point to anything in the filesystem; the value returned by `readlink()` is just text referring to an inode number. A syscall that follows symlinks will nonetheless successfully resolve these.

    [tshaffe1@cclws19 ~]$ stat -L /proc/self/ns/ipc 
      File: `/proc/self/ns/ipc'
      Size: 0         	Blocks: 0          IO Block: 1024   regular empty file
    Device: 3h/3d	Inode: 4026531839  Links: 1
    Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
    Access: 2016-12-01 13:21:04.199953881 -0500
    Modify: 2016-12-01 13:21:04.199953881 -0500
    Change: 2016-12-01 13:21:04.199953881 -0500

As noted in #1548, Parrot tries to follow these symlinks and returns `ENOENT` from calls that should have succeeded.

**Comment by dthain** [comment]
However, note this:
```
$ cat /proc/self/ns/ipc
cat: /proc/self/ns/ipc: Invalid argument
```

**Comment by trshaffer** [comment]
I noticed that path resolution gets short-circuited if the path begins with `/proc/self/` or `/dev/fd/`, while paths beginning with `/proc/$PID/` are handled normally. This issue only occurs if `stat`ing under a PID, but not under `/proc/self/`. Also, the short-circuit allows bypassing mountlists and access restrictions using paths like `/proc/self/../../whatever`. Is this the intended behavior?

**Comment by dthain** [comment]
The idea is that parrot rewrites `/proc/self` to `/proc/PID` otherwise it would accidentally read information about itself, rather than the process currently being traced.

**Comment by trshaffer** [comment]
Should that happen **after** name resolution? At the moment chunks of Parrot's functionality get silently skipped under those directories.

**Comment by trshaffer** [comment]
Merged, so closing this issue
