### ISSUE TITLE
Redesign makeflow log

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#159]
The main purpose of the log is to restart an interrupted makeflow run. However, there at least three aspects of the interrupted run that are ignored by the log:

- The value of the environment variables at the time of the run.
- The parameters to the monitor.
- The state of garbage collection.

For the first two, makeflow should at least print a warning that the values might be different. For the third, gc works after a node is completed, which means that if gc is activated after the interrupted run, some files are not deleted.

**Comment by dthain** [comment]
Addressed by pr #790
