### ISSUE TITLE
Compressed file support in Work Queue

### ISSUE THREAD

**Issue by pivie** [cooperative-computing-lab/cctools#1597]
I would like to propose a new feature for Work Queue.

I have some large compressible datasets. I currently compress and decompress them in each task because spending an extra minute decompressing in every task is faster than spending an extra half hour transferring uncompressed with 1000 workers. It is also cumbersome to bundle compression and decompression code into the task.

For example, one of the datasets is 3,135MB uncompressed and 922MB compressed. Let's say I am using 1000 4-core workers. It is much faster to skip the 30 extra minutes in linear transfer time (2213MB * 1000 workers / 10Gbps) in favor of spending 88 minutes in aggregate (79 seconds to decompress * 4000 tasks) because that takes only 79 seconds in parallel. However, this gets even worse if the compressed file is kept in the cache and is reused for new tasks (which happens a lot for this workflow), since it has to be decompressed for every task.

Would it be possible to provide a decompression command (like 'tar -xf remote_file_name.tar.gz') for files? I am volunteering to add the feature if it wouldn't cause problems in Work Queue. The worker would decompress the file and keep the decompressed copy in the cache, rather than the compressed copy.

**Comment by btovar** [comment]
Perhaps something like:

work_queue_specify_file(mytask, mybigfile, mybigfile, WORK_QUEUE_INPUT, WORK_QUEUE_CACHE | WORK_QUEUE_SEND_COMPRESSED) ?

The file would be compressed by the master, and decompressed by the worker in the cache directory. The tasks would be non-the-wiser regarding whether the file was sent using compression.

**Comment by btovar** [comment]
Also, note that the above cannot be done at the task level, as the uncompressed file would be written in the task directory, rather than the shared cache.

**Comment by dthain** [comment]
If the goal here is to minimize transfer time and not storage, I would suggest that it be compressed/decompressed on the fly in the WQ protocol via zlib.

**Comment by btovar** [comment]
One issue of doing it on the fly is the added load to the master, as the compression would be done more than once per file.

**Comment by nhazekam** [comment]
Now this is not addressed in the above discussion, aside from Peter original post, but is there any merit to allowing the specification of a different compression command? The reason I ask is that CJ Grady on the lifemapper project wrote his own compression program for his data. This is a really niche case, but I just think it may be useful. 

I believe he currently just has it as part of the command currently to always send and receive it as compressed, but that may be old info.

**Comment by dthain** [comment]
So, this is where user expectations get a little tricky.  I think we need to distinguish a few separate controls:

Is the data at the master compressed or uncompressed?
Is the data in transit compressed or uncompressed?
Is the data at the worker compressed or uncompressed?

(You could use a three letter code like CCU to indicate that data at the master is compressed, in transit compressed, and uncompressed at the worker.)

So, look at the possibilities:
CCC - Doesn't need our help, user just provides .gz files.
UCU - Master compresses, worker uncompresses, files are uncompressed in the cache.
UCC - Master compresses the files as they go out, worker just dumps compressed files in the cache. (Presumably the task knows how to read them.)
CCU - User provides gz files, master transmits them unmodified, worker stores them uncompressed.
CUC - Don't do this.  :)
UUU - Current situation.

**Comment by btovar** [comment]
I would say:

UUU as the default. 
CCU on a per file basis. This avoids work queue managing the local storage of compressed files.

To declare files:
work_queue_specify_file(mytask, "name-when-compressed", "name-when-UNcompressed", WORK_QUEUE_INPUT, WORK_QUEUE_CACHE | WORK_QUEUE_DECOMPRESS_FILE);

To expand the files:
We could add libz support to the worker.

We coult add a protocol message that tells the worker how to expand the file, transmit the corresponding tools if needed, etc:

Use tar found at the PATH (worker side):
work_queue_add_decompression(q, "*.tar.gz$", "tar zxf {}", NULL, NULL);

Use specific tar:
work_queue_add_decompression(q, "*.tar.gz$", "/bin/tar zxf {}", NULL, NULL);

Use some other tool, send it along when a file needs it:
work_queue_add_decompression(q, ".*$", "./mypax -r < {}",  "/oth/bin/pax",  "mypax");

**Comment by dthain** [comment]
UCU is also an attractive use case: that allows the user to just flip a switch enabling network compression, without changing of their own behavior.

+1 for making the libz support an integrated feature.  I suspect adding hooks for commands to execute on files will result in a great deal of confusion.

**Comment by pivie** [comment]
UCU would be convenient and at least better than UUU, however, it would be
nice to be able to control or recommend the level of compression. Depending
on the file sizes and the number of workers, xz would be well worth it
(compared to gzip) if available on the master (I believe the worker would
still just need 'tar -xf' to unzip it). This might also alleviate some of
the confusion around compressed folders. I never know if I need to
uncompress into a folder, or if the folder was already included in the
compressed file.

However, speaking personally and from a Big Data perspective, storing
compressed on the master would be nice also. I usually only want to look at
specific intermediate files, not all of them, so manually unzipping for
those specific cases is better for disk storage.

That being said, I recognize that many users of Work Queue like to have
more control over things in the case of custom compression algorithms.
Perhaps we could set up a compression template system where compression
algorithms can be defined like this (similar to Ben's approach, but the
zip/unzip commands are coupled and given a user friendly name):

q.define_compression('gzip9', 'GZIP=-9 tar czvf $NAME.tar.gz $NAME', 'tar
-xf $NAME.tar.gz')

Users could create their own template if desired, and the templates could
be used like this:
t1.specify_file("fileA.txt.tar.gz", "fileA.txt", WORK_QUEUE_OUTPUT,
zip='gzip9', cache=True);
t2.specify_file("fileA.txt.tar.gz", "fileA.txt", WORK_QUEUE_INPUT,
unzip='gzip9', cache=True);

Or this for UCU:
t3.specify_file("fileA.txt", "fileA.txt", WORK_QUEUE_INPUT, zip='gzip9',
unzip='gzip9', cache=True);

Although I recognize that optional parameters are more messy in C.

**Comment by dthain** [comment]
Closing a stale issue: interesting but not a hot priority.
