### ISSUE TITLE
Configure which IP is bound/advertised

### ISSUE THREAD

**Issue by PerilousApricot** [cooperative-computing-lab/cctools#1615]
Hello!

I'm currently getting my feet wet w/cctools (and Lobster) at Vanderbilt, and I've stumbled into a difficulty in our firewalls.

Our interactive nodes are dual-homed with interfaces on `129.59.197.0/24` and `10.0.0.0/16`, and all of our worker nodes live within the private `10.0.0.0/16` range. Any host that is dual homed has its default route set to the external interface and its hostname is set to the public FQDN. If I run a simple lobster example then check the catalog server, I see the following (trimmed) output:

```
$ work_queue_status
PROJECT                      HOST                             PORT WAITING RUNNING COMPLETE WORKERS 
lobster_meloam_20170221      vmps13.accre.vanderbilt.edu      9000      10       0        0       0 
```

Unfortunately, our local security policy requires that we block all external access to the interactive nodes, so trying to connect to (e.g.) `vmps13.accre.vanderbilt.edu:9000` won't work. To be able to use WQ here, we'd want to somehow tell WQ/the catalog that the preferred address to connect to is the internal one, which we also have DNS configured for, if that helps:

```
$ dig +short vmps13.vampire
10.0.20.238
```

If the workers tried to connect to ` vmps13.vampire`/`10.0.20.238` instead of `vmps13.accre.vanderbilt.edu`/`129.59.197.183`, then the connection would work okay.

Would it be possible to tell WQ masters what IP address they should advertise? I think it would be most helpful if it could be configured via environment variables which could be set in login script instead of having to remember to add the command line option each time. Or, perhaps it would be possible for the WQ/catalog to advertise/track all the ip addresses on the host, then let the clients try each one in succession.

Thanks!

**Comment by btovar** [comment]
@nhazekam, any ideas from your experience?

**Comment by nhazekam** [comment]
There are a couple of different solution that may help resolve this.

The first and easiest to try is explicitly specifying the internal IP, of the master, at the workers. i.e. You could directly connect to the without using the Notre Dame catalog.

work_queue_worker 10.0.28.238 9000

The second option would be to try the work_queue_master_preferred_connection option in WQ. You may need to add this to the queue setup in Lobster, but this was used for something similar at Stampede. The two options are IP or HOSTNAME. IP will pass the IP to the worker through the catalog and is what is used by default. The hostname passes the master hostname to be resolved by the worker. If the hostname internally resolves correctly this may solve the problem.

The last solution that occurs to me is to create a catalog server inside of the firewall. From inside the firewall the master should resolve to the internal IP and the workers should get the internal IP. The catalog server executable is part of the CCTools software, so you should have that available directly.

Let me know if these address what you are trying to do, and if they work please let us know.

Nick

**Comment by annawoodard** [comment]
If the first option works, it seems like that would be optimal. How do you tell a factory to explicitly specify the internal IP when starting workers?

**Comment by PerilousApricot** [comment]
It would depend on how you implement it. Typically a server will bind to the catchall `0.0.0.0` address. You can change it to bind to a specific IP instead. I don't know how that works with the 2nd part -- when the master updates the catalog with its own information. Since the master needs to tell the catalog where the workers can reach it anyway, it may be sufficient to continue binding to the catchall address, but just advertise the user-chosen one.

**Comment by dthain** [comment]
Here is the thing we have to be careful of.

When any process advertises itself to the catalog, the catalog fills in or overrides the IP address in that report with the observed address of the sender.  This prevents reporters from lying or spoofing about their address.

However, it breaks when we have multi homed or translated addresses.

We need to make sure that the solution does not create an opportunity for spoofing.

**Comment by nhazekam** [comment]
What version of CCTools are you using?

I believe there is a patch in MASTER that added the ability of the factory to specify IP and port back into it. Instead of specifying -N master_name you can also specify hostname/IP port to the factory. If you don't know the IP prior to running you may need to use one of the other solutions, but if you find the IP and then create the factory that should work. I don't believe this has been released yet, but should be in a release soon.

As for the issue with spoofing, in the first case we already trust was was passed to the worker so that already is allowed. The second case just lets the worker resolve to its observed IP as opposed to the catalog's observed IP. The third case gives the Catalog and the worker the same perspective so they both have the same observed IP. I think that one of these proposed solutions should be able to resolve this. This of course may not always be true, but it may work in this situation.

**Comment by annawoodard** [comment]
> I believe there is a patch in MASTER that added the ability of the factory to specify IP and port back into it. 

Ah, thanks @nhazekam! Checking out the latest master and recompiling, I see it now:

```
[earth] ~/software/cctools>work_queue_factory -h
Use: work_queue_factory [options] <masterhost> <port>
or
     work_queue_factory [options] -M projectname
```

**Comment by nhazekam** [comment]
Glad you were able to grab it. I believe it will also be in the next stable release, though @btovar would have to confirm that.

Nick

**Comment by PerilousApricot** [comment]
Nope, bad click.

**Comment by PerilousApricot** [comment]
This is probably my misunderstanding, but does hardcoding the master IP/port in the factory mean I'd have to start a new factory for each new master I started up, instead of just leaving a single long-running factory running somewhere?

**Comment by nhazekam** [comment]
You are understanding that correctly.

Though that is a shortcoming, finding out if that works wouldn't be a
terrible idea if neither of the other solutions work as they are now.

**Comment by btovar** [comment]
So, we need a way for the master its preferred address, and a way for the catalog to verify that. Can we do that given the setup of the firewall? This is a problem we are likely to face more often in the future.

**Comment by btovar** [comment]
Also, perhaps we can make an exception, and allow the master to indicate its preferred address if such address is private (i.e., {10,172,192.168}.*).

**Comment by dthain** [comment]
So, I think that would fix it nicely in Andrew's specific case, but may not generalize.

Let me throw out a few observations:

1 - Machines may commonly have multiple addresses, so perhaps we should publish all of them.
2 - Users may not necessarily be familiar with the hardware, and may be surprised that they are dealing with multiple network namespaces.
3 - The address that you want to connect to may depend upon where you are in the network.

**Comment by PerilousApricot** [comment]
Does the password authentication solve/sidestep the problem of rogue masters/workers? People can lie about their address all they want, but w/o the password, they can't do anything, right?

**Comment by btovar** [comment]
For 1) A first step would be to allow many addresses at the worker's command line. I suggest something like: 
work_queue_worker x.x.x.x:pppp;y.y.y.y:qqqq


By default, the master reports only one address, as we have done so far. We would add an API call that indicates which network interfaces should be considered (e.g., work_queue_bind_to(q, "eth0:eth1")). 

When the master reports multiple local addresses to the catalog, the catalog turn the addresses into something like the above command line argument, which then the worker can process.

**Comment by dthain** [comment]
I like this approach, because it relieves any component of the necessity of choosing which address is "best".  (There is probably no universal technique for doing so.)  Just publish all the known addresses, and let the worker try them all, in some order.  It also allows the case where you have some workers on the public network, and some on the private network.

**Comment by btovar** [comment]
I like it. I would add the API call so that a user can select a desired interface.
