### ISSUE TITLE
Running cvmfs-enabled parrot_run on a server with cvmfs mounted by FUSE

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#1629]
Currently, running cvmfs-enabled parrot_run on a server (e.g., `earth.crc.nd.edu`) with cvmfs installed by FUSE does not behave elegantly.

Here is an example illustrating this problem:
```
hmeng@earth ~/test/cms_umbrella$ parrot_run ls /cvmfs/cms.cern.ch/
2017/03/20 11:38:21.50 parrot_run[1040246] <child:1040247> notice: CVMFS requires an http proxy.  None has been configured!
2017/03/20 11:38:21.50 parrot_run[1040246] <child:1040247> notice: CVMFS requires an http proxy.  None has been configured!
2017/03/20 11:38:21.50 parrot_run[1040246] <child:1040247> notice: CVMFS requires an http proxy.  None has been configured!
ls: cannot access /cvmfs/cms.cern.ch/: No such file or directory
```

There are several potential solutions to tackle this problem:
1) change the parrot_run code to detect whether /cvmfs is mounted by FUSE: if yes, parrot_run disbles its cvmfs module and use the cvmfs on the server directly; if no, parrot_run delivers cvmfs.

2) add a new option into parrot_run to allow the users to disable the cvmfs module, this should also silent the following warning when the user is running sth irrelavant to cvmfs.
```
2017/03/20 11:38:21.50 parrot_run[1040246] <child:1040247> notice: CVMFS requires an http proxy.  None has been configured!
```

3) ignore it. Let the user to suffer and figure out they would need two versions of parrot_run on a machine with cvmfs installed by FUSE. This one is not very nice.

**Comment by hmeng-19** [comment]
@dthain , @trshaffer , @btovar , PTAL.

**Comment by trshaffer** [comment]
I'd be in favor of adding an option to disable a given service, since I don't like trying to guess what the user wants to do. If there are no objections, I can put in a quick pull request on this

**Comment by hmeng-19** [comment]
@trshaffer , adding a new option sounds good to me. 
It will be great if you have time to fix this. Thanks very much.
