### ISSUE TITLE
allow Umbrella users to set SITECONF for cms apps 

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#1645]
Background:
Run cms applications using parrot in Umbrella requires a `SITECONF` directory which includes the site configuration files (https://twiki.cern.ch/twiki/bin/view/CMSPublic/SiteConfInGitlab).

Problem:
Currently, umbrella does not allow the users to specify the `SITECONF` dir, instead it utilizes a frozen copy of `SITECONF`.

Solution:
Add a new option into umbrella to allow the users to set SITECONF for cms applications.

**Comment by hmeng-19** [comment]
@dthain , PTAL.

**Comment by pivie** [comment]
This is definitely an issue. Otherwise I may need to switch to Singularity to do Monte Carlo production.

**Comment by hmeng-19** [comment]
@pivie , #1653  should fix the issue here.
