### ISSUE TITLE
wq_maker: -disk and -memory options

### ISSUE THREAD

**Issue by nathanweeks** [cooperative-computing-lab/cctools#1647]
In cctools/apps/wq_maker/wq_maker, lines 381-387

```
	$task->specify_cores($cores);
	if($disk){
		$task->specify_cores($disk);
	}
	if($memory){
		$task->specify_cores($memory);
	}
```

Should that be:

```
	$task->specify_cores($cores);
	if($disk){
		$task->specify_disk($disk);
	}
	if($memory){
		$task->specify_memory($memory);
	}
```

**Comment by nhazekam** [comment]
Thanks for letting us know. I'm currently working on a branch and well
address this asap. I'll mention this issue with the pull request tonight.

**Comment by nhazekam** [comment]
This should have been addressed, please reopen if you have more comments.
