### ISSUE TITLE
Remove Autobuild Platforms

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1658]
@btovar please remove rhel5-x86_64 and osx-i386 from the current autobuild configuration and web page.

**Comment by btovar** [comment]
Changes were pushed to autobuild, waiting to confirm nothing is broken.

**Comment by dthain** [comment]
Whoops, I think you took out too many.  Let's keep i686-redhat6 for now.
http://ccl.cse.nd.edu/software/autobuild/

**Comment by btovar** [comment]
done
