### ISSUE TITLE
Variables used in loop condition not modified in loop body

### ISSUE THREAD

**Issue by charleszheng44** [cooperative-computing-lab/cctools#1661]
The function `text_array_save_range` in dttools/src/text_array.c has a nested for loop, and the variables 'y' and 'h' used in the first loop condition not modified in loop body `for(j = y; y < (y + h); j++) `. Is that correct?

**Comment by dthain** [comment]
Actually, I think I fixed this a few days ago on master, can you check?

**Comment by charleszheng44** [comment]
Yes. It is fixed in the latest master
