### ISSUE TITLE
Taking the absolute value of unsigned type 'uint64_t'

### ISSUE THREAD

**Issue by charleszheng44** [cooperative-computing-lab/cctools#1664]
In `dttools/src/histogram.c` lin 95, we assign `ceil(value/h->bucket_size)` to `unit64_t b`, and in line 96, we try to get the absolute value of b by using `b = abs(b)`. When I compiling the cctools I got warning `taking the absolute value of unsigned type 'uint64_t'`. Is `b = abs(b)` redundant?

**Comment by dthain** [comment]
Sure sounds like it.  Newer compilers are able to find inconsistencies for us.
