### ISSUE TITLE
work queue graph log doesn't work

### ISSUE THREAD

**Issue by cguccione1** [cooperative-computing-lab/cctools#1674]
work_queue_graph_log (filename).mf.wqlog created this line:
gnuplot> 1271.143505 6.528339
         ^
         line 0: invalid command

gnuplot> EOF
         ^
         line 0: invalid command
and no graph was produced.

**Comment by btovar** [comment]
could you send me your log? (at btovar at nd.edu)
also, could you send me the output of gnuplot --version  ?

**Comment by btovar** [comment]
Your log seems ok, as it worked for me.  How are you calling the script?

**Comment by nhazekam** [comment]
@btovar I think you are correct about the gnuplot version, as the installed gnuplot is version 4.2 and I think this relies on version 5. @cguccione1 You may want to touch base with some one in the office about using cclimport, as that is the quickest way to get the correct version.

**Comment by btovar** [comment]
I know version gnuplot 4.6 patchlevel 1 works. 

Indeed, I just tried with a 4.2, and it failed. I'll add a check for that.

**Comment by btovar** [comment]
Could anybody tell Caitlin how to set the correct gnuplot path?

**Comment by dthain** [comment]
@cguccione1 see the software instructions here:
http://ccl.cse.nd.edu/internal/storage.php

**Comment by btovar** [comment]
@cguccione1, thanks for the report!
