### ISSUE TITLE
cctools fails to compile at NERSC cori cluster (SuSE Linux Enterprise Server)

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1679]
In particular, one of our users needs parrot + cvmfs. It build be nice if we can provide a binary too.

**Comment by dthain** [comment]
@btovar Please update if this is working now

**Comment by btovar** [comment]
It works now. It seems that some environment variables were affecting the configure script. Using the vc3-builder (wget  https://github.com/vc3-project/vc3-builder/blob/master/vc3-builder) I was able to compile it, and generate a binary as:

./vc3-builder  --require cctools
name=cctools-nersc-${VC3_MACHINE_ARCH}
tar --xform="s:${VC3_ROOT_CCTOOLS}:${name}:" -zPcf ${name}.tar.gz ${VC3_ROOT_CCTOOLS}

**Comment by btovar** [comment]
Actual recipe used at nersc. All the --sys and cmake load are there to save time, as the builder could compile that too.

module swap PrgEnv-intel PrgEnv-gnu
module load cmake

./vc3-builder --require cctools --revar '.*' --sys perl:5.18=/usr --sys python:2.7.9=/usr --sys cmake:3.3.2=/usr/common/software/cmake/3.3.2 --install clean --sys patch:2.7.5=/usr --sys openssl:1.1.0=/usr  --var TERM=xterm
