### ISSUE TITLE
shared-fs + remote file renaming fails

### ISSUE THREAD

**Issue by annawoodard** [cooperative-computing-lab/cctools#1680]
Hi experts! Sorry if I'm missing something obvious here, but is it possible to mix remote file renaming and the (extremely useful!) `--shared-fs` option?  I'd like to be able to use renaming and avoid having to copy files around when I can. Of course I could add a clause to the command, but I'd prefer to have Makeflow handle it if possible. You can find a minimal example in case it's helpful at `/afs/crc.nd.edu/user/a/awoodard/shared-fs-test`. The first two rules are successful and the third fails. 

```
[earth] ~/shared-fs-test >cat Makeflow
1.txt->remote.txt:
	echo foobar > remote.txt

/afs/crc.nd.edu/user/a/awoodard/shared-fs-test/2.txt:
	echo foobar > /afs/crc.nd.edu/user/a/awoodard/shared-fs-test/2.txt

/afs/crc.nd.edu/user/a/awoodard/shared-fs-test/3.txt->remote.txt:
	echo foobar > remote.txt
```

```
[earth] ~/shared-fs-test >makeflow -T wq -M ttV_FTW --shared-fs '/afs/crc.nd.edu/user/a/awoodard/'
parsing ./Makeflow...
checking ./Makeflow for consistency...
./Makeflow has 3 rules.
recovering from log file ./Makeflow.makeflowlog...
starting workflow....
listening for workers on port 9000.
submitting job: echo foobar > remote.txt
submitted job 1
submitting job: echo foobar > /afs/crc.nd.edu/user/a/awoodard/shared-fs-test/2.txt
submitted job 2
submitting job: echo foobar > remote.txt
submitted job 3
warning: this work queue master is visible to the public.
warning: you should set a password with the --password option.
job 1 completed
echo foobar > remote.txt did not create file /afs/crc.nd.edu/user/a/awoodard/shared-fs-test/3.txt
job 2 completed
job 3 completed
workflow failed.
```

**Comment by dthain** [comment]
@trshaffer Could you please take a look at how these two features interact with each other?

**Comment by trshaffer** [comment]
This might be possible. Unfortunately, it's incompatible with our current implementation. I think Makeflow should just error out on trying to use remote renaming on a shared fs.

The `--shared-fs` option only exists within Makeflow; it prevents Makeflow from passing files down to the batch system. The `batch_job` interface between Makeflow and Work Queue doesn't have any way to specify options on individual files. We'd probably need to extend that interface and add handling to `batch_job_work_queue` (and there's no real reason not to allow it on all the backends).

@nhazekam and I were talking about it, and more conceptually, these two features seem incompatible. Most batch job backends don't support it because it's not really a general-purpose renaming feature. Work Queue and Condor don't assume a shared filesystem, so we have a feature to change the name of a file mid-transfer. With `--shared-fs`, you're telling Makeflow not to do a transfer at all, so there's nowhere for remote renaming to take effect. To support these two features together, we would need to expand the scope of remote renaming as a general feature for rearranging files. Thoughts @dthain?

**Comment by dthain** [comment]
I think it comes down to a question of where the renaming is applied.

I was under the assumption (perhaps incorrect) that the mountlist feature was applied at the whole-dag level before execution began.  And that was different from the per-file renaming feature applied at the level of a single rule by sending the remapping down to the batch system.  Am I misunderstanding something?

**Comment by dthain** [comment]
Oh, sorry, I didn't read the example carefully enough.  I got stuck on the mountlist feature and didn't see that remote renaming was in effect.

It seems to me that a request for remote renaming indicates that the user *does* want the file transferred, right?  Is the shared-fs decision done at a point where we can simply special-case "but not if the file must be renamed?"

**Comment by btovar** [comment]
You are correct, but the request for '--shared-fs'  explicitly required to bypass of all of the makeflow checkings, even the mountlist (no need to mount, as the absolute path is the target path anyway).

**Comment by btovar** [comment]
I think we have to be careful here.  Remote renaming and absolute paths seem incompatible with each other. Makeflow would not be able to guarantee that two tasks will be writing to the same file at the same time (before the renaming back). As it is right now, makeflow can detect when two absolute paths are the same.

We could make it work by imposing a sequential order on nodes that share a remotely renamed absolute path, but I am not sure this is something desirable.

**Comment by dthain** [comment]
You are quite right about writing shared output files.  But we never supported that anyway.

What about reading shared input files?

**Comment by btovar** [comment]
If I remember correctly, writing to shared output files is used in the vectorbase makeflows.

**Comment by dthain** [comment]
Yikes!

**Comment by btovar** [comment]
Also, note that Anna's example, unless I misunderstand, is asking for renames in the output files.

**Comment by dthain** [comment]
I think we are over-thinking this.

@trshaffer is there any reason we can't just adjust this function to check for "if on a shared filesystem and not renamed" ...
https://github.com/cooperative-computing-lab/cctools/blob/master/makeflow/src/makeflow.c#L446

Am I missing something?

**Comment by trshaffer** [comment]
That's an easy fix. I'm inclined to error out to avoid unexpected performance changes, though. I can put in a PR for this

**Comment by trshaffer** [comment]
@annawoodard this PR ought to work for your use case above. Let me know!

**Comment by annawoodard** [comment]
Thanks for the help, everyone, and the quick fix, @trshaffer! I have tested and can confirm that the use case above is working.

After reading the discussion, I understand now that my question was misguided: I was not considering the 'remote' part of 'remote file renaming' (that it is something that really only applies to makeflow-transferred files) and instead thinking of it as a general feature for rearranging files (which it isn't, as @trshaffer pointed out). I think such a feature would be useful, but understand if it's beyond the current scope. The fix in #1681 means that any renamed files won't be able to take advantage of `shared-fs`. For my own use case, being able to use `shared-fs` to keep makeflow transfers from being a bottleneck trumps the convenience of file renaming, so I'll just add a clause to my command to take care of it. It's possible a user might have a mix of rules with renaming and those without where allowing both with `shared-fs` would make sense. My only minor feedback would be to add a printout statement informing the user if a file has been marked for transfer due to file renaming which otherwise would not have been because of `shared-fs`. I see that a note has been added to the documentation, but don't overestimate us users, we sometimes don't read as carefully as we should...

**Comment by annawoodard** [comment]
Although note that now that I understand that file renaming is meant just for makeflow-transferred files, I think it would be just as reasonable to error out if the user tries to mix renaming and `shared-fs`.

**Comment by trshaffer** [comment]
After the discussion and @annawoodard's comments, I've **disallowed** this in my PR. We could look at introducing more general renaming features down the road, but for the moment @nhazekam and I would prefer to be conservative with this and error out rather than introduce performance surprises
