### ISSUE TITLE
Resource Monitor Rounds Up Aggressively on Cores

### ISSUE THREAD

**Issue by klannon** [cooperative-computing-lab/cctools#1685]
You can consider this either a bug report of a feature request.

Based on my observations, it seems that the resource monitor rounds pretty aggressively when calculating the number of cores used.  The end result is that if I submit a N-core application, it usually gets measured as using N+1 cores.  I haven't checked exhaustively, but it seems like applications that use 400.3% CPU (according to top) get measured as 5 cores.  I appreciate that when trying to enforce resource limits, a conservative approach is probably justified.  However, it seems like rounding 4.003 CPUs to 5 is maybe overboard.  It seems like 4.1 or 4.2 could safely be rounded down to 4.

What do you think?

**Comment by btovar** [comment]
Yes, let's think about something more sensible.

**Comment by btovar** [comment]
Fixed by #1710
