### ISSUE TITLE
Update Manuals 

### ISSUE THREAD

**Issue by cguccione** [cooperative-computing-lab/cctools#1692]
http://ccl.cse.nd.edu/software/manuals/man/makeflow.html
The Amazon section in the manual above does not specify that -T amazon should be used as well.

http://ccl.cse.nd.edu/software/manuals/makeflow.html#ec2
In the manual in the link above it says -ec2 should be used to call Amazon when really -amazon works.

**Comment by dthain** [comment]
Fixed by PR #1701
