### ISSUE TITLE
Explicit Message When Worker Idles Out?

### ISSUE THREAD

**Issue by klannon** [cooperative-computing-lab/cctools#1693]
This is a feature request (assuming the feature doesn't already exist! :smile: ) based on discussions between myself and Bryan Harris (@t172).

When a worker decides to shut down for any reason (presumably mostly because it has idled out, but maybe there are other reasons), it would be good if it sent a final "goodbye" message to the master which would get logged in the appropriate log (transactions?) so that we could distinguish between workers that were killed or otherwise died unexpectedly from workers that decided to terminate.

I won't be hurt if you close this issue without addressing it.  I'm just suggesting it because it seems like it would help Bryan with his current study trying to separate evictions from workers just deciding to shut down.

**Comment by btovar** [comment]
The goodbye message is already sent, and printed to the debug log. In the case of @t172, we just need to write that message as a transaction in transactions.log, or something like that.
