### ISSUE TITLE
what's the default value for cores ?

### ISSUE THREAD

**Issue by zeronot** [cooperative-computing-lab/cctools#1704]
Hi,
     the default cores number is 1 ????
     my local machine has such the following recource information :
CPU(s):                28
On-line CPU(s) list:   0-27
Thread(s) per core:    2
Core(s) per socket:    14
socket : 1 

if I set CORES=20 , it is bigger than this machine maxium value .so It's ok for makeflow ?

**Comment by btovar** [comment]
It depends on which version you are using, and which batch system you are using.

In the currently released version (6.1.1), and executing jobs locally (no -T command line argument, or -Tlocal), the CORES value is ignored.  If -Tcondr, -Tsge, -Twq, etc.,  CORES is used to make sure the task fits in a given executing node. If one of CORES, MEMORY, or DISK is not specified, the task takes the whole node.

In the current development snapshot (i.e., git master branch), and jobs executing locally, CORES=1 if not specified, and MEMORY and DISK=0 if not specified. makeflow tries to guess how many cores are in the machine, so if you set CORES=32, but the machine has only 16, the task won't be executed. You can bypass the makeflow guess with --local-cores, --local-memory and --local-disk.

**Comment by btovar** [comment]
The new released version 6.1.3  follows the behavior of 'current development snapshot' described above.

**Comment by zeronot** [comment]
@btovar 
I use makeflow version 7.0.0  .
in the front of mf file , I  set : 
.MAKEFLOW CATEGORY Mutect2 
.MAKEFLOW CORES 10
.MAKEFLOW CATEGORY Mutect2 
out : input  
       java -jar   GATK.jar -T Mutect2  -nct 20 .....

I assigned 10 cores by Makeflow (-Tlocal）,every core have two CPU threads in my local machine. 
but I  checked my load average value（htop)  is just  3-4. So I guess  the cmd can not use the specified 
resource setting (-nct 20)  because of the Makeflow problem??

**Comment by zeronot** [comment]
makeflow version 7.0.0  (released 2017-07-18 10:11:41 +0000)

**Comment by btovar** [comment]
I am not sure what is your expectation... Makeflow simply is doing resource management by not simultaneously running tasks whose declared resources would add to more than the available resources. It does not do anything with your threads or processes in a task. In particular, it is your job to set -nt and -nct accordingly.

If a task does not effectively use the 10 cores, makeflow cannot do anything about it.

**Comment by zeronot** [comment]
Hello,I just wanna konw whether Makeflow rescource management will limit  the use of "-nct 20"  resource setting from cmd ?  and in other words any effects to the resource setting of cmd ?

**Comment by btovar** [comment]
In general, it can't by itself.  Each application has its own mechanisms by which it limits or throttles resources. If you want to match the cores hint given to makeflow and that of your application, you can use shell syntax, as:

java -jar GATK.jar -T Mutect2 -nct '$((CORES*2))'  .....

Assuming you want '20' when cores is '10'.

To help you better, could you describe in general terms what are you trying to do?

**Comment by WinterLi1993** [comment]
I just wanna improve GATK speed by -nct 20 , but I found  there is no effects via the makeflow （CORES 10).
So  I asked the question about resource limits.  maybe the problem is GATK-Mutect2 ? not makeflow ..

**Comment by btovar** [comment]
Correct. At most makeflow can _*limit*_, but not improve execution speeds of a single task.

**Comment by WinterLi1993** [comment]
because of makeflow limit ,so -nct 20 is useless for GATK-Mutect2 ?

**Comment by btovar** [comment]
If -nct 20 does not have the effect you want _*outside*_ makeflow (e.g., if you directly type the GATK task at the command line), then that would not change _*inside*_ makeflow.
