### ISSUE TITLE
Add JSON/JX to Examples

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1709]
The makeflow examples should be augmented with equivalent `.json` and `.jx` files alongside the `.mf` files, so we can start to show people how to use these formats.

**Comment by dthain** [comment]
@AndrewLitteken I beleive you have already done this, can you please issue a pull request with your changes?

**Comment by nhazekam** [comment]
This exists in both `makeflow/examples/` and in makeflow-examples with https://github.com/cooperative-computing-lab/makeflow-examples/pull/15.
