### ISSUE TITLE
Update inline JX Expressions

### ISSUE THREAD

**Issue by nkremerh** [cooperative-computing-lab/cctools#1712]
The JX expression on line 278 of Work Queue Status is out of date since the syntax has changed.

**Comment by dthain** [comment]
Ah, I didn't realize the recent JX changes deprecated `&&` in favor or `and`.
Could this break anything else?

**Comment by trshaffer** [comment]
Since JX is a Python subset now, it uses `and` and `not` and such. I didn't realize there are snippets of JX hard-coded places. I can search around the codebase and see if anything else is out of date
