### ISSUE TITLE
Include C-style logical operators

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1721]
As mentioned in #1720, add c-style logical operators to jx_parse_string. 

Currently valid are the python: `and or not`

Proposed addition would be: `! || &&`

**Comment by dthain** [comment]
@AndrewLitteken please take a crack at this one, it's a relatively small patch to the code.

**Comment by nhazekam** [comment]
Just an update, currently being addressed in #1767
