### ISSUE TITLE
any method can hide the source code when using MakeFlow ?

### ISSUE THREAD

**Issue by WinterLi1993** [cooperative-computing-lab/cctools#1725]
HI, 
  I am using makeflow to run my pipeline .but I found  it must generate a makeflow file  so that it show the source code of pipeline . So  I wanna know which method can hide the pipeline souce code .

Best

**Comment by btovar** [comment]
Sorry, I don't understand the question. Could you post an example of what you get today, and what you want instead?

**Comment by WinterLi1993** [comment]
HI,
  when we use makeflow , we must create a mf file including our pipeline workflow code. So hope MakeFlow can support to run the makeflow  without generating mf file .

**Comment by trshaffer** [comment]
Are you trying to avoid using disk, or is this a privacy issue, or something else? Makeflow needs to get its input from *somewhere*. You could use something like a named pipe (see `man mkfifo`) to stream input from a script and avoid disk writes, but that doesn't address privacy concerns.

**Comment by dthain** [comment]
Closing unclear question.
