### ISSUE TITLE
Parrot lock file issue while trying to use cvmfs at NERSC

### ISSUE THREAD

**Issue by khurtado** [cooperative-computing-lab/cctools#1737]
Using parrot at NERSC by setting up the lock dir somewhere inside the user's home area (e.g the default for the builder running from bosco), it fails

I can reproduce this with the options below at NERSC, inside a RH6 shifter image:

```
export HTTP_PROXY=http://cache01.hep.wisc.edu:3128
export PARROT_TMP=/global/homes/b/btovar/parrot_test/cvmfs_lock
$PWD/bin/parrot_run -d cvmfs -t $PARROT_TMP ls /cvmfs/cms.cern.ch
```

The error given is below. Setting -t /tmp/xxx instead works.
```
2017/09/15 09:07:01.80 parrot_run[154777] <child:154779> cvmfs: Using libcvmfs version: 2
2017/09/15 09:07:01.85 parrot_run[154777] <child:154779> cvmfs: setenv CERNVM_UUID=`parrot-6-0-0'
2017/09/15 09:07:01.85 parrot_run[154777] <child:154779> debug: Using CVMFS global options: cache_directory=/global/homes/b/btovar/parrot_test/cvmfs_tmp/parrot_btovar,lock_directory=/global/homes/b/btovar/parrot_test/cvmfs_lock/parrot-instance.CI3Tkf/cvmfs_locks_vZfpxR,alien_cache,change_to_cache_directory,log_prefix=libcvmfs
2017/09/15 09:07:01.90 parrot_run[154777] <child:154779> cvmfs: [ERROR] could not acquire lock (524)
2017/09/15 09:07:01.90 parrot_run[154777] <child:154779> cvmfs: ERROR: failed to initialize cvmfs (-4)
ls: cannot access /cvmfs/cms.cern.ch: No such file or directory
srun: error: nid05273: task 0: Exited with exit code 2
srun: Terminating job step 6833581.0
```

For Ben:
This can be reproduced in your NERSC home area: ` cd ~/parrot_test ; sbatch run.slurm`

**Comment by dthain** [comment]
Hypothesis: The NERSC $HOME filesystem is a distributed filesystem that doesn't support POSIX locking.

Could you send us the output of `df $HOME` to check?

**Comment by khurtado** [comment]
@dthain 

```
cori07:~/parrot_test> df $HOME                       
Filesystem        1K-blocks        Used   Available Use% Mounted on
tlhome2        109521666048 60593466624 48928199424  56% /global/u2
cori07:~/parrot_test> cat /etc/fstab| grep global\/u2
tlhome2              /global/u2           gpfs       rw,nosuid,nodev,dev=TSAILUN2.nersc.gov:tlhome2,ldev=tlhome2,noauto 0 0
```

**Comment by dthain** [comment]
A quick browse of the CVMFS source suggests that it is using `flock` internally.  I have done a quick search to understand whether GPFS supports flock, but I haven't found anything authoritative yet.

@khurtado could you try running the  command line `flock $HOME/test true` as a quick test to see if the filesystem supports that kind of lock?

(if it doesn't, I'm not sure that there is much we can do.)

**Comment by khurtado** [comment]
This is what I get

```
> flock --verbose $HOME/test true
flock: getting lock took 0.000006 seconds
flock: executing true
```

**Comment by dthain** [comment]
@jblomer Can you help us out with this one?
What might cause CVMFS to emit this when the lock dir is in GPFS?

```
2017/09/15 09:07:01.90 parrot_run[154777] <child:154779> cvmfs: [ERROR] could not acquire lock (524)
2017/09/15 09:07:01.90 parrot_run[154777] <child:154779> cvmfs: ERROR: failed to initialize cvmfs (-4)
ls: cannot access /cvmfs/cms.cern.ch: No such file or directory
```

**Comment by jblomer** [comment]
This use of `flock` is a remnant from the Fuse module, which is picky about the concurrent use of the cache.  If alien caches are used, the "lock directory" can safely point to a different, local directory, such as /tmp. The 524 error code means "not supported".

That reminds me, the option setting and mounting got saner with the 2.4 release.  Much of the code for libcvmfs and the Fuse module is the same now, unlike in earlier versions.  Before we update the "libcvmfs-stable" branch I anyway wanted to talk to you to test the result with parrot, but that's for a different thread.

**Comment by khurtado** [comment]
@dthain @jblomer 
I realized I should have tried `flock` inside shifter, since that's where I noticed the issue. The error 524 is indeed showing up like that

```
> shifter --image=docker:benediktriedel/spt_test_shifter:latest flock $HOME/test1 true
flock: /global/homes/b/btovar/test1: Unknown error 524
```

**Comment by dthain** [comment]
I see, so something in the shifter->gpfs stack is not supporting file locks..
This is looking like not our bug, but is there something we can do better to detect/display it?

**Comment by khurtado** [comment]
From the user's perspective, it took me a while to figure out why this wan't working. When I ran this inside shifter as a vanilla slurm job and no `-t` option added, everything was working (because it was using `/tmp` by default), but when I tried through the builder doing the exact same thing, no `-t`, it didn't (because it tried the gpfs fs).

There were no warnings or errors at all, so it wasn't until I added debug mode that I was able to tell what the issue was. It would be nice to display an error message from parrot that says "Hey, your cvmfs request won't work" and the exit rather than silently failing except when in debugging mode.

**Comment by dthain** [comment]
Hmm, it appears we have had this discussion before, and Parrot *does* emit a message if a `flock` on
this directory fails:
https://github.com/cooperative-computing-lab/cctools/blob/master/parrot/src/pfs_service_cvmfs.cc#L473

However, perhaps we are checking the wrong directory.

@trshaffer please take a look at this and make sure that parrot is synchronized with the latest cvmfs, looking in the appropriate lock directory.

**Comment by trshaffer** [comment]
@khurtado as of #1741 there's an error message regardless of debug mode when CVMFS initialization fails. This should make it easier to track down issues.

**Comment by dthain** [comment]
@khurtado is out for a while now, and I'm pretty sure this solves the issue, so closing..
