### ISSUE TITLE
CCTools manual out of date

### ISSUE THREAD

**Issue by pivie** [cooperative-computing-lab/cctools#1747]
The page:
http://ccl.cse.nd.edu/software/manuals/install.html
refers to the file
http://ccl.cse.nd.edu/software/files/cctools-6.0.15-source.tar.gz
but it should probably be
http://ccl.cse.nd.edu/software/files/cctools-6.1.7-source.tar.gz

**Comment by btovar** [comment]
6.1.8 now...

changing to just say the latest version.

**Comment by dthain** [comment]
I think we want to avoid updating documents everytime the version gets bumped.
Can we either do this automatically, or otherwise word the manula so as to indicate "the current version" ?

**Comment by btovar** [comment]
Yes, "the current version" is my current fix.
