### ISSUE TITLE
Project: MPI Worker Array

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#1755]
Many HPC sites are really only set up to run MPI programs, encouraging the user to submit small numbers of jobs that use a large number of cores.  We can still get Work Queue programs in the environment if they are "wrapped up" inside an MPI program.

So: Design a program called `mpi_worker` which is an MPI program that takes the same arguments as `work_queue_worker` but invokes a multi-core worker on each node of the MPI program, and exits when they all finish.

Version 2: Modify `mpi_worker` to start a foreman on rank 0, and workers on the other ranks that communicate with the foreman.

**Comment by Nekel-Seyew** [comment]
This was answered by merged pull request #1986

**Comment by Nekel-Seyew** [comment]
@btovar we can close this one.
