### ISSUE TITLE
Incorrect CATEGORY attribute was assigned to the rule

### ISSUE THREAD

**Issue by isanwong** [cooperative-computing-lab/cctools#1771]
Use the uploaded all.mf makeflow file, and then run makeflow with -d all option, I got the  debug log saved in the nohup.out file.

I checked the debug output, found that the commands were not assigned with the right category and CORES, MEMORY, and DISK constraints.

[nohup.out.zip](https://github.com/cooperative-computing-lab/cctools/files/1393805/nohup.out.zip)
[all.mf.zip](https://github.com/cooperative-computing-lab/cctools/files/1393806/all.mf.zip)

**Comment by btovar** [comment]
Thanks for your report, I'm on it.

**Comment by btovar** [comment]
The category field is parsed correctly, but not exported correctly during execution. The last category name is always used.

**Comment by isanwong** [comment]
Do cores, memory, and disk resources constraints exported correctly?

**Comment by btovar** [comment]
They do, yes.  Have you seen a case where they are not exported correctly?

**Comment by btovar** [comment]
@isanwong :  I included a fix for this in the 6.2.1 release. Please let us know if it works for you.

http://ccl.cse.nd.edu/software/downloadfiles.php

**Comment by isanwong** [comment]
Great, I'll test and reply the result ASAP.

**Comment by isanwong** [comment]
@btovar Now CATEGORY attribute exported correctly.

**Comment by btovar** [comment]
Great, thanks for letting us know.
