### ISSUE TITLE
Makeflow can not bring envrionment variables to the computing nodes while running in -Twq mode

### ISSUE THREAD

**Issue by isanwong** [cooperative-computing-lab/cctools#1790]

**Comment by btovar** [comment]
Thanks for your report!, but I can't reproduce this error. Could you post your makeflow?

**Comment by isanwong** [comment]
run command:

`MAKEFLOW_FILE=$1
WORK_DIR=$(dirname $(realpath $MAKEFLOW_FILE))
#WRAPPER="sh $(dirname $0)/wrapper.sh {} > stdout.%% 2> stderr.%%"
echo Makeflow file: $MAKEFLOW_FILE
echo Work directory: $WORK_DIR
#echo Wrapper script: $WRAPPER
makeflow -Tlocal --catalog-server mu02:9097 -M gtest-project --debug all --summary-log ${WORK_DIR}/summarylog --makeflow-log ${WORK_DIR}/makeflowlog --wrapper='./wrapper.sh {} > stdout.%% 2> stder
r.%%' --wrapper-output='stdout.%%' --wrapper-output='stderr.%%' --shared-fs /lustre --shared-fs /work --working-dir ${WORK_DIR} ${MAKEFLOW_FILE}`

**Comment by isanwong** [comment]
makeflow file:

`/work/tmp/test.export :
	export > /work/tmp/test.export
/work/tmp/test.path :
	echo $PATH > /work/tmp/test.path
/work/tmp/test.hostname :
	hostname > /work/tmp/test.hostname`

**Comment by btovar** [comment]
Makeflow only exports explicitly named variables. I suggest adding:

export MAKEFLOW_FILE

at the top of your makeflow file.

**Comment by isanwong** [comment]
But then there is non-consistent implementation regarding the environment variables among Work Queue, Local, and other batch types.

**Comment by btovar** [comment]
Indeed!, and that's a bug we have been carrying for historical reasons.  We are working in making -Tlocal to work more like the remote execution environments, but we have still some work to do.

One problem, for example, is the variable PATH. It's value will be probably different for the workers and for the node running the master, thus we cannot export it blindly. On the other hand, some current makeflow usage assumes the value of PATH for local executions.

**Comment by isanwong** [comment]
There is a -V option in SGE, which tell the schecular bring the whole environment variables set to the job running node. Is there a similar option in Makeflow/WorkQueue?

**Comment by btovar** [comment]
We certainly can add something similar if that is helpful to you.

**Comment by btovar** [comment]
Moved to #1796
