### ISSUE TITLE
Work Queue Factory Wrap Workers

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1794]
There is some interest in providing a wrapper interface for the Work Queue Factory, such that the factory submits workers and also runs the worker within a wrapper program. 

The case of interest is that of using a worker in Singularity, though it should be applicable to other containers and wrappers.

**Comment by dthain** [comment]
Does PR #1783 address this?  That allows you to use runos to run in a singularity container.

**Comment by btovar** [comment]
--wrapper and --runos seem to  cover this one.
