### ISSUE TITLE
Ability to configure specific docker image for a single rule

### ISSUE THREAD

**Issue by isanwong** [cooperative-computing-lab/cctools#1795]
A great demand for using docker to run programs is that to resolve the conflicts (maybe system-lib version conflicts or others), so if there are rules should using different programs that have conflicts, an only option in the command line maybe not enough.

**Comment by Nekel-Seyew** [comment]
@btovar I think we can close this, as there are many ways to include Docker and Singularity with Makeflow and subsequent batch systems.
