### ISSUE TITLE
CCTools CVMFS repo

### ISSUE THREAD

**Issue by annawoodard** [cooperative-computing-lab/cctools#1798]
As @PerilousApricot pointed out recently, it should be pretty straightforward to get software installed in CVMFS [1]. Would maintaining a CCTools repo in CVMFS be feasible? This would simplify the recipe for sharing my analysis code (which relies on Makeflow+WQ) with non-ND collaborators at CERN.

[1] [http://openhtc.org/docs/data/external-oasis-repos/](http://openhtc.org/docs/data/external-oasis-repos/)

**Comment by dthain** [comment]
This sounds like a good idea, but I would like to avoid standing up a new service if an existing one will do.

@bbockelm Is there an existing OASIS repo that would be a good place to deploy cctools binaries?  (Or perhaps there is already one out there?)

**Comment by bbockelm** [comment]
It would fit neatly into `/cvmfs/oasis.opensciencegrid.org`.  There's a part of that repository maintained by OSG-Software, but it is meant to be reused by multiple groups.

Are you thinking of this as part of a nightly build / CI?  Or just the CCTools release process?  Or maybe as part of the OSG release?  Depend on the rate of updates (and acceptable latency), there might be different solution approaches.

**Comment by dthain** [comment]
@annawoodard @PerilousApricot would it be sufficient if we published numbered releases in to the the OASIS repo?

**Comment by annawoodard** [comment]
@dthain Numbered releases in the OASIS repo would do nicely, thanks!

**Comment by dthain** [comment]
@btovar can you please work with @bbockelm to get the latest cctools into OASIS?
Hopefully there is a streamlined procedure for handling new releases as they occur.

**Comment by bbockelm** [comment]
Note that the LIGO guys have put together a nice way to automate the publication into CVMFS as part of their CI process:

https://github.com/ligo-cbc/pycbc/blob/master/tools/docker_build_dist.sh#L87

**Comment by btovar** [comment]
Link for future reference:

https://openhtc.org/docs/data/update-oasis/

**Comment by dthain** [comment]
It looks like someone added some older versions here:

```
[dthain@cclws15 dropbox]$ ls -la /cvmfs/oasis.opensciencegrid.org/osg/modules/cctools
total 9
drwxrwxr-x 1 root root 1024 Oct 20  2016 .
drwxrwxr-x 1 root root 1024 Jan 16 19:07 ..
drwxrwxr-x 1 root root 1024 Feb 25  2016 4.4.2
drwxrwxr-x 1 root root 1024 Feb 25  2016 5.2.3
drwxr-xr-x 1 root root 1024 Mar 24  2016 5.4.7
drwxr-xr-x 1 root root 1024 Oct 18  2016 6.0.7
```
