### ISSUE TITLE
Passing resource information to tasks sometimes incorrect

### ISSUE THREAD

**Issue by AndrewLitteken** [cooperative-computing-lab/cctools#1805]
Makeflow measures the local resources for a job and in some cases, passes the information as a requirement for a rule.  This is incorrect because we are setting the size of the host that runs the master makeflow as the requirement for the subtasks.

**Comment by dthain** [comment]
@AndrewLitteken I didn't quite understand this report when you submitted it.
Do you want to clarify, or has the moment past?

**Comment by AndrewLitteken** [comment]
I think the moment as passed. I'm cannot really remember what the issue was here, and it may have been rectified when actually implementing the feature.
