### ISSUE TITLE
[WorkQueue] Complaints about an output file with the same name as an input file

### ISSUE THREAD

**Issue by matz-e** [cooperative-computing-lab/cctools#1811]
I want to provide a default output file that will get overwritten by the task to make post-running processing easier, and when doing so, I get the following error message:

    Error: output file /tmpscratch/users/matze/lobster_test_20171215_0825/ttH/running/0000/0001/report.json conflicts with an input pointing to same remote name (report.json).

Is this really an error? Why can't I provide a default output file to be filled/augmented?

**Comment by dthain** [comment]
@matz-e While I can see why you want to do this, this results in semantics that are very hard to provide in the presence of failures.  What you are defining is effectively a file that is both input and output.  Now, if a task should fail after the output has been written or delivered, then the contents of the original input file would be modified, and the "output" would be delivered as "input".  While your application could be designed to deal with this possibility, it would play havoc with caching etc in WQ.

The general rule for data in WQ is that files are either input-only or output-only, and once a file is created, it is immutable.

Could you perhaps set this up by delivering the default file as an input, and then having the app read the default file and create a new output file under a different name?

**Comment by matz-e** [comment]
Thanks for clarifying! And yes, the renaming step is what I've resulted to doing (as the very first thing the task does). The argument with the caching makes a lot of sense.
