### ISSUE TITLE
Streaming stdout, stderr from rules running on batch system

### ISSUE THREAD

**Issue by philipjhj** [cooperative-computing-lab/cctools#1815]
Hi,

When I run my workflow through makeflow on e.g. torque, each rule gets a qsub, but the output and error streams seem to be redirected to /dev/null giving no way to track the output of individual jobs.

Specifically I am thinking of the settings of the -o and -e options.

I have tried to redirect the output of the rule, i.e. 'python myScript.py >> script.log 2>script.error, the files are created but the output does not appear before the completion of the job.

I'd liked to track the progress of individual tasks, and it seems the only way to get realtime info is through the output and error streams from the job.

Is there an easy workaround for this? What is the reason for redirecting to /dev/null anyways?

P.S.: Thanks for these great tools, I am really impressed with them, and especially makeflow is useful for my work.

**Comment by btovar** [comment]
Philip,

Redirecting like that should work. Are you adding script.log and
script.error as outputs of the rule? (could you post the exact rule you are
using?)

Are script.log and script.error created at all?

Ben

On Wed, Jan 3, 2018 at 11:17 AM, Philip Joergensen <notifications@github.com

**Comment by dthain** [comment]
It would also be helpful to know if your setup involves a distributed filesystem such as NFS, AFS, Lustre, etc.
Those can result in a delay of output being delivered.

Glad you find the software useful.

**Comment by philipjhj** [comment]
Edited third paragraph of my original question to make it more precise. Sorry for the confusion.

@btovar I did not add the two files as outputs of the rule. The files are created (as soon as the job starts) but the content does not appear until the job is completed. I believe it keeps a local temporary copy on the node of the job and then copies it over.

Previously when I have specified the log files through the -o and -e PBS settings, they are written real-time during the computation of the job.

@dthain I believe all the nodes of the HPC cluster that I am using has direct access to my home directory on a ZFS filesystem. Also we have a DFS using BeeGFS available, which I could use in case it solves this issue.

The cluster's resource manager is Torque using MOAB as scheduler.

**Comment by btovar** [comment]
Philip,

I misunderstood your original question. I misread it as saying that the
files were not created.

I think your intuition is correct. There is a local copy of the file in the
running node which is not immediately updated globally in the shared file
system. When you use the "-o" or "-e" options, it is my understanding that
torque calls "fsync" to make the global updates in the file system. Using
the redirection directly in the command, a sync would only happen when the
file is finally closed. If this sounds correct to you, then we can think of
some ideas on how to go about it.


Ben

​


​

**Comment by philipjhj** [comment]
Ben,

your description sounds correct. I was not aware of fsync.

Not sure if it provides any help, but I noticed the following today: 
ran a workflow with a rule calling a python script using tqdm for a progress bar.  The progress bar output could be seen realtime in the script.error file. (I thought it would be printed to stdout, and not until end of the batch job like the rest)

I would be happy to assist in finding a suitable solution for this.

**Comment by btovar** [comment]
Philip, could you try something like:

stdbuf -oL -eL python myScript.py >> script.log 2>script.error

or this one:

python -u myScript.py >> script.log 2>script.error

?

**Comment by dthain** [comment]
@philipjhj Is this still an open problem for you?

**Comment by Nekel-Seyew** [comment]
@btovar Given that the last comment on this was from Jan, I think we can close this.
