### ISSUE TITLE
Makeflow wrappers

### ISSUE THREAD

**Issue by trshaffer** [cooperative-computing-lab/cctools#1816]
After thinking about the Makeflow wrapper use cases discussed with @nhazekam and @dthain, I've come to the conclusion that there are two separate features here. This is kind of a long issue, and I'm sure there'll be some further discussion as it differs from what @nhazekam and I talked about. The cases we came up with involve some combination of manipulating the inputs/outputs, command line, environment, filesystem, etc. We were also interested in running commands on different events such as task success and failure. Some proposed wrappers, especially Umbrella, need to be able to do stuff on workflow-level events, such as workflow start and after submitting each task. Some of these features need to be tied into the batch job interface to be passed down to workers, and some of the job specification stuff could be relevant to Work Queue as well.

I think that these use cases are served by two orthogonal features: command wrappers and hooks into Makeflow's event loop. Wrappers would be expressed as JSON data structures, and do process-based (not string-based) command line wrapping. This is what covers sandbox wrappers, enforcement, `parrot_run`, and a few other current use cases. They should include input/output files, and probably some extra info such as environment variables and the like. None of this is specific to Makeflow, and would fit well in the batch job or Work Queue interface. Rather than adding a Makeflow-specific wrapper feature, I propose defining a flexible JSON specification for a command execution that works across batch job, work queue, local execution, and maybe Chirp. JX is powerful enough as-is that Makeflow could eval one or more wrapper definitions in a straightforward way to build one of these JSON command specifications. Some of the ideas we've been whiteboarding are discussed below.

The other feature I see here is Makeflow event loop hooks. Umbrella and some of the container things need actions that run on workflow start or before task submission. Whereas wrapping a command can change inputs and outputs and thus make structural changes to Makeflow's DAG, these setup and teardown actions should not be able to alter the structure of the workflow. This is in line with Makeflow's approach of statically validating its DAG before executing. Hooks would be runtime actions that users can stick into Makeflow's event loop. This would cover fetching container images and Umbrella fetching remote files and whatever else it needs to do. This would also let users add stuff like custom debugging, logging each rule, checkpointing, perhaps doing some cleanup on rule failure, and who knows what else. More detail below.

Command Wrappers
--------------------------

The JSON format we've been whiteboarding looks something like this.

    {
        "command": ["sh", "-c", "./run.sh foo.txt"],
        "inputs": ["run.sh", "foo.txt"],
        "outputs": ["foo.xml"]
    }

This would be a simple command to run in a shell. Work Queue could look at the inputs and outputs to figure out what to transfer. After any necessary file transfers, `command` is `exec`ed. To indicate a wrapper, the `command` can include a nested list of args, like so.

    {
        "command": ["strace", "-o", "run.strace", ["sh", "-c", "./run.sh foo.txt"]],
        "inputs": ["run.sh", "foo.txt"],
        "outputs": ["foo.xml", "run.strace"]
    }

To execute this command, first write a temporary script containing the wrapped command, then replace the command line list with the name of this script. So for example, we would write out `wrapper.y52VcMHrD5` containing

    #!/bin/sh
    exec 'sh' '-c' './run.sh foo.txt'

Then the main command is executed as `["strace", "-o", "run.strace", "./wrapper.y52VcMHrD5"]`. Next, we need a way for the user to define transformations like this. JX works well here. That `strace` wrapper could be specified as

    {
        "command": ["strace", "-o", "run.strace", CHILD["command"]],
        "outputs": CHILD["outputs"] + ["run.strace"],
    }

where `CHILD` is bound to the wrapped command. For brevity, keys specified in the child but not the wrapper are copied up. With list comprehensions, you can do all sorts of things.

    # add a prefix to inputs/outputs
    ["prefix/" + x for x in WHATEVER]
    # remove files in /tmp
    [x for x in WHATEVER if not startswith(x, "/tmp")]

JX currently doesn't have a `startswith` function, but it's easy to add general-purpose builtins for manipulating strings and paths and such. We can keep the necessary C code behind JX builtin functions, and let users specify wrappers as plain JX documents. Users could also use these command wrappers to check for valid output or clean up after failure at the execution site, before Makeflow gets things back.  For Makeflow, we would want to add a command line arg to specify wrapper files. It would also be useful to add wrapper specifications to Makeflow's JX format, so that you can apply a wrapper to a single rule, to a category, or to the whole workflow. Makeflow would then generate a JSON command spec (like the first example) for each rule, and eval any wrapper(s) onto them. The final inputs/outputs go into building the DAG. Then to execute a rule, Makeflow just passes the generated JSON to batch job or Work Queue or wherever.

Makeflow Hooks
---------------------

I'm not certain that adding general-purpose hooks to Makeflow's event loop is a good idea, but it would be a very powerful way to customize a workflow's behavior without modifying Makeflow's source.  I'm imagining some command like options  like or `--on WORKFLOW-START=hook.sh`. The hooks we came up with include
- workflow start, end
- task submit
- task success, failure

If there are hooks registered for an event, Makeflow can run them and pass info as environment variables a la CGI scripts. The first things that come to mind to pass in would be command lines, inputs/outputs, category info, exit code, workflow filename, batch system details, etc. It's also easy to add more in the future without breaking existing hook scripts. I don't think these scripts should be able to modify the structure of the workflow or change the result of a task from failure to success. A hook script exiting unsuccessfully should cause the workflow to fail. I don't think these fit as wrappers, because they don't have a compositional nature, especially the workflow-level ones. They're just actions to be run one after another when some event happens inside Makeflow.

Implementation
--------------------

I think the changes discussed here can be implemented without much hassle, and can fit alongside the current stuff. Using a combination of command wrappers and Makeflow hooks, we should be able to cover all the use cases we whiteboarded, after adding some builtins to JX. Makeflow hooks would be pretty straightforward to implement. We just get a list of hook scripts from the command line, then put some calls throughout the event loop. There should be some helper functions to set up the environment variables as well.

Command wrappers would require two parts: evaluating wrapper documents in Makeflow and executing nested commands. Adding wrapper evaluation to Makeflow should take about as much work as the previous part. Read wrappers off the command line, stick evaluation between the parsers and the main program (@nhazekam's parser refactor helps here), and modify task submission to use the pre-computed JSON command specs. To actually run JSON command specs, we could add a function like `batch_job_json_submit` that pulls command lines, inputs/outputs, etc. from a JSON spec and calls the underlying batch job functions. We would probably want to generate temporary scripts for wrappers here, and pass them along as inputs through batch job.

**Comment by dthain** [comment]
@trshaffer thanks for the detailed writeup.  
@nhazekam @btovar could you weigh in on this proposal with your thoughts first?

**Comment by dthain** [comment]
Some quick thoughts -

1 - A wrapper should not be able to change the structure of a DAG.  Rather, think of the DAG as the original source of a job object.  The job object is then copied, modified by the wrappers, and then achieves its final form before submission to the batch system.  To the extent that various features need to run before/after the entire workflow, they should only be manipulating local state (e.g. downloding or deleting files.)

2 - The JSON approach to defining wrappers is interesting, I like how you are using the child object by reference.  Now, can you show some examples that demonstrate this method is sufficient to express each of our existing wrapper types?

3 -I am not sanguine about hooks defined as external scripts, that seems difficult to carry state in and out of makeflow.  Rather, I imagined hooks simply defined as C callouts within the makeflow main loop.  for example, call hook_job_start(), hook_job_end(), etc within the Makeflow main loop.  Then, these callouts become the code points at which wrappers and other actions are implemented.  Put another way, C hooks are just the code structure for implementing wrappers.

**Comment by nhazekam** [comment]
Currently being worked on in #1830. This pull request sets up the internal workings for creating and pushing a wrapper to a set of nested executables.
