### ISSUE TITLE
chirp tests fail on i386-centos6 

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1826]

**Comment by btovar** [comment]
They fail with autobuild/condor. When ssh-ing to the machine, all tests complete correctly.

**Comment by dthain** [comment]
I think this is the issue: the jobs run with uid 108041 (ccl) but that user wasn't on the machine, so unix authentication fails.

```
whoami: cannot find name for user ID 108041
```
I just added the ccl user to that machine, so let's see if that fixes the problem.
