### ISSUE TITLE
Job wall time as a resource advertised by the worker.

### ISSUE THREAD

**Issue by dpandiar** [cooperative-computing-lab/cctools#183]
This feature request comes from Lee-Ping as below:

This resource would basically keep track of the seconds that are left in the batch job.  Since my jobs are long (20000s - 72000s) and the nodes have a 24 hour wall time limit (86400s), it creates a bad situation when a worker first finishes a 20000s job, then it starts a 72000s job but is killed after 66400 seconds.  Since I have an idea of how long jobs are expected to take, I can submit my tasks with a "walltime resource" requirement of 80000 seconds, and they will only start running on relatively fresh workers.  Again, this shouldn't affect how long the task actually takes to run, it will just prevent the job from running on workers which don't have enough time left.

**Comment by Nekel-Seyew** [comment]
@btovar this can be closed. It seems that  it would cause too much of a change to WQ to effectively do. Maybe it's something for WQ2?

**Comment by btovar** [comment]
superseded by #2590
