### ISSUE TITLE
parrot_run error on 6.2.3, but not in 6.0.13

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1831]
ctools-6.0.13-x86_64-redhat6/bin/parrot_run
to
cctools-6.2.3-x86_64-redhat6/bin/parrot_run

the same application gets errors like

11:16:41 awk: fatal: could not find groups: Invalid argument
11:16:41 ERROR in cling::CIFactory::createCI(): cannot extract standard library
include paths!
11:16:41 Invoking:
11:16:41   LC_ALL=C g++  -O2 -DNDEBUG -xc++ -E -v /dev/null 2>&1 >/dev/null | aw
k '/^#include </,/^End of search/{if (!/^#include </ && !/^End of search/){ prin
t }}' | GREP_OPTIONS= grep -E "(c|g)\+\+"
11:16:41 Results was:
11:16:42 awk: fatal: could not find groups: Invalid argument
11:16:43 With exit code 256

More error below.

Cheers,
Rod.

11:19:19 input_line_1:1:10: fatal error: file '/usr/lib/gcc/x86_64-redhat-linux/
4.4.7/../../../../include/c++/4.4.7/new' modified since it was first processed
11:19:19 #include <new>
11:19:19          ^
11:19:19 In file included from input_line_3:38:
11:19:19 /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/st
ring:55:2: error: unterminated conditional directive
11:19:19 #ifndef _GLIBCXX_EXPORT_TEM
11:19:19  ^
11:19:19 /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/st
ring:35:2: error: unterminated conditional directive
11:19:19 #ifndef _GLIBCXX_STRING
11:19:19  ^

11:19:54 PyRoot: Maybe you need to load the corresponding shared library?
11:19:54 PyRoot: IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime
6gClingE' unresolved while linking [cling interface function]!
11:19:54 PyRoot: You are probably missing the definition of cling::runtime::gCli
ng

**Comment by btovar** [comment]
Hi,
At least all the ask related stuff seems to boil down to

> id
uid=331089(ri32bz2) gid=33665(pr58e)id: failed to get groups for the current process: Invalid argument

and maybe this causes the later errors too.

I hope so because the rest is not pretty, and you need a machine with cvmfs .....

> cctools-6.2.3-x86_64-redhat6/bin/parrot_run  bash

export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase;source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh --quiet;source $AtlasSetup/scripts/asetup.sh AtlasOffline,21.0.15,notest --platform x86_64-slc6-gcc49-opt --makeflags="$MAKEFLAGS"
Sim_tf.py

might work.

Cheers,
Rod.

**Comment by btovar** [comment]
Tim: I can reproduce this on my cclws16 with the latest cctools master:

% parrot_run id  
uid=196886(btovar) gid=40(dip)id: failed to get groups for the current process: Invalid argument

**Comment by trshaffer** [comment]
Looks like this is a bug in Parrot's handling of the `getgroups` syscall. PR coming up shortly

**Comment by trshaffer** [comment]
Should be fixed by cfb4f82

**Comment by dthain** [comment]
Thanks Tim, that just happened to fix a similar problem I had encountered on RHEL7 but hadn't narrowed it down to a bug report yet.

**Comment by btovar** [comment]
Thanks Tim.
