### ISSUE TITLE
Parrot issues reading some symlinks from oasis.opensciencegrid.org

### ISSUE THREAD

**Issue by khurtado** [cooperative-computing-lab/cctools#1836]
Hello,
I'm trying to use  voms  from `oasis.opensciencegrid.org` via parrot and noticed there are some symbolic link files that just couldn't be read (the file the links are pointing to can be accessed though).

For example, from a machine with cvmfs, I can get:

```
$ ls -l /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0
lrwxrwxrwx 1 cvmfs cvmfs 15 Jan 14 21:14 /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0 -> cilogon-osg.pem
```

and this is what I get with parrot:

```
-bash-4.2$ ./parrot_run bash
bash-4.2$ ls -l /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0
LibCvmfs version 2.4, revision 25
ls: cannot read symbolic link /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0: No such file or directory
lrwxrwxrwx 1 root root 15 Jan 14 22:14 /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0
bash-4.2$ ls -l /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/cilogon-osg.pem
-rw-r--r-- 1 root root 1383 Jan 14 22:14 /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/cilogon-osg.pem
bash-4.2$ 
```

Any hint on how to solve this?

**Comment by dthain** [comment]
@trshaffer can you please take a look at this?

**Comment by khurtado** [comment]
Just to update on this:

There is something weird when reading either the actual files or the symlinks using the absolute PATH, but not when I read them from its parent directory

```
-bash-4.2$ ./parrot_run bash
bash-4.2$ tail /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0
LibCvmfs version 2.4, revision 25
tail: cannot open ‘/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/70d35895.0’ for reading: No such file or directory
bash-4.2$ tail /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/cilogon-osg.pem
tail: cannot open ‘/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/cilogon-osg.pem’ for reading: No such file or directory
bash-4.2$ cd /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates
bash-4.2$ tail -n 1 70d35895.0
-----END CERTIFICATE-----
bash-4.2$ tail -n 1 cilogon-osg.pem
-----END CERTIFICATE-----
bash-4.2$ 
```

**Comment by trshaffer** [comment]
This looks like a couple of bugs in Parrot's handling of symlink resolution in path components. Parrot needs to resolve the symlinks in paths by itself before calling into CVMFS. The changes in e19db29 left this feature off for `readlink` only, which I think was a mistake. That commit is from five years ago, but @btovar do you remember anything?

After turning on resolution for symlinks in non-final path components, the bug is still there. Going through the logs, it appears a few of the syscalls (`readlink`, `open`, `getdir`) correctly resolve symlinks in parent components, but continue to use the original path. For example,

    <child:1850> cvmfs: lstat(/mis)
    <child:1850> cvmfs: lstat(/mis/osg-wn-client)
    <child:1850> cvmfs: lstat(/mis/osg-wn-client/3.3)
    <child:1850> cvmfs: lstat(/mis/osg-wn-client/3.3/3.3.31)
    <child:1850> cvmfs: lstat(/mis/osg-wn-client/3.3/3.3.31/el6-x86_64)
    <child:1850> cvmfs: lstat(/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc)
    <child:1850> cvmfs: lstat(/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security)
    <child:1850> cvmfs: lstat(/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates)
    <child:1850> cvmfs: readlink(/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates)
    <child:1850> cvmfs: expanding symlinks /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/cilogon-osg.pem to /cvmfs/oasis.opensciencegrid.org/mis/certificates/cilogon-osg.pem
    <child:1850> cvmfs: stat(/mis/certificates/cilogon-osg.pem)
    <child:1850> cvmfs: open(/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/cilogon-osg.pem)

After passing the resolved name (from the next to last `stat` above) back and using it as the final path to `open`, everything seems to work correctly. Same for the other two affected syscalls. I would like to have someone test this more extensively, though, since changes to the path resolution like these make me nervous...

**Comment by khurtado** [comment]
@trshaffer 
Just to confirm, besides the symlink resolution I also noticed I can stat the regular file, but not open it unless I am in the parent directory. Will the above also solve that issue?

```
bash-4.2$ stat /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/cilogon-osg.pem
  File: ‘/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/cilogon-osg.pem’
  Size: 1383      	Blocks: 3          IO Block: 65336  regular file
Device: 1h/1d	Inode: 4469        Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-01-14 22:14:14.000000000 -0500
Modify: 2018-01-14 22:14:14.000000000 -0500
Change: 2018-01-14 22:14:14.000000000 -0500
 Birth: -
bash-4.2$ tail /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/cilogon-osg.pem
tail: cannot open ‘/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.3/3.3.31/el6-x86_64/etc/grid-security/certificates/cilogon-osg.pem’ for reading: No such file or directory
bash-4.2$ 
```

**Comment by trshaffer** [comment]
@khurtado yes this covers `readlink`, `open`, and `getdir`. The `stat`family of syscalls go down a different code path, so they weren't affected. Your examples with `tail` work for me on this branch.

**Comment by khurtado** [comment]
@trshaffer Thanks! Could I have a static version of parrot from this branch to test in my actual workflow?

**Comment by khurtado** [comment]
@trshaffer Thanks! Can I get a static parrot_run for rh6/rh7 to test?

**Comment by btovar** [comment]
Kenyi, I'll work on the static parrot now.

**Comment by khurtado** [comment]
I can confirm #1837 fixed my issue
