### ISSUE TITLE
Parrot issues when using bash process substitution

### ISSUE THREAD

**Issue by khurtado** [cooperative-computing-lab/cctools#1847]
I've been trying to use a bash script that uses bash process substitution in a similar way to this:

```
#! /bin/bash
while read input
do
  echo "$input"
done < <(echo "Hello world")
```
This is what I get when running the script above with and without parrot:

```
$ ./parrot_test.sh 
Hello world
$ ./afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/cctools/current/bin/parrot_run ./parrot_test.sh 
cat: /dev/fd/63: No such file or directory
```

A simpler way to test this is:
```
-bash-4.2$ bash -c 'cat <(date)'
Mon Feb  5 16:56:11 EST 2018
-bash-4.2$ /afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/cctools/current/bin/parrot_run -- bash -c 'cat <(date)'
cat: /dev/fd/63: No such file or directory
-bash-4.2$ 
```

**Comment by dthain** [comment]
@trshaffer plase take a look at this one.  I note that `pfs_table::resolve_name` maps `/dev/fd/%d` into `/proc/%d/fd/%d` so that might be the place to start...

**Comment by trshaffer** [comment]
This seems to be an issue with magic `/proc` symlinks again. If you look at `/proc` inside a redirect (outside Parrot), you can see what's happening.

    $ cat <(ls -l /proc/self/fd)
    total 0
    lrwx------ 1 tshaffe1 dip 64 Feb  7 12:09 0 -> /dev/pts/3
    l-wx------ 1 tshaffe1 dip 64 Feb  7 12:09 1 -> pipe:[11612898]
    lrwx------ 1 tshaffe1 dip 64 Feb  7 12:09 2 -> /dev/pts/3
    lr-x------ 1 tshaffe1 dip 64 Feb  7 12:09 3 -> /proc/13050/fd

Anonymous pipes (used in process substitution) don't have any real representation in the filesystem, so the kernel just presents them with bogus link targets. Parrot tries to dereference that symlink and of course fails with `ENOENT`.

**Comment by trshaffer** [comment]
@khurtado this should be fixed by #1851

**Comment by khurtado** [comment]
@trshaffer Thanks!
@btovar Can I get a static parrot that has both #1837 and #1851 on it?

**Comment by btovar** [comment]
On it.
