### ISSUE TITLE
condor_submit_workers ignores manually specified resources

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1866]
The command line generated is:

arguments =  -M testcondor --disk 10000 --memory 2000 --cores 1 --cores $$([TARGET.Cpus]) --memory $$([TARGET.Memo
ry]) --disk $$([TARGET.Disk/1024])

The condor defaults overwrite the manually specified ones.

**Comment by nhazekam** [comment]
@btovar Does #1867 fix the bug addressed here?
