### ISSUE TITLE
parrot memory error with perl

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1874]
This works:

% perl -e 'use Cwd'
%

This does not:

% parrot_run perl -e 'use Cwd'
panic: memory wrap at /usr/lib64/perl5/vendor_perl/Cwd.pm line 339.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.

**Comment by trshaffer** [comment]
@btovar where are you seeing this? I can't reproduce with `master` on RHEL7

**Comment by btovar** [comment]
I tried it in my workstation.

However you got me thinking. If I tried from my workstation with a clean environment (e.g. /usr/bin/env -i USER=btovar HOME=/tmp PATH=/bin:/usr/bin:/sbin sh), then it works fine.

I do set some perl path variables, so maybe it is getting confused between versions.

**Comment by btovar** [comment]
Works with latest master.

**Comment by btovar** [comment]
For what is worth, this issue first appear in b6a0e92f53f084a008182ffa4c6a77ba34dfeb4f
and disappeared in cfb4f82e1264c81c2fc4ab9dc4d4b6b723df1ff6

**Comment by trshaffer** [comment]
Huh, looks like cfb4f82 fixed a number of spooky issues. @dthain mentioned in #1831 another problem vanishing after that commit, in addition to the main issue
