### ISSUE TITLE
Installation of Work Queue module using Python 3

### ISSUE THREAD

**Issue by leeping** [cooperative-computing-lab/cctools#1877]
Hi there,

First off, thank you for providing such a useful library - I haven't been talking much on the mailing list, mainly because the Python module has been working very well in my Python 2 environment. I'm starting to have some issues as I migrate to Python 3.

I've tried a few times to install the Work Queue module into my Python 3 environment.  I get various errors at compile-time and import-time, and I was finally able to get things to work after numerous workarounds.  Hopefully someone here has insight into what might be happening, so that a future version would not require all these workarounds.

I'm using the systemwide GCC, version 4.8.4.  I have Miniconda with Python 3.6 installed, from https://conda.io/miniconda.html .

My configure line is:

`
CFLAGS="-I/home/leeping/opt/miniconda3/include -I/home/leeping/opt/miniconda3/include/python3.6m" ./configure --prefix /home/leeping/opt/cctools/6.2.7 --with-python-path no --with-perl-path no --with-globus-path no --with-python3-path /home/leeping/opt/miniconda3 --with-swig-path /home/leeping/opt/miniconda3
`

Here are some possibly relevant lines in the generated `config.mk`.  I have no idea where these variables come from:
```
CCTOOLS_PYTHON3=/home/leeping/opt/miniconda3/bin/python3
CCTOOLS_PYTHON3_CCFLAGS=-I/home/leeping/opt/miniconda3/include/python3.6m -I/home/leeping/opt/miniconda3/include/python3.6m  -Wno-unused-result -Wsign-compare -march=nocona -ftree-vectorize -fPIC -O3 -pipe  -fdebug-prefix-map==/usr/local\
/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes
CCTOOLS_PYTHON3_LDFLAGS=-L/home/leeping/opt/miniconda3/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/home/leeping/opt/miniconda3/lib -lpython3.6m -lpthread -ldl  -lutil -lrt -lm  -Xlinker -export-dynamic
```

When I run make, I get this error message:

```COMPILE work_queue_wrap.o
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
gcc: error: unrecognized command line option ‘-fno-plt’
```

It seems gcc doesn't recognize the options `-mtune=haswell -fstack-protector-strong -fno-plt` which are part of `CCTOOLS_PYTHON3_CCFLAGS` above.  I deleted these options from `config.mk` and ran `make` again.

The next error message is:
```
LINK _work_queue.so
/usr/bin/ld: /home/leeping/opt/miniconda3/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(abstract.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

I don't fully understand this error but it seems related to the static nature of `libpython3.6m.a`.  I deleted `-L/home/leeping/opt/miniconda3/lib/python3.6/config-3.6m-x86_64-linux-gnu` from `CCTOOLS_PYTHON3_LDFLAGS` and ran `make` again; this time the compilation continues and runs to completion.

The files `_work_queue.so`, `work_queue.py` are found in the `work_queue/src/python3` subfolder. I copied these to my Python site-packages folder, i.e. `/home/leeping/opt/miniconda3/lib/python3.6/site-packages` .

When I attempt to import Work Queue, the following error appears:

```
leeping@breakaway:~$ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import work_queue
Traceback (most recent call last):
  File "/home/leeping/opt/miniconda3/lib/python3.6/site-packages/work_queue.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/leeping/opt/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/leeping/opt/miniconda3/lib/python3.6/site-packages/_work_queue.so: undefined symbol: compress
```

This symbol should be provided by `libz.so`, and I resolved it by adding `-lz` to `CCTOOLS_PYTHON3_LDFLAGS`.  

After making these changes, I'm able to get WQ to work under Python 3.

Is there something I'm doing wrong with my configuration and installation from the beginning that leads to all of these workarounds?  Or is there something about the cctools build chain that needs fixing?

Your input is appreciated.  Thanks a lot!

- Lee-Ping

**Comment by btovar** [comment]
Lee-Ping,

Thank you for the detailed report!  I don't think you are doing anything out of the ordinary. I will try to reproduce your report in my workstation.

**Comment by btovar** [comment]
Lee-Ping,

I was able to reproduce it with miniconda. (It does work with python3 not from anaconda.)

I am making some changes so that it will work with anaconda out of the box.

**Comment by btovar** [comment]
The flags to the compiler I have fixed easily.

The linking problem seems like a bug in anaconda. I have filed the following bug report:

https://github.com/conda/conda-build/issues/2738

I am adding a roundabout in the meanwhile. (and in case the conda people determine it really think is not a bug.)

**Comment by btovar** [comment]
Well, it was a bug in conda. However print(sysconfig.get_config_vars('LDSHARED')) does not give us all the libraries needed. I'll look for a better way to find the libraries, but it may be that the current roundabout is the way to do it.

**Comment by btovar** [comment]
Lee-Ping, can you tell me if commit 98e58a5300afa7bb2bb174249793a808ce58a705 works for you?

Your configure command should look like:

./configure --prefix /home/leeping/opt/cctools/6.2.7 --with-python-path no --with-perl-path no --with-globus-path no --with-python3-path /home/leeping/opt/miniconda3 --with-swig-path /home/leeping/opt/miniconda3

(Assuming you have swig inside miniconda3, as your original line. You should not need to set the CFLAGS manually anymore.)

**Comment by leeping** [comment]
Hi Ben,

Thanks a lot - we'll check it over here and I'll let you know!

- Lee-Ping

**Comment by leeping** [comment]
I'm sure I'm doing something silly, somehow I cannot check out this commit after cloning the repository.  Here is the error I'm seeing:
```
(main) leeping@libra:~/src/cctools$ git checkout 98e58a5300afa7bb2bb174249793a808ce58a705
fatal: reference is not a tree: 98e58a5300afa7bb2bb174249793a808ce58a705
```
Additionally, this commit doesn't show up in the `git log`. The GitHub webpage doesn't show this commit as being on any specific branch or fork. Do you know what might be going on?

**Comment by yudongqiu** [comment]
Thanks for the help!

I manually overwrited the `configure` script with the one provided in commit 98e58a5, and tried to compile it with Anaconda Python 3. I got this error message: 

```rmonitor_wrap.c:149:21: fatal error: Python.h: No such file or directory```

The configuration command I used was:
```./configure --prefix /home/qyd/opt/cctools-6.2.7 --with-python-path no --with-perl-path no --with-globus-path no --with-python3-path /home/qyd/codes/anaconda3 --with-swig-path /home/qyd/codes/anaconda3```

The complete output for the configure command and make command are attached below.

[configure.log](https://github.com/cooperative-computing-lab/cctools/files/1799825/configure.log)
[make.log](https://github.com/cooperative-computing-lab/cctools/files/1799824/make.log)

**Comment by btovar** [comment]
I apologize, I gave incomplete instructions. By that commit I should have said the whole branch here:

https://github.com/cooperative-computing-lab/cctools/pull/1878

As you found out, there are other files that needed some changes.

**Comment by leeping** [comment]
Thanks Ben, I was able to install WQ successfully from your commit.  On my machine, Python.h was located here: `/home/leeping/opt/miniconda3/include/python3.6m/Python.h`

Here's what's contained in `config.mk`: 

`CCTOOLS_PYTHON3_CCFLAGS=-I/home/leeping/opt/miniconda3/include/python3.6m -I/home/leeping/opt/miniconda3/include/python3.6m`

Thanks,

- Lee-Ping

**Comment by btovar** [comment]
Thanks for letting us know!
