### ISSUE TITLE
parrot with libcvmfs writes checksum files in PWD.

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1880]
Example:

% rm cvmfschecksum.cms.cern.ch

% parrot_run ls /cvmfs/cms.cern.ch

% cat cvmfschecksum.cms.cern.ch
b9f8a5caacfac603a3a2d75a6a0463f99031bbe5T1520592252

**Comment by dthain** [comment]
Where should it go?

**Comment by btovar** [comment]
I'm not sure. /tmp/parrot.XXXXX ?
I don't think we had them until we updated libcvmfs.

**Comment by btovar** [comment]
But better, why is it there at all?

**Comment by btovar** [comment]
Doing an strace, the first time that file is tried is at /tmp/parrot.XXXX:

open("/tmp/parrot.196886/cvmfs/cvmfschecksum.cms.cern.ch", O_RDONLY) = -1 ENOENT (No such file or directory)
open("./cvmfschecksum.cms.cern.ch.wObQ37", O_RDWR|O_CREAT|O_EXCL, 0600) = 9
rename("./cvmfschecksum.cms.cern.ch.wObQ37", "./cvmfschecksum.cms.cern.ch") = 0

It would seem the open and rename are using an incorrect path.

**Comment by btovar** [comment]
https://github.com/cvmfs/cvmfs/pull/2070

**Comment by dthain** [comment]
Looks like this is fixed in cvmfs?

**Comment by btovar** [comment]
It is.
