### ISSUE TITLE
work queue does not url encodes file names inside a directory

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#1892]
work queue url encodes the name of single files or directories. However, it does not do the encoding for files inside a directory. If a filename inside a directory contains a space, the file transfer fails, the master blames the worker, and the task is retried indefinitely.

**Comment by dthain** [comment]
That's a nice targeted solution.
Do we have the same problem on the `work_queue_worker.c` side?

**Comment by btovar** [comment]
We don't. The problem is the recursive "file dir/filename", where filename may have spaces.

**Comment by dthain** [comment]
What I meant was, we have the same recursive protocol for both worker->master and master->worker transfers.  What happens if the master sends a directory recursively, and one of the files has a space in it?

**Comment by btovar** [comment]
Ah, yes. I thought those names were computed on submission time, but they are computed in send time. I'll fix the worker accordingly.

**Comment by dthain** [comment]
This one is merged, right?
