### ISSUE TITLE
Makeflow/Batch Job never allows retrieval of 0 jobid

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1895]
Makeflow allows 0 to be a valid submitted jobid.

`batch_job_submit` allows 0 as well:
"On success, returns a unique identifier for the batch job.  On failure, returns a negative number." from `batch_job.h`.

Makeflow will collect jobids with `batch_job_wait_timeout` but only try to reap the job if the id is greater than 0. If a node is ever actually submitted to 0 the job is added to the jobs tables and then never reaped.

`batch_job_wait_timeout` returns 0 if " there were no more jobs to wait for" from the header.

This is likely a rare occurrence, but still a problem we should resolve.

The general question now: 
- Is 0 a valid jobid?
- Should batch job and makeflow pass structs to differentiate valid submit vs actual jobid?

This return is being overloaded and doesn't seem capable of fully covering both cases.

Thoughts @btovar @dthain

**Comment by dthain** [comment]
I see what you are saying about the consistency of the API: submit() could potentially return jobid zero, but wait() has no way of returning it.  In any case, I would like to eventually move to a string-based jobid, for a variety of reasons.

But I'm not sure what you mean about the difference between a "submit" and "actual" jobid...?

**Comment by nhazekam** [comment]
The reason I said "valid submit" vs "actual jobid" was to say that it used to indicate both the success of submit and the actual jobid if successfully submitted. I didn't mean there were different "submit jobids" vs "actual jobids". Sorry for the unclear wording.

**Comment by dthain** [comment]
Do we have an existing batch system that could return zero as a job id?
If so, then this is a problem that needs to be solved.
If not, then just make a note of it in the API, and move on to other things.

**Comment by nhazekam** [comment]
I don't believe we do. I can make a note of it in the API. I will leave this issue open to reflect the existing gap in the API.

**Comment by Nekel-Seyew** [comment]
When designing the amazon batch subsystem, it was an issue I ran into, since my ids were originally just a counter starting at 0 and increasing from there. I switched to a random id system when I found this bug.

**Comment by trshaffer** [comment]
I think this is related to poisoned log files I'm getting. I'm debugging submit failures, and rules with jobid 0 are showing up in the log. From there, `batch_job_local_remove` seems to be `SIGTERM`ing the main Makeflow process. Once this starts happening, Makeflow becomes unusable and I have to clean up everything by hand.

**Comment by dthain** [comment]
Using what batch system?

**Comment by trshaffer** [comment]
SGE, it's the issue from this morning with the Shakespeare example

**Comment by dthain** [comment]
Looking at the code, that occurs when the driver cannot create the initial wrapper files and submit (incorrectly) returns zero, causing confusing.  Solution incoming..

**Comment by dthain** [comment]
PR #1927
