### ISSUE TITLE
Support for archives/disk images in Parrot

### ISSUE THREAD

**Issue by trshaffer** [cooperative-computing-lab/cctools#1947]
There's been occasional discussion for some time about using Parrot to "mount" a tarball or similar file and present it to the user as a directory tree. There seems to be some interest now in the HEP community about using this kind of approach for distributing self-contained software. I'm opening this issue to track discussion on this feature.

An initial question is what format(s) to support. A few suggestions:
- **TAR**: Likely be the simplest to implement and widely used, but poorly structured for use as a mountable filesystem.
- **SquashFS**: More complicated structure to support directory indexes and seeking, as it's designed as a performant, mountable filesystem.
- **ISO 9660**: Simpler to implement than SquashFS, structured with proper directory trees (unlike TAR). Has some legacy limitations on file size, paths, etc.
- **ext[2-4]**: Default filesystems for many Linux systems. Used with Shifter. There is a library interface included in e2fsprogs.

IIRC Docker images are structured as tarballs of tarballs. @Nekel-Seyew mentioned that Singularity supports SquashFS for compressed disk images. On the desktop side of things, Ubuntu's Snap format also uses SquashFS. Are there other technologies to consider? How are HEP people planning to do things?

**Comment by btovar** [comment]
TIm, as I understand it, SquashFS is now the default in singularity, that is, we should expect most singularity images to use SquashFS.

**Comment by nhazekam** [comment]
@jblomer May have more insight into this, but the above suggested formats sound reasonable. The work I am currently doing is targeting both TAR and SquashFS as outputs for the packaged CVMFS repository. If there was Parrot support for these, the combination could be used in a location where you don't have access to CVMFS (possibly due to network) and you are not able to mount.

**Comment by jblomer** [comment]
I think that would be a super useful feature, if only for my personal use!  I've always wanted a lightweight way to look in VM images, or at least ext2-4 file system blobs.  I'm not sure if there is a user-land library for ext.  Ext image files are, as far as I understand, used with the Shifter container system.
