### ISSUE TITLE
Fifo not blocking on write with  parrot_run

### ISSUE THREAD

**Issue by poquirion** [cooperative-computing-lab/cctools#1964]
I have a program that writes to a fifo and blocks until another one reads it.

The fifo is in `/tmp` and I use parrot_run to access some file in `/cvmfs`

Here is what is happening when I am not using parrot_run (expected behaviour)
```
$ mkfifo /tmp/toto
$ echo 33 > /tmp/toto
# blocking, waiting for a process to read /tmp/toto
```
When I use parrot_run in a one liner (again, expected behaviour)
```
$ parrot_run echo 33 > /tmp/toto
# blocking, waiting for a process to read /tmp/toto
```

My problem is when I start a bash session with parrot_run, 

```
$ parrot_run bash
$ echo 33 > /tmp/toto
bash: /tmp/toto: No such device or address
# Hey what is going on !
$
```
In the last case, if I read from `/tmp/toto` with another process before echoing, I do not get the error.

This in an error typically thrown when the  O_NONBLOCK option is used with open() https://www.tldp.org/LDP/lpg/node19.html

Not sure if it is expected, but  it crashes my code! (actually it freezes it since the reader is blocking on `/tmp/toto` forever, waiting for a process to write in it.)

I have have seen the behavior with cctools-6.2.8-x86_64-redhat7 and cctools-7.0.4-x86_64-redhat7.

**Comment by trshaffer** [comment]
@poquirion thanks for the bug report! I can reproduce this issue, and this is definitely weird behavior. I'll keep this issue updated while I track down the problem.

**Comment by trshaffer** [comment]
@poquirion Parrot does use `O_NONBLOCK` internally. I just put in a PR to catch this corner case. As of 2d3a6125 your examples appear to work as expected. For the one-liner, the open and redirect are happening in the parent shell (Parrot just sees `echo 33`).

**Comment by poquirion** [comment]
Yé!

**Comment by trshaffer** [comment]
@poquirion that change is merged. If you'd like to try it out, you can build CCTools from the `master` branch

**Comment by poquirion** [comment]
@trshaffer Thank a lot!
I've been building it, but cannot have the cvmfs work properly with my build. `./config && make && make install` runs without errors but fails handle the cvmfs connection where it was running without problems with 7.0.4. Perhaps because I am building in centos container on an ubuntu machine... not sure. 
Is the recipe used to build the  redhat 7 release  available somewhere?

**Comment by trshaffer** [comment]
@poquirion to build with CVMFS, you need to point the `./configure` script to your libcvmfs installation (`--with-cvmfs-path`). A prebuilt binary package for RHEL7 is available [here](https://ccl.cse.nd.edu/software/autobuild/commit/5b94c693/cctools-5b94c693-x86_64-redhat7.tar.gz) if you wouldn't mind testing things out. If that solves your issue, we can do a point release.

**Comment by poquirion** [comment]
Mmm, it does solve the bug, but It seems that the software is still hindered by the parrot... I will need to dig a bit more before any new release can help me.
