### ISSUE TITLE
Work Queue: double free or corruption

### ISSUE THREAD

**Issue by rlmv** [cooperative-computing-lab/cctools#1967]
I'm consistently getting a double free error in my work queue master (using CCTools 7.0.4). This takes a while to manifest - maybe after running for 2 or 3 days.

This is the line that causes it: https://github.com/cooperative-computing-lab/cctools/blob/12d56ed2517be5ef6967205f0f98234a794114e1/work_queue/src/work_queue.c#L1139

Here's the backtrace:

```
*** glibc detected *** python: double free or corruption (fasttop): 0x000055c3caca3d90 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x3a79075e5e)[0x7f87db11ce5e]
/lib64/libc.so.6(+0x3a79078cad)[0x7f87db11fcad]
/home/nu_bomarchman/cctools/lib/python3.6/site-packages/_work_queue.so(+0x521aa)[0x7f87a381d1aa]
/home/nu_bomarchman/cctools/lib/python3.6/site-packages/_work_queue.so(+0x526c5)[0x7f87a381d6c5]
/home/nu_bomarchman/cctools/lib/python3.6/site-packages/_work_queue.so(+0x52a37)[0x7f87a381da37]
/home/nu_bomarchman/cctools/lib/python3.6/site-packages/_work_queue.so(+0x531d9)[0x7f87a381e1d9]
/home/nu_bomarchman/cctools/lib/python3.6/site-packages/_work_queue.so(+0x5a63f)[0x7f87a382563f]
/home/nu_bomarchman/cctools/lib/python3.6/site-packages/_work_queue.so(work_queue_wait_internal+0x2f2)[0x7f87a382aa23]
/home/nu_bomarchman/cctools/lib/python3.6/site-packages/_work_queue.so(work_queue_wait+0x6b)[0x7f87a382a2b1]
/home/nu_bomarchman/cctools/lib/python3.6/site-packages/_work_queue.so(+0x398c8)[0x7f87a38048c8]
python(_PyCFunction_FastCallDict+0x91)[0x55c3c3e22ad1]
python(+0x19e67c)[0x55c3c3eb267c]
python(_PyEval_EvalFrameDefault+0x2fa)[0x55c3c3ed4cba]
python(+0x197a94)[0x55c3c3eaba94]
python(+0x198941)[0x55c3c3eac941]
python(+0x19e755)[0x55c3c3eb2755]
python(_PyEval_EvalFrameDefault+0x2fa)[0x55c3c3ed4cba]
python(+0x197a94)[0x55c3c3eaba94]
python(+0x198941)[0x55c3c3eac941]
python(+0x19e755)[0x55c3c3eb2755]
python(_PyEval_EvalFrameDefault+0x10ba)[0x55c3c3ed5a7a]
python(PyEval_EvalCodeEx+0x329)[0x55c3c3ead459]
python(PyEval_EvalCode+0x1c)[0x55c3c3eae1ec]
python(+0x2149a4)[0x55c3c3f289a4]
python(PyRun_FileExFlags+0xa1)[0x55c3c3f28da1]
python(PyRun_SimpleFileExFlags+0x1c4)[0x55c3c3f28fa4]
python(Py_Main+0x63e)[0x55c3c3f2ca9e]
python(main+0xee)[0x55c3c3df44be]
/lib64/libc.so.6(__libc_start_main+0x100)[0x7f87db0c5d20]
python(+0x1c7773)[0x55c3c3edb773]
```

This is being called by `get_output_file`
https://github.com/cooperative-computing-lab/cctools/blob/12d56ed2517be5ef6967205f0f98234a794114e1/work_queue/src/work_queue.c#L1260

Which is called by `get_output_files`
https://github.com/cooperative-computing-lab/cctools/blob/12d56ed2517be5ef6967205f0f98234a794114e1/work_queue/src/work_queue.c#L1305

Which is called by `fetch_output_from_worker`
 https://github.com/cooperative-computing-lab/cctools/blob/12d56ed2517be5ef6967205f0f98234a794114e1/work_queue/src/work_queue.c#L1490

Let me know if I can provide any more information!

**Comment by rlmv** [comment]
FYI @matteograsso @amhaun01

**Comment by btovar** [comment]
Bo, thank you for your detailed report. I'll work on it right away.

**Comment by rlmv** [comment]
Thanks Benjamin. Please let me know if I can help with testing or provide
any more information.

**Comment by btovar** [comment]
I think I got it.

The double free appears when a worker fails while in the middle of transferring back multiple files. This is why you don't see it often, as workers don't usually fail there. If I'm right, there is still the issue of why the worker is failing. (This may not be a problem, as it may be simply temporal network connection problems, evictions, resource lease coming to an end, etc.)

**Comment by btovar** [comment]
Bo, could you give https://github.com/cooperative-computing-lab/cctools/pull/1968 a try?

I can provide binaries if necessary.

**Comment by rlmv** [comment]
I just started a new computation. I'll let you know what the results are!

**Comment by rlmv** [comment]
@btovar This seems to have resolved the problem. I checked a computation that I started a couple weeks ago and it terminated normally. 

Thanks!

**Comment by btovar** [comment]
Bo, thanks for letting us know!
