### ISSUE TITLE
Enable SGE resource specification

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#1978]
Add support for jobs with resource specification to SGE. This can be done with ::
cores -> -pe smp $CORES
mem -> -l h_vmem=3G | -l mem_free=3G | -l h_rss=3G (possibly)
disk -> assumed sharedfs (Will verify later)

Part of this issue is the need for support, but also the interest in allowing specification of a select memory type and possibly in the future multiple different bounds.

::

This was edited to reflect actual options found while in SGE. h_vmem is the preference and default.

**Comment by trshaffer** [comment]
@nhazekam, OK to close this issue?
