### ISSUE TITLE
 Some tasks in running status permanently

### ISSUE THREAD

**Issue by AssassinJY** [cooperative-computing-lab/cctools#1992]
We use makeflow with sge mode to handle a huge workflow of more than 15000 tasks.

As I known, makelfow in sge mode monitor files sge.status.[job_id] to observe  task status. When task complete, makeflow delete files sge.status.[job_id].

When the stroage ( we use a shared parallel stroage ) is overload, getting the status and content of the files is delayed a few second, and makeflow keeps some tasks in running status permanently even if those tasks has completed actually.  Files sge.status.[job_id] do not be deleted also. It seen that makeflow lost the control of those tasks. And finally this workflow is hanged  because those tasks is in running status permanently.

`cat`  files sge.status.* we can see tow lines likes below so i am sure those tasks is completed.

```
start 1544697301
stop 0 1544697572
````
thanks for help!

**Comment by btovar** [comment]
Thank you for your report!

Could you make a run with debugging enabled (-dall -odebug.log), and send us the resulting debug.log, your makeflow file and the  *.makeflowlog file?

**Comment by AssassinJY** [comment]
> Thank you for your report!
> 
> Could you make a run with debugging enabled (-dall -odebug.log), and send us the resulting debug.log, your makeflow file and the *.makeflowlog file?

Sorry for the late reply and thank you for your help.  We finally found out that the makeflow is actually going to be completed normally when we reduce the storage load. So we think the problem is just the slow IO. The makeflow just become slow, but not hanging up.
I will close this issue and thank you again.

**Comment by dthain** [comment]
Glad it's working for you.
When you get a chance, we would be interested to hear a little more about your application:
https://docs.google.com/forms/d/e/1FAIpQLScYGnnjDW4wMBsv4lo1q-hFqpvNzqrJTBnk9msJqyDaRR8ecg/viewform
