### ISSUE TITLE
Installation of work queue on Mac OS 10.14

### ISSUE THREAD

**Issue by yudongqiu** [cooperative-computing-lab/cctools#1998]
Dear Developers,

I was trying to install the work queue program on Mac OS 10.14 but encountering some issues during compilation. I used python 3.6 installed with anaconda. I have also installed the command line tools via `xcode-select --install`

The source code I used was `http://www3.nd.edu/~ccl/software/files/cctools-6.2.10-source.tar.gz`

Once downloaded and decompressed, I used this command to configure:
```
./configure --prefix $HOME/opt/cctools-6.2.10 --with-python3-path /Users/qyd/codes/anaconda3/envs/forcebalance --with-swig-path /Users/qyd/codes/anaconda3/envs/forcebalance --with-perl-path no --with-globus-path no
```
And it finished without any issue.

However, when I follow that to run `make`, the following error pops up:
```
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Fram
eworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.                                    
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Fram
eworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.                                    
ld: -stack_size option can only be used when linking a main executable
clang: error: linker command failed with exit code 1 (use -v to see invocation)                                                               
make[3]: *** [_work_queue.so] Error 1
make[2]: *** [python3] Error 2
rm work_queue_priority_test.o work_queue_test_watch.o work_queue_test.o work_queue_status.o work_queue_example.o work_queue_worker.o          
make[1]: *** [src] Error 2
make: *** [work_queue] Error 2
```

I have attached the full configuration log and the make log. Could you please take a look? Thanks!

[config.mk.txt](https://github.com/cooperative-computing-lab/cctools/files/2705630/config.mk.txt)
[make.log](https://github.com/cooperative-computing-lab/cctools/files/2705631/make.log)

**Comment by dthain** [comment]
Hello Yudong -

Thanks for your interest, but you caught us just as the Christmas holiday
begin.
We'll have a chance to look at this early in the new year.

(The error message suggests some problem with linking basic system
libraries,
are you able to build a simple C program outside of cctools?)

Best wishes -
Prof. Thain

**Comment by yudongqiu** [comment]
Dear Professor Thain,

Thanks a lot for the reply! I completely understand that it's Christmas time.

Yes I am able to compile and build other programs.

The error message that the building process stopped at seems to be

```
ld: -stack_size option can only be used when linking a main executable
```

Here is some additional information about the `ld` program I have:

```
>>>ld -v
@(#)PROGRAM:ld  PROJECT:ld64-409.12
BUILD 17:47:51 Sep 25 2018
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 10.0.0, (clang-1000.10.44.4) (static support for 21, runtime is 21)
TAPI support using: Apple TAPI version 10.0.0 (tapi-1000.10.8)
```

Thanks,

Yudong

**Comment by btovar** [comment]
Yudong,

Could you try compiling a more recent version? E.g., http://ccl.cse.nd.edu/software/files/cctools-7.0.9-source.tar.gz

That way we would know if you encountered a bug we already fixed.

**Comment by yudongqiu** [comment]
@btovar Thanks for the suggestion! I just tried the newer version from your link and it has the same issue.

**Comment by btovar** [comment]
I was not able to reproduce your issue. This is what I did:

Install anaconda3.
Re-login so that swig installation recognizes anaconda's paths.
Install swig.
./configure --with-python3-path path/to/anaconda  --with-swig-path path/to/swig

How did you install anaconda, swig, and how did you create your envs?

**Comment by yudongqiu** [comment]
@btovar Thanks for following up on this. I just repeated the process in a new conda environment to reproduce the above issue.
I installed anaconda 3 (python 3 version) using the command line installer.
I created a conda environment by `conda create -n cctools`, then activated that by `conda activate cctools`
Then I installed python 3.6.7 and swig by `conda install python=3.6.7 swig`
Then I cd into the folder `cctools-7.0.9-source` and ran the following configure command:
```
$ ./configure --with-python3-path=/Users/qyd/codes/anaconda3/envs/cctools --with-swig-path=/Users/qyd/codes/anaconda3/envs/cctools --with-perl-path no --with-globus-path no
```
The configure finished successfully.
Then I tried to compile by:
```
$ make
```
And the above error occurs in the `LINK _work_queue.so` step:
```clang: error: linker command failed with exit code 1```

Two side notes as I was trying to reproduce this problem.

1.  When using the configure command without the last two arguments, i.e.
```
$ ./configure --with-python3-path=/Users/qyd/codes/anaconda3/envs/cctools --with-swig-path=/Users/qyd/codes/anaconda3/envs/cctools
```
Then `make` gives a new error before the `LINK _work_queue.so` step, which is
```
COMPILE chirp_wrap.o
chirp_wrap.c:738:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
make[3]: *** [chirp_wrap.o] Error 1
make[2]: *** [perl] Error 2
```

2. When using Python 3.7.2, i.e. `conda install python=3.7.2`, and configure with the command:
```
$ ./configure --with-python3-path=/Users/qyd/codes/anaconda3/envs/cctools --with-swig-path=/Users/qyd/codes/anaconda3/envs/cctools --with-perl-path no --with-globus-path no
```
  Then `make` give a new error in the `COMPILE work_queue_wrap.o` step:
```
SWIG work_queue.i (python)
ln -sf /System/Library/Frameworks/Python.framework .
COMPILE work_queue_wrap.o
work_queue_wrap.c:1331:20: error: expected expression
    Py_ssize_t l = PyTuple_GET_SIZE(args);
                   ^
/Users/qyd/codes/anaconda3/envs/cctools/include/python3.7m/tupleobject.h:59:34: note: expanded from macro 'PyTuple_GET_SIZE'
#define PyTuple_GET_SIZE(op)    (assert(PyTuple_Check(op)),Py_SIZE(op))
                                 ^
/Users/qyd/codes/forcebalance/tools/cctools-7.0.9-source/dttools/src/assert.h:26:22: note: expanded from macro 'assert'
#define assert(expr) cctools_assert(expr)
                     ^
/Users/qyd/codes/forcebalance/tools/cctools-7.0.9-source/dttools/src/assert.h:14:2: note: expanded from macro 'cctools_assert'
        do {\
        ^
1 error generated.
make[3]: *** [work_queue_wrap.o] Error 1
make[2]: *** [python3] Error 2
```

**Comment by btovar** [comment]
Both of these work for me.  Also, both errors are different from your original error message, which makes me wonder if there is something going on with your environment.

Could you try something like:

```sh
/usr/bin/env -i
__conda_setup="$(CONDA_REPORT_ERRORS=false '/Users/qyd/codes/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
\eval  "$__conda_setup"

conda create -n cctools_new_env
conda activate cctools_new_env

cd cctools-*-source

$ ./configure --with-python3-path=/Users/qyd/codes/anaconda3/envs/cctools_new_env --with-swig-path=/Users/qyd/codes/anaconda3/envs/cctools_new_env
```

**Comment by yudongqiu** [comment]
Sure. The first three commands did not have any output

Then I did the next two:
```
conda create -n cctools_new_env
conda activate cctools_new_env
```
In the new environment, python and swig are not installed yet, so if I directly run the next command, the configure fails with error `I couldn't find the Python3 >= 3.0 libraries`
Then I ran one more command `conda install python=3.6 swig`, then the configuration finishes successfully, but when I try to compile by `make`, it gives me the same error as I described above:
```
chirp_wrap.c:738:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
make[3]: *** [chirp_wrap.o] Error 1
make[2]: *** [perl] Error 2
```

**Comment by btovar** [comment]
Oh yes, I forgot the installation step, sorry about that.

I think I got it. I can reproduce it when I disable python2, as:  --with-python-path no

I assume you have a pure python3 installation then?

Let me see how can I fix it.

**Comment by yudongqiu** [comment]
Yes I have pure python3 installation. Thanks!

**Comment by btovar** [comment]
Could you give #2002 a try? It worked for me with python 3.6.

**Comment by btovar** [comment]
Excellent, thanks for letting us know!
