### ISSUE TITLE
cctools does not configure correctly with OSX Mojave 10.14

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2000]
OSX moved  /usr/include to /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include and we have a bunch of hardcoded /usr/include's in ./configure.

Unfortunately it won't be as easy as adding -I/Library/etc... as the getopt.h used changes if compiling with linux or osx.  Some ifdefs etc. in the getopt.h cctools we provide may be needed.

**Comment by dthain** [comment]
Appears to be fixed.
