### ISSUE TITLE
R Bindings for Work Queue

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#2026]
Approached about interest in R bindings and to see what the distance exists to export them.

Prior to this we may need to explore the ease of export, stability of version/binding, and what examples would look like in R.

**Comment by dthain** [comment]
@trshaffer @charleszheng44 as discussed yesterday, please get this going this week.

**Comment by charleszheng44** [comment]
I just added the swig r binding for work_queue and chirp #2033. @trshaffer Could you help me to review the PR ?

**Comment by dthain** [comment]
Changing approach to use JSON-server for multi-language bindings.
