### ISSUE TITLE
condor_submit_makeflow

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2027]
Greg Thain writes:

```
At the workshop today, it was suggested that one needs to remain logged 
into the submit machine for the duration of a makefile run.  For long 
runs, it was suggested to remember to log into via tmux or screen first.

What would it take to make a condor_submit_makeflow, like 
condor_submit_dag, that would run the makeflow as a scheduler universe 
job under the schedd, so that users could "submit and logout"?
```

As it turns out, we have a command with exactly that name that does what is expected.  If you installed cctools, it's already there, however:
1 - It isn't documented in our manual or man page index.
2 - It hasn't been tested in a while, and could use a quick run through that it behaves as expected.  (In particular, I wonder if the right thing happens when the makeflow is removed.

**Comment by dthain** [comment]
@trshaffer please a look at this one.

**Comment by dthain** [comment]
@btovar I think you already started on this, yes?

**Comment by btovar** [comment]
Yes
