### ISSUE TITLE
Unable to run job: job rejected: the requested parallel environment "smp" does not exist. Exiting.

### ISSUE THREAD

**Issue by lidd77** [cooperative-computing-lab/cctools#2060]
HI,
 My command is "makeflow -T sge " ,but  a error happened as the below ,
"Unable to run job: job rejected: the requested parallel environment "smp" does not exist.
Exiting.",
I checked my cluster ,there is no smp ,so how to solve this problem ??? thanks !:
 $ qconf -spl
mpi
mpich
orte

**Comment by nhazekam** [comment]
The first thing you can try is to add the `--safe-submit-mode` option `makeflow -T sge`. This will disable to resources from being specified, which is the source of the error, as `smp` is the configuration we use at Notre Dame. 

If this resolve the current issue, but creates another, the `-B, --batch-options` lets you pass a string that will be append to the batch submission after Makeflow's created submission. This lets you add options and in some cases overwrite previously stated options. With this you can specify different parallel environments or queues.

**Comment by lidd77** [comment]
HI, @nhazekam 
I really got another error，　＇Unable to read script file because of error: error opening CORES=1: No such file or directory， notice: job submission failed: no output from sge＇，
after I executed "makeflow --safe-submit-mode -T sge " ,  
How to resolve this ?

**Comment by lidd77** [comment]
HI, I checked makeflow help information, 
--safe-submit-mode          Excludes resources at submission.(**SLURM, TORQUE**),
My cluster system is /opt/gridengine/, so  I shouldn't add  --safe-submit-mode ??

**Comment by lidd77** [comment]
@nhazekam 
when I tried this below command ,I also met a error : 'qsub: Numerical value invalid!
The initial portion of string "sge.wrapper" contains no decimal number '
makeflow  -T sge  -B '-pe mpi' justBwa.mf ,

I’m not sure whether MAKEFLOW cannot run in my cluster system .

**Comment by lidd77** [comment]
I have told my cluster manager to open the mpi for me , so I can use mpi now .
for BATCH_OPTIONS,  the below setting is  correct  for specifying  many parameters  ?
BATCH_OPTIONS=-q  qu.q  , -cwd, -V , -e xx.e , -o xx.o

**Comment by nhazekam** [comment]
@lidd77 can you email me at nhazekam@nd.edu so I can get more concrete information about your setup. In addition to this can you also try adding the `-d all` option to Makeflow so we can get a better sense of what Makeflow is submitting. Do you have a command that successfully submits on your resources? We can then use this as a reference for what information needs to be submitted.

**Comment by nhazekam** [comment]
@lidd77 Please let us know if this is still an issue for you.
