### ISSUE TITLE
Work Queue task result not set in submission failure.

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#2061]
If a task submission failures submitting files (such as the case where the file does not exist) the tasks result should be set to reflect that, setting a result of:
WORK_QUEUE_RESULT_INPUT_MISSING = 1

Currently, the debug is reporting FILE does not exist, but does not set task result. This leaves the task with a return code of -1 and result of 32 which is :
WORK_QUEUE_RESULT_UNKNOWN = 4 << 3

@btovar Please let me know if this is a misunderstanding of this or if you can recreate this.

**Comment by btovar** [comment]
Solved by #2062
