### ISSUE TITLE
Work Queue Manual Resource Specification needs updating 

### ISSUE THREAD

**Issue by tjdasso** [cooperative-computing-lab/cctools#2072]

**Comment by tjdasso** [comment]
The Work Queue User Manual states that only one resource needs specification per task in order to limit its use (under Running Multiple Tasks per Worker). However, I needed to specify all three resource requirements in order to run multiple tasks on one worker.

**Comment by dthain** [comment]
Great, please make a PR!

**Comment by btovar** [comment]
fixed by #2073
