### ISSUE TITLE
Update Release Procedure

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2077]
@btovar please update our release/deploy procedure to match the current infrastructure, and also include whatever bits are needed to update the Conda deployment package:
http://ccl.cse.nd.edu/internal/deploy.php

**Comment by dthain** [comment]
More broadly: write out our overall deployment procedure that maps out the steps from issuing a release in github to seeing packages deployed in condor/pip/spack/cvmfs, and then performing tests on the installation.

**Comment by dthain** [comment]
Catching up on some old tickets...  Is this process suitably documented, and if so, where?

**Comment by btovar** [comment]
It is documented in  ccl-technotes (internal ND page).
