### ISSUE TITLE
Some Travis Builds Fail at Curl Step

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2078]
Autobuilds for cctools fail in the test stage on docker image cclnd/cctools-env:x86_64-centos7 when the basic makeflow test attempts to use curl to download capitol.jpg from ccl.cse.nd.edu.

For example:
https://travis-ci.org/cooperative-computing-lab/cctools/builds/549881197?utm_medium=notification&utm_source=email

This appears to be some sort of environmental problem, like dns or networking not set up right in the container, because the curl fails after almost exactly 30 seconds with SIGTERM.

**Comment by dthain** [comment]
To clarify, this is an intermittent problem.

**Comment by btovar** [comment]
Not using travis anymore.
