### ISSUE TITLE
Catalog Update Processing Bug

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2094]
We have periodic instances of garbage data in the catalog server, starting on May 14th and continuing through July.  It appears to happen to several different kinds of updates, both wq_master and chirp, where we get lots of duplicated JSON fields, almost as if the parser/printer is stuck in an infinite loop.

JX per se hasn't changed much recently, except for the jx_merge PR, which was merged in April:

https://github.com/cooperative-computing-lab/cctools/pull/2050/files

Can you take a very careful look at jx_merge (and how it is used) to make sure we aren't missing something?

Here is the first instance of corrupt data, notice that the "categories" field keeps repeating:

/afs/crc.nd.edu/group/ccl/data/catalog.deltadb/2019/132.log

```
...
T 1557769005
M 128.120.146.3:55115:128.120.146.3 {"categories":[{"max_allocation_count":32,"first_allocation_count":0,"workers_able":8,"tasks_cancelled":0,"tasks_failed":0,"tasks_done":1849,"tasks_dispatched":0,"tasks_running":8,"tasks_waiting":24,"category":"default"}],"capacity_weighted":1729,"capacity_instantaneous":1729,"capacity_disk":112345068,"capacity_memory":364870308,"capacity_cores":2838,"capacity_tasks":2838,"bytes_received":2487225008,"bytes_sent":2440241115,"time_workers_execute_good":291666918299,"time_workers_execute":291666918299,"time_application":2435971838,"time_polling":46212240734,"time_internal":2729822,"time_status_msgs":717509,"time_receive_good":1067528820,"time_receive":1068267042,"time_send":36261965,"tasks_complete":1849,"tasks_done":1849,"tasks_dispatched":1857,"tasks_waiting":24,"categories":[{"max_allocation_count":32,"first_allocation_count":0,"workers_able":8,"tasks_cancelled":0,"tasks_failed":0,"tasks_done":1849,"tasks_dispatched":0,"tasks_running":8,"tasks_waiting":24,"category":"default"}],"capacity_weighted":1729,"capacity_instantaneous":1729,"capacity_disk":112345068,"capacity_memory":364870308,"capacity_cores":2838,"capacity_tasks":2838,"bytes_received":2487225008,"bytes_sent":2440241115,"time_workers_execute_good":291666918299,"time_workers_execute":291666918299,"time_application":2435971838,"time_polling":46212240734,"time_internal":2729822,"time_status_msgs":717509,"time_receive_good":1067528820,"time_receive":1068267042,"time_send":36261965,"tasks_complete":1849,"tasks_done":1849,"tasks_dispatched":1857,"tasks_waiting":24,"time_application":2435971838,"time_polling":46212240734,"time_internal":2729822,"time_status_msgs":717509,"time_receive":1068267042,"time_send":36261965,"categories":[{"max_allocation_count":32,"first_allocation_count":0,"workers_able":8,"tasks_cancelled":0,"tasks_failed":0,"tasks_done":1849,"tasks_dispatched":0,"tasks_running":8,"tasks_waiting":24,"category":"default"}],"capacity_weighted":1729,"capacity_instantaneous":1729,"capacity_disk":112345068,"capacity_memory":364870308,"capacity_cores":2838,"capacity_tasks":2838,"bytes_received":2487225008,"bytes_sent":2440241115,"time_workers_execute_good":291666918299,"time_workers_execute":291666918299,"time_application":2435971838,"time_polling":46212240734,"time_internal":2729822,"time_status_msgs":717509,"time_receive_good":1067528820,"time_receive":1068267042,"time_send":36261965,"tasks_complete":1849,"tasks_done":1849,"tasks_dispatched":1857,"tasks_waiting":24,"categories":[{"max_allocation_count":32,"first_allocation_count":0,"workers_able":8,"tasks_cancelled":0,"tasks_failed":0,"tasks_done":1849,"tasks_dispatched":0,"tasks_running":8,"tasks_waiting":24,"category":"default"}],"bytes_sent":24402
```

**Comment by dthain** [comment]
It just occurred to me that our backup catalog is running a slightly older version, so we can do some differential diagnosis:

backup-catalog.cse.nd.edu is running this binary:

```
/afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/cctools/test-merge-event/bin/catalog_server -v
/afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/cctools/test-merge-event/bin/catalog_server version 8.0.0 DEVELOPMENT from source (released 2019-02-05 13:34:39 -0500)
	Built by btovar@cclws08 on 2019-02-05 13:34:39 -0500
	System: Linux cclws08 3.10.0-514.6.2.el7.x86_64 #1 SMP Fri Feb 17 19:21:31 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
	Configuration: --strict --build-label from source --build-date  --tcp-low-port 9000 --sge-parameter -pe smp $cores --with-fuse-path /afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/fuse/cctools-dep --with-irods-path /afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/irods/cctools-dep --with-mysql-path /afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/mysql/cctools-dep --with-python3-path /afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/python3/cctools-dep --with-globus-path /afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/globus/cctools-dep --with-swig-path /afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/swig/cctools-dep --with-xrootd-path /afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/xrootd/cctools-dep --with-cvmfs-path /afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/cvmfs/cctools-dep --with-uuid-path /afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/uuid/cctools-dep --with-curl-path /afs/crc.nd.edu/group/ccl/software/x86_64/redhat7/curl/cctools-dep --strict --prefix /var/condor/execute/dir_7176/cctools-e8292fc1-x86_64-redhat7
```

And it received the same UDP update at the same time and recorded it as follows:

```
T 1557769005
M 128.120.146.3:55115:128.120.146.3 {"tasks_waiting":24,"tasks_dispatched":1857,"tasks_done":1849,"tasks_complete":1849,"time_send":36261965,"time_receive":1068267042,"time_receive_good":1067528820,"time_status_msgs":717509,"time_internal":2729822,"time_polling":46212240734,"time_application":2435971838,"time_workers_execute":291666918299,"time_workers_execute_good":291666918299,"bytes_sent":2440241115,"bytes_received":2487225008,"capacity_tasks":2838,"capacity_cores":2838,"capacity_memory":364870308,"capacity_disk":112345068,"capacity_instantaneous":1729,"capacity_weighted":1729,"categories":[{"max_allocation_count":32,"first_allocation_count":0,"workers_able":8,"tasks_cancelled":0,"tasks_failed":0,"tasks_done":1849,"tasks_dispatched":0,"tasks_running":8,"tasks_waiting":24,"category":"default"}]}
M 10.32.74.142:9094:disc02.crc.nd.edu {"load1":2,"memory_avail":9619415040}
```

So, that narrows it down: it's definitely a problem at the catalog (not the sender) and it's the result of a code change since February.

One thing that jumps out at me is that the duplicated portion is itself an object.

Something related to nested objects?

**Comment by dthain** [comment]
@btovar adding you for context

**Comment by dthain** [comment]
FYI, I'm running the backup catalog with the new binary and MALLOC_CHECK enabled to see if something unusual happens.

**Comment by dthain** [comment]
Oh wow, it exploded quickly, but didn't throw a malloc error.

I am returning the backup catalog and the main catalog back to the last known good catalog binary until we figure this out.

**Comment by dthain** [comment]
Ok, I think I see the problem now.
The issue here is that the _semantics_ of `jx_merge` changed.

When a recovering `jx_database` is attempting to read its log, it invokes `jx_merge` to combine an M log event into an existing record:
https://github.com/cooperative-computing-lab/cctools/blob/master/dttools/src/jx_database.c#L286

It is expecting that `jx_merge( {a:A,b:B,c:C} , {a:X} , 0 )` will throw out `a:A` from the first object and replace it with `a:X` from the second object, resulting in ` {a:X,b:B,c:C}`

The new implementation of `jx_merge` is just smashing the pairs together into a list, with the result of `{a:A, b:B, c:C, a:X}`.  And so, if we process a whole lot of update records, the json objects just get bigger and bigger and bigger.  Yikes!

**Comment by dthain** [comment]
And now going back to look at the PR discussion, I think the underlying issue here is that there are two different use cases for `jx_merge`, so fixing it for one breaks the other.

@trshaffer does that make sense to you?

**Comment by trshaffer** [comment]
Yes, that seems to be what's happening here. I can reproduce a minimal case.

First, start up a catalog server with logging and history turned on.

    $ catalog_server -L updates.log -H history

Now we can send some data,

    $ echo '{"data":5}' | nc -u 127.0.0.1 9097
    $ echo '{"data":6}' | nc -u 127.0.0.1 9097
    $ echo '{"data":7}' | nc -u 127.0.0.1 9097

which gives the expected result on the catalog.

    $ curl http://127.0.0.1:9097/query.json
    [
    {"name":"localhost","lastheardfrom":1563370219,"address":"127.0.0.1","data":7}
    ]

If we kill the server and examine the history, everything is normal.

    $ cat history/2019/197.log
    T 1563370212
    C 127.0.0.1:0:localhost {"name":"localhost","lastheardfrom":1563370212,"address":"127.0.0.1","data":5}
    T 1563370215
    M 127.0.0.1:0:localhost {"data":6}
    T 1563370219
    M 127.0.0.1:0:localhost {"data":7}

Starting the server back up in the same way, it replays the history and things get weird.

    $ catalog_server -H history
    $ curl http://127.0.0.1:9097/query.json
    [
    {"name":"localhost","lastheardfrom":1563370212,"address":"127.0.0.1","data":5,"data":6,"data":7}
    ]

The calls to `jx_merge()` resulted in all the updates appearing in the object, in reverse order. If we now send another update, the catalog state goes back to normal.

    $ echo '{"data":8}' | nc -u 127.0.0.1 9097

    $ curl http://127.0.0.1:9097/query.json
    [
    {"name":"localhost","lastheardfrom":1563370586,"address":"127.0.0.1","data":8}
    ]
 But the merge record in the history is now corrupted.

    $ tail -n 2 history/2019/197.log
    T 1563370586
    M 127.0.0.1:0:localhost {"data":8,"data":8,"data":8}

Everything behaves normally after this, since the previous state gets thrown out on each update.

**Comment by trshaffer** [comment]
Also note that this weirdness can occur without stopping the server (and thus without `jx_merge()` being called). Starting over with a clean history and fresh server,
we can send a weird update to do the same thing.

    $ echo '{"data":5,"data":6,"data":7}' | nc -u 127.0.0.1 9097
    $ curl http://127.0.0.1:9097/query.json
    [
    {"name":"localhost","lastheardfrom":1563371042,"address":"127.0.0.1","data":5,"data":6,"data":7}
    ]

And again, the next update will result in a corrupted merge record.

    $ echo '{"data":9}' | nc -u 127.0.0.1 9097
    $ cat history/2019/197.log 
    T 1563371177
    C 127.0.0.1:0:localhost {"name":"localhost","lastheardfrom":1563371177,"address":"127.0.0.1","data":5,"data":6,"data":7}
    T 1563371196
    M 127.0.0.1:0:localhost {"data":9,"data":9,"data":9}

**Comment by trshaffer** [comment]
This happens because the code to compute the difference between an update and the current state ([here](https://github.com/cooperative-computing-lab/cctools/blob/master/dttools/src/jx_database.c#L213)) loops over every entry in the old object and adds an update record for each occurrence. Each update record does a lookup on the new object to find the updated value,
which results in many copies of the same field in the merge record.

Removing old entries during `jx_merge()` would make that operation more computationally expensive but avoid grabbing all the garbage data. That would prevent these massive merge records, but doesn't actually fix the corruption if e.g. someone sends strange JSON. A check on `jx_insert()` against duplicate keys would fix the corruption, but makes that operation more expensive.

This might be a good time to revisit #2051, since this is not the first time we've had issues with a mismatch between the expected behavior and the implementation.

**Comment by dthain** [comment]
That's a good summary of the problem. Can you please look at all of the call sites of jx_merge and determine the behavior desired by the caller?
- Mode 1: jx_merge(A,B) should simply concatenate all entries in A and B  (fast)
- Mode 2: jx_merge(A,B) should override fields in A with properties from B (possibly slow)

**Comment by trshaffer** [comment]
There don't seem to be any cases in the code where it's actually desired to retain the previous entries; the caller always expects Mode 2, and functions like `jx_lookup()` don't show observable difference.

**Comment by dthain** [comment]
That suggests reverting to the prior behavior.
What was the reason for the new implementation, initially?

**Comment by trshaffer** [comment]
There was a correctness issue that was causing problems with Makeflow/JX. The previous implementation reversed the order of pairs during a merge (and *sometimes* removed duplicates, making it potentially expensive). If objects didn't allow for duplicated keys, this would be fine. `jx_insert()`, however, simply prepends, so overriding a value and then calling `jx_merge()` would cause the previous value to come back to life.

In #2050 I fixed the correctness problem but punted on questions of performance or object implementation. Looks like #2051 got away from us, so there was never a decision about the semantics/behavior of JX objects.

**Comment by dthain** [comment]
Ok, how should we fix it?

**Comment by trshaffer** [comment]
Depends on how we proceed with the implementation of objects. If we switch to another structure like a hash table, these problems disappear. Alternatively, we could add checks to `jx_merge()`, `jx_insert()`, the parser, and possibly elsewhere so that duplicate keys aren't created in normal circumstances, but this would make these operations more expensive.

I'm also wondering if we could add a function like `jx_compact()` or something that removes all duplicates while sticking to the current list-based implementation. It would be necessary to call this function after operations that may override entries in an object (most uses of `jx_merge()`, some uses of `jx_insert()`), else this weird behavior ensues. This approach would allow O(1) inserts in the common case where we're building up objects with known keys, and gives the option of deferring cleanup to once at the end of a loop rather than rechecking the entire list on every insert. We could also compact JX with unknown contents (e.g. catalog updates) to ensure that objects behave *as if* they're unordered.

**Comment by dthain** [comment]
Tim, we need a targeted fix with high confidence so we can get the catalog server back in action,
and issue a bug fix release ASAP.  What would be the most focused change that accomplishes this?

**Comment by trshaffer** [comment]
Adding a `jx_compact()` function and calling it during the log replay after each merge ([here](https://github.com/cooperative-computing-lab/cctools/blob/master/dttools/src/jx_database.c#L290)) would fix this bug without requiring heavy changes to the codebase or requiring a decision about #2051.

**Comment by dthain** [comment]
Fixed.
