### ISSUE TITLE
JX String Formatting

### ISSUE THREAD

**Issue by trshaffer** [cooperative-computing-lab/cctools#2107]
cc @dthain @btovar @nhazekam 

In using JX for some of our workflows, the current string formatting is sort of a rough patch. Especially with highly-parametric workflows, things can get ugly for users (see the [BWA example](https://github.com/cooperative-computing-lab/makeflow-examples/blob/master/bwa/bwa.jx)). We currently have a few ways to work with strings:
- `format()` function
- Concatenation with `+`
- Automatic coercions from numbers, etc.

Python also has a number of string formatting facilities (`%` operator, `.format()`, etc.). Many of the awkwardness with strings has shown up there, so the Python people introduced f-strings in 3.6 as a more flexible option. The full description is given in [PEP 498](https://www.python.org/dev/peps/pep-0498/). To summarize, f-strings
- appear as string literals prefixed with `f` or `F`. This is not the first case of a prefix on a string in Python, but would be the first in JX.
- are expressions and not *actually* literals. They are evaluated at run time, not parse time. They can be evaluated multiple times in a loop body, etc. If there are side effects from the expressions, the evaluation order is defined left to right.
- support arbitrary expressions between curly braces. Literal curlies in f-strings are doubled as `{{` and `}}`.
- introduce some limitations on contents. Comments (with `#`) are not allowed in expressions (but are fine in the enclosing string). Backslash escapes are also not allowed.
- are somewhat awkward with strings for dictionary lookups, etc. Python sort of avoids this issue since they support both single and double quotes.

I'll give a few examples for JX here, and see if there are any other suggestions.

Current Syntax
-------------------

1. `format(“String %s, number %d”, VAR, 42 + i)`
2. `“file-” +  n + “.dat”`
3. `format("%s %s %s %s.%d > %s.%d.sam 2> %s.%d.err", BWA,ARGS,REF,INPUT_PRE,i,INPUT_PRE,i,INPUT_PRE,i)`

This syntax is very clear about how potentially complex expressions are handled, and fits within the current syntax without weird restrictions or incantations. For more complex substitutions, it can be a burden to work with (see example 3). It gets annoying when writing (and especially modifying) workflows to count over `%` fields and make sure the letter specifiers line up. This syntax is pretty familiar to C people or those using older Python.

F-strings
-----------

1. `f“String {VAR}, number {42 + i}”`
2. `f“file-{n}.dat”`
3. `f"{BWA} {ARGS} {REF} {INPUT_PRE}.{i} > {INPUT_PRE}.{i}.sam 2> {INPUT_PRE}.{i}.err"`

This syntax is much friendlier, especially for longer commands like example 3. Python's version allows for arbitrary expressions as in example 1. We could instead allow a restricted form that only supports bare variable names, to avoid some of the issues above with quoting and evaluation. As mentioned in the meeting, the prefix indicates that something weird is happening, and makes this functionality opt-in without changing the behavior or normal strings. This is somewhat foreign-looking syntax for me, but it's easy to explain to users who know Python (though this could be a liability if we don't support the full syntax). 

Implementation wise, these are a little awkward. I would be inclined to treat `f` as a unary prefix operator. The parser would validate that the string is well formed and we could print it back correctly, without intermediate sugar leaking out. If we only allow bare variables, then we can simply use the string as the operand and look up the variables at evaluation time. Allowing full expressions would either require additional parsing passes at eval time (ick) or some awkward in-memory representation as a list of string literals with expressions interspersed. We would need plenty of comments explaining how things need to look in memory, but none of this is user-visible.

New Format Function
-------------

1. `f(“String {VAR}, number {42 + i}”)`
2. `f(“file-{n}.dat”)`
3. `f("{BWA} {ARGS} {REF} {INPUT_PRE}.{i} > {INPUT_PRE}.{i}.sam 2> {INPUT_PRE}.{i}.err")`

Another suggestion was to introduce a new function that formats strings with substitutions rather than using a prefix. This would have many of the same advantages as f-strings, and we could still choose between variables only and arbitrary expressions. As a user, the function syntax throws me a bit. We haven't elaborated JX functions to a great extent, but we haven't given users any reason to think that functions don't work as usual, i.e. values go in as arguments, and a value comes back. This syntax implicitly uses the *calling* context, like C macros. I'm not sure if users would care, but I'm hesitant about something looking like a function but pulling in arguments/context implicitly. For explaining to new users, I wouldn't want to teach this as Python f-strings but written as functions, because I don't have a good reason (that doesn't involve digging around in our implementation) for why we didn't use an `f` prefix. If we're doing a more restricted form with bare variables only and will never allow expressions, this could be helpful so users don't expect things to act like Python.

Implementation wise, this is very simple. We would add another function called `f()` or what have you, without special parsing and printing required. Supporting arbitrary expressions without introducing special printing and such might require eval-time parsing. But this would be a fairly self-contained addition.

**Comment by dthain** [comment]
Hmm, I can definitely see that this is easier to read.

After thinking about it some more, I'm not so concerned about `f"xyz"` vs. `f("xyz")`  My main concern here is that it's taking us back to shell strings and all that attendant mess with escape characters, dollar signs, etc, that causes so much confusion when substituting complex values.  For example, a substituted JX expression could validly contain a brace.  How is that handled?

I was hoping to go the other direction (see #1505) where a command would be represented as an argv array in JX, and that would really kill parsing issues once and for all, without adding new language elements to JX.  For example:

```
command = [ "bwa", args, ref, input "-p", param ]
```

**Comment by dthain** [comment]
Ah, but now I see that my example would eliminate the use of shell constructs in the command, so you couldn't do output redirection, pipes, etc in the command.  Hmm.

**Comment by trshaffer** [comment]
In the string part, you **must** double braces to include them literally, e.g. `f"literal {{ brace"`. If you use a brace in the expression part, it will be matched within the expression. A stray brace would throw an error at parse time. This differs from shell-style quoting in that when you hit an opening brace, you parse a full expression and ensure that the next character is a single closing brace. Handling strings within the expressions is more trouble; the Python people have that figured out using both single and double quotes, but JX doesn't currently have the former.

I think we had initially considered an `argv` form for commands, but the main issue was that the batch job interface doesn't support that. If @nhazekam is considering a more JX-y batch interface, I'd be in favor of supporting that too.

**Comment by trshaffer** [comment]
JavaScript Template Literals
-------------------------------------

As another point of comparison, JS supports a similar thing, branded as [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). The functionality is pretty much the same as f-strings, but with quoted with backticks rather than prefixed.
1. `` `String ${VAR}, number ${42 + i}` ``
2. `` `file-${n}.dat` ``
3. `` `${BWA} ${ARGS} ${REF} ${INPUT_PRE}.${i} > ${INPUT_PRE}.${i}.sam 2> ${INPUT_PRE}.${i}.err` ``

Template literals make no pretense of being strings, so there are no restrictions on quotes or other characters within the expressions. You can also nest them *within* braced expressions, e.g.

    `sh ${SCRIPT ? `${SCRIPT}.sh` : `-c 'rm ${FILE}'`}`

which allows for some pretty ugly expressions. I'm not sure that kind of flexibility is worth it. For users, this is similar to f-strings with a bit more visual noise. Template literals are also delimited differently than normal strings, indicating that magic is happening. This syntax does place the fewest restrictions on what users can do.

Implementation wise, we would likely need to introduce a new fundamental JX type, e.g. `JX_TEMPLATE` since there is arbitrary nesting of expressions. This would entail the usual boilerplate for printing, cleanup, etc. Parsing wouldn't be too bad since there's no need for special contexts inside templates. Evaluation would be similar to that of f-strings, but more recursive.

**Comment by trshaffer** [comment]
From the discussion today in the meeting, here's a summary of the string formatting functions in Python. F-strings are covered above, and there's also the `%` operator that's similar to the current JX `format()` function. There is also the [`string.format()`](https://www.python.org/dev/peps/pep-3101/) method, which follows a specification syntax similar to f-strings. Python's full formatting language allows several types of specifiers:
- `{}` for positional fields
- `{2}` to refer to specific positional fields
- `{name}` for named fields

These can be mostly mixed and matched in a single format string. The values are passed as positional and keyword arguments to the format function, e.g.

    "{} {word}".format("Hi", word="there")

You can also use `*` and `**` to unpack lists and dictionaries as arguments. Python functions do not (cannot?) capture from the enclosing scope, so there's no way to implicitly pull values. Various hacks discussed on the mailing lists involved using `locals()` and `globals()` under the hood to do that.

There's also *another* standard string formatting setup called [Template()](https://www.python.org/dev/peps/pep-0292/) that looks more like shell or perl. It substitutes (again via `args` and `kwargs`) variables only:
- `$$` is a literal dollar sign
- `$var`
- `${var}`

Based on discussion after the meeting, the indexed/positional specifiers don't have much appeal. A JX formatting function might take a format string with named fields to resolve in the current context. An optional second argument would be an object that overrides values from the context. Something like this, assuming that `y` is defined in the enclosing context.

    fmt("{x} {y}", {"x": "hi"})

As to the function name, @btovar pointed out that this does something different than `format()` and is not an "abbreviated" version of that function, so we might not want to call it `fmt()`. Some possibilities include prefixing it with something (e.g. `nformat()`, `dformat()`, etc.) or using another name like `template()`.
