### ISSUE TITLE
Makeflow syntax extensions

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#211]
(Converting pull request #141 into an issue)

Original Peter Bui description:

During the XSEDE Makeflow and Work Queue tutorial, a user mentioned that having the ability to glob or use some more of GNU Make's syntax features would make Makeflow more attractive.

This is have been a controversial topic for us and in the past we have resisted going down that path. That said, I believe this is a reasonable request, and went ahead and added three new syntax extensions:

    wildcard substitutions: users can perform globbing by using the wildcard function:

    MAKEFLOW_SOURCE = $(wildcard *.makeflow)

    implicit variables: users can use implicit variables as placeholders for rule inputs and outputs:

    output: input
    command $^ > $@

    static pattern rules: users can utilize template patterns that expand to a number of nodes:

    $(wildcard *.makeflow): %.md5sum: %.makeflow
    md5sum %^ > $@

For the most part, I tried to stay as close to GNU Make's syntax as possible. I've added three test cases (one for each of the new extensions).

Please let me know your thoughts on these extensions.

**Comment by dthain** [comment]
With apologies to to @pbui I'm closing this issue.  We do need some new syntax, but what is needed is a structural macro, as opposed to pattern matching with the filesystem.
