### ISSUE TITLE
Python module work_queue not found

### ISSUE THREAD

**Issue by gilv** [cooperative-computing-lab/cctools#2115]
I am not sure if this is an issue or some step I missed.
I successfully installed cctols from source. I also added PYTHONPATH and pointed it to cctols/lib/python-2.7/site-packages

However when I use Python and write

      from work_queue import *
I am getting

    ImportError: No module named work_queue

How to install work_queue into Python?

**Comment by btovar** [comment]
Gil,

If you are installing from source, you have to make sure that you have 1) [swig](http://www.swig.org); and the 2) development files for your version of python, which are readily available if you installed python from source or from conda, or as packages from linux distributions, such as, python-devel or python-dev.

You can check whether the configure script is picking up the necessary files with:

./configure  | grep -E '(python|swig)'

If python dev or swig are installed, but the configure script is not picking them up, you can use:

./configure --with-swig-path ... --with-python-path ...

**Comment by gilv** [comment]
@btovar thanks...that's very helpful. So I am using pyenv and following your suggestion:

> 

gilv1-mac:cctools gilv$ ./configure | grep -E '(python|swig)'
checking for /usr/bin/swig...no
checking for swig.../usr/local/bin/swig
checking for /usr/bin/python2...no
checking for /usr/bin/python...yes
python version is 2.7.10
checking for /usr/include/python2.7/Python.h...no
*** skipping python bindings support
checking for /usr/bin/python3...no
checking for /usr/bin/python...yes
*** skipping python3 support
prune requires python >= 2.6
weaver requires python >= 2.6
python version is suitable for umbrella
gilv1-mac:cctools gilv$ 

> 

so seems I have issues with my Python pyenv environment and this explains that work_queue related bindings didn't added, is this correct?

**Comment by btovar** [comment]
Yes, in particular the lines:
 checking for /usr/include/python2.7/Python.h...no
 *** skipping python bindings support

indicate that the development files for python are missing.

**Comment by gilv** [comment]
@btovar thanks a lot. Issues is resolved.
As a general note for those who use pyenv, you need to provide python path, for example

     ./configure  --prefix ${HOME}/cctools --with-python-path=/Users/me/.pyenv/versions/2.7.15

**Comment by btovar** [comment]
Excellent, thanks for including the note!
