### ISSUE TITLE
LOCAL access control in parrot's mountlists has no effect

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2121]
We can either remove it in favor of --disable-filesystem, or make it work exactly as --disable-filesystem. 

I like the latter, as it shields a mountlist against services included when compiling parrot.

**Comment by trshaffer** [comment]
It looks like it would be a fairly small fix for `LOCAL` to skip services on specific paths. I'm not sure if there are cases where this is useful, but specifying via mountlist rather than `--disable-service` would allow finer control over service dispatch.
