### ISSUE TITLE
Parsl-WQ Throughput Improvements

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2124]
The initial Parsl-WQ integration works, but has low task throughput due to the cost of pickling.  Figure out how to improve the performance.

@tjdasso has a working solution and a PR against parsl, but there is still some cleanup work to push the PR through to completion:
https://github.com/Parsl/parsl/pull/1152

**Comment by benclifford** [comment]
Parsl/parsl#1152 has been merged
