### ISSUE TITLE
Extend keeplives to detect broken connections at worker

### ISSUE THREAD

**Issue by dpandiar** [cooperative-computing-lab/cctools#213]
Currently, the workers don't detect broken connections between starting and completing a task execution. 

This is especially magnified in Lee-Ping's setup with tasks that take a day to complete. There, the worker tries to communicate with the master on the task completion, detects the broken connection, and cleans-up losing a day's worth of computation.

Note, the current keepalive implementation doesn't work here since they are master-initiated.

**Comment by btovar** [comment]
Workers send resource updates to the master now, thus broken connections are detected in a timely manner.
For the rest of the issues, note that solving #145 will solve them too (workers not always connected to the master).
