### ISSUE TITLE
perl api doc's are not being generated

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2133]
It seems that when we re-organized the bindings directories, we did not update the paths in doc/Makefile for perl.

E.g., for work_queue, they point to src/perl, rather than src/bindings/perl

**Comment by dthain** [comment]
You already fixed this one:
https://github.com/cooperative-computing-lab/cctools/commit/64b3c0a2e09f0ac29bde0a06d6277ca7f77302f4
