### ISSUE TITLE
how to display results from  replica exchange example?

### ISSUE THREAD

**Issue by gilv** [cooperative-computing-lab/cctools#2139]
I executed example from
https://github.com/cooperative-computing-lab/cctools/tree/master/apps/wq_replica_exchange

It worked great, generated bunch of output files, like

         ww_exteq_nowater1.0-1.pdb
         ww_exteq_nowater1.0-1.vel
          ......

Can someone please explain me how "read and understand" results of this replica exchange example? I know that VMD tool can be used to show graphical presentation, but i have no clue to how to use VMD to show results from replica exchange example.

Thanks

**Comment by dthain** [comment]
Hello @gilv - Glad you got Repex working.  I'm afraid we aren't experts on the PDB data; this code was developed with some collaborators who do molecular dynamics that knew how to deal with the data.  That said, I think that just simply viewing a PDB file in VMD should not be difficult (once VMD is installed).  There are a number of introductions to VMD online, here is one that I found:
https://www.ks.uiuc.edu/Training/SumSchool/materials/sources/tutorials/01-vmd-tutorial/html/node2.html
