### ISSUE TITLE
Work Queue User's Manual C example will not compile

### ISSUE THREAD

**Issue by zsurma** [cooperative-computing-lab/cctools#2141]
When working through the Work Queue User's Manual, attempting to compile the C example with command:
```
gcc work_queue_example.c -o work_queue_example -I${HOME}/cctools/include/cctools -L${HOME}/cctools/lib -lwork_queue -ldttools -lm
```
it fails and yields this error message:
```
/afs/crc.nd.edu/user/z/zsurma/cctools/lib/libdttools.a(catalog_query.o): In function `catalog_query_compress_update':
/afs/crc.nd.edu/user/z/zsurma/cctools-src/dttools/src/catalog_query.c:236: undefined reference to `compressBound'
/afs/crc.nd.edu/user/z/zsurma/cctools-src/dttools/src/catalog_query.c:239: undefined reference to `compress'
collect2: error: ld returned 1 exit status
```

**Comment by btovar** [comment]
Could you try:

```sh
gcc work_queue_example.c -o work_queue_example -I${HOME}/cctools/include/cctools -L${HOME}/cctools/lib -lwork_queue -ldttools -lm -lz
```

?

It seems that a `-lz` is missing from the manual.

**Comment by zsurma** [comment]
@btovar That works perfectly, thanks!

**Comment by dthain** [comment]
@zsurma now you can make a PR to update the manual.  :)

**Comment by zsurma** [comment]
@dthain Is the manual page `cctools/doc/workqueue.html`? It seems like [line 94](https://github.com/cooperative-computing-lab/cctools/blob/master/doc/workqueue.html) already shows a corrected version of the command (with `-lz` flag).

**Comment by dthain** [comment]
Aha, it does.  Perhaps the latest version just hasn't been deployed to the web yet.
