### ISSUE TITLE
Deploy Jupyter and Work Queue Together

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2148]
Figure out how to deploy Jupyter and Work Queue together, and develop a simple and easy set of instructions.

Users will initially "play" with Jupyter/WQ applications by running a single worker locally to test things out, then deploy additional workers on clusters via the usual ways.

Add in some graphing mechanism so that users can easily and interactively see the number of workers, tasks running, tasks complete, etc.

**Comment by rykermcintyre** [comment]
I don't think I can assign myself to this, unless I'm missing something. @dthain @btovar could one of you look into doing this for me?

**Comment by dthain** [comment]
Fixed by #2239
