### ISSUE TITLE
Update Amazon Driver to Reuse Machine Images

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2153]
Update batch_job_amazon, so that when jobs end, the virtual machine is held at the ready, until (possibly) another job comes along to use it.
 
Challenge: Make sure that too many machines don't sit idle in the module.

@epyifany

**Comment by epyifany** [comment]
I believe this issue/feature has been resolved/implemented on PR#2191

Thanks,
Yifan

**Comment by dthain** [comment]
Fixed by #2191
