### ISSUE TITLE
Ensure Package is Relocatable

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2159]
In order to play well with new build environments (like Spack, Conda, etc) we must ensure that the whole cctools build package is relocatable.  That means, even if built and installed in the path /home/xxx, there should be nothing wired into the binaries regarding that path.  It should be possible to copy the whole package to /somewhere/yyy and (after setting the PATH) expect the software to work correctly.

So, the configure-time variable CCTOOLS_INSTALL_PATH may be used inside the Makefiles for the purpose of building/testing, but should *not* be defined as a C macro and used within the source code itself.  Wherever we invoke an executable, it should be done via a path search.  (There may be limited reasonable exceptions such as /bin/sh).

**Comment by btovar** [comment]
This was achieved with the integration with conda.
