### ISSUE TITLE
Update Install Instructions

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2164]
Now that the readthedocs format has been merged into master, we need to do a major update of the install instructions.  Here is what I want it to look like:

1 - Install via Conda
2 - Install via Spack
3 - Install via Git
4 - Special Cases (as already given)

And then let's drop the source/binary tarball installation instructions, I think that's outmoded.

@tjuedema please make a PR with the Spack instructions added ASAP, then pass it off to @btovar to add the rest.

**Comment by dthain** [comment]
The current instructions indicate "Warning! This command currently fails."
Is that really the case?

**Comment by btovar** [comment]
See #2252
