### ISSUE TITLE
Update Webpage with Doc Pointers

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2166]
Once the new build methods are in place and documentation is switched over, edit the main website so that existing URLs are redirected to the readdthedocs page, and the deployment methods are highlighted as the primary ways to get the software.

**Comment by dthain** [comment]
@btovar does this look about right to you:

Drop an .htaccess file in the root of our web server, with:

RewriteEngine On

# Top level page
Redirect /software/manuals/ http://cctools.readthedocs.io/en/latest

# Specific cases of: X.html -> X
RewriteRule ^/software/manuals/([awe|catalog|chirp|confuga|makeflow|jx|network|parrot|prune|resource_monitor|umbrella|watchdog|work_queue)\.html$ http://cctools.readthedocs.io/en/latest/$1 [R-301,NC,L]

# jx-quick.html -> jx/jx-quick
# jx-install.html -> jx/jx-install
Redirect /software/manuals/jx-quick.html http://cctools.readthedocs.io/en/latest/jx/jx-quick
Redirect /software/manuals/jx-tutorial.html http://cctools.readthedocs.io/en/latest/jx/jx-tutorial

# work_queue_examples in subdirectories
Redirect /software/manuals/work_queue_example.c http://cctools.readthedocs.io/en/latest/work_queue/examples/work_queue_example.c
Redirect /software/manuals/work_queue_example.pl http://cctools.readthedocs.io/en/latest/work_queue/examples/work_queue_example.pl
Redirect /software/manuals/work_queue_example.py http://cctools.readthedocs.io/en/latest/work_queue/examples/work_queue_example.py
Redirect /software/manuals/work_queue_example.py http://cctools.readthedocs.io/en/latest/work_queue/examples/work_queue_example.py3

# Individual man pages goes right to target
RewriteRule ^/software/manuals/man/(.*)\.html$ http://cctools.readthedocs.io/en/latest/man_pages/$1 [R-301,NC,L]

**Comment by btovar** [comment]
It looks good.
