### ISSUE TITLE
WORK_QUEUE_PREEXIST  is confusing in the API documentation

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2178]
We use it internally to prevent `WORK_QUEUE_THIRDGET` files to be deleted, however, a user should not be able to set it manually. This is not clear from their documentation:

```C
WORK_QUEUE_PREEXIST = 4, /**< If the filename already exists on the host, use it in place. */
WORK_QUEUE_THIRDGET = 8, /**< Access the file on the client from a shared filesystem */
```

In fact, `WORK_QUEUE_THIRDGET` does not care whether the file is in a shared filesystem, only that the path is accessible at the worker. 

Currently, it seems that  `WORK_QUEUE_THIRDGET | WORK_QUEUE_SYMLINK` is closer to what the documentation of `WORK_QUEUE_PREEXIST` describes.

**Comment by dthain** [comment]
Let's just clarify this in the documentation, or perhaps even leave it undocumented.
