### ISSUE TITLE
Work Queue Transaction Log Task Done can be Ambiguous

### ISSUE THREAD

**Issue by nkremerh** [cooperative-computing-lab/cctools#2188]
When using Work Queue's transaction log, it lists when tasks are finished (done) with the following syntax:

`# time master-pid TASK taskid {RETRIEVED|DONE} {SUCCESS|SIGNAL|END_TIME|FORSAKEN|MAX_RETRIES|MAX_WALLTIME|UNKNOWN|RESOURCE_EXHAUSTION limits-exceeded} [resources-measured]`

The SUCCESS tag is ambiguous because failed tasks can report SUCCESS upon completion. SUCCESS in this case refers to the program exiting normally, so more fine-grained output in this log may be helpful, like SUCCESS being split into SUCCESS, FAILURE, etc.

**Comment by dthain** [comment]
@btovar can you suggest who to evolve the log format?

**Comment by btovar** [comment]
Transactions results map then enum work_queue_result_t. A SUCCESS in work_queue_result_t indicates that the task ran to completion, regardless of the exit code.

I think we can safely add the exit_code after resources-measured, as:

.... DONE SUCCESS {} exit_code
or
..... DONE SUCCESS {....actual resources when measured....} exit_code

**Comment by btovar** [comment]
Fixed by #2193
