### ISSUE TITLE
wq factory -Twq is confusing

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2190]
With -Twq, the factory runs itself as a work queue master, that is, in order to run workers, a worker should connect to the factory, which is unexpected behavior.

I propose to either remove -Twq from the factory, or make it the same as -Tlocal, which is most likely the expected behavior.

**Comment by dthain** [comment]
Did someone get bitten by this mistake?

I would like to retain the possibility of running WQ on top of WQ (meta-pilot jobs) but I'm ok if we make that option harder to find so people don't stumble over it...

**Comment by btovar** [comment]
Yes, a student of Nirav asked me over slack.

**Comment by dthain** [comment]
How about -T wq exits with a helpful suggestion to use -T local,
but can be overridden with an embarrassingly long option?

**Comment by btovar** [comment]
Fixed by #2192
