### ISSUE TITLE
Incorrect number options are silently read as 0.

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2196]
A user tried '-w=1' to set the minimum number of workers in the factory. Since it is a short option format, the number specification read was "=1", which was silently converted to the number 0 by atoi. A warning is needed when incorrect number specifications are needed (e.g., change atoi when reading options to a utility function that exits on error.)

Should we also skip by default a "=" following a short option?

**Comment by dthain** [comment]
While I can see how someone might run into this, I think it may be adding too much complexity to add parsing and exception cases for every place we take a number as an option...

**Comment by btovar** [comment]
Sounds good.
