### ISSUE TITLE
Custom timeouts in Work Queue

### ISSUE THREAD

**Issue by leeping** [cooperative-computing-lab/cctools#2199]
Hello there,

I've been using Work Queue for ~7 years now, and I have always compiled the programs, libraries and Python bindings from source.  More recently I found that it was possible to install CCTools via `conda install -c cclnd cctools`; that is really great!  This will greatly benefit my research projects and make a lot of our workflows more sustainable. 

Before making the switch, I'd like to request a feature, or ask if this feature is available.  Many years ago, I was stymied by various kinds of timeouts when running workers with long jobs.  I traced some of the timeouts to parameters in the Work Queue source codes, and ever since then I have modified the timeouts in the source code with `sed` prior to compiling and installing (see snippet below).  This would no longer be an option if we start using the Conda ecosystem to install CCtools, so I was wondering if it could be possible to set these timeouts through the Python API.  Maybe this is already available and I just don't know it yet!

Please let me know, as I'd be very interested to make the switch over to using Conda for CCTools installation.  It would greatly reduce our maintenance burden by removing the need for local build scripts and customizations, not to mention it would make it much easier for our collaborators to install and use.

Thanks,

- Lee-Ping

```diff --git a/work_queue/src/work_queue.c b/work_queue/src/work_queue.c
index 6fabd68..d44bee3 100644
--- a/work_queue/src/work_queue.c
+++ b/work_queue/src/work_queue.c
@@ -4855,8 +4855,8 @@ struct work_queue *work_queue_create(int port)
 	q->worker_selection_algorithm = wq_option_scheduler;
 	q->process_pending_check = 0;
 
-	q->short_timeout = 5;
-	q->long_timeout = 3600;
+	q->short_timeout = 7200;
+	q->long_timeout = 86400;
 
 	q->stats->time_when_started = timestamp_get();
 	q->task_reports = list_create();
@@ -4882,8 +4882,8 @@ struct work_queue *work_queue_create(int port)
 	q->asynchrony_multiplier = 1.0;
 	q->asynchrony_modifier = 0;
 
-	q->minimum_transfer_timeout = 10;
-	q->foreman_transfer_timeout = 3600;
+	q->minimum_transfer_timeout = 7200;
+	q->foreman_transfer_timeout = 86400;
 	q->transfer_outlier_factor = 10;
 	q->default_transfer_rate = 1*MEGABYTE;
 
@@ -5691,7 +5691,7 @@ struct work_queue_task *work_queue_wait(struct work_queue *q, int timeout)
 
 	if(timeout != WORK_QUEUE_WAITFORTASK && timeout < 0) {
 		debug(D_NOTICE|D_WQ, "Invalid wait timeout value '%d'. Waiting for 5 seconds.", timeout);
-		timeout = 5;
+		timeout = 7200;
 	}
 
 	return work_queue_wait_internal(q, timeout, NULL, NULL);
diff --git a/work_queue/src/work_queue_worker.c b/work_queue/src/work_queue_worker.c
index a39adb4..225bd75 100644
--- a/work_queue/src/work_queue_worker.c
+++ b/work_queue/src/work_queue_worker.c
@@ -106,7 +106,7 @@ static int connect_timeout = 900;
 static const int active_timeout = 3600;
 
 // Maximum time for the foreman to spend waiting in its internal loop
-static const int foreman_internal_timeout = 5;
+static const int foreman_internal_timeout = 7200;
 
 // Initial value for backoff interval (in seconds) when worker fails to connect to a master.
 static int init_backoff_interval = 1;
```

**Comment by leeping** [comment]
On a related note, please let me know if you have updated links to the API documentation.  I'm getting 404 errors at these links:

https://cctools.readthedocs.io/en/latestapi/html/classwork__queue_1_1WorkQueue.html

**Comment by dthain** [comment]
Ah, sorry, you caught us right in the middle of a documentation transition.

The API docs should be in the usual place:
http://ccl.cse.nd.edu/software/manuals/api/html

You may need to clear your browser cache to eject a (temporarily) bad link.
If it still doesn't work, please let us know.

**Comment by dthain** [comment]
@leeping no problem, we can easily modify `work_queue_tune` to do what you want.
One question: are you actually making use of the worker in `--foreman` mode?

**Comment by dthain** [comment]
After taking a quick look at the code, most of the capability you need is already there, it's just not documented very well.  You should be able to do this right away from inside your main program:

```
work_queue_tune(q,"min-transfer-timeout",7200);
work_queue_tune(q,"short-timeout",7200);
work_queue_tune(q,"long-timeout",86400); // Not available yet
```

(If you are using Python, the equivalent is `q.tune(name,value)` for each of those.)

I think that two of those changes don't have much effect:
- The 5 second wait after "Invalid wait" only occurs if you pass in an invalid time to `work_queue_wait`.
- The `foreman_internal_timeout` only affects how responsive the foreman is to the master when its own workers are not responding.  It doesn't lead to a failure.

I just made a new PR #2201 that updates the documentation and adds the `long-timeout` option.

You don't need to upgrade, unless you happen to be using the foreman.

Let us know if it works for you.

**Comment by leeping** [comment]
Hello Doug,

Thank you for the quick reply!

I'm currently not using the foreman feature, so I guess it is not necessary to upgrade.  It seems we should be able to use your existing API to set the timeouts.  It's too bad I don't have a unit test for this, because it's hard to "craft" the situation that was leading to timeouts a while back.  

I'll start switching over to the conda installable package and I'll let you know if we start to experience any interesting behavior.  Thank you again!

- Lee-Ping

**Comment by leeping** [comment]
(BTW, you may close the issue after seeing this.)

**Comment by dthain** [comment]
Ok, keep us posted.
