### ISSUE TITLE
Taks retries history is not kept explicitely kept

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2209]
The reasons for retrying a task (i.e., resource exhaustion, and workers' disconnection, failures, and fast aborts), are not explicitly recorded in any structure, or in the logs. The history of retries can be reconstructed from the transactions log, but this can only be done by an expert.

Here are some suggestions:

- On the final transaction of the task, that is the DONE transaction, we can also print the history of retry causes.
- The causes may be made available in either the task structure, or by a request to the work queue object.

**Comment by dthain** [comment]
Let's keep this in mind for dataswarm.  Easier to make a running record in a JSON document for the task.
