### ISSUE TITLE
How to exchange results of tasks in WorkQueue

### ISSUE THREAD

**Issue by gilv** [cooperative-computing-lab/cctools#2218]
I want to submit two tasks - t1, t2 to the workqeue and i have two workers each running on separate machine (with good network between them), such that worker 1 pull t1 and worker 2 pull t2. I want to use MPI to exchange output results that were generated by t1 with t2. Then I want to resubmit tasks again to workqueue and pull them again automatically by the workers. I basically want to create sort of loop, where each step exchange results with MPI and resubmit back tasks to WQ

Does WQ or some other cctools package supports to use MPI to exchange results between t1 and t2? Does WQ support the entire scenario with task resubmisisons? or i need to implement this logic outside of work queue?
Thanks

**Comment by btovar** [comment]
Our task abstraction assumes that they do not communicate with other tasks, and that any task in the queue is ready to be executed to completion.

You could make your scenario work by implementing yourself the following logic:

- You guarantee that at all times either exactly two tasks are submitted, or no tasks are submitted.
- The tasks themselves know to wait for the other tasks.
- The work queue master waits for the two tasks to return before submitting more. 
- If one task fails or hangs, you cancel the other.

The 'work queue way' of doing things would be to make tasks smaller, in the sense that they write the partial results to a file and terminate. The master then creates new tasks from the partial results. In this way, while a single task may be slower than the two MPI tasks, you will be able to have more tasks running concurrently, which may or may not be what you want.

**Comment by gilv** [comment]
@btovar thanks...is there some easy way to submit "mpi tasks"?

**Comment by btovar** [comment]
work queue's design assumes that tasks don't communicate with each other during their execution, thus there is not a way to coordinate mpi tasks that need to communicate to other mpi tasks.

Of course,  mpi tasks that execute in a single host using multiple process are supported, but in such case the fact that the tasks use mpi is not very relevant.

**Comment by dthain** [comment]
Closing b/c conversation seems to have died out.
