### ISSUE TITLE
Name error on cancellation in WQ futures

### ISSUE THREAD

**Issue by trshaffer** [cooperative-computing-lab/cctools#2242]
I'm playing with the new WQ futures interface, and I'm getting an exception when trying to get the result of a cancelled task.

    Error when executing future object callback:
    Traceback (most recent call last):
      File "cctools/work_queue/src/bindings/python3/work_queue_futures.py", line 324, in _invoke_callbacks
        fn(self)
      File "./wq_tool", line 70, in _taskcb
        t.result()
      File "cctools/work_queue/src/bindings/python3/work_queue_futures.py", line 273, in result
        raise CancelledError
    NameError: name 'CancelledError' is not defined

Looks like the exception is here:
https://github.com/cooperative-computing-lab/cctools/blob/cad910d63d290131ffdcbb4975ace9c80d3d9c0e/work_queue/src/bindings/python/work_queue_futures.py#L273

Is this just missing an import for `asyncio.CancelledError` @btovar ?

**Comment by btovar** [comment]
Tim, yes, it seems that way.

**Comment by btovar** [comment]
It is actually concurrent.futures.CancelledError, submitting a pr shortly.
