### ISSUE TITLE
cvmfs not enabled in 7.1.0 with --with-cvmfs-path

### ISSUE THREAD

**Issue by tmarkhuang** [cooperative-computing-lab/cctools#2263]
cvmfs is not enabled in parrot_run, when building 7.1.0 with --with-cvmfs-path

Details:
I am interested in using parrot_run with cvmfs.  The [pre-compiled binary for 7.1.0](https://ccl.cse.nd.edu/software/files/cctools-7.1.0-x86_64-centos6.tar.gz) doesn't support cvmfs.  So, I decided to build it from source, with this configuration and GCC 4.8.5 on CentOS 6.10

<pre>
./configure --prefix /home/user/cctools --with-cvmfs-path /path/to/libcvmfs/usr
</pre>

However, cvmfs not enabled in parrot_run:

<pre>
$ /home/user/cctools/bin/parrot_run --help | grep Enabled
Enabled filesystems are: chirp ftp multi http hdfs grow anonftp

$ /home/user/cctools/bin/parrot_run --version
/home/user/cctools/bin/parrot_run version 7.1.0 FINAL (released 2020-03-17 15:14:13 -0500)
        Built by user@server on 2020-03-17 15:14:13 -0500
        System: Linux server 2.6.32-754.25.1.el6.x86_64 #1 SMP Mon Dec 23 15:19:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
        Configuration: --prefix /home/user/cctools --with-cvmfs-path /path/to/libcvmfs/usr
</pre>

  Library and include files for libcvmfs were unpacked from cvmfs-2.7.1-1.el6.x86_64.rpm and cvmfs-devel-2.7.1-1.el6.x86_64.rpm, downloaded from [CVMFS download site](https://cernvm.cern.ch/portal/filesystem/downloads).

  I did a similar configuration with 7.0.22 and cvmfs was enabled in parrot_run.

**Comment by btovar** [comment]
Thanks for your report! I am working on reproducing it on our side.

**Comment by btovar** [comment]
@tmarkhuang, could you give version 7.1.1 a try?

cvmfs should now be correctly enabled in all cases.

**Comment by tmarkhuang** [comment]
Thanks for fixing the bug/issue.  cvmfs is now enabled in parrot_run for 7.1.1 with --with-cvmfs-path.  I tested both source tgz from CCL web site and cctools release page on Github, and both work correctly.  I noticed that source tgz files from these two locations have different top level directory names, 'cctools-7.1.1-source' (CCL) vs 'cctools-release-7.1.1' (Github).  This is a minor issue.
 
I also tested pre-compiled binary for 7.1.1 and cvmfs is enabled in parrot_run.  

On a separated issue (but related to 7.1.0/7.1.1), I noticed that issue #1880 is still exhibited in pre-compiled parrot_run.  I don't see such issue in my locally built parrot_run with cvmfs 2.7.1-1.  Could it be an older version of cvmfs was used to build the binary?

**Comment by btovar** [comment]
Great, thanks for letting us know!

About #1880, indeed. As you probably noticed, with this new release we updated our distribution channels. The older version is one that we could easily statically compile to include in the parrot binary. We just need to revise this procedure for a newer cvmfs version.
