### ISSUE TITLE
how to handle python environments in work queue

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2294]
Consider a python environment generated by a tool such as conda-pack. The environment is saved to a tar file. In order to use the environment, the file needs to be expanded to a directory (via tar), followed by a conda-unpack, which updates absolute paths in the contents of files inside of that directory.

The current work queue model cannot handle these environments in a satisfactory manner:

- If the python environment file is specified per task, then it is up to the task to expand and unpack the environment. This is inefficient, as each task has to repeat these operations. Also, it has the potential of not being kind to the filesystem if many tasks running in a single worker try to expand the environment at the same time.

- If the python environment is sent as an expanded directory, then it is still up to the tasks to run the unpack command. There is the potential of two tasks trying to write to the same file at the same time.

- The expandind/unpacking may be handled by a wrapper sent with the task (such as python_package_run). This wrapper makes sure that the expansion occurs once. The problem with this approach is that work queue has no knowledge of the directory to which the environment was expanded. If the environment was sent as a tar file, this is inefficient as now the environment is present both expanded and not expanded. Further, tasks are implicitly coordinating for a resource, all of these hidden to work queue.

The main issue here is that there is an input (i.e., the python environment) which is not ready to be presented to the tasks, and at the same time, work queue assumes that input files/directories are never modified.

If python environment did not need the conda-unpack step, then we could in principle efficiently stream from the master the tarball and let the worker write the expansion. The problem with conda-unpack, even if we turn it into a filter, is that the contents of the tarball are modified. For the specifics of conda python environments and work queue these modifications may not be important, but it may not generalize to other data that need to be transformed before presented to a task.

**Comment by btovar** [comment]
I did a small test to turn conda-pack into a filter, with a command such as:

```
tar -C ./my-env  -xvf my-env.tar.gz | ./conda-unpack-filtered
```

Some notes:

- conda-unpack filtered is based on the particular conda-unpack contained in my-env.tar.gz. Thus, the streaming cannot be done right away. Getting conda-unpack and transforming it into conda-unpack-filtered can be done once at the master, though.
- Unlike conda-pack, conda-pack-filtered has to assume that there is a python >= 2.7 on the PATH at the execution site.
- conda-unpack-filtered turns a list of files in conda-unpack into a dictionary. Rather than iterating the list, it just checks filenames from stdin to the keys of the dictionary.
- tar's option -v prints the filename currently being expanded, thus conda-unpack-filtered does not start working on a filename until it gets the next filename.
- This test assumes that no filename has a newline in it.

**Comment by dthain** [comment]
Ok, I appreciate the investigation, but it sounds like it can't really be done in a "streaming" mode.  (Where "streaming" means only writing the final output to local storage.)  And, it would create new execution dependencies at the master, in particular, python.

What we need here is a model where the tarball is unpacked, and then something inside the tarball is executed to bring it to a final state.  That would only require that `tar` and `gzip` be present at the master, right?

**Comment by btovar** [comment]
Indeed. The only case I can see conda-unpacked-filtered being marginally useful is if the master streams the tarball and the worker modifies the files before writing them. In this way, the worker would not have to have space for both the tarball and the expanded directory.  However, this increases the number of dependencies (python), and the size of the data to transfer.

Otherwise, sending a tar.gz assumes that tar and gzip can be found at the execution site, and that a python, conda, and conda-pack are included in the conda environment.

**Comment by dthain** [comment]
Earlier, we talked about three different general abstractions:

- Stream: the worker provides a process P that reads the incoming data and writes the final version into target T.
- Transform: the worker provides a process P that reads the stored version S and writes a new version to target T.
- Mutate: the worker provides a process P that modifies the stored version S to become the final version S-prime.

So, the conda-unpack problem could be expressed as a special case of the mutate operation, and specified by the user like this:
```
{
localname  : "conda-dir"
remotename : "conda-dir"
mutate: "./bin/activate; conda-unpack"
}
```

Or, in the old way:

```
work_queue_specify_file_mutate(  task, lname, rname, flags, command );
```

It's a bit harder to retro-fit this into WQ than it will be to fit it into DataSwarm from the beginning, but I see two ways to go about it:

1 - Worker sends a `put` or `url` operation as normal to create the file in the remote cache, then sends a separate `mutate` operation to run a command-line on the cached object, to achieve the final form.  This will be easy to add inside the send-task operation, transparent to the user.  However, handling failure is interesting.  If its possible for the mutation to fail, then we need to it send back a result, and the master ends up waiting for those mutations syncronously.  If we think mutations cannot fail, then the master doesn't have to wait, but failures result in a drop of the connection.

2 - Worker sends a file over as normal, and then dispatches a first-class task to modify the object.  (Tasks aren't really supposed to modify storage objects, but at least this is happening at the master's explicit direction.)  This allows the mutation to happen asynchronously at multiple workers simultaneously.   However, it makes the master rather complex, because now it is generating tasks implicitly, and has to "hide" them from the end user in some way.  Complications.

**Comment by btovar** [comment]
The mutate operation could be done after the task has been sent, but before it is about to start at the worker (e.g., just before the fork). Should mutate fail, it can be charge as a failure to the task with an appropriate error code. In this way the master does not have to wait for the mutate operations, and failed mutates are only tried once per task. Further, since it is done before the fork, we ensure that no two tasks try to mutate the data at the same time.

The problem with a drop connection when mutate fails is that the task will be tried over and over again.

I don't think we want to dispatch first-class task to modify the object, at least in work queue. It will make collecting statistics really hard.

**Comment by dthain** [comment]
In that case, who is responsible for tracking that the mutate has been done once (and no more than once), taking into account task failures?

**Comment by btovar** [comment]
The worker would remember whether the mutation was successful. If it was a failure, the worker can immediately return any new tasks sent to it that depend on the mutation. Note that this does not prevent the master sending new tasks that depend on the mutation, and this is important to guarantee that the master keeps making progress. When a task fails because of a failed mutation, it is not retried and returned to the user. 

As an optimization, the master could keep track of which mutations failed per worker, and send task accordingly. One problem with this is that if the mutation fails in all the workers, then no task will be dispatched and the workflow will be stuck.

We cannot mark a mutation as generally 'failed' at the master, as the failure may depend on the worker's environment. If the mutate failure is because of the worker, then that worker can later be blacklisted by a user.

**Comment by dthain** [comment]
I think I'm uncomfortable associating the mutation with the task, rather than the file.

The master sends tasks to locations where the needed files are present.  It seems to me that if the mutation is not complete (or failed) then the master should not be sending tasks there in the first place...

**Comment by btovar** [comment]
I agree with you if we are talking about Data Swarm.

However, I think that in the work queue model things are a little different:

- Files are always associated with tasks. There is no way no specify a file outside a task.
- As far as the master is concerned, it did the transfers it needed to: data + mutator.
- No execution happens outside a task. Thus, it is natural to tack the mutation to the execution of the task.
- Blacklisting of workers because of execution failures is left to the user. By not sending tasks because of mutate failures we are effectively blacklisting workers. Moreover, if some tasks do not depend on the mutation, the blacklisting is selective, which will be confusing.
- There is no way to communicate to the user that a mutation failed other than returning a task. Returning some tasks with failure, but not trying all of them at a worker puts those later tasks in a weird idle/held state.

**Comment by dthain** [comment]
Your comment that "Files are always associated with tasks." isn't quite so simple.  That is certainly true at the API level.   But at the level of the master-worker protocol, they are two separate things:  A `file` operation puts a file into the cache with a given them.  Then, a `task` operation specifies a task, and the `infile` sub-command binds a name in the sandbox to the cached file name.

**Comment by btovar** [comment]
Yes, I think you are correct. I think what I had in mind is that files do not know about anything but themselves. The master knows which files each task has, and which files are at which worker. To ask for the status of a file, we would need to transverse the list of tasks and workers.

It seems that we need the reverse mapping: a file should know at least on which workers it is. In that way, it can know the workers it has been successfully mutated, etc.

**Comment by dthain** [comment]
Ok, I think I am understanding your point now.
How about this:

Same proposal as before:
https://github.com/cooperative-computing-lab/cctools/issues/2294#issuecomment-625310950

Except that:

The master sends the file over as normal via `put` or `url` and then follows it up with a `mutate` command. The worker accepts the mutate command silently and buffers it up.

As you suggested, when a task is setting up its sandbox, the mutation is performed, and then the task either continues or fails.  The worker remembers so that the mutation is performed only once per file object?

How does that sound?

**Comment by btovar** [comment]
Sounds good! 

We still have the ugly case of sending doomed tasks to a worker that failed to mutate a file, but I don't see how we can treat all tasks consistently otherwise.

We could send tasks only to workers that have not failed the mutation, and when no such worker exits, fail the task. But if the only worker that successfully mutated the file disconnects, then we probably do not want to fail all of the tasks.  At the same time, we do not want to hold them indefinitely.

**Comment by dthain** [comment]
Oh, but that leaves an interesting question.
If the mutation fails, the task fails, obviously.
But then what is the state of the file?

**Comment by btovar** [comment]
Yes, it is even more interesting because it is not a single state, but there is a state per worker of mutation tried.

**Comment by dthain** [comment]
I think that this long thread has developed suitably into the `poncho` toolkit, which can share unpacked packages between tasks, or do packing at the worker level.
