### ISSUE TITLE
JX Schema Behavior?

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2312]
Nate, is this the intended behavior of the schema function?  It appears to return an object on its output for every object on its input:

```
./jx_test
{}
schema( select( type=="catalog", fetch("http://catalog.cse.nd.edu:9097/query.json") ) ) )
```

Returns:
```
[
{"type":"string","owner":"string","port":"integer","address":"string","name":"string","lastheardfrom":"integer","url":"string","starttime":"integer","version":"string"},{"type":"string","owner":"string","port":"integer","address":"string","name":"string","lastheardfrom":"integer","url":"string","starttime":"integer","version":"string"},{"type":"string","owner":"string","port":"integer","address":"string","name":"string","lastheardfrom":"integer","url":"string","starttime":"integer","version":"string"},{"type":"string","owner":"string","port":"integer","address":"string","name":"string","lastheardfrom":"integer","url":"string","starttime":"integer","version":"string"},{"type":"string","owner":"string","port":"integer","address":"string","name":"string","lastheardfrom":"integer","url":"string","starttime":"integer","version":"string"},{"type":"string","owner":"string","port":"integer","address":"string","name":"string","lastheardfrom":"integer","url":"string","starttime":"integer","version":"string"}
]
```

My first inclination would be that it returns one object describing the schema of the entire list, perhaps with duplications and variations collapsed in some way:

```
{"type":"string","owner":"string","port":"integer","address":"string","name":"string","lastheardfrom":"integer","url":"string","starttime":"integer","version":"string"},
```

Or am I misunderstanding how this is used?

**Comment by nkremerh** [comment]
I made the assumption that we may be asking about multiple different component types which share keys. In the case that we are querying from two different software authors, they may use the same key name with different meaning, so I made the decision to keep each object's schema as a separate object to be pushed to an array.

Perhaps this is more of a corner case than an expected scenario (it may also be due to my preference for verbosity in debug output). If this is the case, I can see a reason to condense the output.

**Comment by dthain** [comment]
I think it all depends on the intended use case.

If the objective is simply to describe the type of a expression, then I would expect it to just recursively substitute values with type names, like this:

```
schema(123)
-> "integer"
schema( {"name":"fred","port:123} )
-> {"name":"string","port":"integer"}
schema( [ {"name":"fred", "port":123}, {"name":"wilma", "port":456} )
-> [ {"name":"string","port":"integer"}, {"name":"string","port":"integer"}]
```

On the other hand, if the goal is to summarize a dataset before querying it, then I would expect it to collapse all members of a list:

```
schema( [ {"name":"fred", "port":123}, {"name":"wilma", "port":456} )
-> {"name":"string","port":"integer"}
```

Because if you are attempting to understand a large dataset with millions of records, it wouldn't be helpful to get back a result with millions of elements.

**Comment by nkremerh** [comment]
Fixed.
