### ISSUE TITLE
JX Parse HTML Oddity

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2314]
I missed this the first time around: `jx_parse_from_html` is a very strange function:
https://github.com/cooperative-computing-lab/cctools/blob/d4aefcdb3d11c86cbd587ace1bf282581ea16018/dttools/src/jx_querytools.c#L18

If I am understanding it correctly, it fetches JSON from a web server by assuming that there is some HTML terminated by a very specific H1 tag, and then assumes all the JSON is entirely on the next line.  This seems like a very fragile set of assumptions .

Here is better solution:
1 - Modify the TLQ server to just give back nothing but raw JSON at the desired line.
2 - Modify `jx_parse_from_html` to just open the file stream and use `jx_parse_stream` to get it.

That way you can efficiently transfer/parse a large amount of data, and the tools will work across any web server that delivers plain JSON.  (I can't fix it myself here since it depends upon a specific behavior of TLQ.)

**Comment by nkremerh** [comment]
You were reading my mind. This is already in the works.

**Comment by nkremerh** [comment]
Fixed.
