### ISSUE TITLE
Compilation on FreeBSD with MPI

### ISSUE THREAD

**Issue by sprock** [cooperative-computing-lab/cctools#2318]
Hello,

I have been able to compile cctools on FreeBSD (11.3) without MPI after making a few changes (= crude hacks) to the git source (ed44c33d1ffb810acdc79b13fc8dd1f7064777fa).   I ran a few simple examples and makeflow, at least, seems to work fine.

I tried enabling MPI (mpich-3.2.1_6):

./configure --with-swig-path /usr/local/bin/swig3.0 --with-readline-path /usr/local \
--with-mpi-path /usr/local --prefix=/home/rmason/.local/cctools

but compilation fails:

/usr/local/bin/ld: libforce_halt_enospc.o: relocation R_X86_64_32S
against symbol `__stderrp@@FBSD_1.0' can not be used when making a
shared object; recompile with -fPIC

I note that -fPIC is already in the configure script, so something else is going on.

I appreciate any help, and thanks for making these tools available.

Roger

**Comment by btovar** [comment]
@sprock,   libforce_halt_enospc  is not essential for the main components to run. You could set  
```
PRELOAD_LIBRARIES =
```
in `dttools/src/Makefile` around lin 65 and see where that takes you.  You probably will also need to run 

```
./configure --without-system-resource_monitor  --without-system-parrot  --with-fuse-path=no  ...etc...
```

as those components are pretty linux specific, or also need shared libraries.

MPI is only optionally used in makeflow, thus it may also not be essential for you. In fact, in our binary distributions we do not include MPI by default. As for the particular error, I'm afraid we do not have much experience compiling cctools+mpi in freebsd, but it sounds to me that the compilation and linking processes may be using different tools (e.g. one mpi, the other clang, or something like that.)

**Comment by sprock** [comment]
Hello,

Benjamin Tovar <notifications@github.com> writes:

> @sprock,   libforce_halt_enospc  is not essential for the main components to run. You could set  
> ```
> PRELOAD_LIBRARIES =
> ```
> in `dttools/src/Makefile` around lin 65 and see where that takes you.  You probably will also need to run 
>
> ```
> ./configure --without-system-resource_monitor  --without-system-parrot  --with-fuse-path=no  ...etc...
> ```
>
> as those components are pretty linux specific, or also need shared libraries.
>
> MPI is only optionally used in makeflow, thus it may also not be essential for you. In fact, in our binary distributions we do not include MPI by default. As for the particular error, I'm afraid we do not have much experience compiling cctools+mpi in freebsd, but it sounds to me that the compilation and linking processes may be using different tools (e.g. one mpi, the other clang, or something like that.)

Thanks for the response.

I could not get it to compile, but MPI is not essential, so I am
content.

Cheers,
Roger

**Comment by dthain** [comment]
Closing this b/c I think the use case has been addressed.
Please let us know if you have any further problems.
