### ISSUE TITLE
WQ-JSON Worker Port Detection

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2321]
As written, the WQ-JSON client tells the server to use a fixed port number for workers.  Again, this won't work due to collisions between port numbers.

Native WQ applications handle this by telling the manager to listen on port zero, (meaning any port) and then read back the actual port via `work_queue_port`.

Fix this up in WQ-JSON by adding a new API operation `status` that reads back all the high level configuration of the server: port, project_name, tasks ready/running/etc, workers connected/etc and send that back in one JSON blob.

So then the standard WQ-JSON app will create the server listening on port zero, then immediately to a `status` to get the port number back, and continue that way.

**Comment by dthain** [comment]
@camicarballo per our discussion today, you should be able to use the `link` object as it is.
`link_address_local` tells you the address and port of the local connection.
http://ccl.cse.nd.edu/software/manuals/api/html/link_8h.html#acc347b042e023a279eec60de1395e9ae

If you want to write a little helper function `link_local_port` as a wrapper around `link_address_local`, that would be fine.
But I don't think any major surgery to link is needed.

**Comment by camicarballo** [comment]
Should all of the properties of the struct work_queue_stats be returned? Or just some _important_ ones?

**Comment by camicarballo** [comment]
Also, the port number cannot be obtained from this work_queue_stats structure as it has been deprecated. So, for the purposes of port detection, this issue is addressed by #2332. In terms of adding a `stats` operation to the WQ-JSON API, I can create a separate issue specifically for that if needed.

**Comment by dthain** [comment]
The JSON `status` command need not correspond exactly to one single WQ C API call. 
Use `work_queue_port` to get the port and put that in the status field.
There are a lot of fields there, I think it would be sufficient just to put the `task_*` and `worker_*` fields in there to start.

**Comment by dthain** [comment]
It's a small thing, but let's call this JSON API operation `status` rather than `stats`.
The former implies the current state of the system, while the latter implies "statistics".
