### ISSUE TITLE
SLURM MPI Dispatch

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2328]
Makeflow does not currently dispatch MPI jobs to SLURM correctly.
The underlying issue is that SLURM expects a somewhat different invocation for MPI vs non-MPI jobs.

For example, a 4-core multithreaded job should be submitted like this:
```
sbatch -N 1 -n 1 -c 4 job.sh
```

While a 4-process MPI job (each process using one core should be submitted like this:
```
sbatch -N 1 -n 4 -c 1 job.sh
```

Further, `job.sh` must include a call to `srun --mpi=pmi2` in order to set up the MPI environment properly, in the latter case.

Solving this requires two things:
1 - Some sort of syntax in Makeflow to convey that a particular job employs MPI and the desired configuration of the job.
2 - Appropriate support in `batch_job_cluster` to convert that information into the appropriate `sbatch` commands for SLURM.

May need to consider whether similar support is needed for other systems.

**Comment by btovar** [comment]
We have .MAKEFLOW_CORES to set the number of cores. One thing we could do is to add .MAKEFLOW PROCESSES. The example above would look like:

.MAKEFLOW CORES 1
.MAKEFLOW PROCESSES 4

I am not sure about the `srun --mpi=pmi2`, as it is modifying the command line for a specific batch system. For slurm we could have it so that  `srun ...` etc. is automatically added if  PROCESSES > 1.  

We would also need to add an option that disables any of these and only honors BATCH_OPTIONS. We have that for sge, but only for sge.

**Comment by dthain** [comment]
I think that's on the right track.  Are the resources then divided among the processes, or is each process assumed to consume the stated cores, memory, and disk?

Perhaps we should be explicit about an application being MPI?

Agreed about the resource disabling.  Isn't that what `--safe-mode` does?

**Comment by btovar** [comment]
I think we need to assume that each process consumes the stated resources.  For example, the resource monitor would have to check for --max-concurrent-processes=4 --cores=4.   Otherwise, we would get --cores=1, which probably is not what we want.

**Comment by dthain** [comment]
That makes sense.

How about we make `PROCESSES` explicitly `MPI_PROCS` so that it's clear that we are enabling MPI functionality?
Is there any other supported programming model where we are expecting to dispatch P x ( CORES, MEM, DISK ) in parallel?

**Comment by btovar** [comment]
There is the local MPI mode that Kyle added, and most likely some sge installations will have something similar.

**Comment by dthain** [comment]
Well, that's a different thing -- in that case, Makeflow itself is the MPI
program and dispatches tasks among MPI processes.

**Comment by btovar** [comment]
My proposal is then:

- Extend --safe-mode to all batch systems.
- Add MPI_PROCS to correctly set -n for slurm.
- Set -N by dividing CORES / MPI_PROCS.  With this CORES has the total cores among all the mpi processes. This is consistent with CORES, MEMORY, and DISK stating the total cores used by the rule, and allows easy tests by simply changing the -T argument.
   - If CORES is not given, it is assumed to be MPI_PROCS. 
   - If MPI_PROCS is not given, only -N is set.
   - It is an error if CORES is not a multiple of MPI_PROCS.
- Do not modify the command line adding srun --mpi=pmi2. This is left to the user to specify the particular local queues.

**Comment by dthain** [comment]
I agree with most of that, except: "If MPI_PROCS is not given, only -N is set."

I think in that case, it's a multi-core program, not an MPI program, so you want -N 1 -n 1 -c $CORES, right?

**Comment by btovar** [comment]
Ah yes, missed that.

**Comment by btovar** [comment]
safe-submit-mode is actually enabled in all the appropriate batch systems.

**Comment by dthain** [comment]
@btovar please touch base with the original reporter on this one.

**Comment by Dcn303** [comment]
Hi everyone 
i am working on  HPC cluster 
i have 2 node with 4 core each .
How will i write a makeflow script to allocate the 4 core of both the node 1 and node 2 
.I have a script simple.sh as shown below 
`#! /bin/bash `
`N=8 `
`(mpirun -np $N simpleFoam -parallel) 2>&1 | tee log.simpleFoam `
`touch c`
which uses 8 mpi processes to execute 
i also have to submit to slurm 
i have written the makeflow script(run.makeflow) as show below 
`BATCH_OPTIONS= --nodes=2 --ntasks-per-node=4`
`.MAKEFLOW MPI_PROCESS 8`
`.MAKEFLOW CORES 8`
`c : b a `
     ` srun $(BATCH_OPTIONS)  ./simple.sh`
 `b: a`
     ` srun ./decompose.sh`
`a: `
      `srun ./blockMesh.sh`
i have submitted the makeflow to slurm as 
`makeflow -T slurm run.makeflow `
the rules
 `b: a`
     ` srun ./decompose.sh`
`a: `
      `srun ./blockMesh.sh` works fine and it have also allocated the two node1 and node2
but the ./simple.sh  is not executing
can anyone kindly help me on this regard
