### ISSUE TITLE
JX Lacks Dictionary Comprehensions

### ISSUE THREAD

**Issue by tshaffe1** [cooperative-computing-lab/cctools#2336]
We added list comprehensions to JX quite a while ago, and they serve as a powerful way to manipulate and filter expressions. The syntax is taken directly from Python ([PEP202](https://www.python.org/dev/peps/pep-0202/)). Python also supports an analogous syntax for dictionaries ([PEP274](https://www.python.org/dev/peps/pep-0274/)). Initially, JX was primarily used for expanding Makeflows so only list comprehensions were implemented. There is no particular reason that dict comprehensions couldn't be implemented, aside from lack of interest.

@nkremerh your current work would benefit from adding this to JX?

**Comment by nkremerh** [comment]
Yes, this would greatly benefit the querying capabilities of JX.

**Comment by dthain** [comment]
Let's think a little bit about the semantics.

Suppose you have:
```
d = { "a":5, "b": 10, "c":20 }
```

Do you want the comprehension operator to accept a dictionary, like this?
```
x for x in d -> ["a","b","c"]
```

Or do you want to explicitly extract keys and values in some way?
(In which case the comprehension operator still operates on lists.)
```
x for x in keys(d) -> ["a","b","c"]
x for x in values(d) -> [5,10,20]
```

**Comment by nkremerh** [comment]
Another consideration, do we want to keep it Pythonic or not? I remember this being an important discussion for prior functionality.

**Comment by dthain** [comment]
Ok, what would that look like?

**Comment by trshaffer** [comment]
Python's version depends on helper functions to choose which way to operate. You might use `dict.keys()`, `dict.values()`, or `dict.items()` so e.g.

    {k: v+1 for k, v in d.items()}

There's a bit of distance to get this exact syntax implemented in JX.
- We don't have function lookup with the `.` operator. This would make it much easier to copy Python on various things, but we start having to decide with which of multiple ways to express the same functionality (operator vs. top-level function vs. method). I'm not sure if copying Python's syntax is worth going down that road.
- `dict.items()` returns a list of `(key, value)` pairs. The above syntax works in Python due to tuple unpacking, which JX doesn't have. Again, not sure if it's worth adding a general language feature to get this syntax to work.

Since we've already broken somewhat from Python, I'd propose a Python-like syntax:

    {k: v+1 for k: v in d}

Also note that if we generalize a bit, we can get those helper functions using comprehensions.

    [k for k: v in d]    # dict.keys()
    [v for k: v in d]    # dict.values()
    [[k, v] for k:v in d]    # dict.items()

Not sure how useful `dict.items()` is for JX, but it would be possible. And likewise, objects from arrays:

    {k: 0 for k in a}

Language wise, the expression on the left would have to match the enclosing type (`{}` has `k:v`, `[]` has `v`), while the iterator variable(s) after the `for` need to match the type of the collection being iterated.

**Comment by dthain** [comment]
Nate, I think it would be helpful if you can show some examples of queries that you want to write, but cannot, due to the lack of comprehensions-on-dictionaries.  That would give us some direction here.

**Comment by dthain** [comment]
Also, I think those examples show that we are bumping up against the peculiarity of pairs `k:v` which are really just two-element tuples `[k,v]`.  Suppose that we had dict-comprehensions just return each pair as an array `[k,v]`, similar to what you did with `items`  Then you wouldn't have to change the syntax at all:

```
x for x in d -> [  ["a",5], ["b",10], ["c",20] ]
```
And then:

```
keys(d) := x[0] for x in d
values(d) := x[1] for x in d
```

**Comment by nkremerh** [comment]
Using this object:
```
obj = [
"task1": {
  "setup": {"status": "success", "error": 0, "msg": "setup complete"},
  "runtime": {"status": "success", "error": 0, "msg": "successfully executed command in 3.02 seconds"},
  "cleanup": {"status": "failure", "error": 3, "msg": "could not clean up intermediate data files"}
},
"task2": ...
]
```

I might want to run the following queries to figure out the error message of the cleanup stage in task1:
```
selexpr = select(x["error"] != 0 for x in task1, obj);
project(msg, selexpr);
```

**Comment by trshaffer** [comment]
For lists of pairs, can we only use that to pull components of objects -> arrays, or put another way is there any way for a comprehension to *produce* an object?

Also, the main motivating example I had in mind from Makeflow is filtering/modifying workflow components, e.g. double all resources

    {k:v*2 for k: v in RESOURCES}

or filtering environment variables out

    {k:v for k:v in ENVIRONMENT if k!="PATH"}

Probably not useful enough by itself to justify adding dict comprehensions, but a flexible structure might come in handy elsewhere.

**Comment by dthain** [comment]
Ah, I see.  Not just arrays and dictionaries in, but also arrays and dictionaries out.  Are all four combinations needed, or just like-to-like?

**Comment by trshaffer** [comment]
I think list->list and dict->dict would be the most common, but I don't see a big drawback in allowing cross-comprehensions. Allowing the mix-and-match does allow for some wild expressions, e.g. from Nate's example (assuming the outermost `obj` is supposed to have braces). This would give a list of `"cleanup"` messages pulled out from all tasks where `"error"` is nonzero,

    [v["cleanup"]["msg"] for k:v in obj if v["cleanup"]["error"] != 0]
    -> ["could not clean up intermediate data files", ...]

while this would give something with the same "shape" as `obj` but including only phases that failed.

    {k:{m:n for m:n in v if n["error"] != 0} for k:v in obj}
    -> {
        "task1": {
            "cleanup": {"status": "failure", "error": 3, "msg": "could not clean up intermediate data files"}
        },
        "task2": ...
    }

Makeflow (and I think Nate's stuff) use a combination of lists and dicts in different places, so it makes sense to me to be flexible.

**Comment by dthain** [comment]
Ok, so something like this:

```
x for y in array -> array
k:v for k:v in dict -> dict
k:v for y in array -> dict
x for k:v in dict -> array
```

Awkward problem `k:v` is a `pair` but not an `expr` so it cannot be generally substituted for `x`.
Do we want to make it an `expr` or just a special case for comprehensions?

**Comment by nkremerh** [comment]
Perhaps a question stemming from my own ignorance here, but do we need to explicitly ask for `k:v` as a pair?

For example:
```
k[v] for v in k in dict
```
The exact syntax is probably off here, but does this idea avoid that awkward problem?

**Comment by dthain** [comment]
I'm not sure what the intended meaning is, can you elaborate?

**Comment by nkremerh** [comment]
`k[v]` fits our current expression syntax while `k:v` does not. So, rather than ask for `k:v` as one thing, why not ask first for `k` then for `v`? Keep them as separate things, so we first resolve `dict` then each `k` in `dict` then each `v` in `k`. Does that make more sense?

```
k[v] for v in k in dict
```

**Comment by dthain** [comment]
Hmm, I'm not sure I get it yet.
Try to break it down into parts for me.

`dict` is a dictionary.
`k in dict` takes a key from the dictionary, I think?
`v in k in dict` takes the value corresponding to dict[k], I think ?
`k[v]` seems to imply that `k` is now an array.  Did you mean `[k,v]`?

**Comment by trshaffer** [comment]
Comprehensions are already sort of special cased: there's a `struct jx_comprehension` that contains the name of the iterator variable to use, the thing we're iterating over, etc. So in the AST a basic list comprehension looks like this:

    [x + 1 for x in L]
    struct jx:
        type = JX_ARRAY
        items:
            struct jx_item:
                value:
                    struct jx:
                        type = JX_OPERATOR
                        oper:
                            struct jx_operator:
                                type: JX_OP_ADD
                                left: jx_symbol("x")
                                right: jx_integer(1)
                comprehension:
                    struct jx_comprehension:
                        variable = "x"
                        elements = jx_symbol("L")

When evaluating we either recursively `jx_eval()` the item's `value`, or if there's a comprehension attached we first eval the elements of the comprehension, then repeatedly eval `value` with each of the elements bound to `variable`. I think we can take the same approach with dict comprehensions, just add a `key` to `struct jx_comprehension` and allow `struct jx_pair` to have a comprehension pointer. In the last example (`x for k:v in dict -> array`), we would simply bind two names (`k` and `v`) before evaluating expression `x`.

**Comment by dthain** [comment]
While I don't want to close the door on this in the future, it seems like a general dictionary comprehension has a lot of complicating aspects that we should think about for a while before committing.

In the meantime, suppose that we add some suitable functions.  That's a much lower commitment (and functions are a layer separate than the core language).  If we add functions `keys` and `values`, then that opens up several use cases for Nate, for example:

```
dict[k].msg for k in keys(dict) if dict[k].error!=0
```

**Comment by dthain** [comment]
@trshaffer @nkremerh what do you think?

**Comment by trshaffer** [comment]
If it's sufficient for @nkremerh's stuff, that seems fine. Might also be helpful to add `items()`

**Comment by nkremerh** [comment]
That would be sufficient, yes.

**Comment by dthain** [comment]
@jmrundle perhaps you want to take a look at this one?

**Comment by dthain** [comment]
In the end, we addressed this sufficiently with the `keys` and `values` functions.
