### ISSUE TITLE
Refactor JX Function Dispatch

### ISSUE THREAD

**Issue by trshaffer** [cooperative-computing-lab/cctools#2340]
The function infrastructure in JX is getting to be a bit messy. Previously, function eval consisted of
1. In `jx_eval_operator()` eval the right side **only**
2. If the operator is a function call, skip everything else and go to `jx_eval_call()` to switch on the function name (stored in the left operand; would be an error to evaluate since it's not a defined variable)
3. For other operators, eval the left side and continue with other stuff ....

This is more complicated with @nkremerh's stuff, which needs to defer eval of the right as well. This leads to an extra step at the beginning:
1. If the operator is a function call and the left is a symbol and one of the special functions, convert the first argument on the right to a string.
2. In `jx_eval_operator()` eval the right side **only**
3. If the operator is a function call, skip everything else and go to `jx_eval_call()` to switch on the function name (then those special functions parse the string argument later)
4. For other operators, eval the left side and continue with other stuff ....

In the code in `jx_function.c`, it's necessary to parse and eval the quoted stuff. Looking over the code for our other existing functions, I see some memory leaks (hopefully no memory unsafety!) in receiving arguments. Many functions immediately copy the arguments and operate in place, some don't (possibly for efficiency), some appear to leak arguments and/or copies.

I think a refactor would help here. First, we should push all the function-related decisions into `jx_eval_call()`, before any eval happens. Then the dispatch in `jx_eval_call()` could make it clear whether a function is receiving the original args (for read-only use), a copy, an eval'ed copy, etc. This would make it easier to avoid unnecessary copies, quoting, memory leaks, etc. It would also allow Nate's functions to take the raw, unevaluated arguments without the print/parse step. Function eval would go like this:
1. In `jx_eval_operator()` if the operator is a function call, hand things off to `jx_eval_call()`
2. Eval both sides of the operator.
3. Continue with the usual logic for binary operators

cc @dthain

**Comment by dthain** [comment]
I like that general approach!
