### ISSUE TITLE
JX keys() and values() Functions

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2344]
Breaking this off from #2336: We need two new functions for working with dictionaries: `keys(dict)` returns the keys as an array, `values(dict)` returns the values.

@trshaffer can you take a crack at this one?

**Comment by dthain** [comment]
Actually, I've got some time, I'll work on this one...

**Comment by dthain** [comment]
Whoops, I take that back, I'm giving it back to you, since it depends upon completing #2342

**Comment by trshaffer** [comment]
I added those functions to #2342
