### ISSUE TITLE
"*** swig version 3.0.12 is older than 2.0.4, disabling python3 support"

### ISSUE THREAD

**Issue by bcdarwin** [cooperative-computing-lab/cctools#2353]
I'm compiling from source in the same environment as previously reported (#2327) but with SWIG added.

**Comment by btovar** [comment]
@trshaffer Tim, could you look at this one? I can't reproduce in the regular rhel7.  It is around line 1102 in ./configure.

**Comment by dthain** [comment]
@bcdarwin Can you share your complete output from configure?  We aren't seeing this one.

**Comment by dthain** [comment]
The comparison done directly on the desired text works, so I'm guessing there is some oddity in the string being passed to format_version. For example, this produces `ok` as expected:

```
if [ $(format_version 3.0.12) -lt $(format_version 2.0.4) ]
then
    echo incorrect
else
    echo ok
fi
```

**Comment by bcdarwin** [comment]
I observe the following strange thing with `set -x`:

```
+ format_version 3.0.12
+ echo 3.0.12
+ awk -F. '{printf("%d%03d%03d%03d", $1, $2, $3, $4); }'
+ format_version 2.0.4
+ echo 2.0.4
+ awk -F. '{printf("%d%03d%03d%03d", $1, $2, $3, $4); }'
+ '[' 3000012000 -lt 2000004000 ]
+ echo '*** swig version 3.0.12 is older than 2.0.4, disabling python3 support'
*** swig version 3.0.12 is older than 2.0.4, disabling python3 support
+ python3_avail=no
```

However, copying the test expression into the shell behaves normally.  Either it's something I'm not understanding with nonprinting characters or weird bash semantics being set in the build, or a Bash bug?  Anyway, probably out of scope for you to investigate.

**Comment by btovar** [comment]
One thing to consider is that 3000012000 does not fit in a 32-bit integer (max is 2147483648).  It could be that in this environment, calling /bin/sh limits integers to 32-bit, but calling /bin/bash does not.  Could you please try testing the expressions inside a /bin/sh session?

**Comment by dthain** [comment]
A 32-bit limit sounds like an interesting idea.
FWIW, I did this same text on a 32-bit machine `cclvm09` and still got the correct results:
```
if [ $(format_version 3.0.12) -lt $(format_version 2.0.4) ]
then
    echo incorrect
else
    echo ok
fi
```

**Comment by bcdarwin** [comment]
I didn't manage to discover the cause of this, but it's resolved in Nixpkgs-unstable, so closing for now.
