### ISSUE TITLE
Work Queue: Improved Persistence

### ISSUE THREAD

**Issue by leeping** [cooperative-computing-lab/cctools#236]
Hi there,

I wanted to say thanks again for letting me present my work at your workshop!  I wanted to be there in person, but I couldn't because I was filling out some job applications.  I hope the remote presentation went okay.

This is slightly related to issue #213 .  Recently I have found that workers are much more robust against failed connections (i.e. less likely to get "Failed to read from worker") if they connect through SSH port forwarding.  Previously I had been using this method to get around firewall restrictions, but they seem to be useful even when there is no firewall.

For compute nodes at Stanford connecting directly to my workstation, I can lose up to 500 out of 1000 workers overnight due "Failed to read from worker" errors.  I am not sure when this issue started but it seems to have become more severe in recent weeks.  I think it might be due to faulty network traffic but I'm not really sure.  On the other hand, if I forward the connections through SSH on the cluster's head node, all of the workers stay connected.  The drawback is that if there are too many connections being forwarded through the head node, all of the connections are broken when ssh on the head node crashes, due to a "broken pipe" or "too many open files" error.

Since the SSH port forwarding operation is a bit complicated, I'll reiterate it here.  When the compute node connects directly to my workstation (no forwarding), the command is:

```
./work_queue_worker leeping.stanford.edu 7329
```

With port forwarding, the command is:

```
ssh -N -f -o ServerAliveInterval=180 -L7329:leeping.stanford.edu:7329 leeping@leeping.stanford.edu (on hs-ln01, the head node)
ssh -o ServerAliveInterval=180 -N -f -L7329:localhost:7329 hs-ln01 (on compute node)
./work_queue_worker localhost 7329
```

I have this integrated into my custom job script so it doesn't require any extra work from the user, just an extra `-f` argument to torque_submit_workers.
- Lee-Ping

PS:  In all of my masters, I disabled the Work Queue "keepalive packet".  This is because the keepalive packet appeared to cause more disconnections rather than prevent them, since the master will disconnect the workers that don't send a keepalive response.  However, the keepalive packet might also create network traffic so that the OS won't kill the connection due to idle time.  Is this correct?

**Comment by Nekel-Seyew** [comment]
@btovar @trshaffer Is this still a pressing issue? wouldn't increasing the timeout value do something similar?

**Comment by dthain** [comment]
Still a problem.  Disconnections can occur even with the timeout set high.

**Comment by dthain** [comment]
Hello Lee-Ping - Well, this is a 10-year-old issue, but I think it is finally addressed in TaskVine, which is designed around the idea of data persisting across workers and workflows.  [TaskVine](https://ccl.cse.nd.edu/software/taskvine/) I'm going to close this one out, but happy to talk more if you have new ideas or projects to discuss.  - Doug
