### ISSUE TITLE
Add wall time as a resource for slurm in Makeflow

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2366]
Currently only CORES, MEMORY, DISC, and MPI_PROCESSES are set. For a use case, see:

https://github.com/cooperative-computing-lab/makeflow-examples/issues/35

**Comment by dthain** [comment]
I think this will be easy to add as a specific feature for SLURM.

Perhaps we should think about what it would take to make it work across Makeflow broadly?
- Use the resource monitor to cancel long-running jobs?
- Use the Makeflow main loop?
- Translate the feature to all other batch systems?

Or, if we can't make it universal, we should be careful to document which resources are actually implemented by each batch system.

**Comment by btovar** [comment]
The one with the resource_monitor will be universal, it is just a matter of changing wall_time = -1 to something else in the resources struct.

For others, we need to check which systems actually support time as a resource. I was thinking on adding time just for slurm for now to quickly solve the current issue, and then expand in a larger pr.

**Comment by dthain** [comment]
+1 for a quick fix in slurm.

**Comment by btovar** [comment]
Fixed with #2372
