### ISSUE TITLE
Enable MPI support

### ISSUE THREAD

**Issue by HDsky** [cooperative-computing-lab/cctools#2399]
I compile the cctools (version 7.1.7) in our cluster to enable mpi support

use the next code to configure
```
$ cd ~/cctools
$ ./configure --with-mpicc-path=`which mpicc`
```
but the configure result show that:
```
Optional external systems configured:

General libraries
curl             no
ext2fs          yes
fuse            yes
readline        yes
makeflow mpi     no

Language support:
swig            yes
golang           no
perl            yes
python2         yes
python3          no

External support configured for parrot:
cvmfs            no
globus           no
irods            no
mysql           yes
xrootd           no
```

I make sure that the "which mpicc" to the right mpic path, so how should i do to enable the MPI support in cctools?

**Comment by btovar** [comment]
My guess is that the configure script also printed the message:  ignoring unknown package --with-mpicc-path

Could you try instead with --with-mpi-path=$(which mpicc)  ?

**Comment by HDsky** [comment]
Ok，you are right. Thks a lot. 

But i have to point out that the install guide (https://cctools.readthedocs.io/en/latest/install/from-source/) should be change immediately.

**Comment by btovar** [comment]
Great! Thanks for letting us know.
