### ISSUE TITLE
Coalesced dot visualization

### ISSUE THREAD

**Issue by rampantmonkey** [cooperative-computing-lab/cctools#241]
With large dags the `dot` output from Makeflow becomes impossible to visualize. One option for reducing the complexity of the output is to coalesce tasks in the same category into a single node. The node radius should be proportional to the number of tasks in the category.

`dag_task_category` already contains a list of the nodes associated with the category.

**Comment by dthain** [comment]
This issue has largely been superseded by adding support for Cytoscape visualization, which is much more effective at handling large graphs.
