### ISSUE TITLE
Fix the github repository link in manuals

### ISSUE THREAD

**Issue by HDsky** [cooperative-computing-lab/cctools#2413]
the web page (https://cctools.readthedocs.io/en/latest/install/)

> You will only need to install CCTools from source if you want to track our latest developments on our github repository, to propose a bug fix, or if you need to add a driver support to parrot not normally included in the conda installation, such as CVMFS, or iRODS.

the "github repository" link to https://github.com/cooperative-computing-lab/cctoolscctools-source

I think it is a mistake , should be change it to https://github.com/cooperative-computing-lab/cctools

**Comment by HDsky** [comment]
#2412

**Comment by btovar** [comment]
Thanks for your report and pr!
