### ISSUE TITLE
makeflow: directory existence semantics differ between -Twq and -Tslurm (or other) backends

### ISSUE THREAD

**Issue by bcdarwin** [cooperative-computing-lab/cctools#2423]
Consider the following `makeflow.jx`:

```
{
  "rules" : [
    {
      "command" : "echo 'hello' > some_directory/hello.txt",
      "inputs"  : [],
      "outputs" : [ "some_directory/hello.txt" ]
    }
  ]
}
```

This will clearly fail if `some_directory` does not exist, but what about the situation when it's created by hand, i.e., as an overall input file?  The confusing part is that this depends on the backend used: if `-Ttorque` (or Slurm, etc.) is used, the workflow succeeds, while if `-Twq` is used, it fails with a file write error:

```
submitted job 1
sh: some_directory/hello.txt: No such file or directory
job 1 completed
echo 'hello' > some_directory/hello.txt failed with exit code 1
```

(Tested with 7.1.6.)

**Comment by btovar** [comment]
Ben,

You are observing the different semantics of batch systems, which is a
tricky area that makeflow has to deal with. Torque, slurm, etc. expect a
shared filesystem, but Work Queue does not. Work Queue assumes that it is
doing all of its operations in a sandbox inside the local filesystem where
the worker is running. Thus, when manually doing the "mkdir
some_directory", that only occurs in the shared filesystem area, but the
local Work Queue sandboxes do not see that, and thus the command fails.

One quick way to ensure that the command will work everywhere is as follows:

      "command" : "mkdir -p some_directory && echo 'hello' >
some_directory/hello.txt",

This will create the directory in the shared filesystem if needed when
using torque and slurm, and will create the directory in each of the Work
Queue local sandboxes. When transferring back the output files, Work Queue
will create directories as needed.

One way we could enforce the same semantics everywhere is to construct
sandboxes for all of the batch systems, but we found that this breaks
users' expectations when using slurm, as they expect their files to be
available everywhere.

If you have any suggestions how we can deal with this issue better, please
let us know!

Best wishes,

Ben Tovar

**Comment by bcdarwin** [comment]
From what you've said, I think it makes sense to keep things as they are.  Maybe the best 'fix' is to add a prominent note about this to the Makeflow docs so that naive users such as me don't get the idea they can simply switch backends?  If it's not too involved, a flag to disable the Workqueue sandbox might also be helpful for users using WorkQueue on a Slurm cluster.  (I could add the extra `mkdir` commands as you suggest, but this would obfuscate the workflow in a similar way to adding the directories themselves as dependencies.  Probably the proper fix on my end would be to find the first stage that uses each directory and add the directory as a dep, but I expect to have more issues with file transfers once I get past this step.)

[background:  I'm using Makeflow with WorkQueue as a wrapper around Slurm (or Torque) to batch lots of small jobs to avoid flooding the scheduler (I could manually batch the jobs but that reduces the usefulness of Makeflow) and possibly to increase robustness against jobs being terminated and not restarted (e.g., #2418) (though I haven't finished testing yet so am not sure if this is necessary), and I was confused when switching `-Tslurm` to `-Twq` broke my pipeline.]

**Comment by btovar** [comment]
Thanks for your suggestions! We would definitely add the prominent warning
to makeflow docs. As for Work Queue, 'task in a sandbox' is its execution
model and everything is built around that, so I am afraid that it can't be
changed without major modifications.

Your use case of Makeflow+WQ is one of the reasons we recommend using Work
Queue instead of directly submitting tasks to slurm, so please do let us
know if you find any other issues in this migration.


Ben Tovar

**Comment by btovar** [comment]
Ben,

We have added the warning to the manual you suggested:
https://github.com/cooperative-computing-lab/cctools/pull/2436

Thanks again!,
