### ISSUE TITLE
Makeflow: Nested Jobs Don't Set Log

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2440]
Per this issue from makeflow-examples
https://github.com/cooperative-computing-lab/makeflow-examples/issues/39

Apparently sub-makeflows don't set a distinct log file for each workflow run, which seems like a serious bug.
I think the repair is just to adjust the nested job generation to generate a unique file name, attach it as the log file name, and register it for cleanup, must like `jx_args`:

https://github.com/cooperative-computing-lab/cctools/blob/master/makeflow/src/makeflow.c#L298

**Comment by dthain** [comment]
Meant this:
https://github.com/cooperative-computing-lab/cctools/blob/master/makeflow/src/makeflow.c#L306

**Comment by btovar** [comment]
I'll submit the pr shortly. Writing the test for it.

**Comment by btovar** [comment]
Fixed with #2441
