### ISSUE TITLE
work_queue_factory doesn't have an accurate view of the queue?

### ISSUE THREAD

**Issue by bcdarwin** [cooperative-computing-lab/cctools#2442]
I started a workqueue job and then ran `work_queue_factory -Tslurm $(hostname) 9123`.  Some of the worker jobs are being cancelled by `slurm` for some (yet unknown) reason, resulting in the `work_queue_factory` output disagreeing with `squeue`, i.e., `work_queue_factory` shows

```
2020/10/06 17:59:01: |submitted: 3 |needed: 3 |waiting connection: 1 |requested: 0 
PROJECT            HOST                   PORT WAITING RUNNING COMPLETE WORKERS 
test             test                 9123      66       2      341       2 
```

but according to `squeue` only two jobs exist.

**Comment by btovar** [comment]
We recently added https://github.com/cooperative-computing-lab/cctools/pull/2419 to the master branch to detect this sort of cases. After less than 3 minutes the factory should have detected that the jobs are not running anymore. For how long was the factory running after you observed the discrepancy?

**Comment by bcdarwin** [comment]
Building from a recent commit I see `work_queue_factory` alternates every 30s between the following two states (the Slurm jobs crash immediately due to an environment issue):

```
2020/10/07 17:07:08: |submitted: 0 |needed: 3 |waiting connection: 0 |requested: 3 
PROJECT            HOST                   PORT WAITING RUNNING COMPLETE WORKERS 
test             test                 9123     239       0        0       0 

2020/10/07 17:07:44: |submitted: 3 |needed: 3 |waiting connection: 3 |requested: 0 
PROJECT            HOST                   PORT WAITING RUNNING COMPLETE WORKERS 
test             test                 9123     239       0        0       0 

2020/10/07 17:08:14: |submitted: 0 |needed: 3 |waiting connection: 0 |requested: 3 
PROJECT            HOST                   PORT WAITING RUNNING COMPLETE WORKERS 
test             test                 9123     239       0        0       0 
```

This is less than your 2-minute hard-coded heartbeat, so I guess some other mechanism is causing this?

I guess part of the problem is that my system is misconfigured (inadvertently at first), but I wonder what the proper behaviour is here.

**Comment by dthain** [comment]
Closing inactive issue, please let us know if there is more to discuss.
