### ISSUE TITLE
Separate jx the language from the schema to describe workflows

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2457]
E.g., in:
https://cctools.readthedocs.io/en/latest/jx/jx-tutorial/

the examples generate workflows, but jx is more general than that.

In:
https://cctools.readthedocs.io/en/latest/jx/jx-quick/
already there is a natural division of workflow schema, proper json, and jx library.

**Comment by dthain** [comment]
#2873 separates the expression language from the workflow language.  However, some more discussion of the expression language is needed to flesh things out.
