### ISSUE TITLE
Work Queue Status JSON Problem

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2480]
`work_queue_status --tasks <host> <port>` produces invalid JSON because each object is printed independently.  Adjust it slightly to print the following instead:

```
open-bracket
object
comma
object
. . .
close-bracket
```

You will know that it works because you can do this: `work_queue_status --tasks ... | json_reformat`

**Comment by dthain** [comment]
@btovar this would appear to be the culprit:

https://github.com/cooperative-computing-lab/cctools/blob/23dada7e12c78e5df05a5df44bb138d51aa657f5/work_queue/src/work_queue_status.c#L486

Do you recall why we did it this way?

**Comment by btovar** [comment]
I think the idea was that you could stream the tasks through a pipe.  The next component in the pipe needed to only wait for a complete task, rather than the whole array of all of them.

**Comment by dthain** [comment]
That seems like a general challenge with JSON data, I wonder if there was some specific application that we had in mind for tasks?
