### ISSUE TITLE
WQ: Should the flag WORK_QUEUE_SUCCESS be added when adding files to a task?

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2494]
Similar to #2488 (WORK_QUEUE_FAILURE_ONLY), should we add a flag to retrieve a file only when the task succeeds?

**Comment by dthain** [comment]
I think we talked about several cases yesterday:
`WORK_QUEUE_FAILURE_ONLY` - Only return this file if the task fails.  (already exists)
`WORK_QUEUE_SUCCESS_ONLY` - Only return this file if the task succeeds.
`WORK_QUEUE_OPTIONAL` (is there better name?) Do not consider the job a failure if this file was not created.

Is there another case we should be concerned about?

Related question: should it be possible to express these constraints in Makeflow?
