### ISSUE TITLE
WQ: Fix work_queue_hungry

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2497]
`work_queue_hungry` is designed to simplify the question of whether one should produce more tasks for the queue.
It's used like this:

```
while(work_queue_hungry(q)) {
     task = create another task
     work_queue_submit(task);
}
```

The current implementation dates from way back when we assumed that one task would run on each worker.  So, it assumes that the number of idle jobs in the queue should be roughly equal to the number of workers.  It returns true if there are fewer than this number of jobs in the queue.

But this doesn't work in a multi-core world.  Tasks and workers are described by (cores,memory,disk) and multiple tasks can run on each worker. So, fix up `work_queue_hungry` so that it takes this into account.

Basic idea:
- Sum up the total (cores,memory,disk) available in the workers.
- Sum up the total (cores,memory,disk) of the waiting tasks.
- Decide which resource is the limiting factor.
- Then, if the sum of tasks is less than the sum of workers, return true.

Perhaps I haven't thought this fully through, and there is a better solution.

**Comment by dthain** [comment]
@tphung3 This would be a good next step issue to work on.
It also applies to hypersweep, since using `work_queue_hungry` would allow you to pipeline jobs.

**Comment by tphung3** [comment]
How can I close this issue?

**Comment by dthain** [comment]
Ah, I had to adjust the permissions, can you see the "close" button now?

**Comment by tphung3** [comment]
Great!
