### ISSUE TITLE
Infra: Use Github Actions for CI

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2512]
We are currently using a (recently expensive) paid plan on TravisCI to run continuous integration on every PR.

Set up a github actions workflow to build and test cctools on every PR, on our various supported platform.

As a starting point, you could use our packaging test workflow here:
https://github.com/cooperative-computing-lab/cctools-packaging-test/blob/main/.github/workflows/build.yml

If that works, we will shut off TravisCI and set up a paid plan with Github instead.

**Comment by dthain** [comment]
@btovar you did a nice comparison of CI platforms, can you link that document here?

**Comment by btovar** [comment]
Here it is:
 
https://docs.google.com/document/d/1XbzmiH6xfInZhBD8vIJnj8JGvp_jaLBZNqzEMPoQVE8

**Comment by dthain** [comment]
Just took a  quick crack at this -- it works, but now I'm seeing our choices are simple Windows, Ubuntu and Mac (by invitation only):
https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners

Hmm.  I'm a little concerned we will have to find another platform for redhat etc.  Or do we need to think of our dependencies more discretely, taking into account gcc, glibc, and so forth?

**Comment by btovar** [comment]
The plan is to use docker inside the ubuntu vms. It will be similar to what we do right now with travis.

**Comment by dthain** [comment]
@btovar if your plate is reasonably clear, now is a good time to look at this.  I just renewed the github organization, and would like to shut down the TravisCI account.

**Comment by btovar** [comment]
Done in cctools-packaging-test repo.
