### ISSUE TITLE
WQ GPU Allocation Oddity

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2518]
The WQ manager has some unexpected behavior when allocating GPUs for a task.
To reproduce, use Makeflow to generate a simple task requesting 1 core and 1 GPU:

```
{
	"rules": [
		{
		"resources": { "cores":1,"memory":0,"disk":0,"gpus":1},
		"command": "/usr/bin/env > output."+n,
		"inputs": [ ],
		"outputs": [ "output."+n ]
		} for n in [1,2,3,4]
	]
}
```

Run it in WQ mode:

```
makeflow --jx test.jx -T wq -d all
```

Now run a worker with four cores and four GPUs:
```
work_queue_worker -d all --cores 4 --gpus 4
```

When the worker sends the task over, it specifis the desired cores, but maxes out the memory, disk, and gpus to fill the rest of the machine:
```
2021/02/01 11:26:53.63 work_queue_worker[30775] wq: rx from manager: cores 1
2021/02/01 11:26:53.63 work_queue_worker[30775] wq: rx from manager: memory 15743
2021/02/01 11:26:53.63 work_queue_worker[30775] wq: rx from manager: disk 63806
2021/02/01 11:26:53.63 work_queue_worker[30775] wq: rx from manager: gpus 4
```

I don't think this is the desired behavior.

@btovar can you clarify (a) what's currently going on, and (b) propose what to do about it.

**Comment by dthain** [comment]
Note this behavior is relative to #2517

**Comment by btovar** [comment]
This is the desired behavior, as it is a feature, not a bug. Maxing out is the only way we can keep our promises to tasks, as tasks will use some resource even if they do not state it (e.g., at least it will use some core/gpu, or some memory, or some disk.). Without maxing out, it becomes harder to put the blame on resource exhaustion.

**Comment by dthain** [comment]
@btovar please look at the problem of gpus:1 going to gpus:4.
Then we can discuss the bigger problem of increasing allocations as needed.

**Comment by dthain** [comment]
Now thinking about the overall allocation policy.

I think there are two cases where the outcome is clear:
A - User specifies no resources: the task should consume the whole worker.
B - User specifies all resources: give them what they ask for.

Now, the third case is where it's tricky:
C - User specifies some resources, like 2 cores and 1 GPU.  What do we do for the remaining resources?

0 - Let the resource be unmanaged.
1 - Substitute some reasonable minimum (1 core, 1GB, 1GB, 0 gpus)
2 - Give it a fraction of the resource.  (e.g. if you allocated 1 cpu out of 4, give it 1/4 RAM.)
3 - Give it the whole resource. (what we do now)
4 - Something else?

**Comment by btovar** [comment]
I think the difficult case come when tasks do not specify different types of resources:

a. If all tasks specify the same subset of the resources, then the unspecified resources may be left unmanaged. After all, the user has signaled which resources are important.
b. If different tasks left unspecified different resources, then in effect we should treat them as tasks in different classes. Workers may only execute one class of task at the same time. In this way, we do not have to worry how unmanaged resources may interfered with managed ones. 

The problem with b is that a class of tasks may starve.

I think giving reasonable defaults, or a faction of the resource, will lead to unexpected resource exhaustion.

**Comment by btovar** [comment]
> I think giving reasonable defaults, or a faction of the resource, will lead to unexpected resource exhaustion.

Talking to myself... Perhaps unexpected resource exhaustions are better than tasks failing because they step on each other without us knowing why. The more I think about it, I like some sort of fraction of a resource best. I think the fraction should be scaled to the resources that are specified, say:

largest_fraction = max  task[resource] / worker[resource]  where resource in resources s.t. worker[resource] >= task[resource] > 0.

If largest_fraction is undefined (e.g., no worker[resource] >= task[resource] > 0), then task uses the whole worker. It cannot run on the worker if another tasks is already running there. Otherwise:

Then resources not specified by the task are allocated:  worker[resource] * largest_fraction.

With this, if one task requests %50 of the memory of the worker, it will occupy %50 of all the other resources not specified.

**Comment by dthain** [comment]
A couple of thoughts while I mulled this overnight -

1 - The GPU resource is different from all of the others.  It's discrete like cores, but I think it's likely the users will be more knowledgeable about how they intend to use the GPUs.  More importantly, we have an assignment/enforcement mechanism (CUDA_VISIBLE_DEVICES) to make sure reality matches requests.  And finally, we do not have a *measurement* capability to tell when it's being used.  Therefore, I think we should set GPU allocations to be exactly equal to the request, and treat unset as zero.

2 - For the other resources, I am leaning towards the fractional method as well.  It seems easy to explain and likely to be the unstated intention of the user.

3 - We still want the clever dynamic method available.  Should we do that only if the user specifies no resources?  Or if they specify some but also enable the dynamic mode?

**Comment by dthain** [comment]
4 - I agree that tasks specifying orthogonal resources is where we can get into trouble.  However, I think that's less likely given that WQ addresses a single user at a time.  (I would be more concerned in the HTCondor case where you have intersecting users with very different behaviors.)
