### ISSUE TITLE
WQ: Proposal for default values for unspecified resources in tasks

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2526]
Continuation of #2518

WQ: Proposal for default values for unspecified resources in tasks

Currently if at least one of the values of a task for cores, memory, or disk is left unspecified (e.g., no specify_RESOURCE is used), then the task is allocated a whole worker where the specified resources fit. If no resource is specified, then the task is allocated any whole worker.

The motivation for this conservative approach is to guarantee allocations for resources that are specified. However, it quickly leads to wasted resources, as unspecified resources are not the resources the user cares about, and their allocation may not be the cause of a resource exhaustion.

In this proposal we aim to give better default values. The requirements are:

- Compatible with the current implementation when no resource is specified.
- Minimize unnecessary resource exhaustions (e.g, if a task asks for all the cores of a worker, and %95 of its memory, it should be given %100 of the memory and disk).
- Run more concurrent tasks in workers when specified resources allow it.
- Avoid pathological cases where infinite many tasks can run concurrently in only one worker.
- Incorporate gpus.

To show the basic idea, we first we explore a solution without gpus. Later we will incorporate gpus:

1. If a task does not specify any resource:
1.a If it is running for the first time, then it is allocated to any whole worker.
1.b If it is being retried for resource exhaustion, then it is allocated a whole worker larger than the last attempt, up to `specify_max_retries`. `work_queue_status -A` can be used to find tasks that don't fit currently available workers.

2. If the task specifies at least one resource, we first look at the resources available at a worker candidate to run a task:

```
unit_cores  = 1
unit_memory = worker_memory/worker_cores
unit_disk   = worker_disk/worker_cores
```

To avoid unnecessary resource exhaustion, unit_RESOURCE is the minimum multiple of a resource that can be allocated to a task for any unspecified resource.  Further, to avoid pathological cases, `specify_memory(0), and specify_disk(0)` are errors, and at most one of `specify_cores` and `specify_gpus` can be 0. 

Not specifying a resource should be read as __allocate the worker's minimum default__, and this has the consequence that no worker may run more tasks than its number of cores, as for now cores are an integral value. In the future, cores will be fractional.

Define:

```
int factor(task_RESOURCE, unit_RESOURCE) {
    if(task_RESOURCE < 0)
        return 0;
    if(task_RESOURCE == 0)
        return 1;  // i.e., equivalent  to task_RESOURCE = unit_RESOURCE
    return ceil(task_RESOURCE / unit_RESOURCE)
```

We find:

```
f = max factor(task_RESOURCE, unit_RESOURCE) for all specified RESOURCE in cores, memory, disk.
```

If `f > worker_cores`, then the task does not fit the worker. If `f == worker_cores`, then it gets assigned the whole worker. Otherwise, unspecified resources are allocated to the task as:

```
allocated_RESOURCE = unit_RESOURCE * f
```

3. Incorporating gpus:

We follow the previous point with the following changes:

- unit_gpus for a worker that does not declare gpus is 0, otherwise is 1.
- specify_gpus(0) really means 0 gpus, not unit_gpus as for the other resources.
- if specify_gpus > 0 and specify_cores == 0 or unspecified, then allocated cores is 0.
- unit_RESOURCE is computed as:

```
unit_RESOURCE = worker_RESOURCE / worker_pu

where worker_pu = MAX(worker_cores, worker_gpus)
```

Any decision point that uses worker_cores in 2, should be replaced with worker_pu.

**Comment by dthain** [comment]
I was going to ask how this interacts with the different resource allocation strategies, but then I noticed that they aren't linked to the WQ API:
http://ccl.cse.nd.edu/software/manuals/api/html/work__queue_8h.html

Are those present in rmonitor.h instead?  (And should they be present in the WQ API?)

**Comment by btovar** [comment]
They are available here:
http://ccl.cse.nd.edu/software/manuals/api/html/classwork__queue_1_1WorkQueue.html#a7e3b0fd01d2c1e5c70e54dbe2b993b86

Is that what you a re thinking about?

**Comment by dthain** [comment]
Aha, I see it there now.  But I will "call" your Python API and raise you a C API.  :)
http://ccl.cse.nd.edu/software/manuals/api/html/work__queue_8h.html#af0a676aedd5d831dd7011475f2aa4154

I think the issue here is that the `WORK_QUEUE_` symbols are defined in `category.h` and so don't show up in the general WQ API docs.

How about this:  Let `category.h` contain the natural definition of all symbols starting with `CATEGORY`, and then put this in `work_queue.h`:

```
#define WORK_QUEUE_ALLOCATION_MODE_FIXED    CATEGORY_ALLOCATION_MODE_FIXED   /**< WQ documentation here*/
...
```

Then the `category` module is nice and clean, and the WQ documentation will be self contained.  Would that work?

**Comment by btovar** [comment]
Yes, that's a good idea.  I think our motivation back then was to have these two together so we did forget to update one when modifying the other. But these modes have not changed over all these time.

**Comment by dthain** [comment]
Ok, so now back to the main point:

How does the above interact with the category settings of FIXED, MAX_THROUGHPUT, etc?

**Comment by btovar** [comment]
No change. For fixed, max throughput, etc. it remains the same as we have it now.  Resource exhaustion with any allocation means retry with larger if in a mode that allows retries.

For fixed, if you get a resource exhaustion, then it fails at the first try. This makes sense to me as if it fail because of a default allocation, then the assumption that the resource was not important is incorrect, and thus an error.

**Comment by dthain** [comment]
So the annotations provided by the user always provide the first allocation, and then the algorithm chooses all later tries?

If that's the case (and it makes sense) then we need to update the Coffea-WQ documentation:
https://coffeateam.github.io/coffea/wq.html

**Comment by btovar** [comment]
It depends.

Using specify_RESOURCE directly to the task turns off any automatic allocation for that resource for that task. We use the value provided, and if it is exhausted, we fail.

If the values come from  `work_queue_specify_max_resources`, then they resource values are used as maximum possible for that category. If not given, then we take the value of the maximum worker seen (per resource).

The only way a user can directly set the value for the first allocation is: `work_queue_specify_category_first_allocation_guess`. This value is only used before we get any data for tasks done. If the guess is too small, then tasks are retried in whole workers. If too big, then it gets refined as tasks finish.

There is also `work_queue_specify_category_min_resources` which limits the allocations computed from below (e.g., never allocate less than 100MB memory, etc.)

**Comment by btovar** [comment]
Also, when using FIXED mode, `work_queue_specify_category_max_resources` works as `specify_RESOURCE` for all the resources explicitly mentioned.

**Comment by dthain** [comment]
1 - Please start a PR that has the documentation first, from the perspective of "we recommend you do this"
2 - Then, adjust the code to correspond.

This can come after the GPU minor release.

**Comment by btovar** [comment]
pr in #2545
