### ISSUE TITLE
Infra: Add SHADHO Packaging Test

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2544]
Once you have WQ+SHADHO fixed up, please add a working recipe to the cctools-packaging-test repository.

It should be very short: just conda install from scratch, and then run a trivial SHADHO app.

This gets run nightly, and verifies that everything is working correctly from the current versions of things deployed in Conda.

**Comment by dthain** [comment]
https://github.com/cooperative-computing-lab/cctools-packaging-test

**Comment by dthain** [comment]
@tphung3 what's the status on this one?  I recall that you had Shadho running, and then what happened?

**Comment by tphung3** [comment]
Ah I created an issue instead of a PR to Jeff. Let me fix that later.

**Comment by tphung3** [comment]
So the reason I made an issue instead of a PR is because the code to be fixed is not in the repo but in conda setup of shadho. I just contacted Jeff about it.

**Comment by dthain** [comment]
Status?

**Comment by tphung3** [comment]
[PR made.](https://github.com/cooperative-computing-lab/cctools-packaging-test/pull/3) Not done however.
