### ISSUE TITLE
Worker: Fix CORS Data Access

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2558]
The worker needs to emit an additional HTTP header line, so as to allow JSON data to be incorporated into external sites, displays, and so forth.  Add it here:
https://github.com/cooperative-computing-lab/cctools/blob/master/work_queue/src/work_queue.c#L2649

Access-Control-Allow-Origin: *

**Comment by jmrundle** [comment]
https://github.com/cooperative-computing-lab/cctools/pull/2559
