### ISSUE TITLE
Doc: Python Packaging

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2603]
We have a nice set of tools for managing python environments (`python_package_analyze/create/cache/run`) but they are not documented anywhere, so no-one can find them!  Create a new section in the cctools manual that describes the python packaging tools, so that others can make use of it.

**Comment by dthain** [comment]
@BarrySlyDelgado I think this would be a gooe one for your to work on, just for the purpose of becoming closely familiar with the tools, so you can integrate them into `PyTask` appropriately.  Have a look at `doc/manuals` in the repository.

**Comment by BarrySlyDelgado** [comment]
[https://github.com/cooperative-computing-lab/cctools/blob/master/python_environments/src/README.md](url) There seems to be some documentation here should it just be moved to `doc/manuals`

**Comment by dthain** [comment]
Aha, I didn't see that.  Yes, you can move that over and clean it up.  I'm sure that some things have changed since it was written, so take some time to make it up-to-date.

**Comment by dthain** [comment]
This will get rolled into #2607
