### ISSUE TITLE
WQ PONCHO Packaging Tools

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2607]
Per our discussion Wednesday, I would to evolve `python_package_{analyze|create|cache}` into a set of tools called PONCHO (Python On Networked Computing something something) that cleanly manage environments for execution functions, and can be easily plugged into the PyTask #2600 facility that @BarrySlyDelgado is building out.

The easy part is renaming these to be `poncho_package_{analyze|create|cache|run`

The trickier part is to define the specification language for the environments, so that it cleanly encapsulates the python interpreter, conda packages, pip packages, live pip packages, git repos, incidental files, etc...  @trshaffer began to document an approach here:
[](https://gist.github.com/trshaffer/17471f62261dda8a46fb41f924036fb9)

**Comment by BarrySlyDelgado** [comment]
I believe you meant to link this. [https://gist.github.com/trshaffer/17471f62261dda8a46fb41f924036fb9](url)

**Comment by dthain** [comment]
https://gist.github.com/trshaffer/17471f62261dda8a46fb41f924036fb9
