### ISSUE TITLE
WQ: Evaluate Modifying Order of Main Loop

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2608]
In the current implementation, the inner work queue wait loop has the following behavior:

1. if timeout, return null
2. if there is a retrieved task, return it to the user for postprocessing.
3. if there is a task to be retrieved, retrieve it and go to 1.
4. if there is a task that can be dispatched to workers, dispatch it and go to 1.
5. if there are workers to be connected, connect them.
6. go to 1.

This achieves low latency, as tasks are returned as soon as they finish. This works fine under the assumption that the rate at which tasks are executed, dispatched, and retrieved is slower than the user postprocessing. With this, tasks can be dispatched to newly freed workers. However, if the postprocessing step is slow, workers go unusued, because tasks keep finishing during the postprocessing step, and are immediately returned to the user  when `work_queue_wait` is called. 

If we want execution of the tasks to overlap as much as possible with their postprocessing, we could modify the loop as follows:

1. if timeout,or there are no tasks to be retrieved or dispatched, then return a retrieved task if there is one, or null otherwise.
2. if there is a task to be retrieved, retrieve it.
3. if there is a task to be dispatched, dispatch it, and go to 1.
4. if there are workers to be connected, connect them.
5. go to 1.

This loop will increase the utilization of the workers, as it dispatches tasks as soon as it is able. It has high latency, as tasks are returned until the queue has nothing to do, or a timeout is reached. It does not respect the capacity of the manager, as more workers may be fed tasks compared to the number of workers the manager can actually handle. (One modification is to change step 3 to only dispatch tasks if that would not exceed the computed capacity of the manager).

**Comment by dthain** [comment]
This will be a good next step for @David-Simonetti-ND to work on, once the worker summarization is done.

**Comment by dthain** [comment]
@David-Simonetti-ND as we discussed yesterday, the way to proceed here is to first set up an example that demonstrates the problem that @btovar is describing.  You could do this by writing a little test application that submits some tasks and then "postprocesses" by sleeping.  (Or, you could set up the full Coffea application that shows the problem.)

Then, once you have the problem observed, you can play around with the WQ main loop to see how things can be improved.

**Comment by dthain** [comment]
@David-Simonetti-ND I recall seeing results from this in a weekly meeting, but where is the code?  Did you make a PR?

**Comment by dthain** [comment]
#2726
