### ISSUE TITLE
WQ: Add TLS Support to Manager-Worker Connection

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2635]
Add (optional) support for TLS security in WQ.  This requires several levels of changes:
- Update `configure` and friends to identify libgnutls.
- Update conda and spack build recipes to require libgnutls.
- Modify `link.c` to perform TLS send/recv in place of plain read/write.
- Modify the top level tools to accept options for enabling TLS and loading identity types.

**Comment by bbockelm** [comment]
Dumb question:  why `libgnutls` instead of OpenSSL?  As a consumer, I'm a bit ambivalent between the two -- but as someone who might be able to help debug in the future, I know my way around the OpenSSL code base quite well!

**Comment by btovar** [comment]
We already link to openssl, so my guess is that `libgnutls` above is a typo that means "the chosen tls library". :)

**Comment by dthain** [comment]
No strong opinion about the SSL library.

@bbockelm To be consistent with how you are using Coffea+Dask in coffea-casa, can you tell us a little more about your authentication setup?  e.g. are you using a PSK between manager and workers, or something else?

**Comment by bbockelm** [comment]
Dask does a pretty traditional mTLS setup.  On first login, we generate a CA cert, user cert, and host cert and configure Dask to find the three credentials as needed (client gets user cert, scheduler + worker gets host cert).

**Comment by bbockelm** [comment]
@btovar -- Excited to hear about the TLS support?  In the current implementation, are you using SNI to indicate the desired hostname to the server?

This is the key trick we use in Coffea-Casa to run 100 users behind the same IP address.

**Comment by btovar** [comment]
@bbockelm We are! The workers use the `SSL_set_tlsext_host_name(ssl, hostname)`, so that information should be available before any handshake happens.
