### ISSUE TITLE
wq+coffea: python_package_run transient failures when expanding the environment

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2639]
Once in a while, `python_package_run` does not expand the environment correctly. This occurs both when then environment is shared across tasks in a worker, and when a single task runs in a worker.  The errors reported vary, but mostly point to something not generated correctly. E.g.:

```
FileNotFoundError: [Errno 2] No such file or directory: '/var/condor/execute/dir_10971/worker-230547-10976/full_env_d7122b27_HEAD.tar.gz-env/share/man/man3/ffi_prep_cif.3'
python_package_run: could not relocate environment: full_env_d7122b27_HEAD.tar.gz
2021-07-30T08:27:24.870342299 python_package_run: could not untar environment: full_env_d7122b27_HEAD.tar.gz
```

or sometimes `bin/activate` cannot be run because is not there,  or the `python` executable is not found in PATH and the incorrect python executable is used (which causes a failure because no modules can be found.)

These errors occur one every a handful of thousand tasks. This has been observed by @kmohrman and myself.

**Comment by dthain** [comment]
I believe we have decided this is just another symptom of #2738, correct?

**Comment by btovar** [comment]
Correct.
