### ISSUE TITLE
Vine+Catalog: Report Additional Values

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2642]
Add a few items to the JSON record send from the manager to the catalog, which will assist with better identification of purposes and counts of applications:

- `uuid` - A unique identifier generated each time a WQ manager process starts.  This will allow us to count multiple starts of an application with the same project name.
- `framework` - A string representing the framework sitting on top of WQ, such as `parsl`, `coffea`, and so forth.  This will require an addition to the WQ API, and also some changes to the coffea and parsl executors to use them appropriately.

**Comment by dthain** [comment]
For a variety of reasons, we need to capture telemetry on uses of Parsl, Dask, TopEFT etc with TaskVine.  #3623 adds the method `m.set_property` which the manager then reports to the catalog server.  Once that PR is made part of a release, then we need to update our various frameworks to use the option:
- [ ] @colinthomas-z80 update the Parsl-Vine executor to do `m.set_property("framework","parsl")
- [ ] @BarrySlyDelgado update the Dask-Vine executor to do `m.set_property("framework","dask")
- [ ] @btovar please invite our friends in CMS to turn on catalog reports and set `m.set_property("framework","topcoffea")` or what have you.

**Comment by BarrySlyDelgado** [comment]
#3625 adds property for DaskVine

**Comment by colinthomas-z80** [comment]
Parsl PR merged

**Comment by dthain** [comment]
TopEFT will already set framework to `dask` so I think we are ok there.
Added corresponding hook to makeflow-taskvine.
