### ISSUE TITLE
JX: Invoke Functions as Methods

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2643]
JX has a bunch of nice functions that make is possible to build up queries on remote/distributed data.
However, being plain functions, they result in rather complex nested expressions that are difficult to read/explain:

```
project(disk_avail,select(type=="chirp,fetch(url)))
```

Introduce a new syntax for invoking functions in a method-like style, like this:
```
fetch(url).select(type=="chirp").project(disk_avail)
```

I think this can be done by overloading the dot operator to represent a method call, if it is followed by NAME(args,...).  The semantics of this can be to call the existing function, except using the left side of the operator as the first argument of the function.  The result is that this:

```
X.F(Y)
```

is equivalent to this:

```
F(X,Y)
```

(This may require re-arranging the order of arguments in existing functions, breaking backwards compatibility.  I'm ok with that, since these functions are relatively new anyway.)

**Comment by dthain** [comment]
@jmrundle this would be a good second one to work on.  For an example of a query to clean up, check out page 120 in Nate's recent dissertation:
http://ccl.cse.nd.edu/research/papers/nkremerh-dissertation.pdf

**Comment by dthain** [comment]
@jmrundle you gave us a nice demo of this the other day, ready to make a PR?

**Comment by dthain** [comment]
@jmrundle the running catalog server now has this feature deployed; please make a quick update to the work queue status page to use `like` correctly...
/afs/crc.nd.edu/group/ccl/web/ccl/software/workqueue/status.v4

**Comment by jmrundle** [comment]
Done.  Here's an example:
http://ccl.cse.nd.edu/software/workqueue/status.v4/?owner=^e.+$

**Comment by dthain** [comment]
Looks great, you can update the `status` symlink to v4 and call it done.
