### ISSUE TITLE
Replace python_environments with poncho

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2650]
Note that python_package_run and poncho_package_run may be slightly out of sync.

**Comment by dthain** [comment]
Perhaps I was too soon to merge.  What's changed between the two?

**Comment by btovar** [comment]
At least https://github.com/cooperative-computing-lab/cctools/pull/2644
But it is nothing fundamental, only messages to help me better debug the expansion issue.

**Comment by dthain** [comment]
@btovar is there anywhere else where `poncho` needs to replace `python_package_run`?

**Comment by btovar** [comment]
We need to check that poncho_create_package and analyze work with "source" in parsl. 

Other than that, we need to create a symlink python_package_run to poncho_package_run so that previous versions of coffea work correctly.
