### ISSUE TITLE
PONCHO: Poncho_package_analyze freezing without second argument

### ISSUE THREAD

**Issue by David-Simonetti-ND** [cooperative-computing-lab/cctools#2662]
When running poncho_package_analyze without a second argument (not specifying an output .json file), the program never finishes executing

**Comment by David-Simonetti-ND** [comment]
poncho_package_analyze also seems to delete the contents of the input file if a second argument is not provided and the user control+C's to kill the program.
ex. running "poncho_package_analyze a.py" will erase the contents of a.py once quitting out of the infinite loop.

**Comment by dthain** [comment]
@BarrySlyDelgado if this one is fixed, please link to the PR and close.

**Comment by BarrySlyDelgado** [comment]
This was fixed #2664
