### ISSUE TITLE
Installation question for Windows

### ISSUE THREAD

**Issue by bdw2292** [cooperative-computing-lab/cctools#2665]
Hello,

I can install for linux and I see there is way to install for Mac OS, is windows supported? The conda command only works on my linux machine not from conda within windows however.

Thanks for your time

**Comment by btovar** [comment]
Brandon, we are sorry, but we only provide support for linux and OSX.  Some people have had some luck compiling from source using cygwin in Windows, but it is not something we have a lot of experience, or officially support.
