### ISSUE TITLE
Setting gpus=0 not working?

### ISSUE THREAD

**Issue by bdw2292** [cooperative-computing-lab/cctools#2669]
Hello, quick question. I tagged my gpu jobs with needing 1 gpu, but on the nodes that I dont want gpu jobs on (cause old GPU card), I told work_queue_worker --gpus 0 (see below), but it seems to still send gpu jobs to that node. I am wondering if I have missed something in the correct procedure. I still want to use this node for cpu jobs.

2021-09-02 11:21:54,642 INFO Calling: ssh node59 "source /home/bdw2292/.allpurpose.bashrc ;work_queue_worker nova 9123 -d all -o worker.debug --cores 12 --memory 185600 --gpus 0 -t 100000000 -M RenLabCluster --parent-death"

2021/09/02 11:47:58.18 work_queue_python[16671] wq: tx to node59.bme.utexas.edu (10.0.0.59:37736): task 35
2021/09/02 11:47:58.18 work_queue_python[16671] wq: tx to node59.bme.utexas.edu (10.0.0.59:37736): cmd 365
2021/09/02 11:47:58.18 work_queue_python[16671] wq: ./cctools-monitor --no-pprint --with-output-files=cctools-monitor -L 'memory: 185600' -L 'disk: 33869' -L 'gpus: 1' -L 'cores: 1.000' -V 'task_id: 35' -V 'category: default' --measure-only --sh "dynamic_gpu p-cresol_Simulation_solvwaterboxequil.xyz -k p-cresol_Simulation_solvfinal_config.key 500000 2 100 4 300 1 N > p-cresol_Simulation_SolvSim_300_500000_NPT.out"
2021/09/02 11:47:58.18 work_queue_python[16671] wq: tx to node59.bme.utexas.edu (10.0.0.59:37736): category default
2021/09/02 11:47:58.18 work_queue_python[16671] wq: tx to node59.bme.utexas.edu (10.0.0.59:37736): cores 1.000
2021/09/02 11:47:58.18 work_queue_python[16671] wq: tx to node59.bme.utexas.edu (10.0.0.59:37736): gpus 1
2021/09/02 11:47:58.18 work_queue_python[16671] wq: tx to node59.bme.utexas.edu (10.0.0.59:37736): memory 185600
2021/09/02 11:47:58.18 work_queue_python[16671] wq: tx to node59.bme.utexas.edu (10.0.0.59:37736): disk 33869
2021/09/02 11:47:58.18 work_queue_python[16671] wq: tx to node59.bme.utexas.edu (10.0.0.59:37736): infile file-138-3bac61933472c8329c221ce67682d031-p-cresol_Simulation_solvwaterboxequil.xyz p-cresol_Simulation_solvwaterboxequil.xyz 0
2021/09/02 11:47:58.18 work_queue_python[16671] wq: tx to node59.bme.utexas.edu (10.0.0.59:37736): infile file-139-3b649e6212fc1dc48a52446cb6329e0d-p-cresol_Simulation_solvfinal_config.key p-cresol_Simulation_solvfinal_config.key 0
2021/09/02 11:47:58.18 work_queue_python[16671] wq: tx to node59.bme.utexas.edu (10.0.0.59:37736): infile file-140-39ee9ff69f81a234eb43d5bb42e63da3-amoebabio18.prm amoebabio18.prm 0

**Comment by bdw2292** [comment]
On a side note, I just realized -M should be ---M according to the docs. I am not sure how this would affect reading inputs.

**Comment by btovar** [comment]
It should be `-M`, so that's a bug in the docs.

Let me check why the worker is getting a task it shouldn't...

**Comment by bdw2292** [comment]
Great thanks!!

**Comment by bdw2292** [comment]
https://cctools.readthedocs.io/en/latest/man_pages/work_queue_worker/

this is the page that says ---M

**Comment by btovar** [comment]
Thanks for the documentation bug report!

In your worker's log, can you tell me the lines that look like:

```
2021/09/02 13:16:40.86 work_queue_worker[25717] wq:  workers      0 inuse      1 total      1 smallest      1 largest
2021/09/02 13:16:40.86 work_queue_worker[25717] wq:     disk      0 inuse  40723 total  40723 smallest  40723 largest
2021/09/02 13:16:40.86 work_queue_worker[25717] wq:   memory      0 inuse   7764 total   7764 smallest   7764 largest
2021/09/02 13:16:40.86 work_queue_worker[25717] wq:     gpus      0 inuse      0 total      0 smallest      0 largest
2021/09/02 13:16:40.86 work_queue_worker[25717] wq:    cores      0 inuse      4 total      4 smallest      4 largest
```

In my test, the worker correctly reports 0 gpus, and the manager does not send any tasks.

**Comment by bdw2292** [comment]
Ah crap sorry I just deleted, I will reproduce the error then find.

**Comment by bdw2292** [comment]
2021/09/02 11:54:48.19 work_queue_worker[3722033] wq:  workers      0 inuse      1 total      1 smallest      1 largest
2021/09/02 11:54:48.19 work_queue_worker[3722033] wq:     disk      0 inuse  38423 total  38423 smallest  38423 largest
2021/09/02 11:54:48.19 work_queue_worker[3722033] wq:   memory      0 inuse  22400 total  22400 smallest  22400 largest
2021/09/02 11:54:48.19 work_queue_worker[3722033] wq:     gpus      0 inuse      1 total      1 smallest      1 largest
2021/09/02 11:54:48.19 work_queue_worker[3722033] wq:    cores      0 inuse     12 total     12 smallest     12 largest

actually I see it says 0 gpus in use interesting

**Comment by btovar** [comment]
Well, it says 0 in use, but 1 total. Could you paste the command line you are using for the worker?

**Comment by bdw2292** [comment]
It definitly would not be using the gpu since, for this particular card I have not set up the envioronment correctly (so the dynamic_gpu job will immediteately crash due to incorrect libs). However it still appears to send to the node with gpus =0

**Comment by bdw2292** [comment]
ssh node59 "source /home/bdw2292/.allpurpose.bashrc ;work_queue_worker nova 9123 -d all -o worker.debug --cores 12 --memory 185600 --gpus 0 -t 100000000 ---M RenLabCluster --parent-death"

**Comment by bdw2292** [comment]
Another thing I just realize is we have shared file system, so I can imagine worker.debug is overwritten  by many worker.debug files , I think I can add this to the /tmp folder on each node.

**Comment by bdw2292** [comment]
For now, I will just not use work_queue_worker on nodes with old gpu card

**Comment by btovar** [comment]
Are you running several workers at the same time?  One way we could test if we are looking at the correct logfile is if you manually ssh the command to some node like:

ssh node59 "source /home/bdw2292/.allpurpose.bashrc ;work_queue_worker nova 9123 -d all -o worker.debug.ZERO --cores 12 --memory 185600 --gpus 0 -t 100000000 ---M RenLabCluster --parent-death"

Then we can see if tasks in the log worker.debug.ZERO look like using any gpus.

Another way we can observe any error is this:

```
work_queue_status HOST_IP_OF_YOUR_MANAGER  PORT_OF_YOUR_MGR   -W
```

E.g.:

```
work_queue_status bme-******.edu 9123 -W
```

The last two columns will tell you the workers that report 0 gpus, and whether they claim to be using gpus.

**Comment by bdw2292** [comment]
Oh cool, I didnt know about -W option for work_queue_status. Ummm, if you want I can try another indepdent test. This time I will just isolate that one old gpu node with a work_queue_worker and only submit one job to queue for that node only. Do you need anymore information or would you want log files from that sort of test?

**Comment by bdw2292** [comment]
I think you can have two seperate managers at same time (different projectnames) and they will not interefere if I recall the docs right

**Comment by btovar** [comment]
The log worker.debug.ZERO would be very helpful, thanks!

**Comment by bdw2292** [comment]
To answer your earlier, question, no I am not running multiple at same time. I typically have to kill the python manager script (which for some reason the workers dont die after that with the --parent-death, maybe cause the queue is seperate process underneath), then I ssh to all nodes kill all processes before restarting manager (which ssh to each node and call work_queue_worker)

**Comment by btovar** [comment]
For the workers, I think you want  --single-shot instead of --parent-death.   --parent-death  means the parent process of the worker (e.g., the teminal shell) rather than the manager.

**Comment by bdw2292** [comment]
Ah okay thanks! that will be very useful

**Comment by bdw2292** [comment]
Curiously, it seems to work as expected when I test on single node case and say gpus=0

**Comment by bdw2292** [comment]
In other words just waits in queue forever. I will have to do some more testing later when I have more time, thanks :)

**Comment by btovar** [comment]
Actually, if you are using nvidia gpus I found a case where --gpus=0  launches the automatic discovery of gpus. It could be that the discovery failed for the node that you were trying in isolation.

Anyway, I'll should have a fix soon. It may be that it fixes your observations.

**Comment by bdw2292** [comment]
Interesting, thanks so much!

**Comment by btovar** [comment]
The issue I saw should be closed with #2672.  It is included in the most recent stable release 7.3.2.

**Comment by bdw2292** [comment]
Great! can I grab with conda, or is this only on github?

**Comment by btovar** [comment]
It is submitted to conda, but there is some delay until it becomes publicly available. I should be available soon with:

```
conda update -c conda-forge ndcctools
```

Thanks for your report. Please so not hesitate to contact us if you have any other issues, or questions!

**Comment by bdw2292** [comment]
Okay no worries, I can install from source :) . Is there a way to track
conda updates, then I could compare with github commits?

**Comment by btovar** [comment]
The tag `stable` always corresponds to the latest version submitted to conda.  The commits tagged with `stable` usually look like "Bump to X.Y.Z FINAL", where X.Y.Z is the version shown also in conda.  You can then check the history of the commits before the tag `stable` to see what changes have been included.

I add a summary of the changes to the release page in github here:
 https://github.com/cooperative-computing-lab/cctools/releases

**Comment by bdw2292** [comment]
Great thanks!
