### ISSUE TITLE
Move the script cctools_gpu_autodetect to gpu_info.c

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2671]
The script is simple and does not need its own file. Further, we wouldn't have to worry to send it together with the worker.

**Comment by dthain** [comment]
@Cpreciad another good starter one.  This one is simple but surprisingly important: just invoke `nvidia-smi` directly instead of through `cctools_gpu_autodetect`

**Comment by dthain** [comment]
Just looked at gpu_info and observed that gpu_name_get() does approximately the right thing, but gpu_info_get is far too complex.
