### ISSUE TITLE
WQ+Python: Higher Level Abstractions

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2685]
Add several higher level abstractions to the Work Queue Python interface, something like the follows:

```
wq.map( f, a ) -> [ f(a[0]), f(a[1]), ... ]
wq.allpairs( f, a, b ) -> [ f( a[0], b[0] ), f( a[0], b[1] ), . . . ]
wq.treereduce( f, a ) -> f( f( a[0], a[1] ), f( a[2], a[3] ) ) 
```

These should work by generating functions in the `PythonTask` interface, and then submitting and waiting as needed.
For the first implementation, each element of the array should be a single task, which should be pretty straightforward.
Make that a PR with a nice writeup in the manual.

The second iteration will be more tricky.  Consider the case where each element of the array is very fast to compute.  It won't make sense to have the overhead of a separate function for each element.  Instead, multiple elements will have to be grouped within a task in order to get an acceptable runtime.  Let's talk about that more once version #1 is in place.

**Comment by dthain** [comment]
@bwiseman77 you gave us a nice demo of this the other today.  Ready to make a PR?

**Comment by bwiseman77** [comment]
@dthain I still just have to do treereduce. After I do that though, How would you like me to make a PR/write-up?

**Comment by dthain** [comment]
Commit your changes to a branch, push to your private repository, and then make a pull request.  Then, I'm sure we will have some comments and suggestions when the code is visible..

**Comment by dthain** [comment]
PR #2744

**Comment by dthain** [comment]
PR #2774

**Comment by dthain** [comment]
Next step on this one:

Measure the performance of an AllPairs execution on a relatively simple function for a large matrix that takes, say, one minute to run on ten workers.  Then, very the chunksize from too-small to too-large, so you can see a dramatic change in the performance at either end.

Once you have that, let's talk, and evaluate how to select the chunksize more dynamically.
