### ISSUE TITLE
poncho_package_run should fail when UNPACK_TO directory cannot be created

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2689]
Currently the call to mkdir $UNPACK_TO fails silently and the script keeps going.  The script should fail with an appropriate errmsg if the mkdir fails.

This bug can be reproduced with:
```
mkdir -m500 /tmp/read_only
poncho_package_run -u /tmp/read_only/myenv  -e myenv.tar.gz -- /bin/ls
```

**Comment by dthain** [comment]
@BarrySlyDelgado ping?

**Comment by BarrySlyDelgado** [comment]
With #3629 Poncho now fails if mkdir fails to create the `unpack-to` director and produces error message.
