### ISSUE TITLE
wq: delayed-wait tune parameter

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2691]
Add the tune parameter "delayed-wait" to `work_queue_tune` and `struct work_queue` `delayed_wait`, which is a boolean (int).

If 0 (the default), then work queue works as it currently does. As soon as a task changes state to `WORK_QUEUE_TASK_DONE`, we break out of the wait loop.

If not 0, then we do not break out of the loop, but do so only if the result of `send_one_task` and `receive_one_task` are both zero.  This allows to send and received as much as tasks as possible given the timeout allowed while respecting the manager capacity. (I suggest adding an `int task_event = 0` to the inner `while`, and do a `task_event |= result` after each *_one_task call.)

We have to be careful not to change more than one task to `WORK_QUEUE_TASK_DONE` per wait call. Thus, the call to `t = task_state_any(q, WORK_QUEUE_TASK_RETRIEVED)` should not be done if `t` is already not NULL.

**Comment by dthain** [comment]
#2746
