### ISSUE TITLE
JX: Add internal marker for JX functions with side effects

### ISSUE THREAD

**Issue by trshaffer** [cooperative-computing-lab/cctools#2706]
Most JX functions are pure, i.e. their operation depends solely on their input arguments. (One of our string formatting functions does implicitly capture locals, need to be careful if there's ever a memoization feature.) Some functions, however, can interact with the outside world to e.g. fetch a URL or list a directory. These are useful in certain cases, but present a problem if we want to handle untrusted expressions as in the catalog server. At the moment we simply forbid functions and only allow pure expressions in these situations, but we might want to allow a safe subset.

To this end, it would be helpful if there were an internal marker on functions indicating which are pure vs. impure. We could then add certain functions to the domain of pure expressions. This marker feature should be extensible, as we might add more markers in the future (e.g. a marker for "reductive" functions that operate such that their output size is always less than or equal to their input size might be helpful to screen out expressions that can cause memory blowups). Having a table or similar structure tracking function properties would allow for more precise restrictions on evaluation. Just adding a side effect marker would be sufficient to start, though.

**Comment by dthain** [comment]
@jmrundle this would be a good smaller task to work on while you are ruminating on DeltaDB.
