### ISSUE TITLE
wq: Public addresses are not reported to the catalog when using NAT

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2713]
As reported by  Sean Davey.

In particular, an amazon vm instance gets two ips. One private associated with an interface in the instance, and one public that gets resolved to the private using NAT. The issue is that the public ip is not paired with an interface in the instance, and therefore is never reported to the catalog.  (A wq manager reports all its interfaces and addresses to the catalog.)

Current state:
- When a worker asks the catalog about the information of a manager, it looks at the `network_interfaces` attribute for a list of interfaces and ip addresses to try to connect to the manager.  This list is constructed by the manager itself.
- When the manager sends its information to the catalog, the catalog updates the `address` attribute to the ip the data seems to be coming from.
- The `address` attribute is used to keep track of the manager's record in the catalog, but it is not used when telling workers where to connect.
- When using NAT, the manager may not know that the catalog sees it public address as `address`.

**Comment by btovar** [comment]
A possible solution is that when the catalog updates the `address` attribute, it should also add it as an 'interface' to the `network_interfaces` list if none of the interfaces already have that address value. This allows us to simply update the catalog without forcing users to update their cctools version.

**Comment by dthain** [comment]
(Because the attempt to connect to the manager via an unreachable IP address could fail quickly, or it could fail very slowly.)
