### ISSUE TITLE
Workers default to 0 second timeout

### ISSUE THREAD

**Issue by tphung3** [cooperative-computing-lab/cctools#2714]
Below is the log file for a worker

```
2021/10/08 11:57:02.47 work_queue_worker[17517] debug: ./work_queue_worker version 8.0.0 DEVELOPMENT (released 2021-05-20 16:10:55 -0400)
2021/10/08 11:57:02.48 work_queue_worker[17517] debug: Built by tphung@cclws17 on 2021-05-20 16:10:55 -0400
2021/10/08 11:57:02.48 work_queue_worker[17517] debug: System: Linux cclws17 3.10.0-1127.8.2.el7.x86_64 #1 SMP Thu May 7 19:30:37 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
2021/10/08 11:57:02.48 work_queue_worker[17517] debug: Configuration: --with-perl-path no --without-system-parrot
2021/10/08 11:57:02.48 work_queue_worker[17517] wq: WORK_QUEUE_SANDBOX set to /var/condor/execute/dir_17134/worker-239906-17517.
2021/10/08 11:57:02.48 work_queue_worker[17517] debug: error reading disk usage on directory: ./cache.
2021/10/08 11:57:02.48 work_queue_worker[17517] dns: looking up name condorfe.crc.nd.edu
2021/10/08 11:57:02.49 work_queue_worker[17517] dns: condorfe.crc.nd.edu is 10.32.85.31
2021/10/08 11:57:02.49 work_queue_worker[17517] tcp: connecting to 10.32.85.31 port 9076
2021/10/08 11:57:02.49 work_queue_worker[17517] tcp: connection to 10.32.85.31 port 9076 failed (Connection timed out)
2021/10/08 11:57:02.49 work_queue_worker[17517] tcp: disconnected from 10.32.85.31 port 9076
2021/10/08 11:57:04.49 work_queue_worker[17517] tcp: connecting to 10.32.85.31 port 9076
2021/10/08 11:57:04.49 work_queue_worker[17517] tcp: connection to 10.32.85.31 port 9076 failed (Connection timed out)
2021/10/08 11:57:04.49 work_queue_worker[17517] tcp: disconnected from 10.32.85.31 port 9076
2021/10/08 11:57:04.49 work_queue_worker[17517] notice: stopping: could not connect after 0 seconds.
```
Reason is unclear, but it seems that if we put a hostname and port or the project name as an option for the factory, the timeout of a work queue worker managed by that factory is set to 0.

**Comment by dthain** [comment]
@tphung3 can you confirm whether this is a problem or not?

**Comment by tphung3** [comment]
It is, the problem is reproducible in the Colmena-XTB workflow by the following steps:

- run a program that creates the wq manager by `make xtb`. I ran the manager on `condorfe.crc.nd.edu`
- on another terminal, spawn workers with wq factory like this: 
`work_queue_factory -T condor -M colmena-xtb --condor-requirements='(has_scratch365)' -w 30 --workers-per-cycle=20 --python-package="env.tar.gz" -tasks-per-worker=1 --cores=16 --memory=32000`. The wq factory is also run on `condorfe.crc.nd.edu`
- find the wq workspace in /tmp and check the file `worker.log`. It should have a peculiar line about timeout after 0 seconds like this (last line):
`2021/11/11 23:25:06.16 work_queue_worker[7046] notice: stopping: could not connect after 0 seconds.`

A copy of  `worker.log` is in my work directory under the name `timeout-bug-worker.log`.

Note that this bug can be sidestepped by explicitly setting the timeout to be some value, like this: `work_queue_factory ... -t 300`, so something is overriding the default timeout of worker connection.

**Comment by tphung3** [comment]
Turning on debug mode in wq factory shows that the factory is indeed sending workers with timeout `-t 0`:
`2021/11/11 23:36:33.53 work_queue_factory[20122] batch: cleared option 'workers-blocked'
2021/11/11 23:36:33.53 work_queue_factory[20122] wq: submitting 20 new workers to reach target
2021/11/11 23:36:33.53 work_queue_factory[20122] wq: submitting worker: ./poncho_package_run -e env.tar.gz  ./work_queue_worker -M colmena-xtb -t 0 -C 'catalog.cse.nd.edu,backup-catalog.cse.nd.edu' -d all -o worker.log   --cores=$$([TARGET.Cpus]) --memory=$$([TARGET.Memory]) --disk=$$([TARGET.Disk/1024])`

**Comment by dthain** [comment]
Ok, you almost have it surrounded.  Try running it through the debugger to see where the variable worker_timeout gets changed.

Or consider using valgrind on work_queue_factory to see if it is due to some illegal memory access or similar.

**Comment by tphung3** [comment]
It's an error on the arguments for `work_queue_factory`. It should be `--tasks-per-worker=1` instead of `-tasks-per-worker=1`. In the latter the factory consumes `-t` from `-tasks-per-worker` which results in timeout of 0 seconds. In short, the factory is working as intended, no further actions are required.

**Comment by btovar** [comment]
Nice catch!
