### ISSUE TITLE
coffea: wq executor hits AFS limit of files per directory

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2736]
Currently the filenames the wq executor uses per task are all written to the same directory. Further, the names are longer than 16 characters long, which means we can only write about 32000 files to an AFS directory. Since each task needs at least three files, and we keep all the files during retries and accumulations, Kelci has found the error "File too large", but only when using AFS.  Using the executor "filepath":"/tmp" prevents this error.

To fix this, we need to separate files into subdirectories, either. I was thinking of taking the first characters of the hash of the itemid, and then make sure that the filenames are less than 16 characters long.

Adding this issue here rather than coffea because it has to do with the wq executor in the ND environment.

**Comment by dthain** [comment]
A couple of considerations -
- Do we need to keep all these files for the lifetime of the run?  e.g. would it make sense to delete successful output as we go?
- Can the executor easily detect when the directory is full, so at least to offer a more specific error message?
-

**Comment by btovar** [comment]
We do delete outputs as we go for successful tasks. The issue here seems to be that a retry keeps a reference to the original task (this to ease debugging). So, if xrootd is acting up and all tasks are going into the fifth retry, the number of files quickly adds up. The files themselves are less than 1k, so it is just the number of them. Deleting the original tasks does help, but we may hit the limit anyway when we figure out how to have O(1000) concurrency.

The issue with the detection is that sometimes the error occurs in work queue when it tries to transfer a file back. At that point it just looks as if the output file is missing.

**Comment by dthain** [comment]
Closing unfixed due to change in coffea architecture, can be avoided without using AFS.
