### ISSUE TITLE
wq: worker workspace fails to complete cleanup

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2738]
This issue occurs rarely, and only has been observed with coffea when tasks share a python environment. When a worker disconnects from the manager, the workspace created is removed. However, if any executable file in the workspace is still in use (e.g., by a process that went out of the worker's control), the removal silently fails. If the worker is reused, then there is a chance that newer task will find the partially removed files and fail.

In normal operation is hard to observe this because: 1) the cleanup rarely fails, 2) if it fails, an error can only occur if a task with the same task id is submitted to the worker, and the task takes into account the current state of its workspace when it starts execution.

For coffea, point (2) becomes much more likely, as the shared python environment does not depend on the task id, and tasks try to reuse a python environment already present.  A band-aid was added to coffea so that the name of the python environments is a function of the manager instance currently being served.

To ensure the cleanup and isolation of tasks across managers, we should create workspaces which names depend on the manager instance being served. Further, before removal, the workspace should be moved to a trash directory were it will be out of the way in case the removal fails.

**Comment by dthain** [comment]
Let me make a slightly more narrow suggestion:
- The workspace should have a "trash" directory in addition to tasks and cache.
- Replace instances of "delete_dir" with move-to-trash and then delete everything in the trash.
- Make sure that delete_dir actually checks for errors in remove and propagates them up.

**Comment by dthain** [comment]
I'll take this one and do some hacking...

**Comment by dthain** [comment]
#2740
