### ISSUE TITLE
makeflow: add wq openssl support 

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2747]
pr  #2733 adds openssl support to wq.  We need to add --ssl_key and --ssl_cert options to makeflow to create wq queues with SSL support.

**Comment by btovar** [comment]
It is a little bit more complicated than I expected.  The issue is that `q=batch_queue_create(type)` only takes one argument (the type of batch), but we need to pass the key and cert when the queue is created. I'm thinking on how to this cleanly with minimal changes.

**Comment by dthain** [comment]
Perhaps we need a pattern along these lines?
```
q = work_queue_create( ... )
b = batch_queue_create_wq( q )
```

**Comment by btovar** [comment]
Yes, perhaps something like that. I wanted to avoid the separation as I did not want to have wq as a special case in the wq factory and makeflow, but maybe that is the cleanest way.
