### ISSUE TITLE
wq: low disk space keeps manager running forever

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2783]
Before the manager transfers back an output file from a worker, it first checks that there is enough local disk space. If there is not, the transfer fails, the task fails, and it is reported as a worker error, which means that the worker is disconnected. If using the work queue factory, then this means that workers are replenished, and tasks are retried, but no progress is ever made. If not using the factory, all workers are eventually disconnected, and again no progress is made.

Some alternatives:
- Report the error as an APP_ERROR. The manager then terminates and the workflow fails.
- Reset the transfer attempt, so that results are kept in the worker. Print a warning that disk space is needed. Periodically retry the transfer again.

**Comment by dthain** [comment]
Or an even simpler placeholder:
- Emit a big warning message stating (disk is full) -- and block in that state until the user fixes it...

**Comment by btovar** [comment]
One of the issues about blocking the state is that it is not clear when to unblock. Should we unblock as soon as there is space for the transfer that just failed?

On top of that, like for AFS, the filesystem does seem to have space, but if fails until the close, so it is not exactly clear how much free space is really needed. Because of these, I'm partial to simply fail with an APP_FAILURE.

**Comment by dthain** [comment]
Right: `df /afs` (statfs) doesn't produce useful information about space.  `fs quota` does though...

**Comment by btovar** [comment]
That's was also a confusing aspect. For the topEFT workflow  fs quota gave a 98% utilization, with about 5GB free. Files we were trying to transfer were as small as 40MB, but they all failed. They were definitely some larger than that, but it seemed that those last GB were not available to us. 

But say that `fs quota` does give a number we can use. Do you propose to call `fs quota` if we detect we are running on afs? Maybe we can just call it when we detect that the `close` call fail.

**Comment by btovar** [comment]
Studying the code more closely, the error reported is APP_FAILURE, but the task simply fails with OUTPUT_MISSING. As discussed in our meeting, I'll add a MANAGER_FAILURE that will terminate the workflow immediately. We may want to think of a more refined error handling in the future.

**Comment by dthain** [comment]
I think this issue has been addressed as far is it can be, yes?

**Comment by btovar** [comment]
Correct.
