### ISSUE TITLE
WQ: PythonTask Compatibility Regression

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2792]
(moving discussion over from closed PR)

@RyanGutenkunst reports:

The behavior of PythonTask has changed recently (breaking our code), and my guess is that [this commit](https://github.com/cooperative-computing-lab/cctools/pull/2776#issuecomment-1018921846) did it.

As a quick example, the manager.py code here: https://cctools.readthedocs.io/en/latest/work_queue/ now fails with a
```
TypeError: Traceback (most recent call last):
File "/Users/rgutenk/Desktop/temp.py", line 18, in
task = wq.PythonTask(my_sum, value, value)
File "/Users/rgutenk/cctools/lib/python3.9/site-packages/work_queue.py", line 1838, in init
self._serialize_python_function(func, *args)
File "/Users/rgutenk/cctools/lib/python3.9/site-packages/work_queue.py", line 1901, in _serialize_python_function
dill.dump(list(*args), wf, recurse=True)
TypeError: list expected at most 1 argument, got 2
```
Was this change in behavior intendend?

**Comment by dthain** [comment]
Yikes, this is a big problem, but I'm not encountering it.
Can you share your installation setup (e.g. sequence of Conda commands) so we can  see how you got there?

**Comment by dthain** [comment]
@btovar Can you please look at this on Monday morning?
@David-Simonetti-ND this is a perfect example of why we want to "test the documentation".\

**Comment by btovar** [comment]
@RyanGutenkunst, could you give the current master branch a try to see if it works for you?

**Comment by RyanGutenkunst** [comment]
@btovar This seems to have fixed our issue. Thank you for the quick fix!
