### ISSUE TITLE
update conda instructions to use strict channel

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2795]
As observed in the packaging tests, the dependencies are resolved much faster. This will be the default in the upcoming major version of conda.

- [x] ccl web for developers
- [x] topeft
- [ ] coffea
- [x] packaging test
- [x] cctools readthedocs
- [ ] [parsl](https://parsl.readthedocs.io/en/stable/userguide/configuring.html?highlight=work%20queue#ccl-notre-dame-with-work-queue)

**Comment by dthain** [comment]
Also:
[ ] [Parsl-WQ installation instructions](https://parsl.readthedocs.io/en/stable/userguide/configuring.html?highlight=work%20queue#ccl-notre-dame-with-work-queue)

**Comment by btovar** [comment]
In parsl there is not an issue, because the first thing they recommend is to modify the user's configuration with:

```sh
conda config --add channels conda-forge
```

after which they create a new environment. Since the python they install comes from conda-forge, the dependencies are resolved quicker, as if using `--strict-channel-priority`. 

I suppose this is something we could copy, but this changes the python's a user gets from defaults to conda-forge. I'm not sure if this is that big of a deal, though. Our recommended:

```sh
conda create -n cctools-env -y -c conda-forge --strict-channel-priority python ndcctools
```

has the advantage of being self-contained.

**Comment by dthain** [comment]
No need to rework their instructions, as long as we are fitting inside them nicely.
