### ISSUE TITLE
WQ: Prototype Serverless

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2801]
@nicklocascio here is a summary of what we discussed today on how to prototype a serverless feature in WQ:

- [X] Measure the latency of executing a full PythonTask in WQ.  (you already did this)
- [x] Measure the latency of doing a bare executable (e.g. /usr/bin/true) in WQ.
- [x] Take a look at the code for the worker in work_queue_worker.c (main program) and work_queue_process.c (part that actually invokes a task)  Where an executable would normally be fork/exec'd, check for an executable name of `@FUNCTION`.  If that matches, then instead invoke a simple C function that emits some JSON instead.
- [x] Measure the latency (and throughput) of invoking that built-in function instead.

That last one will give us some lower bound on remove function invocation, and then we can talk about how to generalize it to invoking other kinds of (user installable) functions.

**Comment by nicklocascio** [comment]
PR #2824 has the progress so far for the serverless prototype

**Comment by nicklocascio** [comment]
Here are the results for the tasks listed in this issue:

<img width="726" alt="Screen Shot 2022-02-18 at 3 18 05 PM" src="https://user-images.githubusercontent.com/21242960/154755442-780804f0-f744-4c11-b0ac-82d8429ab2d0.png">

**Comment by David-Simonetti-ND** [comment]
This issue will be the central hub for the improvements to the serverless feature. The bite sized list of tasks to be completed are below. The tasks are listed roughly in the order in which they should be completed.
- [] Get Brett's final PR Remote Python Function #2831 finalized and merged
- [] Measure the latency of executing a c function, running a basic PythonTask, and a basic serverless task to get a rough idea of the overhead for each.
- [] Create a benchmark to compare the performance difference between PythonTask vs serverless
    - [] Multiple different synthetic workloads should be compared, testing the performance of the two options in various scenarios. Some examples could be lots of small tasks, few large tasks, varying the amount of workers, etc.
    - [] A real world workload could be found and a benchmark could be created from it
    - [] Daily/Weekly running of the benchmark and graph the performance of the two over time.
- [] Finalize PR #2854 and move coprocess to its own .h .c. Perform any 
- [] Add support for multiple functions executing at once (one manager having workers with different coprocesses)
- [] Add support for multiple coprocesses per worker 
- [] Create beautiful and engaging example program using serverless
- [] Create documentation for feature

**Comment by btovar** [comment]
@David-Simonetti-ND Right now I'm adding a wq protocol message so that the worker knows whether the command should be executed in a coprocess. Should be done shortly, after that it is all yours...
