### ISSUE TITLE
WQ+Parsl+Colmena+xTB lost tasks' identities

### ISSUE THREAD

**Issue by tphung3** [cooperative-computing-lab/cctools#2813]
Issue: Tasks/Functions from xTB application lose their identities through many layers of function wrappers in Colmena and Parsl.
Details:
- For Colmena: Colmena creates a [ParslTaskServer](https://github.com/exalearn/colmena/blob/b3cd0d1bf9c6363999088860a9c735fd4d3f4c0b/colmena/task_server/parsl.py#L20) that handles task submissions and retrievals. This server [wraps functions](https://github.com/exalearn/colmena/blob/b3cd0d1bf9c6363999088860a9c735fd4d3f4c0b/colmena/task_server/parsl.py#L110) in the [run_and_record_timing](https://github.com/exalearn/colmena/blob/b3cd0d1bf9c6363999088860a9c735fd4d3f4c0b/colmena/task_server/base.py#L145) function, gives it one argument, and [wraps](https://github.com/exalearn/colmena/blob/b3cd0d1bf9c6363999088860a9c735fd4d3f4c0b/colmena/task_server/parsl.py#L112) run_and_record_timing with a [PythonApp](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/python.py#L35). PythonApp [wraps](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/python.py#L40) the given function with [its error handling function](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/errors.py#L153). However run_and_record_timing takes two arguments, so when the PythonApp object is evaluated, it [tries to return](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/errors.py#L159) the original functions but an exception is always raised due to the lack of arguments. A traceback looks like this: `run_and_record_timing() missing 1 required positional argument: 'result'`. The consequence is the [RemoteExceptionWrapper](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/errors.py#L161) object is sent to remote sites instead, causing no real work to be done.
- For Parsl: there are two issues. 
*First, when a [PythonApp](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/python.py#L35) is given a function/Callable, it [wraps](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/python.py#L40) the given function with [its error handling function](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/errors.py#L153), as mentioned above. The error handling function then tries to wrap the given function carefully with the [@wrap](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/errors.py#L154) decorator. However, if the given function doesn't have a `name` attribute (this can happen if users wrap their functions in the [partial](https://docs.python.org/3/library/functools.html#functools.partial) function from functools module), then the [returned function](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/errors.py#L162) will always have the name `wrapper`. This is because the @wrap decorator from the [functools](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/errors.py#L162) module tries to copy several attributes, `name` included, from the wrapped function to the wrapper function, but doesn't throw an error when the wrapped function doesn't have a `name` attribute, so the resulting function has the name of the wrapper function instead. Thus, any PythonApp that is given a nameless function will end up with the name 'wrapper', losing functions' names or identities. While it is at first sensible that if functions don't have names then they don't have identities, functions' names and identities are two different things and perhaps deserved different treatments.
*Second, A PythonApp when [called](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/python.py#L48) will [submit](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/app/python.py#L75) its function to the [DataFlowKernel](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/dataflow/dflow.py#L42). The DataFlowKernel then submits the function to an executor through several calls ([this](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/dataflow/dflow.py#L934), [this](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/dataflow/dflow.py#L513), and [this](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/dataflow/dflow.py#L604)), but during this process, the function in PythonApp is [wrapped](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/dataflow/dflow.py#L596) in a [monitoring function](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/monitoring/monitoring.py#L309). This function then returns the [wrapper](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/monitoring/monitoring.py#L320) with monitoring enabled, but the wrapper doesn't copy the original function's attributes like `name`. Thus any function submitted to any executor will have the name `wrapped` instead of its original name. This gets problematic when Parsl is used with WorkQueue, as the [WorkQueue executor](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/executors/workqueue/executor.py#L77) uses [functions' names as functions' categories](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/executors/workqueue/executor.py#L458). Thus functions' identities are lost.

**Comment by tphung3** [comment]
@WardLT @kylechard

**Comment by benclifford** [comment]
ignoring the first issue in favour of colmena people commenting on it first.

The two parsl issues:

1) I think the behaviour you are experiencing is constrained to using the python app decorator against nameless callables.

I'm not sure what you mean then by this:

> Thus, any PythonApp that is given a nameless function will end up with the name 'wrapper', losing functions' names

Are you expecting parsl to create some other name for this? or do you want the ability to specify a "name" that comes from a source that isn't the decorated un-named callable?
(in the second case, I have seen people do this before, by explicitly setting the name attribute of the appropriate object)

But it sounds like maybe you want this set explicitly for WQ task classification, in which case it might be better to modify the parsl work queue executor to have a `resource_specification` parameter that sets this explicitly rather than trying to trick parsl into finding the result.  This would be the same as how workqueue cores/memory/disk/priority/running_time_min are specified, with a `resource_specification` parameter added to the app invocation.

2) The second problem sounds like its a problem specifically with monitoring turned on - if so, then I think running with monitoring turned off would not show this problem. Can you confirm that?

If so, then probably the parsl monitoring wrapping method can be fixed to convey the original function name, like the python app and bash app decorators do. Does that align with your understanding?

**Comment by WardLT** [comment]
A note about the Colmena side: I've recently changed Colmena (commit on [Jan 4](https://github.com/exalearn/colmena/commit/9d3691059fbe4885bd25f0ffa7444d96153032f8)) to give different `__name__`s to different functions. Have you be able to test with this change? 

I'll push a version of Colmena to pypi with this change by later this week, and can do earlier if you need.

**Comment by tphung3** [comment]
@benclifford I agree that adding another field to the resource specs will work with minimum changes to other codes. Is there any other way to specify a task's type without using the resource specs dictionary, as a task's type is of its own and not a type of resource? For the second problem, it sounds like turning off monitoring will work. A @wrap decorator somewhere around [here](https://github.com/Parsl/parsl/blob/a1e4d6b0d680f6a0e9f5784b994f88941a92bdb6/parsl/monitoring/monitoring.py#L320) would probably work. I'll try it and update you later.

@WardLT Yes I have. The update_wrapper copies the `name` attribute to the wrapper function, so both the function and PythonApp have the correct name from the wrapped function. Can you take a look at the issue with the run_and_record_timing function as mentioned above? I'm not sure how I'd work around this yet.

**Comment by benclifford** [comment]
@tphung3 the WQ task type is definitely the sort of attribute that I think belongs in the resource specifications dictionary, I think. 

"resource" is a pretty loose term here, and includes things like "priority" which is similarly not a resource request in the sense of "I need this much RAM".

I agree that a wrap decorator in the right place is probably the right thing for monitoring - if you fix that rather than turning off monitoring, send in a PR.

**Comment by WardLT** [comment]
Could you post an example stack trace with the "run_and_record_timing() missing 1 required positional argument: 'result'"? I haven't seen that error before.

**Comment by tphung3** [comment]
@WardLT The problem is on my end. I evaluated the function and logged it to see what it was, causing the above issue. Without my debugging code, the wrapped function is never evaluated until it has enough arguments, so your code runs fine. My apologies. Thanks for the pointer to `update_wrapper`. I already put it in my colmena so you don't have to push a new version yet.

**Comment by WardLT** [comment]
Glad you got it figured out and working!

**Comment by benclifford** [comment]
I think there's still a problem in parsl monitoring passing the name through, right?

**Comment by tphung3** [comment]
The fix with wraps decorator is looking good now. I'm waiting for the experiment to complete to confirm.

**Comment by benclifford** [comment]
OK, cool, your PR is merged into parsl `master` branch now which I think resolves your 2nd parsl issue. Thanks for the PR!

**Comment by tphung3** [comment]
Conclusion: No problem with Colmena. 2nd problem of Parsl is resolved (check this [commit](https://github.com/Parsl/parsl/commit/ca1cfcb230d35925b86baf1201f67868249fcade)). 1st problem of Parsl is resolved in [this PR](https://github.com/Parsl/parsl/pull/2226).
