### ISSUE TITLE
WQ: work_queue_factory doesn't output debug info to file

### ISSUE THREAD

**Issue by tphung3** [cooperative-computing-lab/cctools#2816]
I ran work queue factory as follows:
`work_queue_factory -T condor -N colmena-xtb-v2 -w 20 -W 50 --workers-per-cycle 10 --tasks-per-worker=1 --cores 16 --memory=32000 --python-package env.tar.gz --debug-file=debug.log`
WQ factory ran as usual. It created `debug.log` but no information was written to that file, so `debug.log` was always empty. Running `work_queue_factory --help` returns the option with debugging: `-o,--debug-file=<file>         Send debugging to this file.`, so I'm not sure why nothing is written to the debug log.

**Comment by dthain** [comment]
Enable debugging output with `-d all`

**Comment by tphung3** [comment]
Issue resolved [here](https://github.com/cooperative-computing-lab/cctools/issues/2816#issuecomment-1034040283).

**Comment by btovar** [comment]
Perhaps  `--debug-file`  should imply `-dall` if no other `-d` is given?
At least a warning that a `-d` is needed would be helpful.
