### ISSUE TITLE
work_queue_factory does not properly wait for children to finish before it returns

### ISSUE THREAD

**Issue by David-Simonetti-ND** [cooperative-computing-lab/cctools#2819]
work_queue_factory does not properly wait for all children to return before itself quits. An example of the problem is given below
<img width="1434" alt="Screen Shot 2022-02-04 at 10 34 03 AM" src="https://user-images.githubusercontent.com/31227025/153625094-aa5d36c1-846a-4daa-83d2-8ada39c9e456.png">
In this picture, the process tree for before and after sending SIGTERM to the work_queue_factory process is pictured. As shown, the factory process and calling python process are able to successfully exit before both poncho_package_run and its child work_queue_worker are able to return.
The reason for this issue is illustrated below.
<img width="447" alt="Screen Shot 2022-02-11 at 9 59 43 AM" src="https://user-images.githubusercontent.com/31227025/153625504-19b85a4b-b299-4d8a-a7fb-60e054ba2793.png">
When cleaning up, work_queue_factory calls remove_all_workers
<img width="597" alt="Screen Shot 2022-02-11 at 9 59 23 AM" src="https://user-images.githubusercontent.com/31227025/153625599-c451249a-c8bd-4c07-91ed-b73be60473a7.png">
Which calls batch_job_remove
<img width="767" alt="Screen Shot 2022-02-11 at 9 59 16 AM" src="https://user-images.githubusercontent.com/31227025/153625637-13370e09-7922-458f-b208-3cdd51bda856.png">
Which calls (at least in the case shown above) batch_job_local_remove, and this function sends SIGTERM to the child process it wishes to wait for.
<img width="642" alt="Screen Shot 2022-02-11 at 9 59 06 AM" src="https://user-images.githubusercontent.com/31227025/153625718-ae7ceb7f-4e42-446c-9055-6ea41a8280e3.png">
Which calls process_waitpid()
<img width="464" alt="Screen Shot 2022-02-11 at 9 58 58 AM" src="https://user-images.githubusercontent.com/31227025/153625752-56e9e546-59c6-465d-8e4f-1af246f8dccc.png">
Which repeatedly calls process_work() to check for a change in the process state (looking for when the process changes from running to zombie presumably)
<img width="464" alt="Screen Shot 2022-02-11 at 9 58 58 AM" src="https://user-images.githubusercontent.com/31227025/153625972-a7a1d119-30c4-4649-9e4b-e6f78910261a.png">
The problem lies in process_work(). When it calls wait4 on the given pid, it passes in the WNOHANG flag, which causes wait4 to immediately return. If the process specified by pid has not changed state, wait4 will return 0 as the PID. 
<img width="665" alt="Screen Shot 2022-02-11 at 9 58 42 AM" src="https://user-images.githubusercontent.com/31227025/153626772-50b96526-6ebd-4026-ab26-ec21ad7446f7.png">
However, the error checking statement checks if the pid <= 0 for an error, which including the case where the process has not changed state and is still cleaning up as an error state.
Changing the error checking step to pid < 0 causes factory to continuously check until the poncho process cleans up and exits (pictured below)
<img width="1432" alt="Screen Shot 2022-02-11 at 9 58 10 AM" src="https://user-images.githubusercontent.com/31227025/153626831-c6ae71c0-5c77-483f-a107-90d52e38d2cd.png">

**Comment by dthain** [comment]
@David-Simonetti-ND great detective work, appreciate all of the detail.

While this fixes the immediate problem, I want to make sure that this doesn't break some other case where the `process` module is used.  The reasons for this module are described here:

https://github.com/cooperative-computing-lab/cctools/blob/master/dttools/src/process.h

Can you make a good argument that the proposed change does not break the semantics of the module?

**Comment by dthain** [comment]
@David-Simonetti-ND is there work to be done here?

**Comment by David-Simonetti-ND** [comment]
The problem was with batch_job_local_remove and should be fixed with #2822
