### ISSUE TITLE
poncho_package_run does not properly wait for all children to finish before exiting

### ISSUE THREAD

**Issue by David-Simonetti-ND** [cooperative-computing-lab/cctools#2823]
When poncho_package_run enters its cleanup function which it calls on EXIT, it does not terminate any of its children or wait for them to exit before returning.
<img width="852" alt="Screen Shot 2022-02-16 at 9 45 48 PM" src="https://user-images.githubusercontent.com/31227025/154409417-30adab85-cefa-447a-8b47-27641873a7bf.png">
The problem is pictured above. poncho_package_run receives a SIGTERM from the factory, it exits, the factory exits, and then the python program exits, while the worker process is still running and only exits when it checks for parent death.
<img width="948" alt="Screen Shot 2022-02-16 at 10 18 41 PM" src="https://user-images.githubusercontent.com/31227025/154409590-6c99a556-60d6-4af1-bb47-382d530df19d.png">
Above you can also see the worker process sending its exit message after the python program has returned and the bash process begins executing again.

**Comment by btovar** [comment]
@David-Simonetti-ND Is this helpful?

https://linuxconfig.org/how-to-propagate-a-signal-to-child-processes-from-a-bash-script

**Comment by David-Simonetti-ND** [comment]
@btovar it is helpful in the case where child processes are compliant and return but it doesn't address the problem of how to  SIGKILL a rebel child processes which doesn't return after a timeout is reached. 
If poncho_package_run is used to run work_queue_workers, we can count on good behavior from the children and assume they will eventually terminate when sent SIGTERM? And even in the worst case work_queue_factory will kill the poncho process after 2 minutes of waiting for a rebel child.

**Comment by dthain** [comment]
@BarrySlyDelgado please update this with status and recommendation.  Is it fixed?  Does it need to be fixed?
