### ISSUE TITLE
WQ worker hangs at/after dns: looking up name nid002025

### ISSUE THREAD

**Issue by benclifford** [cooperative-computing-lab/cctools#2843]
I've had several users encounter this a few times and I haven't figured out a solution and am a bit lost at how to debug further.

Sometimes we see WQ workers start up enough to make this much debug log, but then nothing more.

```
2022/04/11 21:54:30.42 work_queue_python[19355] tcp: listening on port 9000
2022/04/11 21:54:30.42 work_queue_python[19355] wq: Using default fast abort multiplier for 'default'.
2022/04/11 21:54:30.42 work_queue_python[19355] wq: workers connections -- known: 0, connecting: 0, available: 0.
2022/04/11 21:54:30.42 work_queue_python[19355] dns: looking up name nid002025
```

and then nothing else happens.

Here is stderr and stdout. (the time 21:59 is when we hit ctrl-c):

```
> cat parsl.localprovider.1649739422.1913671.sh.err
2022/04/11 21:59:49.15 work_queue_worker[21062] notice: stopping: abort signal received

> cat parsl.localprovider.1649739422.1913671.sh.out
Found cores : 128
Launching worker: 1
work_queue_worker: creating workspace /tmp/worker-70237-21062
work_queue_worker: using 128 cores, 220000 MB memory, 128625 MB disk, 0 gpus
connected to manager nid002025:9000 via local address 10.249.11.203:45874
disconnected from manager nid002025:9000
work_queue_worker: deleting workspace /tmp/worker-70237-21062
```

This does not always happen, but happens enough to be annoying. I am unsure what I can do on the WQ side to track down what is happening - can you advise?

**Comment by dthain** [comment]
Yes, those debug statements wrap gethostbyname() and similar calls.
So, I think the most likely explanation is some sort of hang in name lookups on the node.

**Comment by benclifford** [comment]
still investigating with the relevant site admins.
