### ISSUE TITLE
C API documentation out of date

### ISSUE THREAD

**Issue by tphung3** [cooperative-computing-lab/cctools#2851]
The C APIs are out of date (I think) on the [ccl webpage](http://ccl.cse.nd.edu/software/manuals/api/html/work__queue_8h.html#a6b194f7d62af5310e5abc02b1d88f007).

**Comment by btovar** [comment]
Could you be more specific so I can check?

**Comment by tphung3** [comment]
The `enum [work_queue_category_mode_t](http://ccl.cse.nd.edu/software/manuals/api/html/work__queue_8h.html#a6b194f7d62af5310e5abc02b1d88f007)` only has three types of allocation strategies, it should be 4 instead as max throughput is missing.

**Comment by btovar** [comment]
Got it. I think something went wrong with the formatting there.

**Comment by btovar** [comment]
Does it look good to you now?

**Comment by tphung3** [comment]
It's good for me.

**Comment by dthain** [comment]
Ben, is there an automated process by which the ccl website gets updated with the latest API?  Or is this a manual process?

**Comment by btovar** [comment]
It updates automatically when deploying the new binaries to ND and the downloads webpage. Just in this particular case I updated that page manually, as it is just a small change.

**Comment by dthain** [comment]
I'm thinking a little bit about upgrading our web infrastructure, and this requires carefully separating our dynamically-generated content from our static pages.

(One possibility is github pages for the static part, and readthedocs for the dynamic part.)

Do you know if we can host doxygen-generated pages as part of readthedocs, or does that require a different kind of service?
