### ISSUE TITLE
Add module dill into the conda dependency list

### ISSUE THREAD

**Issue by sghuang19** [cooperative-computing-lab/cctools#2861]
Python module `dill` used by `PythonTask` in `work_queue` cannot be resolved automatically by `conda`.

Steps to reproduce:
1. Go through the example of `work_queue` at https://cctools.readthedocs.io/en/stable/work_queue/#quick-start-in-python.
2. After installing `ndccltools` via `conda`, try running `python3 manager.py`, which would fail.
```shell
(cctools-dev) [ghuang3@cclws05 ghuang3]$ python3 manager.py 
listening on port 9123
submitting tasks...
Traceback (most recent call last):
  File "/afs/crc.nd.edu/group/ccl/work/ghuang3/manager.py", line 18, in <module>
    task = wq.PythonTask(my_sum, value, value)
  File "/afs/crc.nd.edu/user/g/ghuang3/anaconda3/envs/cctools-dev/lib/python3.10/site-packages/work_queue.py", line 1830, in __init__
    raise RuntimeError("PythonTask is not available. The dill module is missing.")
RuntimeError: PythonTask is not available. The dill module is missing.
```
3. Install `dill` via `conda`, then run `python3 manager.py` again.

In running `conda install -c conda-forge ndcctools`, `dill` is supposed to be also installed automatically.

**Comment by btovar** [comment]
Got it, thanks. dill is an optional module, but given that we use PythonTask in the quickstart example, I think it should be installed automatically along ndcctools. I'm updating the conda spec.

**Comment by btovar** [comment]
And of course... we should add that manager.py example to cctools-packages-test.

**Comment by btovar** [comment]
Done.
