### ISSUE TITLE
wq: add input and output file transfers to the transactions log

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2868]
We need to record to the transactions log when a file is transferred to and from a worker. The transactions should have the following format:

```
timestamp manager-pid TRANSFER INPUT taskid workerid  sizeinmb walltime filename
timestamp manager-pid TRANSFER OUTPUT taskid workerid  sizeinmb walltime filename
```

The function `write_transaction` already takes care of timestamp and manager-pid, so it should be called as:
```
write_transaction(q, "TRANSFER INPUT ...
```

In these records, taskid is the id of the task the needs the input (e.g. t->taskid), or that produced the output, and workerid (e.g. w->workerid) of the worker involved. After the workerid, include the size in MB, the number of seconds for the transfer, and the name fo the file.

**Comment by sghuang19** [comment]
#2879

**Comment by sghuang19** [comment]
- Log format synopsis at the top of log file should also be updated.
- Worker ID or Worker IP Address? the latter one seems more intuitive and handy for following data processing

**Comment by sghuang19** [comment]
```
timestamp manager-pid TRANSFER INPUT taskid worker_address sizeinmb walltime filename
timestamp manager-pid TRANSFER OUTPUT taskid worker_address sizeinmb walltime filename
```
