### ISSUE TITLE
topeft: plot the tasks' graph from the tasks_accum_log

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#2870]
Create a tool that generates a dot file that encodes the dependencies of a topeft workflow. Each vertex represents a task, and there should be a direct edge from task A to task B if task B accumulated the results of A (i.e., the id of B appears as the `accum_parent` of A).

For now, ignore the preprocessing tasks (see category column), and tasks that do not have `accumulated` as their status. 

Note that the final accumulating tasks has an empty `accum_parent`.

**Comment by andrewhennessee** [comment]
I've generated an initial TopEFT workflow visualization that links processing functions to accumulation functions:
[tasks.log.wf.pdf](https://github.com/cooperative-computing-lab/cctools/files/8808415/tasks.log.wf.pdf)

We'd like for the visualization to include nodes for the output file size of each function. The tasks log for TopEFT does not yet track the size of the output files, so I'd like to update the program that produces the log files to include this feature. Where is this file located, and how would I go about tracking that piece of information?
