### ISSUE TITLE
Build: Add viz tools to dependencies.

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2884]
Our various visualization tools assume the presence of gnuplot, convert, and perhaps some other tools in order to work correctly.  We used to assume these were universally available in /usr/bin, but that seems no longer to be the case.  @btovar please add these as proper dependencies in conda.

**Comment by btovar** [comment]
Since `ndcctools` may be included in the poncho packages, this increase in size will be noticeable at runtime (e.g. topEFT or coffea CI) with no upside, as those poncho packages don't use the graphing tools. I'd rather look for another solution.

**Comment by dthain** [comment]
Out of curiosity, what about (ndcctools+python+imagemagick)?

**Comment by btovar** [comment]
```
python + ndcctools + gnuplot + imagemagick -> 1185M
python + ndcctools + gnuplot               -> 1184M
python + ndcctools + imagemagick           -> 797M
```

**Comment by dthain** [comment]
Ok, some potential solutions:

1 - Add all of our viz dependencies to cctools.  As you note above, that's going to be expensive, for those who don't need them.

2 - Modify our scripts to check for the proper dependencies, and then emit a message to "conda install x" if they are missing.  That's not bad, but does make a bit of an inside-out maintenance problem, esp if the user installed by a path other than conda.

3 - Create a new conda package `cctools-viz` that consists of cctools + gnuplot + imagemagick etc and add that to the documentation.

4 - Modify our viz tools to use something already built-in, like matplotlib.

**Comment by btovar** [comment]
- Option 1 is too expensive, and creates hassles to other tools that have a wq dependency (parsl, coffea).
- Option 2 may be ok. We don't need to tailor the instructions for every case. Just print the conda message if we see $CONDA_PREFIX.
- Option 3 will get confusing after a while. Also I'm afraid users may cctools-viz for every case just to be sure.
- Option 4 I like the best. 

I propose to do Option 2 while little by little we update the tools with Option 4.

**Comment by dthain** [comment]
Quick check on impact of adding matplotlib to dependencies?

**Comment by btovar** [comment]
Oh dear, never mind. 1247MB. 

What about option 2b:
- We print a warning when we can't find gnuplot, or convert.
- We add `conda install gnuplot etc.` to the official instructions.

**Comment by dthain** [comment]
Ok, I think this is the best approach all around.

**Comment by btovar** [comment]
Closed as won't implement.
