### ISSUE TITLE
wq: Documentation for transaction log visualizer

### ISSUE THREAD

**Issue by sghuang19** [cooperative-computing-lab/cctools#2898]
We could add a brief usage explanation of the visualizer under this section:

https://github.com/cooperative-computing-lab/cctools/blob/master/doc/manuals/work_queue/index.md#transactions-log

Besides, `work_queue_gantt` is not quite self-explanatory considering we are not only generating "Gantt Chart"? Maybe we should use another file name.

@btovar

**Comment by btovar** [comment]
@sghuang19 I agree on the name. `work_queue_graph_workers_lifetime`, `work_queue_graph_workers`?

**Comment by sghuang19** [comment]
I suggest `work_queue_graph_lifetime`, as the script plots the life time of the tasks and workers, and it conforms with the existing `work_queue_graph_log`.

> @sghuang19 I agree on the name. `work_queue_graph_workers_lifetime`, `work_queue_graph_workers`?

**Comment by sghuang19** [comment]
Docs could be in

https://github.com/cooperative-computing-lab/cctools/tree/master/doc/man/m4

and

https://github.com/cooperative-computing-lab/cctools/tree/master/doc/man/md

And add a section in

https://github.com/cooperative-computing-lab/cctools/blob/master/doc/manuals/work_queue/index.md#transactions-log

to briefly address the existence of the visualization tool.

**Comment by btovar** [comment]
`work_queue_graph_workers_usage`?  Lifetime may not work, as the graph does not really show the complete lifetime of the managers, the workers, or all the tasks states.

**Comment by btovar** [comment]
re: docs. You don't need to modify the .md file. It gets generated from the .m4 file.

**Comment by sghuang19** [comment]
> `work_queue_graph_workers_usage`? Lifetime may not work, as the graph does not really show the complete lifetime of the managers, the workers, or all the tasks states.

Maybe simply `work_queue_graph_workers`?

**Comment by btovar** [comment]
Sounds good.
