### ISSUE TITLE
work_queue coprocess concurrency

### ISSUE THREAD

**Issue by David-Simonetti-ND** [cooperative-computing-lab/cctools#2899]
Currently, there is a one to one correspondence of workers to coprocesses (every worker spawns only one coprocess which remains for the life of the worker). Each coprocess is only able to run one task at a time, so an individual worker running a coprocess, no matter how many resources it has, is only able to work on one coprocess task at a given time. This presents a problem as a coprocess running on a worker with 4 cores is effectively wasting 3 of the cores. Ideally, a worker would create as many coprocesses as it can support/as is defined in command line arguments, so a multicore worker can accept multiple coprocess tasks and run them all at the same time. 
A worker can receive tasks for as long as it has the resources to support them, so it should receive coprocess tasks until the number of tasks it has is equal to the number of coprocesses running on each worker. 
The user should be able to specify the number of coprocesses that are able to run on a given worker as well as the resources each coprocess is allowed to consume. It is my intuition that the number of coprocesses should correspond to the number of cpu cores on the worker, with the rest of the resources divided by total number of cores of the worker (ex. if there are four coprocesses, each receives 1/4 of the disk)
Diagram of what the result should look like below
![Coprocess diagram (1)](https://user-images.githubusercontent.com/31227025/174841927-0f4e217b-c8c8-454c-a3b0-060fc6cc3f7f.png)

**Comment by David-Simonetti-ND** [comment]
To-do list
- [ ] Add an option to work_queue_worker allowing the specification of how many coprocesses to start
- [ ] Add resource specification to each coprocess (ex. one coprocess will get 2 cores, 2gb ram, etc)
     - [ ]  Add default option that will split the resources of the worker evenly between cores
- [ ] Allow the worker to report back to the manager how many coprocesses it is running so it can receive that many coprocess tasks

**Comment by dthain** [comment]
This is a good description of the problem, thank you.
But let's work out some more details to be sure.

Under this scheme, do tasks require a resource specification?  And do they report resource usage when returned?

**Comment by David-Simonetti-ND** [comment]
Diagram laying out the structure of how coprocess will execute
<img width="774" alt="image" src="https://user-images.githubusercontent.com/31227025/176456975-a8787aec-4ff5-4e92-8142-04017c0fd6aa.png">
Terminology/components:
The components that will be used to execute a RemoteTask are the coprocess controller, coprocess invoker, and function. The combination of invoker and function will be referred to as a coprocess instance.

**Comment by David-Simonetti-ND** [comment]
Coprocess instance (invoker/function)
This can behave almost identically to how the current network function works for executing RemoteTasks, except instead of receiving tasks directly from the worker, it will be receiving tasks from the coprocess invoker. Communication between the controller and invoker can be done via tcp as it is currently for the network function, but this can be replaced by pipes since all of the coprocess invokers will be child processes of the invoker.

**Comment by David-Simonetti-ND** [comment]
Resource usage:
There are two separate specifications for resource usage-task level and worker level.
Worker level resource usage will be defined as such 
`work_queue_worker –cores A –memory B –disk C –gpus D –coprocess_cores E –coprocess_memory F –coprocess_disk G –copcrocess_gpus H`
The worker's resources will be partitioned such that the coprocess has the amount of resources guaranteed as specified on the command line and the rest of the resources are reserved for regular tasks to execute.
There will also be an option 
`–number_of_coprocesses X`
which will specify how many coprocess instances the controller will start. Each instance is not committed a specific number of resources (ex. instance A could use 3/4 of the resources and instance B could use 1/4 of the resources).
There is also a task level specification for resources.

**Comment by David-Simonetti-ND** [comment]
Some other considerations:
The worker will need a way to report the split of its resources between coprocess and regular task to the manager. In addition, when the manager is dispatching coprocess tasks, it must check that the worker has enough coprocess resources left to send out the task.
Right now the resource monitors are monitoring the coprocess instances purely by PID but it might work out so that the coprocess instances can be ran through the resource monitor.

**Comment by David-Simonetti-ND** [comment]
Per discussion on 7/1, the coprocess controller will be a module of work_queue_worker
Things to be done
- [ ] Enable the worker to start N number of coprocess, where N is passed at the command line, and keep track of the state of each coprocess
- [ ] Enable the worker to start multiple RemoteTasks at once instead of blocking for each one to complete
- [ ] Enable the worker to send a message to the manager communicating how much of its resources are committed to coprocesses
- [ ] Have the worker monitor each coprocess instance for it failing and to restart the coprocess instance in that case
- [ ] Have the worker monitor each coprocess instance for its resource usage and enforce task resource limits and have the worker enforce maximum resource limits

**Comment by dthain** [comment]
We have converged on a coprocess resource allocation model elsewhere.
