### ISSUE TITLE
work_queue coprocess resource management

### ISSUE THREAD

**Issue by David-Simonetti-ND** [cooperative-computing-lab/cctools#2901]
Any coprocess running on a worker will consume resources, so the resources it consumes should be monitored and reported. If a coprocess is only allocated so many resources and it exceeds that limit, the offending coprocess should be terminated and the job should retry/fail. The complication occurs in that the coprocess incurs an amount of resources when it is ran, and the function call incurs another amount of resources when it is executed. 
There are a few things to note. Once an instance of a coprocess is instantiated and it has completed it set up, the coprocess should not grow to use many more resources since the only job of the coprocess is to communicate between worker and function invocation. While a coprocess is initializing however, the resources it uses can increase substantially (ex. a large library like tensorflow is imported and a big dataset is downloaded from the internet). Should these resources only be considered consumed by the coprocess or somehow added to the resources used by the task (since the libraries and datasets are ultimately only used by tasks)
The amount of resources an individual RemoteTask may consume can vary wildly, so the only concerns here are to measure the resources consumed by the task. This can be summed with the resources consumed by the coprocess and if it exceeds the resources allocated then the task can be killed.
The resources used by the coprocess can be measured by having the worker use the resource monitor to run the coprocess. The resources used by individual tasks can be measured in a similar way by running the task through the resource monitor.

**Comment by David-Simonetti-ND** [comment]
- [ ] Allow command line arguments to specify the resource usage limits for a coprocess (or how to divide up the resources on a worker)
- [ ] Have each coprocess running on one worker be ran through the resource monitor
    - [ ] Gather the resource usage data and kill the offending coprocess(s) if they exceed the limits
- [ ] Run each task through the resource monitor to measure the resource usage of tasks
- [ ] Report the resource usages of the coprocess and tasks

**Comment by dthain** [comment]
We have settled on a minimal model for WQ coprocessor, and moved on to TV libraries, where the resource management of a library is the same model as for a regular task.
