### ISSUE TITLE
Copyright not updated for year 2022

### ISSUE THREAD

**Issue by sghuang19** [cooperative-computing-lab/cctools#2904]
The documentation generated through m4 processor still has a copyright info of "2005 - 2021".

<img width="814" alt="image" src="https://user-images.githubusercontent.com/58419736/175963693-7aa8236b-7794-4ac7-b088-ee6e389a7617.png">

**Comment by sghuang19** [comment]
This could be easily solved by modifying `manual.h`, should I do that? @btovar

**Comment by btovar** [comment]
Yes, please do!
