### ISSUE TITLE
Doc: WQ Manager Compiler Instructions

### ISSUE THREAD

**Issue by sghuang19** [cooperative-computing-lab/cctools#2929]
https://cctools.readthedocs.io/en/stable/work_queue/

This piece of command in the documentation of work queue does not compile the example manager correctly, as it assumes the installation prefix to be home directory and does not include ssl.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/58419736/180501893-6a7fca04-abca-46e5-bc72-d30c1b36a454.png">

Replace it with:

```sh
${CC} work_queue_example.c -o work_queue_example  -I${CONDA_PREFIX}/include/cctools -L${CONDA_PREFIX}/lib  -lwork_queue -ldttools -lssl -lcrypto -lm -lz
```

**Comment by btovar** [comment]
We should add a note that the -I and -L arguments depend on the installation.  If installing from conda, the command in the issue description will work. However, it won't work if using the default --prefix in ./configure, and if ${CC} is not set.

**Comment by dthain** [comment]
Same problem in the TaskVine section.
