### ISSUE TITLE
WQ: Memory leak in queue_to_jx()

### ISSUE THREAD

**Issue by sghuang19** [cooperative-computing-lab/cctools#2930]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/58419736/181014251-8220f138-30eb-4f69-bef6-2131a1840790.png">

https://github.com/cooperative-computing-lab/cctools/blob/cb86e81350cb28ca3bb24740acd8b21fb6abb59b/work_queue/src/work_queue.c#L2626

`total` is not deleted.

**Comment by btovar** [comment]
Taking this one over to speed a release.
