### ISSUE TITLE
Vine: Pick New Project Name

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2962]
Thinking about a new software name for the evolution of Work Queue.
We had previously chosen DataSwarm as the replacement name, and used that in an NSF proposal.
But now that name is taken by some system at Facebook.
So we need some new ideas.

A good name should be:
- Descriptive of the actual system.
- Unique and not easily confused with something related.
- Easy to say and remember.

In retrospect, Makeflow is an excellent name, and Work Queue is a mediocre one

**Comment by dthain** [comment]
Some names from prior discussion with Ben:

- DataSwamp?
- dataspout, datatorrent, datacluster, all taken already.
- Even DataNozzle: https://irp-cdn.multiscreensite.com/d6d035b2/files/uploaded/Fuelling%20Tech%20DATANOZZLE%20Product%20Sheet%20Mar20_v3.pdf
- DataShower
- DataFlower

- datachatter
- datachirp
- datawhisk
- datawisp (taken)
- dataswirl?
- datamasher

- datadart
- datadash
- datasprint (taken)
- dataspring (taken)
- datashower
- datadrizzle
- databurst
- dataclique
- datasquad
- datasquid

-datacliq
- dataclik
- dataclique

- dataquill is an IP litigation firm.  Let's stay away from that one.  :slightly_smiling_face:
- dataclock
- datacastr
- dataclicker
- datacliqr
- dataclickr

I'm trying to get at something here about how the tasks and data "click" together seamlessly.
- datapiler
- datatrawler
- dataheap
- datasifter
- datamatcher
- datadepot
- datasquirrel (taken (edited) 
- datachipmunk
- datachip (taken)
- datamunk
- dataclack?
- dataclank

**Comment by dthain** [comment]
Ben: I like dataclack!

- dataclaq
- dataclak

I'm liking it too, but there are a number of things with a short hamming distance:
- [datacloak.com](http://datacloak.com/)
- [dataclick.co.za](http://dataclick.co.za/)
- dataquack?
- dataquake is taken

**Comment by dthain** [comment]
- dataclack (no hits)
- dataclak (no hits, but google thinks its like datacloak)
- datacliq (no direct hits, but several names containing cliq)
- dataclique is taken

**Comment by BarrySlyDelgado** [comment]
- datacamp
- datafusion
- datafuse
- datacollider
- datacolision
- datsandwich
- datasoup
- closecompute
- datatouie
- DataStorm

**Comment by David-Simonetti-ND** [comment]
datacyclone
datahurricane
datatwister
datatsunami
datamonsoon
datatyphon
databarrage
datablast
datatempest
datarush

**Comment by painswor28** [comment]
DataMingle
DataGate
DataWirl
DataYard
DataJunction
DataStation
DataShed
DataBlend

**Comment by colinthomas-z80** [comment]
DataFlash
TeleData
DataTrain
DataFreight
DataShip
DataVoyage
DataSpark
DataArc
DataMouse
DataCat

**Comment by btovar** [comment]
datattle

**Comment by dthain** [comment]
Thinking about the system as a way of pulling data out of the FS and distributing it around the cluster:
- dataflood
- dataflooder
- datasponge
- datachamois ("datashammy")

**Comment by BarrySlyDelgado** [comment]
DataJet
DataFlash
DataFuse
DataStar
DataNova
DataQuark
DataSwirl
DataSeed
DataStem
DataTide
DataKnight
DataMass
DataField
DataRing
DataVector
DataStrap
DataScreen

**Comment by painswor28** [comment]
datanest
datafungus
dataspore
spore
datastump

**Comment by painswor28** [comment]
datameoba

**Comment by painswor28** [comment]
datamag
datacatamari
datacalamari

**Comment by dthain** [comment]
So, collecting together a number of themes and ideas...
And then eliminating things that already exist in google.

DataClack
DataSwizzle
DataPaver

TaskCyclone
TaskFlood
TaskFount

**Comment by btovar** [comment]
+1 DataClack, DataPaver

DataSwizzle is hard to spell and pronounce.

**Comment by dthain** [comment]
Ok, I think this our list of finalists:
- DataClack
- DataPaver
- DataTulip
- TaskTulip
- TaskLily
- TaskVine
- TaskCyclone
- TaskFount

**Comment by dthain** [comment]
Following today's discussion, we have two finalists:
- TaskCyclone
- TaskVine

**Comment by dthain** [comment]
The verdict is in:

**TaskVine** is the name of the new software, to be used in documentation, papers, and so forth.

`taskvine` should be the top level namespace in any code and documentation:
- `cctools/taskvine/src/manager`
- `cctools/doc/manuals/taskvine`
- `taskvine.h`

The prefix `vine_` will be used as the shorthand namespace qualifier:
- `vine_create()` `vine_submit()` `vine_delete()`
- `vine_task_create()` `vine_task_add_input_file()` `vine_task_delete()`
- `vine_manager.c` `vine_file.c` `vine_task.c`
- `vine_worker` `vine_status` etc
