### ISSUE TITLE
Vine: PONCHO Integration

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#2988]
I think we now have a way to cleanly integrate Python environments via PONCHO in the TaskVine framework.

Here is the problem:

`poncho_package_run package.tgz command` really does three things:
1 - untar a package
2 - specialize the package to the local host
3 - run the command in the package environment

If two instances want to run concurrently, then either they must unpack the package in separate places (wasteful) or lock a common directory (unreliable) as they perform steps 1-2.

What we want to happen is for the worker to do steps 1-2 **once**, and then keep the resulting directory for use by any number of tasks.

I think this can be easily added to TaskVine as follows:

Take a look at the `VINE_UNPACK` flag, which is used in `vine_cache.c`.  If the flag is given, then a tarball (or other package) is unpacked once after transfer, and the unpacked version is used by all consumers thereafter.

Extend this by adding a new flag `VINE_PONCHO_UNPACK` which performs steps 1-2 for a poncho package, leaving the unpacked directory for use by the application in step 3.

This will require adding some arguments to `poncho_package_run` to do only steps 1-2 or step 3 as requested.

**Comment by dthain** [comment]
@BarrySlyDelgado this one is a higher priority than the persistent caching one.

**Comment by BarrySlyDelgado** [comment]
Looking at this now, Is there a reason that under the  `VINE_UNPACK` flag when the cache_file suffix is `tgz` we don't unzip the file but when the `suffix` is `tar.gz` we do? That is, using `tar xf` vs `tar xzf`.

**Comment by dthain** [comment]
@BarrySlyDelgado how is this going?

**Comment by BarrySlyDelgado** [comment]
@dthain Writing out a test, had to get familiar with the interface. Though, I have a question regarding the caching. From my perspective, a user specifies the input file `env.tar.gz` with the flag `VINE_PONCHO_UNPACK`. The command is something along the lines of `poncho_package_run -u <unpack-directory> -e env.tar.gz python test.py` what goes into `<unpack-directory>`. With work queue it was somethng like ${work_queue_sandbox}. for vine it  should be whatever `cache_path` is  with `vine_cache.c` but I'm not sure what that is.

**Comment by dthain** [comment]
From the user's perspective, it should look like this:

`vine_task_add_input_file(task,"package.tar.gz","package",VINE_PONCHO_UNPACK)`

This means that the package will be unpacked into the cache directory,
then linked into the task sandbox as `package`.  So, the user's command should expect the unpacked directory to be in the current working directory, named `package`.

Does that clarify?

**Comment by BarrySlyDelgado** [comment]
Yes, that  makes thins clear.

**Comment by BarrySlyDelgado** [comment]
Update from discussion today:

- There is a current issue with local files not being able to be unpacked when added via `vine_task_specify_input_file(file)`

- Quick fix: use `vine_task_specify_input_url(''file:///<ABSOLUTE_PATH>)` instead 

- There was an issue with the worker using the incorrect version of `poncho_package_run` thus `poncho_package_run` had to be added to the worker's path
