### ISSUE TITLE
allpairs_multicore with multi-slot workers

### ISSUE THREAD

**Issue by dpandiar** [cooperative-computing-lab/cctools#300]
All-Pairs uses allpairs_multicore as the kernel for its tasks. allpairs_multicore has an option to specify the number of cores to use. However, this doesn't interact with the facility we have for running multi-core jobs in WQ.

**Comment by dthain** [comment]
@trshaffer please take a crack at this one.

Modify allpairs_multicore to respect the CORES and MEMORY environmental variables that are set by Makeflow and WQ to tell each job what to do.

**Comment by nhazekam** [comment]
I think this may have been addressed by @trshaffer 's pull request.
