### ISSUE TITLE
Build: CI on OSX-M1

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3010]
- [x] Code must be compatible with M1 for starters.  Currently, we can git clone; configure; make successful on an M1 laptop with Xcode installed.
- [x] M1 support in CI pipeline.  At the moment, it does not seem that GitHub has native support for M1 hardware.  The [Action Runner](https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/) can run on M1 hardware, but they do not provide it in the cloud.
- [x] M1 support in the Conda deployment pipeline.  It does appear that conga-forge does support M1 builds, but it does so by a cross-compiler that runs on X86 hardware, strangely enough.[M1 on Conda-Forge](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/). It may be sufficient to update our [Conda Feedstock](https://github.com/cooperative-computing-lab/ndcctools-feedstock) appropriately.

@btovar can you think of any other blockers in terms of getting things running?

**Comment by btovar** [comment]
I'll give the conda matrix a try.

**Comment by btovar** [comment]
The conda build has been merged. It should become available to install shortly.

**Comment by dthain** [comment]
Some minor things discovered while building on M1 on laptop
- `poncho_package_run` uses `date +%s%N` to generate sub second time resolution, but OSX doesn't support `%N`
- The make flow tests rely on copying `/bin/echo` to the current directory, but for some reason, the executable doesn't work when copied.

**Comment by dthain** [comment]
Current status:
- cctools builds, runs, and passes most tests on my laptop using M1 Conda to deliver environment.
- GitHub does not provide M1 runners, but we do get X86 runners, which covers must issues.

Current failing tests on my laptop:
```
--- Testing makeflow/test/TR_starch_example.sh ...                failure 1s
--- Testing makeflow/test/TR_starch_extract_and_remove.sh ...     failure 0s
--- Testing work_queue/test/TR_work_queue_allocations.sh ...      skipped 0s
--- Testing work_queue/test/TR_work_queue_auto_modes.sh ...       skipped 0s
--- Testing work_queue/test/TR_work_queue_multicore.sh ...        success 2s
--- Testing work_queue/test/TR_work_queue_python.sh ...           failure 16s
--- Testing work_queue/test/TR_work_queue_python_task.sh ...      success 2s
--- Testing work_queue/test/TR_work_queue_remotetask.sh ...       skipped 0s
--- Testing work_queue/test/TR_work_queue_single.sh ...           success 2s
--- Testing work_queue/test/TR_work_queue_ssl.sh ...              skipped 0s
--- Testing work_queue/test/TR_work_queue_tag.sh ...              success 2s
--- Testing work_queue/test/TR_work_queue_valgrind.sh ...         skipped 0s
--- Testing taskvine/test/TR_vine_allocations.sh ...              success 7s
--- Testing taskvine/test/TR_vine_multicore.sh ...                success 1s
--- Testing taskvine/test/TR_vine_python.sh ...                   failure 30s
--- Testing taskvine/test/TR_vine_python_auto_modes.sh ...        skipped 0s
--- Testing taskvine/test/TR_vine_python_cancel.sh ...            success 5s
--- Testing taskvine/test/TR_vine_python_cancel.sh~ ...           success 2s
--- Testing taskvine/test/TR_vine_python_futures.sh ...           success 3s
--- Testing taskvine/test/TR_vine_python_no_serialization.sh ...  success 1s
--- Testing taskvine/test/TR_vine_python_serverless.sh ...        success 5s
--- Testing taskvine/test/TR_vine_python_ssl.sh ...               skipped 0s
--- Testing taskvine/test/TR_vine_python_tag.sh ...               success 3s
--- Testing taskvine/test/TR_vine_python_task.sh ...              success 1s
--- Testing taskvine/test/TR_vine_python_temp_files.sh ...        success 3s
--- Testing taskvine/test/TR_vine_single.sh ...                   success 1s
--- Testing taskvine/test/TR_vine_valgrind.sh ...                 skipped 0s
```
