### ISSUE TITLE
Vine: Add Support for XRootD Data Fetch

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3023]
Add a handler for accessing input data via the xrootd protocol `root://host:port/path`.
This will allow us to pull and manage physics data within the DS cluster.
One likely complication is that the transfer may require some kind of authentication data.
Figure out how to make the auth data file a dependency for the transfer.

**Comment by dthain** [comment]
This should be quite easy to do now that we have Mini-Tasks #3046 !

`f = vine_file_xrootd(url,creds)`

**Comment by btovar** [comment]
Some parameters may be helpful, like:

```python
f = vine_file_xrootd(url,creds,tree_path="Events",start=0,end=-1,...)
```
where the `...` are columns.

**Comment by dthain** [comment]
Yes!  This will allow us to implement a kind of query caching of physics data.

**Comment by btovar** [comment]
Completed in #3132
