### ISSUE TITLE
TaskVine Python link is broken in API Documentation 

### ISSUE THREAD

**Issue by colinthomas-z80** [cooperative-computing-lab/cctools#3040]
https://cctools.readthedocs.io/en/latest/api/html/

Also missing from Namespaces
https://cctools.readthedocs.io/en/latest/api/html/namespaces.html

**Comment by btovar** [comment]
@colinthomas-z80 I do see it at: https://cctools.readthedocs.io/en/latest/api/html/namespaces.html  Perhaps you are looking at a cached version?

I'll fix the other one.
