### ISSUE TITLE
Shadho -  Work Queue releasing workers

### ISSUE THREAD

**Issue by BarrySlyDelgado** [cooperative-computing-lab/cctools#3087]
Sophia has run into an issue where Work Queue will release workers while using a specific method along with Shadho. The workers are released before all of tasks are completed.

- There are other successful run, however those are much shorter.
- It is currently unknown why the manager is telling the workers to be released
- The application is typically ran with around 100 Tasks and 10-20 workers
- One possibility is that Shadho is telling the workers to be released.

**Comment by BarrySlyDelgado** [comment]
There is one section [here](https://github.com/jeffkinnison/shadho/blob/master/shadho/shadho.py#L296) where the program will exit once this exhausted value is true:
`       exhausted = all([space.done(self.max_tasks) 
                         for space in self.searchspaces])`

I don't believe this is equivalent to all tasks being completed as there is a section later that waits for tasks that are still running.

`            # If requested, continue the loop until all tasks return
            if self.await_pending:
                while not self.manager.empty():
                    result = self.manager.run_task()`

**Comment by btovar** [comment]
@BarrySlyDelgado Also from that `done` function, it is also possible that the timeout set has been reached. As you say, `done` does not check whether there are tasks left; its termination conditions imply that it is expected that tasks are left without a completion.

**Comment by BarrySlyDelgado** [comment]
Yes, however the timeout is set to inf in Sophia's workflow so I don't believe the timeout it being reached.

**Comment by btovar** [comment]
shadho has `await_pending : bool, optional`, that looks like forces all the tasks to finish.

**Comment by btovar** [comment]
(Tagging @sabraha2 and @jeffkinnison)

**Comment by btovar** [comment]
As far as I can tell, wq is releasing the workers because it has `shutdown_workers = True` in its initialization. However, shutdown workers is only called when wq is being garbage collected, which should only happen when shadho thinks the workflow has been completed. shadho does not explicitly release workers, it is only done in the destruction of the wq object.

**Comment by btovar** [comment]
After debugging with @sabraha2, it looks like one of the methods, `hom()`, is not generating the expected solution to the input models. Eventually shadho+wq run out of tasks to try and they quit.
