### ISSUE TITLE
Poncho: Package Preparation Primarily in Python Please

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3103]
Right now, Poncho requires you to use the Unix command line in order to create a poncho package.  But there are many uses (like what @David-Simonetti-ND is doing) where we want to create the environment directly from Python.  The first step is just something like this for normal tasks:

```
p = [ "matplotlib","tensor flow","pytorch"]
pkgfile = poncho.MakePackageFromList(p)
task.specify_environment(pkgfile)
```

But then you can do the same thing for duties, so that it is easy to define the environment once.

And then, you might even make the construction of the package a mini-task!

**Comment by dthain** [comment]
@mcarbona1 I think this is a good next step for you, and you can test it out with David.

**Comment by David-Simonetti-ND** [comment]
I think a lot of the machinery needed for this already exists. I don't even think there needs to be a manual list of packages, as if we have the user's function to creation an environment for, there are methods in the poncho python library (scan_pkgs and analyze_function in package_analyze) that can get a full list of packages from the installed conda environment, and then output a yml description of dependencies for that user function. 
Once we have the yml description, package_create can turn that into an actual tarball, and that can be added as an environment for the task.

Some rough pseudocode for what could be done.
```
from poncho import package_analyze as analyze
from poncho import package_create as create

# function we wish to create an environment for
def user_function():
    # lines of code, imports, etc here

# get info about current conda environment
analyze.scan_pkgs()

# read in the code for this file and parse it 
fnc_code = ast.parse(user_function)
# get imports we need
imports = analyze.analyze_function(fnc_code)

env_yml = analyze.export_env(imports)

create.pack_env(env_yml, output_file)

```

**Comment by dthain** [comment]
Yes, the pieces for this are already here, but I want to keep two things separate:
1 - Scanning a function to produce a dependency list.
2 - Packing a dependency list into a package.

The reason for this is that we may want to attach packages to ordinary executables, and not only to server less functions.

**Comment by dthain** [comment]
A related problem I see is that `declare_poncho` incorrectly takes a filename as an argument and assumes that it is a local file source.  Instead, it should take a vine file object as a source, so that it can draw packages from anywhere.

**Comment by btovar** [comment]
I think declare_poncho has both in python. You can pass a vine file, but if you are lazy, you can pass a string a declare_poncho declare_file's that for you.

**Comment by dthain** [comment]
Ok, that makes more sense to me.

**Comment by btovar** [comment]
Also, a lot of the hard parts have been implemented in topEFT's remote_environment.py module. That module starts from a poncho specification, so it shouldn't be too hard to bring to taskvine.

**Comment by dthain** [comment]
I think the key bit here is we want the user to declare deps in JSON form, and ask for them to be materialized into a package.  TaskVine should cache packages, with the name derived from the hash of the JSON dependencies.

**Comment by BarrySlyDelgado** [comment]
This has been completed with the merging of #3349
