### ISSUE TITLE
Vine/WQ: switch default catalog update from udp to tcp

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3113]
It looks like more sites are blocking udp (just happened to Kelci at UFL).  Without catalog updates of the manager, the workers can't find their target projects, and the workload does not make any progress. For users this is a hard problem to debug, as both manager and workers are working correctly just waiting for each other. Further, the way to change the catalog protocol presumes that a user knows about such protocols.

I propose to explore a change to make the default protocol tcp. From the manager side this change is negligible. From the `catalog_server` side, workers ask information via tcp, so it shouldn't also be a significant change.

**Comment by dthain** [comment]
No objection here.  I'm sure there will be some ancillary problem down the road, but let's try it and find out soon.

**Comment by dthain** [comment]
#3114
