### ISSUE TITLE
Vine: Python Task Construction

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3119]
The Python API for task construction follows the C interface in using methods to add details to the structure.  This makes logical sense, but it is verbose and not very Pythonic.  Design a Pythonic structure for representing a task, and have the constructor parse it and call the necessary methods, so that this:

```
software = FileURL("http://.../blast.tgz");
database = FileURL("http://.../landmark.tgz");

t = Task("/path/to/blast -p 3046");
t.add_input(t,software,"blastdir",VINE_CACHE);
t.add_input(t,database,"landmark",VINE_CACHE);
t.add_env_var(t,"BLASTDB","landmark");
```

Becomes something like this:

```
software = FileURL("http://.../blast.tgz");
database = FileURL("http://.../landmark.tgz");

t = Task(
{
    cmd : "/path/to/blast -p 3046",
    inputs : { "blastdir" : file, "landmark" : database },
    output : { ... }
    env : { "BLASTDB" : "landmark" }
}
```

**Comment by dthain** [comment]
Next easy step:
```
taskid = m.submitTask( { cmd: "/path/to/blast", inputs: {...} } )
```

**Comment by dthain** [comment]
@btovar with apologies, I am going to have @JosephDuggan7 work on this one, since he is already knee-deep in the Python interface, ok?

**Comment by btovar** [comment]
Completed in #3167
