### ISSUE TITLE
Vine: File Delete Strategy

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3127]
Now that we have content addressable names and the worker no longer deletes files by default, it is no surprised that storage usage accumulates very quickly.  So, we need to choose to delete files at least some of the time.

Under the old work queue, we have the following behavior:
- The worker would delete all files (cached or not) at startup, disconnection, and exit.
- The manager would deleted NOCACHE files as soon as a task consuming it as input exited.

Under taskvine, we have the following considerations:

The worker could choose to delete files:
- When it starts up.
- When it disconnects from a manager.
- When it exits after giving up or being told to shutdown.

The manager could delete files:
- As soon as a task ends.
- When an input file is no longer needed by any task.
- When an workflow completes.

And we have the following file types:
- FILE - came from the host filesystem
- URL - came from a remote data service
- BUFFER - came from the manager's memory space
- TEMP - came from a task output, will get used as another input
- MINITASK - produced by a synchronous task like untar or unponcho.

What should our deletion strategy be?

**Comment by btovar** [comment]
Some random ideas that maybe we can convert to a simple policy:

- Mark files that need to be cached between runs. (CACHE_?, I don't know how to name them.). These files will only be deleted if explicitly deleted by the user.

Then for all others:

1. If a manager doesn't know about a file (from a cache-update), the file should be deleted.
2. A worker with a unique copy of a file should never timeout.
3. If a worker timeouts or is released explicitly by the manager, all files are deleted.
4. If a worker suddenly disconnects, then no file is deleted. On connecting to a manager, see 1.
5. If a worker shutdowns, then all files are deleted.

**Comment by dthain** [comment]
@BarrySlyDelgado per our discussion today, please modify the worker to ways:
- [ ] clear all files from the cache at startup and shutdown.  (but not disconnect and reconnect)
- [ ] go back to using a workspace directory based on uid and pid.  (so that we don't have to deal with shared cache dirs just yet)

That will give us an improved behavior over WQ, and leave some space to improve things further in the next version.

**Comment by dthain** [comment]
This is working.
