### ISSUE TITLE
Vine: Tune up Hash Methods

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3130]
The computation of file hashes should be improved in several ways:
- [x] `task_to_json` creates a string representation of a task, which is hashed to give a unique task name.  This needs to be looked at carefully and include all elements that control the output of the task.  For example, environment variables should be part of the string.
- [x] `md5_dir` computes a directory hash by having strings containing the name and hash of each file in a directory.  This should be extended to include metadata (permissions, mtime, etc) so that metadata changes force a new object creation.
- [x] `md5_dir` should sort the entries in each directory before hashing, so that values are independent of accidental ordering.

Each one of these is an independent improvement and should be a separate focused PR.

**Comment by BarrySlyDelgado** [comment]
I've completed the metadata hashing and sorting

**Comment by BarrySlyDelgado** [comment]
Completed with #3372
