### ISSUE TITLE
vine: starch and poncho use

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3160]
With `m.declare_{starch,poncho}`, it becomes the responsibility of the user to modify the task command line to take advantage of the setup. With poncho is slightly worse because `poncho_package_run` has to be added as an input to to the task.

Since both of these produce directories, one quick fix for the time being is to generate a wrapper script in their minitask, and copy that script into the directory.  E.g.:

```python
f = m.declare_poncho("p.tar.gz")

t = Task("poncho_dir/run   mycommand line")
t.add_input(f, "poncho_dir")

# where poncho_dir/run is created to call the poncho_package_run included in the environment.
(In fact, we may always want to copy poncho_package_run to the bin directory of poncho packages. In that way, we know to expand them and look for a poncho_package_run that can activate them.)
```

**Comment by btovar** [comment]
I inadvertently broke the `vine_example_poncho` as I thought the explicit call to `poncho_package_run` was superfluous.

**Comment by tphung3** [comment]
I'm not sure about starch, but for poncho, if the manager declares a poncho environment, can't we prepend the task's command line with `poncho_package_run -e p.tar.gz` and add `poncho_package_run` as input?

**Comment by btovar** [comment]
Yes, that's one good alternative.  However, I'm not sure about modifying the command line when we declare a file. I rather add a call such as `t.enable_environment("some_dir")`  where `some_dir` is the output of `declare_poncho` or `declare_starch`.

Internally, we would look for a "some_dir/bin/run_in_env", where `run_in_env` is constructed by poncho_package_create, or starch.

**Comment by btovar** [comment]
completed with `t.add_execution_context`
