### ISSUE TITLE
poncho_package_analyze: bug with scipy

### ISSUE THREAD

**Issue by David-Simonetti-ND** [cooperative-computing-lab/cctools#3162]
When running poncho_package_analyze with having the scipy package installed in my conda environment, I get the following error.
```
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/d/dsimone2/miniconda3/envs/serverless_dev/bin/poncho_package_analyze", line 34, in <module>
    analyze.scan_pkgs()
  File "/afs/crc.nd.edu/user/d/dsimone2/miniconda3/envs/serverless_dev/lib/python3.11/site-packages/poncho/package_analyze.py", line 26, in scan_pkgs
    files = [x.strip() for x in m.get('Files').splitlines()]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'splitlines'
```
I did some digging, and it seems like the code is using a 
`email.parser.BytesParser()`
to decode the output of 
`subprocess.check_output(['pip', 'show', '-f', pkg['name']]`
but the license section is breaking the parser and isn't it allowing it to see the file section.

**Comment by BarrySlyDelgado** [comment]
I was able to recreate the error. Installing scipy via conda does not produce the same error though.

**Comment by David-Simonetti-ND** [comment]
Installing via conda did fix the issue for me. I have to wonder if other packages than just scipy will break poncho_package_analyze.

**Comment by dthain** [comment]
How was it delivered, if not by Conda?

**Comment by BarrySlyDelgado** [comment]
The error appears if you install scipy within your environment like `pip install scipy`. If you do `conda install scipy` It works. Poncho scans the local conda environment to map the imports. And for whatever reason, if scipy was installed using pip the error occurs.

**Comment by dthain** [comment]
So what is the conclusion?
Does poncho only support conda packages?

**Comment by BarrySlyDelgado** [comment]
Scipy is currently the only pip package that produces this issue that we know of.
