### ISSUE TITLE
make -j sometimes breaks taskvine compilation

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3184]
The -j flag executes rules from the makefile concurrently according to the listed dependencies. Since make -j sometimes fails, this means that we are missing some explicit dependencies.

For example, a `make -j` gives:
```
ar: creating libtaskvine.a
ar: vine_manager.o: No such file or directory
make[1]: *** [../../../rules.mk:15: libtaskvine.a] Error 1
```

But a subsequent `make` produces the correct binaries. This is important for conda forge, as it uses `make -j "${CPU_COUNT}"`

**Comment by dthain** [comment]
This one is my fault, I'll fix it..

**Comment by dthain** [comment]
No, I take it back.  :) 

The Makefiles look correct as far as I can tell: libtaskvine.a depends upon the object files, which are built by implicit rules.

I think there is something else going on here...

**Comment by btovar** [comment]
Maybe the `make -j clean all` is confusing it, as   `make clean; make -j` seems to work every time.

**Comment by btovar** [comment]
Can't reproduce only with make -j
