### ISSUE TITLE
vine worker: on disconnect, VINE_CACHE files are not deleted

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3198]
When a worker disconnects from a manager without being properly released (e.g., because the manager terminates without calling `vine_delete()`, or because there was some connectivity error), the VINE_CACHE files at the worker are not deleted. VINE_CACHE names are only valid per workflow, thus here are a couple of ideas to enforce this:

1. On disconnect, the worker deletes VINE_CACHE files and only preserves VINE_CACHE_ALWAYS files. Either we need to send the cache flag with the protocol message, or VINE_CACHE files should be written to a subdirectory of cache that gets deleted on disconnect.
2. The manager computes a random id per workflow (as we do for the worker-id) and sends this id to the worker. After a disconnect, when the worker connects to a new manager, the cache-updates messages should include the id of the manager that created that file at the worker. If the cache-update id and the id of the manager do not match, then the manager requests the files to be deleted. This would be helpful for temporary disconnects.

**Comment by dthain** [comment]
Depends on #3557

**Comment by dthain** [comment]
The worker now does proper cache management at shutdown and startup, by tracking appropriate cache levels in the per-file metadata.
