### ISSUE TITLE
vine transfers: declare output of minitask in manager

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3222]
Currently the `vine_file_local` output of a minitask is added to the task directly in vine_file_mini_task.  Thus, the manager does not know about this output, which reduces our chances of sharing it when appropriate. I propose to change vine_file_minitask to take the arguments:

```C
struct vine_task t;  // the minitask
struct vine_file output;  //the local file produced. This file will be declared in `vine_declare_mini_task`.
int share_task; // if 0, always send the minitask as input. If 1, allow the output to be shared among peers.
                            // Need to think carefully about names and substitutions.
vine_flags_t flags;  //the flags that apply to output, not the task.
```

For now we can modify the current code as if share_output is always zero. @colinthomas-z80 , what do you think? As we talked about, when share_output=1, then we can re-implement declare_url as a mini task.

In general, no `vine_file_*` should add files directly to the mini task they use. All files should be declared in the corresponding `vine_declare_*`.

**Comment by dthain** [comment]
This does need to be worked on, but not prior to the completion of the SC paper.

It's a bit subtle about what's being named here: the minitask itself or the output file.  

The current code really assigns the name to the minitask and assumes that there is one implied output file.

**Comment by dthain** [comment]
#3577
