### ISSUE TITLE
vine: remove fatal's from API calls

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3236]
When using taskvine in jupyter notebooks `fatal()` calls in the C code also terminate the jupyter kernel. This  makes using notebooks more difficult. It is desirable for all API calls to return an exit status that can be checked in the python bindings. The python bindings can then raise an exception when needed.

This is specially important with `binder` where a user would have to request again a notebook when the first one is suddenly terminated.

Moreover, the `fatal()` messages do not get printed in the notebook. As far as the user is concerned, the notebook is just terminated with no explanation.

**Comment by dthain** [comment]
Fixed by #3361
