### ISSUE TITLE
vine: user's can't declare which file is the output of a mini task

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3242]
Previous code used `vine_file_local` to specify the output of the mini task. This call is used internally for all mini-task-based declarations.
However, this call is not available in the public API because it allows adding files to tasks without declaring them first to the manager.

Some options:

- Declare the output of the mini tasks with `declare_file()`. Creates the problem that a user may add this output file directly in a task, rather than the mini task.
- Make `vine_file_local` public. This allows files to be added to the task without declaring them.
- Specify that the output of all mini tasks has to have a name such as "output".  Unsatisfying as it removes flexibility, and some commands may not have an option to change the name of their output.
- Add a call like `Task.set_mini_task_output()` which can call `vine_file_local` internally.  Any task that calls this function and then it is submitted with `m.submit()` would be an error. Conversely, any task declared as a mini task that did not declare an output would be an error too.

I like the last option the best.

**Comment by btovar** [comment]
E.g., for the tasvine manual I have the following example:

```python
# use cpio to expand archives coming from a url
t = Task("cpio -iD output_dir < archive.cpio")

my_url = m.declare_url("http://somewhere.com/archive.cpio", cache=True)
t.add_input(my_url, "archive.cpio")
t.set_mini_task_output("output_dir")

mini_task = m.declare_mini_task(t)

# regular tasks can use the mini task as input 
# the output of the mini task is mounted in the regular task sandbox
my_other_task = Task("my_cmd output_from_cpio/")
my_other_task.add_input(mini_task, "output_from_cpio")
```

**Comment by dthain** [comment]
@btovar this specific problems comes up with PythonTasks as MiniTasks, because a PythonTask produces two outputs: the result of the function, and the standard output of the python process.  So we need a way to declare one as the "minitask" output.

What do you think of the following change to the API?
```
# use cpio to expand archives coming from a url
t = Task("cpio -iD output_dir < archive.cpio")

my_url = m.declare_url("http://somewhere.com/archive.cpio", cache=True)
t.add_input(my_url, "archive.cpio")

mini_task = m.declare_mini_task(t,"output_dir")

# regular tasks can use the mini task as input 
# the output of the mini task is mounted in the regular task sandbox
my_other_task = Task("my_cmd output_from_cpio/")
my_other_task.add_input(mini_task, "output_from_cpio")
```

My reasoning here is that there should be nothing "special" about the Task object that makes up a Mini-Task.  We want to allow any kind of ordinary task there.  The File object representing a Mini-Task is where we should locate special functionality related to Mini-Tasks.  (Such as extracting the specific output.)

**Comment by btovar** [comment]
Looks good!

**Comment by dthain** [comment]
Collecting some several places where this problem manifests itself in the code:

`[vine_worker.c:do_put_mini_task](https://github.com/cooperative-computing-lab/cctools/blob/master/taskvine/src/worker/vine_worker.c#L827)`

**Comment by dthain** [comment]
#3577
