### ISSUE TITLE
vine worker: investigate adding zlib as a static library

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3272]
WIth `ldd vine_worker`, we get:

```text
ldd $(which vine_worker)
        linux-vdso.so.1 (0x00007ffc44598000)
        libz.so.1 => /SOME/PATH/TO/CONDA/ENV/bin/../lib/libz.so.1 (0x00007ffadfe69000)     <--- unfortunate dependency
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffadf484000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffadf0be000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ffaded3c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffadfc58000)
```
This means that workers need to be launched inside the conda environment. It would be nice if we can launch workers without such dependency.

**Comment by btovar** [comment]
Or not... The policy for conda-forge is to remove all static libraries:

https://github.com/conda-forge/cfep/blob/main/cfep-18.md

Thus, we need to update instructions to submit workers together with their packed environments.

**Comment by dthain** [comment]
I'm scratching my head about this one.
Of course we want the worker to be widely portable.
And I get that customs prevent us from really statically linking everything.
But can we not assume that libz is present on any reasonable target machine?

**Comment by btovar** [comment]
The issue is that we have to force the worker not to use the libz from the conda environment at compilation time.
zlib is small enough that we could fetch it and compile statically.  The one that would be more difficult is openssl-static that we get from conda. I hope that one does not go away.

**Comment by btovar** [comment]
The workers does pickup correctly the zlib of the system when outside the conda environment. Checking the worker inside the conda environment links to the zlib in that environment, which was what confused me.
