### ISSUE TITLE
Vine: Peer to Peer Transfer Fixups

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3282]
Currently, worker-to-worker transfers operate correctly when manually enabled, and (I think) only for URL transfers.  Fix up two things so that we can use them ubiquitously:
- [ ] Worker-to-worker transfers should operate correctly for any file type (local, buffer, mini-task output) and not only URLs.
- [ ] Worker-to-worker transfers should be enabled by default and controlled with an `enable/disable` pair in the API.
- [ ] Add a note about enabling and disabling peer transfers in the documentation.

**Comment by colinthomas-z80** [comment]
Resolved in #3290
