### ISSUE TITLE
Vine: Complete Parsl Integration

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3283]
@tphung nice work on the integration PR so far here:
https://github.com/Parsl/parsl/pull/2599

I think this is what remains to do:
- [x] Add documentation to the Parsl PR.  Make sure to explain installation of cctools+parsl using conda+pip
- [x] Add an integration test to `cctools-packaging-test`
- [ ] Manually enable peer transfers in Parsl-TaskVine executor

**Comment by dthain** [comment]
@tphung3 please update here current status and any remaining challenges.

**Comment by dthain** [comment]
Separating out performance into separate issues.

**Comment by tphung3** [comment]
See https://github.com/Parsl/parsl/pull/2809 for more information.

**Comment by dthain** [comment]
Splitting issues out separately.
