### ISSUE TITLE
vine: re-declaring a file using the same file name creates two different file objects when there should be only one

### ISSUE THREAD

**Issue by tphung3** [cooperative-computing-lab/cctools#3317]
When a regular file is declared using its file name and with its cache flag set to `never` or `workflow`, then a re-declaration of the same file creates a different file object as the TaskVine name of the file is randomly generated.

A re-declaration of a file should be detected and mapped to the already generated file object, and this can be done by (either/or):
1. Maintain a table that maps a file's path (entry name) to its TaskVine name
2. A file's TaskVine name is not randomly generated but hashed using its entry name

**Comment by btovar** [comment]
Another option is to just give a warning if the flags are different, and just keep going with the first declaration. Files are supposed to be immutable, so changing their names mid run breaks a design principle and it may be a lot of work for little gain.

**Comment by dthain** [comment]
The problem here is that this code sequence creates two different objects:
```
a = m.declare_file("xyz")
b = m.declare_file("xyz")
```

Because local files (when not cached forever) create a random unique number, to avoid the cost of hashing on content.

**Comment by tphung3** [comment]
Only VINE_FILE and VINE_URL are possibly de-duplicable by maintaining a mapping from source to file object. VINE_BUFFER is not without looking at the buffer's content. VINE_TEMP and VINE_MINI_TASK are unclear to me how the de-duplication happens. 

Deduplicating only VINE_FILE and VINE_URL is probably confusing and inconsistent, so it's probably the best to not change anything and let the user/app do the deduplication.

We can also have something in between where TaskVine maintains a mapping from source to file object for VINE_FILE and VINE_URL and throws a warning whenever it detects possible duplication.

**Comment by tphung3** [comment]
Yes that's correct. The executor maintains a dictionary that maps a file path to a TaskVine File object and checks the dictionary for every file in a submitted task.

**Comment by dthain** [comment]
I believe that this is fixed at two different levels:
- In TV, declaring the same file twice should result in the same underlying hash.
- When used with Dask/Parsl the upper level DAG processor will declare each file once.
-
