### ISSUE TITLE
Vine: Manual is inconsistent

### ISSUE THREAD

**Issue by tphung3** [cooperative-computing-lab/cctools#3363]
1. In section `Running a TaskVine Application`, a script in Python is provided (`functions.py`) but the followed description uses `taskvine_example.py` instead, which is non-existent.

2. Also in the subsection `Submitting Workers to a Batch System`, these scripts work only with WorkQueue, not TaskVine. This will be fixed in an upcoming PR.

3. Subsection `Apptainer Custom Environment` has an empty reference to `run_command_in_apptainer.sh`.

**Comment by dthain** [comment]
1 and 2 look fixed to me.
Is 3 still a problem?

**Comment by tphung3** [comment]
only 2 is fixed in PR #3365 , 1 and 3 are not.

**Comment by dthain** [comment]
@btovar do you happen to have `run_command_in_apptainer.sh` sitting in a directory somewhere?
It looks like you wrote it into the docs but didn't add the file.

**Comment by btovar** [comment]
Yes, sorry about that! Opened https://github.com/cooperative-computing-lab/cctools/pull/3371
