### ISSUE TITLE
Vine: worker runs task then cache updates the task's environment file.

### ISSUE THREAD

**Issue by tphung3** [cooperative-computing-lab/cctools#3446]
Running 1000 tasks each attached with a poncho environment (~1GB) results in a situation where around 3/4 of tasks or even all tasks fail because the poncho environment is seemingly truncated.

Bumping the timeout in `do_worker_transfer` from 120 to 300 seconds reduces the number of failed tasks to < 10, and the machine that has failed tasks run the next tasks successfully.

Examining the transaction log shows that the first cache-update message of the environment file happens 2 seconds after a task is run. The transaction log may not capture causality, but it is probably a bug.

**Comment by tphung3** [comment]
Update: The run above is 1000 tasks and 200 workers. I just ran another experiment with 1000 tasks and 100 workers and all 1000 tasks fail.

**Comment by tphung3** [comment]
The latter experiment fails twice with the same 1000 failed tasks, so it's probably not random,

**Comment by dthain** [comment]
Well, it's easier to debug, then!

Starting point would be to collect the manager log and at least one worker log, right?

**Comment by dthain** [comment]
Is this fixed by #3447 ?

**Comment by tphung3** [comment]
Fixed in #3450.
