### ISSUE TITLE
Vine: vine_transfer needs fsync to work properly

### ISSUE THREAD

**Issue by tphung3** [cooperative-computing-lab/cctools#3448]
Whenever a file is transferred between workers, the receiving worker must call `fsync` on the file descriptor to ensure that the file is dumped to disk.

Evidence: running a workflow with 1024 tasks, each with a poncho environment tarball ~1GB:
- no `fsync`: `success: 78, failure: 946`
- `fsync`: `success: 1024, failure: 0`.

**Comment by dthain** [comment]
I am baffled as to why this is so, but I can't argue with your evidence!
