### ISSUE TITLE
Build: Linting code

### ISSUE THREAD

**Issue by tphung3** [cooperative-computing-lab/cctools#3451]
I see that sometimes master code and PR code use different conventions of tabs and spaces. Do we want to use a linting program to unify this? (e.g., [cpplint](https://anaconda.org/conda-forge/cpplint))

**Comment by dthain** [comment]
Well, there are already several style tools being ignored.  :).
We should pick one and use it consistently.

At the top level, `cctools.indent` is a script that uses `indent` to format C code:
```
indent $@ -bap -br -brs -cdw -ce -cli0 -nfca -nhnl -nprs -nsaf -nsai -nsaw -nsob -npcs -npro -nss -l256 -nbfda -ut -i8 -npsl
```

We also have `.clang-format` which configures the `clang-format` tool:
```
BasedOnStyle: LLVM
IndentWidth: 8
UseTab: Always
ColumnLimit: 120
ContinuationIndentWidth: 16
AlignAfterOpenBracket: DontAlign
BreakBeforeBraces: Linux
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
BreakStringLiterals: false
BinPackArguments: false
```

And then this is the simple setup I have in emacs:
```
; Force indentation with a hard tab instead of spaces.
(setq-default indent-tabs-mode t)

; For display purposes, a tab is eight spaces wide
(setq-default tab-width 8)

; Each indentation level is one tab.
(defvaralias 'c-basic-offset 'tab-width)
```

Those all make sense for C code.  We should probably use something different for Python.

**Comment by dthain** [comment]
See #3462.  Can you recommend tools for checking style constraints?

**Comment by tphung3** [comment]
For C I tested [cpplint](https://anaconda.org/conda-forge/cpplint), like this:
```
cpplint cctools-src/taskvine/src/manager/*.c
```
It will check formatting styles and return all errors, like this:
```
vine_worker_info.c:85:  Tab found; better to use spaces  [whitespace/tab] [1]
vine_worker_info.c:86:  Tab found; better to use spaces  [whitespace/tab] [1]
vine_worker_info.c:89:  Extra space after ( in function call  [whitespace/parens] [4]
vine_worker_info.c:90:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
vine_worker_info.c:91:  Tab found; better to use spaces  [whitespace/tab] [1]
```
It's conda installable `conda install -c conda-forge cpplint` and probably used by many groups (its download number on conda is around 400K).
The downside is that running this on taskvine code alone will result in ~12K errors as taskvine has a different convention than `cpplint`. Most errors can be `sed`'ed I think.

For python I'd suggest `flake8` (Parsl uses this, ~6.5M downloads on conda). It follows Python PEP 8 so pretty standard.

Both of these tools can be integrated to the current development environment via `conda`, and it should be straightforward to add them to `make test`. What do you think?

**Comment by dthain** [comment]
done
