### ISSUE TITLE
Vine: Scheduler Linear Ops

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3459]
@colinthomas-z80 There are a few more items in `vine_manager.c` that look like linear traversals:
- `task_state_any` iterates over the entire task table to find one task in a given state.  I think any use of that function can be replaced with either a `size` operation or a lookup on a data structure, depending on the need.
- `list_remove` also iterates over an entire list.  It is used in a few places where popping the head (tail) could still be done.

With these fixed up, I think you are ready to re-evaluate the scheduler performance.

**Comment by colinthomas-z80** [comment]
task_state_any removed in #3463

**Comment by colinthomas-z80** [comment]
There are two occurrences of list_remove in the expire_task routine which can be converted to single operations.

The final and most concerning instance of list_remove is in reap_task_from_worker, where the state of the task in question is not known upon entering the function. We would be most interested in improving the normal state of waiting_retrieval.

We do tend to push relevant tasks to the head of the waiting_retrieval_list shortly before calling reap_one_task, however the ordering of these tasks in w->current_tasks cannot be guaranteed to be the same as in the waiting_retrieval_list.

I ran a test to measure the depth of the searched list each time we perform this operation and it looks like it should not be more than the amount of cores, or simultaneous tasks that the worker can be running. On one 4 core worker it usually takes 2 or 3 iterations to find the task. It remains the same when adding 2 or 3 more 4 core workers.
