### ISSUE TITLE
Vine: Check Library Task Against Worker

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3475]
`vine_manager_send_library_to_workers` attempts to send a library task to all workers that don't have it yet.  However, it doesn't bother to check whether there are sufficient resources available at each worker.  That's easily done, it just needs to call `vine_schedule.c:check_worker_against_task` to determine whether the library task is actually compatible.

Now that I think about it, the library-sending functions are just a variation on the scheduling idea, and so perhaps they would be better placed as part of `vine_schedule` instead.

**Comment by tphung3** [comment]
Fixed with PR https://github.com/cooperative-computing-lab/cctools/pull/3477.
