### ISSUE TITLE
Build: Make CCTools codebase conform to a unified code format.

### ISSUE THREAD

**Issue by tphung3** [cooperative-computing-lab/cctools#3481]
Currently only TaskVine's C source code and Python bindings are formatted to conform to `.clang-format` and `flake8`. A beginner-friendly improvement is to add these formatting/linting checks to other packages in CCTools.

Priorities to implement these checks are as follows:
- `dttools` - C
- `poncho` - Python
- `resource_monitor` - C and Python
- others.

**Comment by dthain** [comment]
done
