### ISSUE TITLE
vine: some workers can't be reused across workflows

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3498]
If a worker is reused across managers that use the same poncho tarball, then the poncho environment is not always correctly generated. This seems to be an intermittent issue, but when it happens, the tasks commands in a worker immediately fail (e.g., the resource monitor does not even create a summary file, thus probably it didn't even start.)

**Comment by dthain** [comment]
What we know:
- Tarball is really distributed with the right size.
- Some of the task run on other workers.
- The workers continue to run, rather than restart on the same storage.
- The failure only happens when we reuse inputs on a second run of the workflow.
- In the second run, the mini task output gets a new name, but the tarball is the same.

Possibilities of failure:
- [ ] Is the worker sending back the right metadata, and does it match the original metadata?
- [ ] Is the worker correctly checking for failure when running a mini task?
- [ ] Is the worker deleting incomplete mini-task outputs?
- [ ] Shouldn't the manager generate the same name for the same mini-task?
- [ ] Is the worker attempting to unpack or overwrite an existing name?
- [ ] Is the worker creating outputs directly to the original names, rather than renaming to temp?

**Comment by BarrySlyDelgado** [comment]
So, from my understanding, the workers are receiving the tarball during the first workflow and unpacking it via a mini-task. On the second workflow the worker "should" have the unpacked directory in their cache and ideally there shouldn't be an issue running poncho_package_run for a task in the second workflow but are failing.

Here is a map of the what should happen during this process:

- The manager in workflow 1 creates a poncho mini_task that will get attached to tasks. The VINE_FILE_MINI_TASK has a cache name generated by the task definition(the command and file dependencies). 
- When a task that needs a minitask is received at a worker the worker will unpack the tarball via minitask. The tarball is copied to a minitask sandbox and the resulting directory from the unpacking is the copied  into the worker's cache
- When the task runs, during stagein the directory is copied into the task's sandbox with poncho_package_run prefixed to the task command. This should only do a conda unpack. 
- during stageout the environment directory gets deleted.
- When the second workflow starts the workers should connect to the manager and provide a cache-update with the unpacked tarball present in that update.
- Any tasks in the second workflow that use the  environment should be able to by copying the environment to their sandbox during stagein, activating the environment, and deleting copied environment during stageout.  

Notes:

- There shouldn't be any executing of minitasks in workflow 2 if they already occurred in workflow 1.
- The worker will designate that a mini task has failed if either 1.) the process exits abnormally, 2.) the process failed with an exit code 3.) it failed to stageout), 4.) The resulting file was not created.
- incomplete minitask outputs should be deleted via stageout when the minitask's sandbox is deleted.
- the same name should be created across managers.(Is that happening...?)

- I think the idea of the worker trying to overwrite the file is a good possibility for this error and I'm not sure if this is safeguarded/would happen. That is if the worker process is for some reason overwriting the env directory in its cache and simultaneously would start a task the task would probably fail. However, The worker should check if the resulting file from a minitask is present before executing a mini-task that would overwrite it.

**Comment by btovar** [comment]
> When the second workflow starts the workers should connect to the manager and provide a cache-update with the unpacked tarball present in that update.

Is the unpacked tarball supposed to be in the cache update, or only the tarball? The unpacked tarball gets a random name, and can't be shared among workers. As I understand what we want to happen is for the second manager to send a mini task to unpack the already present tarball, and not to reuse the expansion of the previous manager. If the expansion should be reused, then it needs a canonical name, not a random name.

**Comment by dthain** [comment]
Ok, I think we are exploring a lot of hypotheticals without enough organized facts.
@btovar can you briefly summarize how TopEFT invokes Poncho?
(e.g. does it call `t.add_environment` or something else?
Then @BarrySlyDelgado please write up a trivial TV program that runs a bunch of tasks using poncho in the same way, so that we can re-create and explore the problem in a portable way.

**Comment by BarrySlyDelgado** [comment]
@btovar what flag are you using with `declare_poncho`?

**Comment by btovar** [comment]
What topEFT assumes:

1. Declare a regular file with the conda tarball,  `tarball_file`.
2. Declare a poncho file `poncho_file` with `tarball_file` as input. `poncho_file` is a mini task with randomly named directory `expanded_env` as output.
4. Declare a regular task `proc_task`.
5. Attach `poncho_file` to `proc_task` with `add_environment`.
6. When dispatching `proc_task`, if `expanded_env` not in the worker, manager first sends the mini task to create the `expanded_env` using `poncho_package_run`.
7. When setting the `proc_task` sandbox, the worker symlinks `cache/expanded_env`  in the sandbox.
8. `proc_task` runs with `poncho_package_run` using `-U expanded_env` from its sandbox.
9. When worker disconnects,  it should delete `expanded_env`. It should only delete `tarball_file` if not marked as CACHE_ALWAYS.

Steps 7 is not working as intended. The sandbox is getting a whole copy of the environment. This could occur because either the worker itself is making the copy, or because `poncho_package_run` creates it inside the sandbox in step 8 when it does not see it there.

**Comment by btovar** [comment]
As observed, the issue occurs even when the environment is sent by the factory, so the issue is not likely to be with the poncho environment expansion.

**Comment by dthain** [comment]
Hypothesis:

Manager attempts to peer transfer a file from worker X to worker Y.
Worker X recently restarted and reports its cache contents correctly.
It is about to (but hasn't yet) sent the rest of its startup messages indicating peer transfer address and so forth.
The manager instructs Y to get the file from X, but this fails because of a malformed URL for X.
Y then has a bad copy of the file, and proceeds to execute the task incorrectly.

@btovar @colinthomas-z80 what do you think?

**Comment by btovar** [comment]
I think that's right. In the log of a run the manager starts using peer transfers before any transfer-address message is received.

**Comment by colinthomas-z80** [comment]
Agreed. There doesn't seem to be a proper indicator for when a worker is ready to be used, vs still communicating preliminary data.

**Comment by dthain** [comment]
And then there is a second bug in that worker Y somehow does not detect that the transfer was bad.  It should know this primarily from the result of the transfer function, and secondarily b/c the size of the file doesn't match expectations.

**Comment by colinthomas-z80** [comment]
It would be nicer to detect and report the transfer was bad, but I think the cache invalid and task failure will happen either way.

**Comment by dthain** [comment]
So what **should** happen is that the transfer fails, resulting in a `cache-invalid` message, and then the worker notices that it cannot create the sandbox properly for the task and returns it with result `VINE_RESULT_INPUT_MISSING`.

But what Ben is reporting is that the task actually gets to the point of fork/exec, and then fails quickly with exit status zero.  So something else is going wrong...

**Comment by btovar** [comment]
I'm don't think the task gets to the exec part. As seen from the proxy.pem example, the task should be able to run without that file. Moreover, the resource summary does not produce a summary file to send back. The task fails with output missing, so I wonder if it fails somewhere after the fork but before the exec.

**Comment by dthain** [comment]
Good point.  If it ended up with "output missing" then it at least did a fork.
I don't think the `exec` per se is likely to fail, since it consists of `/bin/sh -c (command)`:
https://github.com/cooperative-computing-lab/cctools/blob/master/taskvine/src/worker/vine_process.c#L455

So either it's failing between fork and exec, or it's failing in the command script.

What exactly is the task command in this case?

**Comment by btovar** [comment]
It is a TaskVine.PythonTask, so it looks like `python some_wrapper`.   The python env comes from the factory.

**Comment by btovar** [comment]
Using #3511 I have not seen the errors when reusing workers.

**Comment by dthain** [comment]
fingers crossed!

**Comment by dthain** [comment]
Ok, I am able to isolate the output missing problem with the following program:

```port_file = None
try:
    port_file = sys.argv[1]
except IndexError:
    sys.stderr.write("Usage: {} PORTFILE\n".format(sys.argv[0]))
    raise


# Define a function to invoke remotely
def my_fun():
    print("the function")


# Create a new m
m = vine.Manager(port=[9123, 9130])
print("listening on port {}".format(m.port))
with open(port_file, "w") as f:
    f.write(str(m.port))

file = m.declare_url("worker://:0/stuff")

# Submit several tasks for execution:
print("submitting tasks...")
t = vine.PythonTask(my_fun)
t.add_input(file,"input.txt")
m.submit(t)

while not m.empty():
    t = m.wait(5)
    if t:
        if t.successful():
            print(t.output)
        else:
            print(f"Something went wrong with the task: {t.result}\nstdout: {t.std_output}")
```

**Comment by dthain** [comment]
The worker does the right thing it attempts to download the file, fails, and sends back a `cache-invalid` message.  Then, it can tell that the task cannot run, and returns it with an `INPUT_MISSING` status.  So far so good.

The problem is that the manager receives the result message but then proceeds to fetch the output files for the task.  And because the output files are not there, it concludes that the proper status is `OUTPUT MISSING`:

```
2023/09/22 14:12:34.28 vine_worker[339908] debug: ../src/worker/vine_worker version 8.0.0 DEVELOPMENT (released 2023-09-22 14:08:03 -0400)
2023/09/22 14:12:34.28 vine_worker[339908] debug: Built by dthain@cclws15.cse.nd.edu on 2023-09-22 14:08:03 -0400
2023/09/22 14:12:34.28 vine_worker[339908] debug: System: Linux cclws15.cse.nd.edu 4.18.0-477.21.1.el8_8.x86_64 #1 SMP Thu Jul 20 08:38:27 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
2023/09/22 14:12:34.28 vine_worker[339908] debug: Configuration:
vine_worker: creating workspace /tmp/worker-102744-339908
2023/09/22 14:12:34.36 vine_worker[339908] vine: VINE_SANDBOX set to /tmp/worker-102744-339908.
vine_worker: using 4 cores, 15610 MB memory, 39562 MB disk, 1 gpus
2023/09/22 14:12:34.37 vine_worker[339908] dns: looking up name localhost
2023/09/22 14:12:34.37 vine_worker[339908] dns: localhost is 127.0.0.1
2023/09/22 14:12:34.37 vine_worker[339908] tcp: connecting to 127.0.0.1 port 9123
2023/09/22 14:12:34.37 vine_worker[339908] tcp: made connection to 127.0.0.1 port 9123
connected to manager localhost:9123 via local address 127.0.0.1:57956
2023/09/22 14:12:34.37 vine_worker[339908] vine: connected to manager localhost:9123 via local address 127.0.0.1:57956
2023/09/22 14:12:34.37 vine_worker[339908] vine: preparing workspace /tmp/worker-102744-339908
2023/09/22 14:12:34.37 vine_worker[339908] tcp: listening on port 1024
2023/09/22 14:12:34.37 vine_worker[339908] vine: started transfer server pid 339912 listening on 0.0.0.0:1024
2023/09/22 14:12:34.37 vine_worker[339908] vine: loading cache at: /tmp/worker-102744-339908/cache
2023/09/22 14:12:34.37 vine_worker[339908] dns: looking up name cclws15.cse.nd.edu
2023/09/22 14:12:34.37 vine_worker[339908] dns: cclws15.cse.nd.edu is 129.74.155.71
2023/09/22 14:12:34.37 vine_worker[339908] dns: looking up addr 129.74.155.71
2023/09/22 14:12:34.37 vine_worker[339908] dns: 129.74.155.71 is cclws15.cse.nd.edu
2023/09/22 14:12:34.37 vine_worker[339908] dns: finding my hostname: uname = cclws15.cse.nd.edu, address = 129.74.155.71, hostname = cclws15.cse.nd.edu
2023/09/22 14:12:34.37 vine_worker[339908] vine: tx: taskvine 3 cclws15.cse.nd.edu Linux x86_64 8.0.0
2023/09/22 14:12:34.37 vine_worker[339908] vine: tx: info worker-id worker-96f868cbf9b7fa0da2a186f2b4ad5d75
2023/09/22 14:12:34.37 vine_worker[339908] vine: tx: feature NVIDIA%20RTX%20A2000
2023/09/22 14:12:34.37 vine_worker[339908] vine: tx: transfer-address 0.0.0.0 1024
2023/09/22 14:12:34.38 vine_worker[339908] vine: tx: info worker-end-time 0
2023/09/22 14:12:34.38 vine_worker[339908] vine: tx: alive
2023/09/22 14:12:34.38 vine_worker[339908] vine: Sending resource description to manager:
2023/09/22 14:12:34.38 vine_worker[339908] vine:  workers      0 inuse      1 total
2023/09/22 14:12:34.38 vine_worker[339908] vine:     disk      0 inuse  39562 total
2023/09/22 14:12:34.38 vine_worker[339908] vine:   memory      0 inuse  15610 total
2023/09/22 14:12:34.38 vine_worker[339908] vine:     gpus      0 inuse      1 total
2023/09/22 14:12:34.38 vine_worker[339908] vine:    cores      0 inuse      4 total
2023/09/22 14:12:34.38 vine_worker[339908] vine: tx: info end_of_resource_update 0
2023/09/22 14:12:34.38 vine_worker[339908] vine: tx: info tasks_running 0
2023/09/22 14:12:34.38 vine_worker[339908] vine: working for manager at 127.0.0.1:9123.
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: puturl worker://:0/stuff url-rnd-khjmnhflsfajagh 0 777 F0C6B207-0150-448E-B5E9-60DDDD0C5B89
2023/09/22 14:12:34.38 vine_worker[339908] vine: Insert ID-File pair into transfer table : url-rnd-khjmnhflsfajagh :: F0C6B207-0150-448E-B5E9-60DDDD0C5B89
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: file file-meta-82bbeee2e7d57fbd98323abeb259b0b5 624 0644
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: file file-meta-d79385903990390b3b24b4cc52cf984c 699 0644
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: file file-meta-a805441f0f0b71ca196839130690f097 19 0644
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: task 1
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: cmd 250
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: python3 pytask_wrapper_86f9e20a-b18e-4463-9f9d-9490194f19c9.py function_86f9e20a-b18e-4463-9f9d-9490194f19c9.p args_86f9e20a-b18e-4463-9f9d-9490194f19c9.p out_86f9e20a-b18e-4463-9f9d-9490194f19c9.p > stdout_86f9e20a-b18e-4463-9f9d-9490194f19c9.p 2>&1
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: category default
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: cores 4.000
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: gpus 0
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: memory 15610
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: disk 39562
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: infile url-rnd-khjmnhflsfajagh input.txt 0
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: infile file-meta-82bbeee2e7d57fbd98323abeb259b0b5 pytask_wrapper_86f9e20a-b18e-4463-9f9d-9490194f19c9.py 0
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: infile file-meta-d79385903990390b3b24b4cc52cf984c function_86f9e20a-b18e-4463-9f9d-9490194f19c9.p 0
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: infile file-meta-a805441f0f0b71ca196839130690f097 args_86f9e20a-b18e-4463-9f9d-9490194f19c9.p 0
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: outfile file-rnd-qkyjbxoyxcczpqe stdout_86f9e20a-b18e-4463-9f9d-9490194f19c9.p 0
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: outfile file-rnd-umzcewvmhyphabz out_86f9e20a-b18e-4463-9f9d-9490194f19c9.p 0
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: end
2023/09/22 14:12:34.38 vine_worker[339908] vine: forking transfer process to create url-rnd-khjmnhflsfajagh
2023/09/22 14:12:34.38 vine_worker[339908] vine: cache: transferring worker://:0/stuff to url-rnd-khjmnhflsfajagh
2023/09/22 14:12:34.38 vine_worker[339913] vine: Setting up worker transfer file worker://:0/stuff
2023/09/22 14:12:34.38 vine_worker[339913] vine: An error occured when creating url-rnd-khjmnhflsfajagh via mini task: Could not establish connection with worker at: %d
:543519744
2023/09/22 14:12:34.38 vine_worker[339908] vine: transfer process for url-rnd-khjmnhflsfajagh (pid 339913) exited normally with exit code 1
2023/09/22 14:12:34.38 vine_worker[339908] vine: transfer process for url-rnd-khjmnhflsfajagh failed
2023/09/22 14:12:34.38 vine_worker[339908] vine: cache: unable to create url-rnd-khjmnhflsfajagh
2023/09/22 14:12:34.38 vine_worker[339908] vine: Sending Cache invalid transfer id: F0C6B207-0150-448E-B5E9-60DDDD0C5B89
2023/09/22 14:12:34.38 vine_worker[339908] vine: tx: cache-invalid url-rnd-khjmnhflsfajagh 30 F0C6B207-0150-448E-B5E9-60DDDD0C5B89
2023/09/22 14:12:34.38 vine_worker[339908] vine: input: url-rnd-khjmnhflsfajagh is not ready in the cache!
2023/09/22 14:12:34.38 vine_worker[339908] vine: tx: info tasks_running 0
2023/09/22 14:12:34.38 vine_worker[339908] vine: tx: available_results
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: send_results -1
2023/09/22 14:12:34.38 vine_worker[339908] vine: tx: result 1 1 0 1695406354381880 1695406354381880 1
2023/09/22 14:12:34.38 vine_worker[339908] vine: tx: info tasks_running 0
2023/09/22 14:12:34.38 vine_worker[339908] vine: tx: end
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: get file-rnd-qkyjbxoyxcczpqe
2023/09/22 14:12:34.38 vine_worker[339908] vine: tx: error file-rnd-qkyjbxoyxcczpqe 2
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: get file-rnd-umzcewvmhyphabz
2023/09/22 14:12:34.38 vine_worker[339908] vine: tx: error file-rnd-umzcewvmhyphabz 2
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: kill 1
2023/09/22 14:12:34.38 vine_worker[339908] wq: trashing file /tmp/worker-102744-339908/task.1 to /tmp/worker-102744-339908/trash/cwefcrc.1695406354382410
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: unlink url-rnd-khjmnhflsfajagh
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: unlink file-meta-82bbeee2e7d57fbd98323abeb259b0b5
2023/09/22 14:12:34.38 vine_worker[339908] wq: trashing file /tmp/worker-102744-339908/cache/file-meta-82bbeee2e7d57fbd98323abeb259b0b5 to /tmp/worker-102744-339908/trash/cqxbacp.1695406354382568
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: unlink file-meta-d79385903990390b3b24b4cc52cf984c
2023/09/22 14:12:34.38 vine_worker[339908] wq: trashing file /tmp/worker-102744-339908/cache/file-meta-d79385903990390b3b24b4cc52cf984c to /tmp/worker-102744-339908/trash/stvicnr.1695406354382632
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: unlink file-meta-a805441f0f0b71ca196839130690f097
2023/09/22 14:12:34.38 vine_worker[339908] wq: trashing file /tmp/worker-102744-339908/cache/file-meta-a805441f0f0b71ca196839130690f097 to /tmp/worker-102744-339908/trash/mgkhzxj.1695406354382693
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: unlink file-rnd-qkyjbxoyxcczpqe
2023/09/22 14:12:34.38 vine_worker[339908] vine: rx: unlink file-rnd-umzcewvmhyphabz
```

**Comment by btovar** [comment]
Nice!

**Comment by dthain** [comment]
See #3514 for the output missing problem.

**Comment by dthain** [comment]
Ok, let's circle back on Monday to evaluate if this one is solved.

**Comment by dthain** [comment]
@btovar @colinthomas-z80 are you satisfied that this problem is solved?
