### ISSUE TITLE
vine: recovery tasks are created incorrectly

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3512]
In some cases recovery tasks do not seem to be created and this causes segfaults. Looking at the gdb backtrace of those tasks:

```json
{task_id = 13519, type = VINE_TASK_TYPE_STANDARD, command_line = 0x0, tag = 0x0, category ...
```

Note that the type should be RECOVERY (STANDARD is 0 in the enum). The task does not have a command, nor a mount lists (which is what causes the segfault when checking for consistency).

**Comment by btovar** [comment]
Issue seems related to tmp files that are lost twice, i.e., lost again once the recovery task ran.

**Comment by btovar** [comment]
It seems the recovery tasks are deleted unconditionally once ran (which seems ok), but they are not recreated.

**Comment by btovar** [comment]
I think it just needs a t->recovery_task = NULL; after the task is deleted. Let me try that.

**Comment by btovar** [comment]
The task does not know its 'parent' file, that might be a complication.

**Comment by btovar** [comment]
I'll try with a vine_task_reset instead.

**Comment by dthain** [comment]
Actually, I think it's the other way around.
The file object contains a single `file->recovery_task`.
If it is needed, it is submitted.
When done, I think we want it left in place, so it can be submitted again if needed.
So either we *shouldn't* delete it when done, or we should add a reference on submission.

**Comment by btovar** [comment]
I think you are right, does the vine_task_reset make sense to you then?

**Comment by dthain** [comment]
See `vine_manager_consider_recovery_task`

**Comment by btovar** [comment]
Oh I see, we just shouldn't delete it, now I get it, I think.
