### ISSUE TITLE
vine: vine_status cannot connect directly to a manager

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3520]
When I try:   `vine_status -dall 127.0.0.1`  I get:

```
2023/09/27 07:49:09.57 vine_status[676732] tcp: connecting to 127.0.0.1 port 9123
2023/09/27 07:49:09.57 vine_status[676732] tcp: made connection to 127.0.0.1 port 9123
couldn't read from 127.0.0.1 port 9123: Resource temporarily unavailable
zsh: exit 1     vine_status -dall 127.0.0.1 9123
```

and in the transactions log:

```
1695815465232306 665381 WORKER (null) DISCONNECTION FAILURE
```

Thus, I think it is not a network or firewall issue, as the worker does seem to connect to the manager.  The `vine_status` status command fails immediately.

**Comment by dthain** [comment]
@colinthomas-z80 please take a look at this one, hopefully you can reproduce with a simple test program.

`vine_status` should be sending a `worker_status` line to the manager, causing it to send back a data dump.
]

**Comment by btovar** [comment]
Actually the -W (worker_status) works.  It is that it is sending queue_status when the manager expects manager_status.

**Comment by dthain** [comment]
Easy fix then
