### ISSUE TITLE
Task with command containing "&>" redirection operator sometimes fails

### ISSUE THREAD

**Issue by leeping** [cooperative-computing-lab/cctools#3524]
Hello there,

My grad student (@hjnpark) and I have run into an issue where a Work Queue task can fail if it includes the `&>` operator.  An example of the problematic task is the command:

```qchem run.in run.out &> run.log```

where the expected input file is `run.in` and the expected output files to be returned to the master are `run.out` and `run.log`.  The expected behavior is that the application (`qchem`) should produce the output file, `run.out`, and both stdout and stderr should be redirected to `run.log`.  

Instead, what we observed was that `run.log` was empty and `run.out` was not produced at all.  This happens despite the fact that the `qchem` executable is in the PATH, and the `run.in` file is being properly uploaded and is present in the worker's temporary folder.  I expected there to be some content to `run.log` (such as `qchem: Command not found`) but there seemed to be nothing captured from stdout/stderr; the file size was 0 bytes.  The process completed with an exit code of 0, but because the expected output file was not present, the task did not complete successfully.  A snippet of the worker debug output is attached.

To rule out other common problems, we are able to run the task on the command line normally (i.e. outside of Work Queue), and we were also observing this issue with applications other than `qchem`, so I don't think it's an issue specific to the application.

To work around the issue, we replaced the command with this:

```qchem run.in run.out > stdout.tmp 2> stderr.tmp ; cat stdout.tmp stderr.tmp > run.log```

This task completed in the expected way.

What puzzles me is that this task is one we have used routinely with Work Queue for years, and we saw experienced this issue just yesterday on one workstation.  The workstation experiencing the issue was running Ubuntu 20.04.4 LTS, Python 3.11.5 and ndcctools 7.6.1.  I failed to reproduce the issue on a different workstation running Ubuntu 20.04.5 LTS, Python 3.9.18 and ndcctools 7.6.1.  My hunch is the small version differences are not causing the issue and it's something else.

If needed, we can make a minimal test case to reproduce the problem.  Please let me know.

As always, thank you for your help and for providing such a useful tool! :) 

- Lee-Ping

[work_queue_worker_debug.txt](https://github.com/cooperative-computing-lab/cctools/files/12775382/work_queue_worker_debug.txt)

**Comment by btovar** [comment]
Hi Lee-Ping!

The reason is that Work Queue executes commands with /bin/sh and &> is a
/bin/bash extension. bash is a superset of sh, so most linux distributions
actually use bash when using sh commands. One exception is debian-based
distributions (like ubuntu) which use /bin/dash. dash does not implement
these bash extensions and that's why the command fails in that workstation.

Our recommendation would be exactly what you have already tried, which is
to redirect stdout and then stderr. This is the way sh expects things to be
executed.

Please let us know if we can help you with anything else!

Ben

**Comment by leeping** [comment]
Hello Ben,

Ah, thanks!  Indeed, the problem was that I had changed my /bin/sh to bash using `dpkg-reconfigure dash`, but that wasn't done on my student's workstation.  My mistake was assuming that /bin/sh is the default shell that is used when a new terminal is opened; now I know they can be different.

- Lee-Ping
