### ISSUE TITLE
Vine: Plot Colors Option

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3532]
@JinZhou5042 we want to be able to put these graphs side-by-side in a paper to compare the behavior of Dask and TaskVine:
![Dask Graph](https://github.com/cooperative-computing-lab/cctools/assets/2752914/9fdc34f1-e710-4dd7-bfa0-fa9057b371d3)
![TaskVine Graph](https://github.com/cooperative-computing-lab/cctools/assets/2752914/d80ca2de-4df0-4063-bf35-1ff0a0092c2e)

Please add an option like `--dask-colors` to `vine_plot_txn_log` so that it produces a graph where the colors etc look similar to that of Dask.  It doesn't have to be absolutely identical, just follow the same conventions so that it is easy for the reader to compare and understand them side by side.  Check with @BarrySlyDelgado for some sample data.

**Comment by JinZhou5042** [comment]
Sure, I will handle this and talk with Barry soon!
