### ISSUE TITLE
Vine: Performance Suffered with Large Amount of Workers

### ISSUE THREAD

**Issue by JinZhou5042** [cooperative-computing-lab/cctools#3533]
In this particular example, I submitted 100,000 tasks with 1,000 workers and measured how the number of workers changes in the process of running my application and completing tasks separately.

The following figure shows Condor has approved my 1,000 workers request:
![Screenshot from 2023-10-05 16-41-39](https://github.com/cooperative-computing-lab/cctools/assets/142265839/dec306ef-2947-4e34-9c82-c9c2adfca194)
![Screenshot from 2023-10-05 16-46-17](https://github.com/cooperative-computing-lab/cctools/assets/142265839/19b09c71-69f1-410b-a6c3-43c47f82ed72)

But as my application runs, the number of connected workers suffered a significant drop, hundreds of workers kept idle in the first stage then lost connection to the manager. And the total connected workers are much less than what I submitted to Condor and what the Condor tell me.
![Screenshot from 2023-10-05 16-51-41](https://github.com/cooperative-computing-lab/cctools/assets/142265839/ddfbbe1f-8806-4020-9ced-53f78ab403c8)
The left figure shows the exact number of busy workers and idle workers as time the application runs, while the right figure demonstrates how many workers are busy or idle as my tasks done, the red part and the grey part make up as the total connected workers.

**Comment by JinZhou5042** [comment]
Here is another try:
![100000tasks_487workers](https://github.com/cooperative-computing-lab/cctools/assets/142265839/07dbfce4-130f-41eb-867a-4c6aa04fc85e)

**Comment by JinZhou5042** [comment]
Ideally, I can successfully connect 1,000 workers at the very beginning, each worker will be assigned approximately 100 tasks in the whole process. I am looking into the code to find some clues.

**Comment by dthain** [comment]
Keep in mind that workers have a built-in `--idle-timeout` (default 15 mins) that causes them to exit if they do not receive any task from the manager.  (This is to avoid wasting resources). It seems pretty clear from your graphs that 300 or so workers are giving up and disconnecting b/c the manager isn't giving them work to do.  So, that aspect of the system is working as designed.

Now, *why* isn't the manager keeping them busy?  There are two main possibilities:
1 - The manager is fully occupied sending/retrieving data and tasks from the workers.  That could be the case if the tasks are short running and/or have large inputs/outputs.
2 - The tasks to be run don't fit those workers.  That could happen if, for example, the tasks require 8 cores but the workers only have 4 cores.

**Comment by dthain** [comment]
@JinZhou5042 is this still a known problem, or has it been handled by other issues and fixes.

**Comment by JinZhou5042** [comment]
I think just as you mentioned, this might not be an `issue` or `flaw` and is something innocuous on TaskVine. It is the manager's insufficient capability to corporate with a large number of workers if those tasks are really short. 

For this posted figure:
<img width="422" alt="image" src="https://github.com/cooperative-computing-lab/cctools/assets/142265839/ad48763a-62e7-4535-9712-3ab592b31c72">

It's like the manager has always been going to great lengths to assign tasks to around 100 workers, bringing back their results and re-assign tasks to those already connected workers. It has no more idle slots to corporate with additional workers.

**Comment by dthain** [comment]
Ok, go ahead and close it out..
