### ISSUE TITLE
vine: dispatching of libraries does not behave as dispatching of tasks

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3534]
When the internal wait reaches `vine_manager_send_libraries_to_workers` then all the libraries are sent to all the workers until the timeout is reached. This breaks the rest of the logic of the internal wait, as for example, it only dispatches one regular task at a time. Is this behavior intended? It seems to break the manager capacity, e.g., the manager does not have a chance to overlap the execution of functions and the dispatch of libraries. It seems that it would be more efficient to dispatch a library and continue on the top of the loop to try and dispatch as many functions as we can.

The current implementation seems to correspond to the aggressive prefer-dispatch batch mode.  However, wait internal was designed to be as interactive as possible (i.e., return a task as soon as one is available).

**Comment by dthain** [comment]
@tphung3 what do you think?

**Comment by btovar** [comment]
From the comment in #3535, the current behavior also breaks the assumption that delivering libraries has the lowest scheduling priority and may lead to undesirable behavior. E.g., at the ramp-down if there are no more ready tasks, the loop will send libraries to newly connected workers instead of preferring to retrieve the few tasks remaining. (It takes just one iteration of the loop where nothing happens for the dispatching of libraries to take over.) The current behavior seem to make sense for long running homogeneous loads using a stable set of workers.

**Comment by tphung3** [comment]
> Is this behavior intended?

No it's only there so I don't have to think about how to send libraries :)
I agree that we can improve the current way to send libraries. I think if we can set up library task by binding them as a minitask then most potential issues above would go away (send library only when there's a function to be sent, multiple functions can share the same lib task). New feature to be added later? @dthain

**Comment by dthain** [comment]
Solved in #3591
