### ISSUE TITLE
vine: library management

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3535]
The current library dispatch prefers to send libraries one by one to all the workers. I wonder if this can cause some deadlocks where the resources of all workers are committed to one library, and functions of a second library (or regular tasks for that matter) can never be executed.

Should only one library be allowed per manager? (This would be the typical use, anyway, I think.)

**Comment by dthain** [comment]
At the moment, the manager strives to launch one library (of each installed type) per worker as the lowest priority scheduling activity.  And the library consumes whatever resources that the user declares.  Max of one library type per worker.

Agreed that this will cause trouble if the user has multiple kinds of libraries, or the load is changing.
 
A more sophisticated approach would be to deploy libraries sufficient to satisfy the offered load of functions, with some hysteresis.

**Comment by dthain** [comment]
Addressed by #3591
