### ISSUE TITLE
Vine: Store Metadata With Cached Files

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3557]
Currently, the `vine_cache` object in the manager stores the contents of each file in a name computed from the contents, and nothing else.  On a reboot, `vine_cache_load` scans the `cache` directory to load all the objects from disk.  Fine so far.  However, the cache module also keeps track of some metadata about each file (modification time, transfer time, type, etc) that gets lost when the worker exits and restarts.

So: Modify the `vine_cache` module in the worker to store metadata in JSON format in a file along side each stored object.  Write this metadata out when a file is added, and read it back in when scanning the cache directory in startup.  Use tyhe`jx` library to construct and parse JSON.

So for example, if there exists a file like `cache/abc1234` then it should have alongside it `cache/abc1234.meta` with contents something like: `{ "size" : 4050, "mtime" : 1234578, "transfer_time", 35, "checksum" : "abc1234", "source" : "http://....tar.gz" }`

Once this is in place, then we may start adding further details to track.

**Comment by btovar** [comment]
Probably #3558 is an instance of this.

**Comment by dthain** [comment]
PR #3655
