### ISSUE TITLE
TaskVine: Changes to resource monitor with large number of tasks.

### ISSUE THREAD

**Issue by BarrySlyDelgado** [cooperative-computing-lab/cctools#3558]
I've run across an issue where a warning will be frequently outputted stating that there have been changes to the resource monitor during workflows with a large number of tasks. It does not seem to affect the result of the workflow itself but could be representative of an underlying issue within TaskVine.

**Comment by dthain** [comment]
Please post the details showing the exact text of the warning, and the conditions that provoke it...

**Comment by BarrySlyDelgado** [comment]
I failed to take a screenshot when I first encountered this issue. I'll post the exact text was it pops back up. However, it likely occurs when a worker is removed and then returns.

**Comment by dthain** [comment]
Not enough information to make this actionable...
