### ISSUE TITLE
Vine: Serverless Preamble with Imports

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3559]
Currently, to set up a serverless library in taskvine, one does this:
```
lib = create_library_from_functions("libname",f,g,h)
```

And then `f`, `g`, and `h` can be invoked by creating tasks like this:
```
t = FunctionCall("lib name","f",args);
```

This all works fine, except that if each function needs to import some heavy libraries (such as `numpy`) then the import occurs in each individual function (repeatedly) rather than in the parent process once.

To improve this, modify things so that you can pass a list of functions to the library creation routine:

```
lib = create_library_from_functions("libname",f,g,h,imports=["numpy","tensor flow"])
```

And then insert those as `import` statements into the preamble of the serverless library.  This should have a significant impact on the startup of individual functions that use large libraries.

**Comment by dthain** [comment]
@tphung3 @BarrySlyDelgado what do you think?

**Comment by tphung3** [comment]
That sounds doable. I think poncho automates this by scanning import stmts from function ASTs, but it is probably a good first issue.

**Comment by BarrySlyDelgado** [comment]
This should work. should probably also include things like import `x as y`

**Comment by dthain** [comment]
Look in `poncho/src` for `package_serverize` and `library_network_code.py`

**Comment by dthain** [comment]
And then modify `taskvine/test/vine_python_serverless.py` to test your work.

**Comment by JinZhou5042** [comment]
![ff23aa3d22b942eabcfddc0838ebbebb_0](https://github.com/cooperative-computing-lab/cctools/assets/142265839/2e34a755-55fd-45a6-9008-2da0171df90c)
![bda8eec6986a9c6d27c03eea0baeaa58_0](https://github.com/cooperative-computing-lab/cctools/assets/142265839/e8e2d11c-7f4a-4030-beb1-382d03cd8ee5)

**Comment by JinZhou5042** [comment]
How can we create a DAG-based FunctionCall task in TaskVine?
The basic pratice in`cctools/taskvine/src/examples/vine_example_function_call.py` looks like this:

```python
# create library
libtask = q.create_library_from_functions('test-library', divide, double)
q.install_library(libtask)

# submit tasks one by one
tasks = 100
for i in range(0, tasks): 
    s_task = vine.FunctionCall('test-library', 'divide', 2, 2**2)
    q.submit(s_task)
    s_task = vine.FunctionCall('test-library', 'double', 3)
    q.submit(s_task)

# run tasks one by one
total_sum = 0
x = 0
while not q.empty():
    t = q.wait(5)
    if t:
        x = t.output 
        total_sum += x
        print(f"task {t.id} completed with result {x}")

```

This will execute `divide(2, 2**2)` and `double(3)` for 100 times. The arguments are pure integers so it makes sense to me. 
But if I want to submit some tasks in which the input arguments are based on the other tasks' outputs? This is something like `divide(double(3), divide(2**double(5)))`, which is a DAG-based task in a high level.
Could anyone give me some suggestions?

**Comment by dthain** [comment]
If using plain tasks, then you must wait for one task to complete, then submit the next task.

Or use Futures:
https://cctools.readthedocs.io/en/stable/taskvine/#futures

**Comment by BarrySlyDelgado** [comment]
There may be multiple ways to do it. The general idea is that the output of the function call should be a temp file and the subsequent tasks use that temp file as an input. You may want to look at `futures.py` which does this automatically and you may be able to incorporate it into the function call code.

**Comment by JinZhou5042** [comment]
Thanks for the information!

**Comment by JinZhou5042** [comment]
Assuming I have a simple function:
``` python
def double(x):
    return x * 2
```
Currently, here is the way to submit future tasks:
``` python
executor = vine.Executor(manager_name='m', port=9125)
a = executor.task(double, 4)
f1 = executor.submit(a)
b = executor.task(double, f1)
f2 = executor.submit(b)
print("result = ", f2.result())
```


The way to submit a function call using `Executor` is:
``` python
executor = vine.Executor(manager_name='m', port=9125)
libtask = executor.manager.create_library_from_functions('lib', double, add_env=False)
executor.manager.install_library(libtask)

fc = vine.FunctionCall('lib', 'double', 2)
executor.manager.submit(fc)

while not executor.manager.empty():
    t = executor.manager.wait(5)
    if t:
        print(f"task {t.id} completed with result {t.output}")
```


Now I want to submit a **future function call** via `Executor`, do I need to change its implementation so that I can use something like this:
``` python
fc = vine.FunctionCall('lib', 'double', 2)
executor.submit(fc)
print("result = ", fc.result)
```
Is there any other methods to achieve this goal?

**Comment by BarrySlyDelgado** [comment]
Yes, I think you would need to change the implementation. You would probably get some unexpected results if you tried that now. For that example to work, I think you would need to convert the function call to a future.

**Comment by dthain** [comment]
Keep in mind that the chaining of function calls is for many applications provided by the layer above (Dask or Parsl), so we don't have to solve that problem.  What we need right now is `import` statements moved to the serverless preamble, as described above.

**Comment by JinZhou5042** [comment]
The reason I asked this was our example was tested on Dask and DaskVine, they were good to build a DAG-based application, but TaskVine fails to do this because it can't use a future function call that uses the library we have already installed on the manager. Does it mean I can forget our matrix multiplication example (or any DAG-based examples) for now and only focus on the `import` statements?

**Comment by dthain** [comment]
Please work on the `import` problem.  You are welcome to look at chained functions afterwards...

**Comment by JinZhou5042** [comment]
OK, that would be great!

**Comment by JinZhou5042** [comment]
The previous practice to install a library in which a function uses `numpy` was like:
``` python
def func():
    import numpy
    # ......
```
After using the new parameter `imports` to create a library: `lib = create_library_from_functions("libname",f,g,h, imports=['numpy'])`, that function can be written without `import` statements:
``` python
def func():
    # ......
```
The arguments should be formatted as:
```
imports = {
    'numpy': 'np',  # import numpy as np
    'sys': ['path', 'argv'],  # from sys import path, argv
    'os': {'environ': 'env', 'path': 'os_path'},  # from os import environ as env, path as os_path
    'tensorflow: ['*']  # from tensorflow import *
}
```
This is what I understand right now and what I have completed, but seems that the 'import' statements don't really take much time, usually on tens of microseconds.

**Comment by dthain** [comment]
#3567
