### ISSUE TITLE
Vine: Crash on Empty Output Mount List

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3566]
As @jdolak discovered, the vine worker crashes when you have a task that declares no output files.
This is unusual, but unfortunately happens in the quickstart example  (sigh).

The problem is that in several places, we iterate over `t->output_mounts` without checking to see if it exists.  (The list is not created until an output mount is added.)  So, any use of `t->output_mounts` should be protected with a null check.

Note, for example, how **input_mounts** is protected before use here:
https://github.com/cooperative-computing-lab/cctools/blob/05d31a9cb5ed77af37d0c6e8b0136fd81b0e94c4/taskvine/src/worker/vine_sandbox.c#L40

**Comment by btovar** [comment]
We could simply create the empty list when creating the task.  This eliminates the errors where we forget to check if it exists, and for most tasks it will be created anyway.

**Comment by dthain** [comment]
Sure, that's a good solution too.  @jdolak its up to you, but fix quickly, this is high priority.

**Comment by jdolak** [comment]
@dthain I was unable to reproduce the issue on Thomas's environment so it may be something with my environment causing the segfault. Should I still implement a fix for `t->output_mounts` anyway?

**Comment by dthain** [comment]
Hmm, something else may be going on.  Whenever you encounter pointer problems, then you should immediately turn to valgrind, run it on the worker just like this:
```
valgrind --leak-check=full -- vine_worker . . .
```
And it should let you know where the problem is.
It's possible there is more than one bug!

**Comment by btovar** [comment]
See https://github.com/cooperative-computing-lab/cctools/blob/05d31a9cb5ed77af37d0c6e8b0136fd81b0e94c4/taskvine/src/manager/vine_task.c#L50

It seems like the output mount list is always created.

**Comment by btovar** [comment]
Segfaults may occur when changing the .h file but not performing a make clean (i.e. the .h and .o are out of sync).  If so, technically this would be a bug in the makefile.

**Comment by dthain** [comment]
Seems like this problem was due to an inconsistent installation.
