### ISSUE TITLE
Vine: Generalize Futures to FunctionCall Tasks

### ISSUE THREAD

**Issue by JinZhou5042** [cooperative-computing-lab/cctools#3568]
Currently, by using the serverless feature we can easily install a library on TaskVine and invoke functions in it whenever we need:
```python
def divide(dividend, divisor):
    import math
    return dividend / math.sqrt(divisor)

libtask = q.create_library_from_functions('test-library', divide)
s_task = vine.FunctionCall('test-library', 'divide', 2, 2**2)
q.submit(s_task)
```

We can also create a future function call in which the input arguments depend on the previously ones' outputs:
```python
def my_sum(x, y, negate=False):
    from operator import add, mul

    f = 1
    if negate:
        f = -1
    s = mul(f, add(x, y))
    return s

t1 = executor.task(my_sum, 3, 4)
t2 = executor.task(my_sum, 2, 5)
a = executor.submit(t1)
b = executor.submit(t2)
t3 = executor.task(my_sum, a, b)
c = executor.submit(t3)
```

I think it would be more helpful if we could integrate future function calls into the library (or implement a combination of both), utilizing both features for enhanced usability.

**Comment by dthain** [comment]
This is a good idea, and the way to go is to change FutureTask so that it is not an extension of PythonTask, but rather is constructed with a pointer to either a FunctionCallTask or a PythonTask and forwards its methods as appropriate.
