### ISSUE TITLE
Vine: vine_remove_file semantics and implementation

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3576]
A call to `vine_remove_file` resets tasks that use the file to `VINE_TASK_READY`, and then deletes it from the manager's file table. This could lead to hard to debug bugs as cache names may not be generated in the same way (e.g., if a local file changed in some way). Also, it makes the application responsible to manage the cached files currently needed, and those that can be deleted.

I propose for `vine_remove_file` only to remove the file (from both the workers and the file table) only if its reference count is less than 2.  As tasks are marked as DONE and their structure deleted, when no task references a cached file, its refcount should be 1. With this change, the part of resetting the tasks shouldn't be needed anymore.

**Comment by dthain** [comment]
Yes, I like this line of thinking.  `vine_remove_file` really is an indication from the user that they don't intend to use the file again.  And so we should mark it as such and then destroy when safe.

Now, it may be worthwhile to distinguish between refcounts for the sake of memory management (e.g. it is safe to delete the file object in memory when nothing points to it) and refcounting for the sake of removing the remote replicas.  I could easily imagine a situation where there are multiple pointers to the file object in memory, but all of them from replicas that we don't need any more.

**Comment by dthain** [comment]
@colinthomas-z80 you might be interested in this.

**Comment by dthain** [comment]
Thinking about this a little more...

My previous comment was at least partially wrong.  A file cannot be used (at least in the application) beyond the call to `remove_file`, since that is the closing-brace to `declare_file`.  (And so it should perhaps be called `undeclare_file`.

**Comment by dthain** [comment]
After tinkering around with the implementation, I decided this was way too complicated b/c it involved a number of expensive checks for who is using what.  We want `remove-file` to be inexpensive so that it can be called frequently.

**Comment by dthain** [comment]
This is adequately addressed by #3637.
