### ISSUE TITLE
vine: possible scheduling issue using function calls in TaskVine

### ISSUE THREAD

**Issue by BarrySlyDelgado** [cooperative-computing-lab/cctools#3595]
I've done some investigation in regard to scheduling function calls using TaskVine. This stated with some weird graph outputs for workflows that use function calls as seen below:
[tt5.pdf](https://github.com/cooperative-computing-lab/cctools/files/13719569/tt5.pdf)

In the workflow each worker receives a library that has 8 function slots. However, the graph shows that a worker is receiving more than 8 functions calls simultaneously.

Initially, I think this could be due to an error with my plotting setup, however I think there may be a different bug. I inserted print statements in the manager any time we commit a function call to the worker and any time we receive a function call from the worker. To show this issue, lets look at this screenshot:
![Screenshot from 2023-12-19 14-33-15](https://github.com/cooperative-computing-lab/cctools/assets/25990259/85b88e04-92f7-437b-8219-b34af55a2fa7)
From the screenshot, we can see that function calls 464 and 432 are committed to the library with the id 462.
This Library exists on the worker with id worker-e8f2721fae427c536121cb0eebcbedf7
![Screenshot from 2023-12-19 14-37-05](https://github.com/cooperative-computing-lab/cctools/assets/25990259/3bd51214-2143-4a86-9167-7cfffa2909cb)

However, from the transaction log, function call 464 runs on worker with id worker-2b3136addd1e698d9e562f32dbf8d655
![Screenshot from 2023-12-19 14-40-08](https://github.com/cooperative-computing-lab/cctools/assets/25990259/9168183f-01bb-4a32-940d-4d79b293d7ed)
This worker has the Library with task id 262
![Screenshot from 2023-12-19 14-43-01](https://github.com/cooperative-computing-lab/cctools/assets/25990259/d6c161f6-274c-44f6-8cea-f3bddc017f7a)

From parsing the Transaction log:
![Screenshot from 2023-12-19 14-46-41](https://github.com/cooperative-computing-lab/cctools/assets/25990259/6a0814e2-2f7c-4bdf-9d89-378d5ee5792d)
Workers seem to get more function calls than slots available at a time and the overall number of tasks are correct.

However, from parsing the output of the manager print statements.
![Screenshot from 2023-12-19 14-48-06](https://github.com/cooperative-computing-lab/cctools/assets/25990259/7c0c50fa-78ae-4c4e-a806-7f700f893ca2)
Each worker gets the correct amount of functions per slots available and total number of tasks are correct.
(In the Dictionary each key is the library id and the list contains the differential between tasks received and sent as the first element and the total number of tasks as the second element. 262 has 1 as the first element due to an error)

So, either tasks are being sent to a worker unintentionally causing more slots to be used OR we are not accounting correctly when writing to the transaction logs.

**Comment by dthain** [comment]
I think this is the problem:

`vine_schedule_by_files` (and others) rely upon `check_task_against_worker` to evaluate whether the two are compatible.  However, this also sets `t->library_task = w` if there is a match, assuming that a good match is the one actually used.  But is isn't!  Because we might, for example, be evaluating which worker has the most data available.

So here is what needs to happen: `check_task_against_worker` should check slots but *not* set t->library_task.

Wait until `commit_task_to_worker` to then select a library task on that worker with available slots, and set `t->library_task` there.

**Comment by BarrySlyDelgado** [comment]
Yep this fixes it!
[aa.pdf](https://github.com/cooperative-computing-lab/cctools/files/13720256/aa.pdf)
