### ISSUE TITLE
vine: dask outputs are deleted when tasks are garbaged collected.

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3603]
The good news is that garbage collection seems to be working. However, it breaks taskvine+dask as the output of tasks is deleted before it is loaded into memory.

With regular python tasks this is not a problem as they load the results as soon as a task returns. With dask the results are not immediately loaded, as often the only result needed is the one from the very last task executed.

I'm working on this one to have results ready for the upcoming deadline.

**Comment by BarrySlyDelgado** [comment]
Is this causing Connor's dv2_processor to fail?I've been having some failures when attempting to run.

**Comment by btovar** [comment]
This causes it to fail until the very end with a load() failing. Is that what you see?

**Comment by BarrySlyDelgado** [comment]
Workers were failing mid run for me.

**Comment by btovar** [comment]
That might be something else. My runs are ok, and this error is actually local to the manager.

**Comment by dthain** [comment]
Summarizing our discussion today:

Assumptions:
- `vine_file` and `vine_task` objects are correctly refcounted in the presence of recovery files.
- Python garbage collection correctly calls `vine_file_delete` and `vine_task_delete` as appropriate:

There is still a premature clean-up problem that occurs when a PythonTask (or any similar task) creates its own input files on the local filesystem, and then unlinks them when done:

**If the outputs are temporary files, the manager will (correctly) create a recovery task internally, which increases the refcount on the input files.  But then the PythonTask will delete the underlying file on the filesystem, even though the file is still needed internally.**

The solution is to instead give the problem of deleting the file to the`vine_task` object.  We need a flag indicating "clean up on delete" that will remove the underlying file only when the `vine_task` object is garbage collected.  Then, the PythonTask can simply create the file with this flag, and not worry about when to delete it.

Not sure what to call this capability.  Intermediate files?  Delete on close?  Automatic cleanup?

FYI @BarrySlyDelgado and @JinZhou5042

**Comment by dthain** [comment]
Fixed by #3612, we think.
