### ISSUE TITLE
Vine: Performance of Preamble Imports

### ISSUE THREAD

**Issue by JinZhou5042** [cooperative-computing-lab/cctools#3608]
I ran 10000 tasks on 16 workers, each with 4 cores and 4GB memory. One single task generates two 1000x1000 matrices and performs multiplication.

I ran multiple times either with or without import_modules, the execution time varied a lot even in the same condition.

I think the execution environment is unstable itself, therefore it's hard to visualize how this change impacts performance.

Without `import_modules`:

![txn](https://github.com/cooperative-computing-lab/cctools/assets/142265839/e961696f-d7e1-4fcf-9075-4103936f83dc)
![txn](https://github.com/cooperative-computing-lab/cctools/assets/142265839/540a6e47-c204-4e4f-8e67-3a7d8c56226c)

With `import_modules`:
![txn](https://github.com/cooperative-computing-lab/cctools/assets/142265839/b3f26af6-e3ef-4519-b607-5d5252a0e58e)

![txn](https://github.com/cooperative-computing-lab/cctools/assets/142265839/b57b5c9e-45a0-41b2-a902-3f8b0c8ea5d9)

**Comment by JinZhou5042** [comment]
Tasks are sparsely ran as the figure shows, some workers are filled with tasks during lifetime while some are keeping idle. Is network should be blamed for that?

**Comment by dthain** [comment]
@JinZhou5042 let's handle discussion of results and performance on Slack, since there are many knobs to turn here before we understand what's going on.

If there is something that is clearly a "bug", then file that as a GitHub issue.

**Comment by JinZhou5042** [comment]
Sure!
