### ISSUE TITLE
vine,wq factories in OSG need condor log in $HOME

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3615]
As reported by @nkremerh, when using the work queue factory on OSG:

ERROR: Failed to commit job submission into the queue.
ERROR: Job event logs produce by 'log =' in the submit file and the DAGMan nodes.log must be written inside your home directory as of February 7th, 2023.
2024/01/24 09:00:22.62 work_queue_factory[3340245] notice: couldn't open logfile condor.logfile: No such file or directory

This can be currently solved with --scratch-dir $HOME.  It is unclear if this is just particular to the OSG condor installation.
If this is a change in condor, then this breaks the factory in setups like AFS in Notre Dame, as the scratch directory cannot be at $HOME.

**Comment by dthain** [comment]
We have long had special features to deal with the peculiarities of AFS at Notre Dame.  I think that now this is a very peculiar setup, and we should have our system work by default for everyone else, and require a little more effort for running at ND.

Suggested solution:
- Make the default factory scratch directory in $HOME
- Add to the factory a quick check and warning for the combined case of HTCondor and AFS, much like we do for Makeflow:
https://github.com/cooperative-computing-lab/cctools/blob/365837e75a30aa9491ab054e033a569439716109/makeflow/src/makeflow.c#L2437
- Update our local instructions with appropriate configurations for our local HTCondor/AFS setup.

FYI @nkremerh

**Comment by dthain** [comment]
Fixed by #3630
