### ISSUE TITLE
Vine: Replicate to Count on Worker Failure

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3642]
Files of type `VINE_TEMP` are (by design) not returned to the manager, but maintained within the cluster.  This allows for acceleration of the workflow by avoiding data transfer.  Ff a worker crashes or is otherwise removed from the system, such files can be lost.

We currently address this as follows: When a `VINE_TEMP` file is created, the worker sends back a `cache-update` message to the manager, which then turns around and calls `replicate_temp_file` to create `n` additional copies of the file via `vine_manager_put_now`.  This is a good start, but now if there are further worker failures, the file could still be lost.

So, to make the feature complete, we need the following:
1 - Modify `replicate_temp_file` so that it finds a good replica of the given file, counts the total number of replicas, and then calls `vine_manager_put_url_now` to bring the total replica count up to the desired quantity.
2 - Call `replicate_temp_file` from both `handle_cache_update` and `remove_worker` so that on the loss of a worker, files of `VINE_TEMP` are replicated from other sources to bring it back up to `n` copies.

**Comment by btovar** [comment]
The more I think about it, I don't think this one is as easy and the more I like how @colinthomas-z80 implemented it. Kind of giving "lives" to what a task created, and rerun recovery tasks when those lives run out.

I'm worried about the case where a workflow loses a large number of workers. The remaining workers will scramble to make replicas which make fill their storage. I think we want to replace replicas only if some percentage of the distributed cache is free, but choosing what percentage seems hard.

Also, note that it won't be enough to add replication when a worker is lost. If at the time the worker is lost there is not good candidate to make a replica, then no replica will be created until a remaining replica is also lost, or the recovery task runs.

**Comment by dthain** [comment]
I agree that there is a danger here of what happens when we lose a large number of workers.  (And there may be other dangers as well.). But let's see what Chris comes up with.  And perhaps he can even demonstrate that particular hazard, which would be a nice result to show!  The counterweight may be to add some throttle to the rate of replica creation.

**Comment by dthain** [comment]
Fixed by #3744
