### ISSUE TITLE
vine: mount flags are not documented correctly

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3644]
In the comments at manager/taskvine.h we have:
```
@param flags May be zero or more @ref vine_mount_flags_t or'd together. See @ref vine_task_add_input.
```

Unfortunately, that line is also in the documentation of `vine_task_add_input`.

**Comment by EamonTracey** [comment]
@btovar Is the only documentation problem here that the docstring for `vine_task_add_input` references `vine_task_add_input` when it should reference `vine_task_add_output`?
