### ISSUE TITLE
Failure to run DaskVine examples

### ISSUE THREAD

**Issue by JinZhou5042** [cooperative-computing-lab/cctools#3666]
I am trying to build a DaskVine example for the doc, however failed to the existing examples under `cctools/taskvine/src/examples`.

The error messages for `vine_example_dask_awk_array.py`:
<img width="664" alt="image" src="https://github.com/cooperative-computing-lab/cctools/assets/142265839/2207d38b-a8ce-4225-b6d3-c21358117a76">

For `vine_example_dask_delayed.py`:
<img width="666" alt="image" src="https://github.com/cooperative-computing-lab/cctools/assets/142265839/d398540e-f76b-4889-b750-240aa8c9a762">

And for `vine_example_dask_graph.py`:
<img width="663" alt="image" src="https://github.com/cooperative-computing-lab/cctools/assets/142265839/c759e83c-ebfb-4fa0-9f65-b87ad394a637">

**Comment by JinZhou5042** [comment]
That was because I didn't install the needed packages. But for the `vine_example_dask_awk_array.py` example, after installing all the packages, the manager still keeps listening for workers on 9123, is there a certain reason for this? @btovar 
![Screenshot from 2024-02-21 15-44-59](https://github.com/cooperative-computing-lab/cctools/assets/142265839/a9fd0124-6286-4f0d-88a1-caa056bb6884)

**Comment by dthain** [comment]
Well, there could be a lot happening behind the scenes.
Suggest that you turn on `-d all` on the worker to see what's happening there.
And also tail the debug log at the manager.

**Comment by dthain** [comment]
So, to understand what's happening, you need to turn on some debug files one way or the other.
The Factory object just starts a `vine_factory` process which runs `vine_worker` processes.
I think all the log files are in `/tmp/vine-factory-something` by default.
If you give the factory the `--debug-workers` option, then all the workers will also produce debug logs...

**Comment by JinZhou5042** [comment]
I think I am close to it.
