### ISSUE TITLE
vine: temp file replica replacement

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3680]
When a worker with a temp file is lost, then the manager should check that the minimum of number of replicas is still met. (I.e., whatever we currently do that triggers a replica on a cache-update we should do for workers lost.)

Related to #3563, @colinthomas-z80

**Comment by colinthomas-z80** [comment]
This may be a duplicate of #3642

**Comment by btovar** [comment]
Duplicate of #3642
