### ISSUE TITLE
Landing Jobs in Machines that Have Python Installed

### ISSUE THREAD

**Issue by aniquaTabassum** [cooperative-computing-lab/cctools#3682]
Hello, I am using WorkQueue to submit a bunch of jobs in Condor. The only issue is, sometimes the machines where the jobs are landing does not have Python installed in them, and my jobs are failing. To be specific, I am getting this error:

`2024/02/29 00:59:26.38 makeflow[2464516] error: Task 1147 ran for a very short time and exited with code 127.
2024/02/29 00:59:26.38 makeflow[2464516] error: This usually means that the task's command could not be found, or that
2024/02/29 00:59:26.38 makeflow[2464516] error: it uses a shared library not available at the worker, or that
2024/02/29 00:59:26.38 makeflow[2464516] error: it uses a version of the glibc different than the one at the worker.
sh: python3: command not found`

Is it somehow possible to make sure that I am getting a machine that has python installed in it? Thank you.

**Comment by dthain** [comment]
Hello @aniquaTabassum let me suggest that you use [Poncho](https://cctools.readthedocs.io/en/stable/poncho) to deploy your desired python environment with each worker.  @BarrySlyDelgado can work with you on the details.

**Comment by BarrySlyDelgado** [comment]
Hello @aniquaTabassum, as @dthain suggested, using Poncho would ensure that Python is available on each worker.

Poncho is a toolkit that synthesizes and packages portable Conda environments.
I'd say the most straightforward way of getting Python on each worker is the following:
- createa local Conda environment that has Python
- create a Poncho tarball using `poncho_package_create`: `poncho_package_create <PATH_TO_CONDA_ENV> env.tar.gz`
- The environment can then deployed on each worker using the factory: `work_queue_factory -M <projectname> -T condor --poncho-env=env.tar.gz`

**Comment by aniquaTabassum** [comment]
Thank you so much, using Poncho solved my issue!

**Comment by BarrySlyDelgado** [comment]
Great to hear! Of note, any necessary libraries ( numpy, tensorflow, etc.) needed for your computation can be added to your Conda environment and packaged with Poncho for reference.
