### ISSUE TITLE
vine: think of policy for temp files when workers can't use peer transfer

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3693]
Currently the manager assumes that a temp file can be transferred between workers. If for some reason a worker can't do peer transfers, then the temp file can only be used by tasks that run on that worker. 

Some random ideas:

- Add a switch that kills a worker if it can't set peer transfers.
- Add an option for the manager to release workers that can't do peer transfers.
- Transform temp files into regular files if the worker can't support peer transfers.
- Use the manager as a third-copy route to transfer the temp file to the correct worker. This could be done asynchronously from the rest of the manager.

**Comment by dthain** [comment]
Merging into #3563
