### ISSUE TITLE
vine: add bookkeep information to current transfers

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3698]
When a transfer fails, there is not enough information to keep track of these failures. For example, we may want to release a source worker from which transfers have failed n number of times. At least we would like to avoid asking for the same transfers over and over again in a small time window.

However, currently there is not a relation between the source string in the transfer and the possible worker it uses. The source string has the peer transfer port, but there is not a mapping from a transfer port to the worker that hosts it.

@colinthomas-z80

**Comment by dthain** [comment]
Doesn't `vine_current_transfers` record an association between source, destination, and transfer ID?

**Comment by colinthomas-z80** [comment]
We would need to remap the ip+port back to a specific worker

**Comment by dthain** [comment]
Yep the worker table provides that map:
https://github.com/cooperative-computing-lab/cctools/blob/03bf6ad5efdcc4c69986a2f5275fae3cfc7f35c0/taskvine/src/manager/vine_manager.c#L864

**Comment by dthain** [comment]
No, I stand corrected: the worker table is keyed by the address of the `link` object.  `addrport` is a property, not the key.

**Comment by colinthomas-z80** [comment]
At least the recent hash_table_random_start should avoid any egregious scheduling to undesirable workers

**Comment by dthain** [comment]
This is now addressed by #3745 and several other PRs that track failed workers/files and avoid retrying too quickly.
