### ISSUE TITLE
vine: tasks with input peer transfers that failed should be retried

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3699]
When a task fails because the worker couldn't get an input file from another worker, the task is returned by `vine_wait` with an input missing code. However, this input missing is an internal transient issue from which taskvine may recover (e.g., if the source worker is in the process of disconnecting, the input file may be regenerated somewhere else).

Currently we don't have enough information to determine whether the task should be retried or returned. I was thinking that we if the state of the task is READY, an input missing error means that the task can be returned via wait. If the state is RUNNING, then the task should be retried. But the latter only works if all the transfers come from workers; if the transfer is an external url, we don't want the task to be retried forever.

Further, we don't want any retries to be done immediately. If a task needs to be retried, we can use `vine_task_set_time_start` to delay its reschedule (say 30s to 60s).

**Comment by dthain** [comment]
IMHO, the key is to distinguish between "couldn't transfer" (temporary) and "not present at all" (permanent).

The manager sets `INPUT_MISSING` if it tries to send an input file from the local filesystem, and it cannot open it.  (that seems like a permanent failure.)

But the worker also sets `INPUT_MISSING` if it cannot transfer a remote file to the local cache.  (that seems temporary to me.)

**Comment by btovar** [comment]
Perhaps we need a distinction? Like `XFER_MISSING` to be set by the worker?

**Comment by dthain** [comment]
I think so, although it gets tricky with things like http transfers.

**Comment by dthain** [comment]
This is the same problem as #3731
