### ISSUE TITLE
fatal: Expecting a filename for input file with two dash in the name

### ISSUE THREAD

**Issue by gerald2545** [cooperative-computing-lab/cctools#3700]
Hi
I'm using makeflow 7.7.2

I get an error : 
```
parsing Makeflow...
2024/03/08 17:49:07.08 makeflow[4029576] fatal: Expecting a filename. line: 1 column: 91
```
The line in the Makeflow file is : 
/work/user/ng6/jflow/work/addrun/wf000655/AddRawFiles_default/m64244_240218_084809_bc2083--bc2083_hifi_reads.count: /work/project/PlaGe/data/PacBio/sequel2/cromwell-executions/pb_demux_ccs/65f8322b-87e1-4258-9a9f-d347b521f3bb/call-auto_ccs_outputs_barcoded/execution/m64244_240218_084809_bc2083--bc2083_hifi_reads.fastq.gz /work/user/ng6/jflow/work/addrun/wf000655/.working/fa903baacb/_Stash/0/0/0/w0000000

If I manually execute each line of the Makeflow file, all is working fine

if I rename the file m64244_240218_084809_bc2083--bc2083_hifi_reads.fastq.gz to remove on dash in --, the makeflow runs fine!!

is it a normal behavior? the file with the double dash is generated by a software we can't modify.....

any idea to solve this problem is welcome ;)

thank you for your help

Gérald

**Comment by dthain** [comment]
Hello @gerald2545, thank you for the report. This is definitely not expected behavior. I can reproduce the bug, will get back to you with a solution soon.  Cheers, Doug

**Comment by dthain** [comment]
Hello @gerald2545 this is fixed in issue #3701.
If you are building Makeflow from source, you should be able to try it right away.
If you are deploying via Conda, we will make a new point release for you next week.
Please let use know if that solves your problem.

**Comment by gerald2545** [comment]
Thank you for your quick fix!!
tested and validated for my case!!

**Comment by dthain** [comment]
You are welcome, let us know if you have any other troubles.
