### ISSUE TITLE
vine: VINE_CACHE_LEVEL_FOREVER stay forever at a worker

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3711]
Once a file is marked VINE_CACHE_LEVEL_FOREVER, there is no mechanism to delete the file from the worker.  `vine_undeclare_file` explicitly skips over forever files: https://github.com/cooperative-computing-lab/cctools/blob/ebd317b7dbcc3a0247b0a280967271e54d038998/taskvine/src/manager/vine_manager.c#L5664

I propose to change `vine_undeclare_file` to delete files from the cluster regardless of their cache level. In some sense, there's no need to call undeclare unless we want to reclaim cache space at the workers.

**Comment by dthain** [comment]
Hmm, I am undecided about this.

`undeclare_file` pulls two things together: the cleanup of the memory state, and the removal of the cached file.

But I could imagine that you want to do one and not the other.

For example, I would expect that a DAG processor would properly undeclare all files at completion, if only to remove all memory state.  And yet you might want to leave a "forever" cached file behind in the cluster for a future workflow.

(This is part of why we need to write up a document explaining the desired caching behavior from a global perspective.)

**Comment by btovar** [comment]
Sounds good. To be consistent with the current implementation, it seems that undeclare file should preserve VINE_CACHE_LEVEL_WORKER.

**Comment by dthain** [comment]
Closing this in favor of #3851.  We need to separate pruning of outstanding replicas from undeclaring of the file.
