### ISSUE TITLE
vine: workers disconnect after puturl_now

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3714]
During workflow runs, about 1/3 of workers disconnect after a puturl_now message. This does not happen every time, but it does greatly increase the total runtime.   For example, of 700 hundred submitted workers, almost 200 have disconnected like that. From the logs of workers created by a factory I see:

```text
grep -B2 "disconnecting from manager" worker.*.log | grep manager | wc -l
187

grep -B2 "disconnecting from manager" worker.*.log
...
--
worker.95.log-2024/03/14 08:41:12.00 vine_worker[965817] vine: tx: file temp-rnd-gtzqoaudetvvifb 161147542 0644 1710419887
worker.95.log-2024/03/14 08:41:12.01 vine_worker[960612] vine: rx: puturl_now worker://10.32.93.114:1024/temp-rnd-qacxduipfkssdvx temp-rnd-qacxduipfkssdvx 1 0 0755 F5E1311D-D61A-4A
3A-92B0-40D704CC2F03
worker.95.log:2024/03/14 08:41:12.01 vine_worker[960612] vine: disconnecting from manager 10.32.93.156:9126
--
worker.99.log-2024/03/14 08:40:41.19 vine_worker[3654899] vine: rx: file temp-rnd-dsetbbqxoodlrbr 26491008 0644 1710420041
worker.99.log-2024/03/14 08:40:41.23 vine_worker[3650455] vine: rx: puturl_now worker://10.32.90.169:1024/temp-rnd-dsetbbqxoodlrbr temp-rnd-dsetbbqxoodlrbr 1 26491008 0755 E564CED2
-BB37-4753-92C7-4F5932608F44
worker.99.log:2024/03/14 08:40:41.23 vine_worker[3650455] vine: disconnecting from manager 10.32.93.156:9126
...
```

**Comment by btovar** [comment]
I don't remember errors like this before #3655, but I can't say for sure.

**Comment by btovar** [comment]
@colinthomas-z80 This may involve code that you are working on with #3709. I won't try any modifications so not to step on what you are doing.

**Comment by btovar** [comment]
Related to VINE_CACHE_FLAGS_NOW. If transfer fails after one attempt, the worker disconnects. If puturl_now fails, we should send back an invalid cache message rather than terminate the worker. Alternatively, is there a reason for puturl_now?

**Comment by colinthomas-z80** [comment]
In order to replicate temp files, what might be the alternative to puturl_now?

**Comment by dthain** [comment]
Hold on, don't start changing the system until we fully understand what's going on.
It seems likely that there is a bug resulting in the worker crash.
Let's figure that out first.

**Comment by dthain** [comment]
A good way to debug this would be to temporarily modify the manager to always use `puturl_now` in place of `puturl` then run one worker manually and watch what it does...

**Comment by btovar** [comment]
The crash comes from do_put_url_now returning 0, which in turn disconnects the worker. Either a bug in do_put_url_now, or some transient connection error that prevents the file transfer at that particular time.

Re: changing to puturl, making a run like that. So far no worker has disconnected.

**Comment by dthain** [comment]
Looking at `vine_cache_add_transfer`, there is only one reason it would return zero, and that is if there already exists an item by that name in the cache.

So that's truthful information, but not a reason to disconnect.   Seems like the solution is to just return one in that cost.

Note that `puturl_now` does *not* do the transfer synchronously, it just forks the transfer right away.  (A normal `puturl` would wait to transfer the file until it was about to start a task that needed it.)

**Comment by btovar** [comment]
@colinthomas-z80 could it be that `replicate_temp_file` does not create a pending replica record, which then schedules the same transfer twice at a worker?

I have conflicting thoughts about vine_cache_add_transfer to return 0 if transfer is already scheduled. If it returns 1, at least the maanger should get an error debug message from the worker.

**Comment by colinthomas-z80** [comment]
I was thinking about it possibly scheduling a transfer twice, but I don’t think that would happen since the replication only occurs on a cache update event. Which there should only be one per file. Unless you have multiple tasks creating the same temp file

**Comment by btovar** [comment]
If you have several cache-updates related to the same file because of previous replication request, isn't it possible that a worker that is slow to create the replica gets a request twice? I'm able to "force" this error by asking for 20 replicas per file.

**Comment by btovar** [comment]
Or if the worker gets a task that uses the file, and then gets a replication request for that file.

**Comment by colinthomas-z80** [comment]
Only the original cache update should trigger a replication. The rest come back with a transfer id so we do not keep exponentially replicating

**Comment by colinthomas-z80** [comment]
Maybe if you loop around the table and somehow hit the same worker twice

**Comment by dthain** [comment]
If you have a debug log for the run, you should be able to search backwards for the same cachename, and determine why the worker already has the file.  That should clear things up.

**Comment by btovar** [comment]
Say that the original cache update triggers a replication of f to worker w. While the replication is being performed, the manager sends a task to w that uses f. Wouldn't that cause the issue?

**Comment by colinthomas-z80** [comment]
Yes that sounds right. We don’t check the transfer table

**Comment by dthain** [comment]
Not the transfer table, the replica table: when the manager sends a `puturl_now` it should add an entry to the replica table with a status of `PENDING`.

**Comment by btovar** [comment]
Do you think that `vine_current_transfers_add` should create the `PENDING` replica?   It seems like a natural way, although I don't like the asymmetry created between transfers_add and transfers_remove.

**Comment by btovar** [comment]
In a current run where `vine_current_transfers_add` creates replicas, and without modifying the vine worker, I have not lost a single worker. I'll make a pr with that change.
