### ISSUE TITLE
Build: FreeBSD Porting

### ISSUE THREAD

**Issue by sprock** [cooperative-computing-lab/cctools#3725]
Some files in chirp/src don't compile, with errors like this:

`/usr/local/bin/ld: /home/rmason/Software/CCTools/cctools-source-git/chirp/src/chirp_swig_wrap.o: relocation R_X86_64_32S against symbol `__stderrp@@FBSD_1.0' can not be used when making a shared object; recompile with -fPIC`

I have sometimes worked around this successfully just by compiling that file by hand, using -fPIC.  However: I have also seen this now:

`/usr/local/bin/ld: /home/rmason/Software/CCTools/cctools-source-git/chirp/src/libchirp.a(chirp_recursive.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC`

In addition some headers seem to be missing from chirp/src - debug.h for example.

For reference, I'm compiling on FreeBSD 13.2 patching 7d6d82df01344744fc74366ed5139691b473de19 as I go.  If I get this to compile & run, and you want the patches, please let me know.

**Comment by dthain** [comment]
Hello, let's roll all of the FreeBSD build issues into one thread to keep the discussion in one place.  We are happy to accept changes that improve portability, if it doesn't create undue complexity for the main supported platforms.  Suggest that you propose one PR with all the changes needed.

**Comment by dthain** [comment]
To your specific points:
- There are a number of code modules that can aggregated into shared objects for a variety of reasons, so I would recommend putting `-fPIC` into the global compiler options. 
- `debug.h` is found in `dttools/src`.  The Makefile should set things up so that code in `chirp` gets `-I ../../dttools/src`.

**Comment by sprock** [comment]
How do I specify -fPIC globally?  I assume that `configure` does that but the help does not say how.  Please note that I'm doing this without conda: not available on FreeBSD.

**Comment by dthain** [comment]
Global compile options are set here, it looks like they already include `-fPIC`:

https://github.com/cooperative-computing-lab/cctools/blob/686630b79ca6fe1fe609bdd0535edd67893557ae/configure#L94

**Comment by sprock** [comment]
Hello,

Douglas Thain ***@***.***> writes:

> Global compile options are set here, it looks like they already include -fPIC:
>
> https://github.com/cooperative-computing-lab/cctools/blob/686630b79ca6fe1fe609bdd0535edd67893557ae/configure#L94

This patch seems to work (lightly tested):

diff --git a/configure b/configure
index 081aa8f80..f5713447f 100755
--- a/configure
+++ b/configure
@@ -762,7 +762,7 @@ then
 
        if [ "${mpi_avail}" = yes ]
        then
-               ccflags="-DCCTOOLS_WITH_MPI"
+               ccflags="${ccflags} -DCCTOOLS_WITH_MPI"
                ccompiler=${mpi_exe}
                linker=${mpi_exe}
        else
@@ -1092,7 +1092,7 @@ then
 
        if [ "${openssl_avail}" = yes ]
        then
-               openssl_ccflags="-I${openssl_path}/include"
+               openssl_ccflags="-I${openssl_path}/include -fPIC"
                openssl_ldflags="-L${openssl_path}/lib -lssl -lcrypto"
        fi
 fi
@@ -1241,7 +1241,7 @@ echo "checking for package compatibility..."
 
 if [ "${include_package_chirp}" = chirp ]
 then
-               internal_ccflags="${internal_ccflags} -DCCTOOLS_WITH_CHIRP"
+               internal_ccflags="${internal_ccflags} -DCCTOOLS_WITH_CHIRP -fPIC"
 fi
 
 if [ "$include_package_parrot" = parrot ]

However, chirp does not compile - details in next message.

Thanks.

**Comment by sprock** [comment]
Hello,

Douglas Thain ***@***.***> writes:

> The Makefile should set things up so that code in chirp gets -I
> ../../dttools/src.

Unless I copy debug.h to chirp/src the build stops like this:

chirp_global.c:116:3: warning: implicit declaration of function 'debug' is invalid in C99 [-Wimplicit-function-declaration]
                debug(D_CHIRP, "catalog queries disabled\n");
                ^
chirp_global.c:116:9: error: use of undeclared identifier 'D_CHIRP'
                debug(D_CHIRP, "catalog queries disabled\n");

I copied it elsewhere to fix other failures:

./grow/src/debug.h
./makeflow/src/debug.h
./deltadb/src/debug.h
./ftp_lite/src/debug.h
./dttools/test/debug.h
./work_queue/src/debug.h
./batch_job/src/debug.h
./taskvine/src/tools/debug.h
./taskvine/src/worker/debug.h
./taskvine/src/debug.h
./taskvine/src/manager/debug.h

I wonder if 'sh' in linux is a symlink to 'bash'?  In FreeBSD it is not.
But still, I'm surprised it does not work here.

Thanks.

**Comment by sprock** [comment]
Hello,

Douglas Thain ***@***.***> writes:

> Hello, let's roll all of the FreeBSD build issues into one thread to
> keep the discussion in one place. We are happy to accept changes that
> improve portability, if it doesn't create undue complexity for the
> main supported platforms.  Suggest that you propose one PR with all
> the changes needed.

Patches for FreeBSD.  Tested on FreeBSD-13.2-RELEASE.



Configuration:

#!/bin/sh
./configure --with-curl-path /usr/local \
	    --with-mpi-path /usr/local \
	    --with-perl-path /usr/local \
	    --with-openssl-path /usr/local \
	    --with-zlib-path /usr/local \
            --without-system-chirp \
	    --without-system-resource_monitor

Thank you for your help, it is much appreciated and I hope I'm not
bombarding you with too many messages.

Roger

**Comment by dthain** [comment]
Thanks bug I think your patches got eaten by the GitHub email gateway.  Could you propose a PR instead?  Thanks, Doug

**Comment by sprock** [comment]
Does this work?
[patches_for_freebsd.tar.gz](https://github.com/cooperative-computing-lab/cctools/files/14727552/patches_for_freebsd.tar.gz)

**Comment by dthain** [comment]
So I think the main irritant here is that there was a bug in configure that accidentally dropped all the ccflags when MPI support is enabled.  This caused the loss of -fPIC and several include directories.  Apart from that, most of the compatibility cases seem to be handled by the ifdefs similar to those needed for Darwin.
