### ISSUE TITLE
Per-application contextualized chirp_job_wait

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#373]
Currently, Chirp's `job_wait` will return any job that is finished and not reaped. If a previous invocation of Makeflow left behind unreaped jobs, then `job_wait` will always return immediately with old jobs. It will never actually wait. This is costly behavior so `job_wait` should be enhanced by allowing to wait on some attribute of jobs set by the application. Something like:

```
job_create {
  "executable": "/bin/sh",
  "tag": "MAKEFLOW-cclws13.cse.nd.edu-123939cjsj3ksj",
  ...
}
```

```
job_wait "MAKEFLOW-cclws13.cse.nd.edu-123939cjsj3ksj"
```

So job_wait can also take a string.

**Comment by dthain** [comment]
Closing old bugs without a driving use case.
