### ISSUE TITLE
vine: vine worker should fall back to ssl.

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3770]
If a worker tries to connect to a manager and gets an immediate error, it should retry using ssl. It is easy for users to specify that flag. Alternatively, we should be able to detect that the manager wants ssl and report an error in the worker.

**Comment by btovar** [comment]
Should we enable ssl by default?

**Comment by dthain** [comment]
Hmm, we may be headed that way, if the most common uses of TaskVine are outside of HPC situations where the network is tightly controlled.  But I would at least like to characterize the performance hit, compared to not using it.

**Comment by btovar** [comment]
Sounds good!
