### ISSUE TITLE
vine: default library cores and slots

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3798]
A common use case  (e.g. DakVine) is for all tasks to come from one library,  for the library to use all the cores in the machine, and for the number of slots to match the number of cores. If unspecified, currently a library gets one core and one slot. It would be helpful to have a setting where the library automatically uses all resources in a worker so that the user does not have to modify the library definition when changing the size of the workers.

**Comment by dthain** [comment]
This should be a general capability of any kind of task: have an autosize mode to fill the entire worker. The idea interacts with `vine_category_mode_t`.  Maybe the way to proceed here is to define a new category with mode `VINE_ALLOCATION_MODE_WHOLE_WORKER` and then attach tasks to that category.

(Although for libraries there is the additional question of how many slots to give an autosized library.)

**Comment by dthain** [comment]
Fixed by #3904
