### ISSUE TITLE
vine: library resources are not accounted for workers

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3819]
The resource accounting is done by `start_one_task`, but library tasks bypass that. This causes the library to be sent multiple times to the worker.

**Comment by btovar** [comment]
Mmm, they do call start_one_task, so the accounting error is happening somewhere else.

**Comment by btovar** [comment]
Unrelated to accounting. Instance and template type for libraries were not updated everywhere, pr upcoming...

**Comment by dthain** [comment]
Is this still a problem or was it fixed by a recent PR?
