### ISSUE TITLE
vine: send library task when sending first function call that uses it

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3825]
Currently libraries are send from `check_worker_against_task`.  This modifies the worker even when the task won't get to run there because a better worker is found. Instead the library should be sent from `start_one_task`  `check_worker_against_task` should simply check whether the library template fits the worker.

**Comment by dthain** [comment]
This one particularly concerns me as a lurking future bug, so I'm going to take a crack at it.
