### ISSUE TITLE
vine: a peculiar run  

### ISSUE THREAD

**Issue by JinZhou5042** [cooperative-computing-lab/cctools#3844]
I got a peculiar run this afternoon. It was 3000 tasks (all are the same) running on a 64-core worker, there were 4 libraries each with 16 cores and 16 function slots. 

- At the very early stages the functions were fast
<img width="1013" alt="image" src="https://github.com/cooperative-computing-lab/cctools/assets/142265839/41fe88ab-324c-4afe-a512-c14502c8124d">

- Then I got some functions very slow
<img width="1490" alt="image" src="https://github.com/cooperative-computing-lab/cctools/assets/142265839/0af8ac21-9123-4461-9bea-49865071577a">

- Then there were significant gaps (I observed that in those gaps the sandboxes for functions were created, but the input files were not sent)
<img width="1056" alt="image" src="https://github.com/cooperative-computing-lab/cctools/assets/142265839/7099b5b4-cad3-492a-b25b-093da40043c9">

- Then the functions resumed to run fast
<img width="992" alt="image" src="https://github.com/cooperative-computing-lab/cctools/assets/142265839/bec51abb-e2eb-4556-a8a1-c677239558da">

This figure can be found [here](http://45.76.17.95:9122/) 

I also checked the machine resource usage status, it turned out that no other users were consuming notable resources.

The manager was doing something weird, but I didn't find some useful suggestions from the log files [2024-05-23T160436.zip](https://github.com/cooperative-computing-lab/cctools/files/15422795/2024-05-23T160436.zip)

**Comment by dthain** [comment]
Well, if there is a gap across everything at the same time, it would suggest the culprit is the manager, or perhaps the application.  What do you see by looking at the debug log around the time of the gap?

**Comment by JinZhou5042** [comment]
The manager set the tasks' status from ready to running, and then everything was similar to the previous lines. I thought there might be some scheduling issue that it didn't report. I will look into it this weekend.

**Comment by dthain** [comment]
Closing this out b/c it appears to be a transient issue...
