### ISSUE TITLE
vine: Include task_id when logging transferred files in the transactions log

### ISSUE THREAD

**Issue by JinZhou5042** [cooperative-computing-lab/cctools#3845]
I found it is helpless to look up when the input/output file of a specific task was sent/received to/from the worker from the transactions file. 

Currently the way to log the input/output file transfer is:

<img width="803" alt="image" src="https://github.com/cooperative-computing-lab/cctools/assets/142265839/1f0c9f92-1e66-492e-bb3d-d31e76d1c043">

It has the corresponding records:
```
1716494695303464 2034612 WORKER worker-cb7c6c4c5130033fdb68942b826bc325 TRANSFER INPUT infile 45 95 1716494695303367
1716494695329694 2034612 WORKER worker-cb7c6c4c5130033fdb68942b826bc325 TRANSFER OUTPUT outfile 113 1330 1716494695328337
``` 

I think it would be better if we can include the task id of those transferred files.

**Comment by btovar** [comment]
@JinZhou5042 One issue is that cached files are sent only once. With your proposal we would only know the first task that needed that file that ran in that worker, which I think will make it more confusing. For debugging purposes you could obtain this information from the debug log with some manual searches; would that be enough?

**Comment by JinZhou5042** [comment]
Yes, that definitely helps!

**Comment by JinZhou5042** [comment]
I submitted 100 tasks to 1 worker, all tasks are the same. I thought there would be only 1 cached input file on the worker, so that it was sent once and every task can read it. But it turns out each task has its own cached input file under the `cache` dir. Is that as expected?

![Screenshot from 2024-05-27 10-33-53](https://github.com/cooperative-computing-lab/cctools/assets/142265839/e42bff34-cf75-46f8-b3d0-9b20af6a1ef0)

**Comment by dthain** [comment]
A basic design principles is that files are "first class citizens" that are declared independently of tasks.  A file could be transferred to serve one task, or perhaps many tasks, or perhaps no tasks at all.  (Maybe the manager is duplicating a file for reliability purposes.)

**Comment by dthain** [comment]
As for the 100 files transferred, take a look at the application code.  Is the file declared exactly once, and marked as cachable?

**Comment by JinZhou5042** [comment]
The application is simply:
``` Python
q = vine.Manager(port=9123)
q.set_name("test-manager")
libtask = q.create_library_from_functions('test-library', my_func, estimate_pi, add_env=False)
libtask.set_env_var('PATH', '/scratch365/jzhou24/env/bin/:$PATH')
libtask.set_cores(16)
libtask.set_function_slots(16)
q.install_library(libtask)

for _ in range(0, 100):
    task = vine.FunctionCall('test-library', 'my_func', args.size)
    q.submit(task)
```

I tried to set `cache=True` when the manager declares the input file for`FunctionCall` tasks (`task.py:FunctionCall:submit_finalize`):
``` Python
self._input_file = self.manager.declare_file(name, unlink_when_done=True, cache=False, peer_transfer=True)
```

**Comment by dthain** [comment]
Oh, I see what's happening here.  Each one of those function calls has its arguments encoded into a file which is provided to the task as an input.  So you have 100 distinct files, each one an input to a different task.  That's expected behavior -- each function need a description of its arguments...
