### ISSUE TITLE
vine: poll link status mapping

### ISSUE THREAD

**Issue by JinZhou5042** [cooperative-computing-lab/cctools#3854]
While polling the link status, we map `POLLHUP` (which means the fd was hung up by the remote process) as `LINK_READ` . I thought this is for simplicity, but I am concerned that will it cause some issues if the fd has been closed but we still consider its status as readable?

``` C
static int link_to_poll(int events)
{
	int r = 0;
	if (events & LINK_READ)
		r |= POLLIN | POLLHUP;
	if (events & LINK_WRITE)
		r |= POLLOUT;
	return r;
}

static int poll_to_link(int events)
{
	int r = 0;
	if (events & POLLIN)
		r |= LINK_READ;
	if (events & POLLHUP)
		r |= LINK_READ;
	if (events & POLLOUT)
		r |= LINK_WRITE;
	return r;
}
```

**Comment by dthain** [comment]
Yes, that is correct.  If the other side has hung up, then we should keep reading until no data is left.  When `link_read` or `link_readline` returns zero, it's the end of the stream and an indication to close it.

**Comment by JinZhou5042** [comment]
If `link_read` or `link_readline` returns zero, doesn't it mean that there is no currently readable data but still a possibility of data being put in the future?

**Comment by dthain** [comment]
https://ccl.cse.nd.edu/software/manuals/api/html/link_8h.html#a7dfc178bb7b3d669f949ba25a4f9f91b

**Comment by JinZhou5042** [comment]
Oh, now I understand! Thank you!
