### ISSUE TITLE
Poncho: Simplify import failure

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3893]
BenC pointed this out in a Parsl issue:
https://github.com/Parsl/parsl/issues/3552

Basically, we are trying too hard to capture an import error and replace it with something more explanatory.  (There may have been a reason for this in the past.). Now that we rely on Conda to get proper python environments everywhere, we should just `import` normally and (if that fails) let it fail with the normal exception.

**Comment by dthain** [comment]
Barry, can you do this one up quickly?  I think it's a small change and then we can close it out...

**Comment by BarrySlyDelgado** [comment]
We now let the import errors happen by forgoing catching the exception via #3907
