### ISSUE TITLE
vine_factory: resource specifications do not carry through to batch job submit script

### ISSUE THREAD

**Issue by colinthomas-z80** [cooperative-computing-lab/cctools#3921]
I've been having an issue using the factory to deploy htcondor workers within the taskvine/parsl executor. I found that regardless of cores requested, the generated submit script will specify only 1. 

I reverted to a point before #3898 and the issue is no longer present. 

Invoking the vine factory by itself can exhibit the issue:

`vine_factory -T condor --cores=12 condorfe.crc.nd.edu 9123`

You can immediately kill the process and check the submit script generated in the log directory

`request_cpus = 1
`

**Comment by dthain** [comment]
Aha, this is my mistake in the big rework.  See here in the old code that `resources` were passed as part of submit:
https://github.com/cooperative-computing-lab/cctools/pull/3898/files#diff-5100174d977217693333f3e584f0f7b78c8a0ebcd6e7cfb58a117414986f0c07L513

Now, they should be attached to the job prior to submission.
Should be an easy fix.

Make sure to get both `vine_factory` and `work_queue_factory`.

**Comment by colinthomas-z80** [comment]
#3924
