### ISSUE TITLE
chirp: add option to chirp_server to limit ticket duration

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#3982]
Currently a ticket may be created with any time duration. Angel de V. has requested an option to `chirp_server` to limit the maximum duration of a ticket.

Looking at the source, the limit can be easily enforced on the `chirp_server` side, but it is not clear to me how to communicate the limit to the chirp tool. The limit could be silently enforced, but that would only generate confusion. Is there a way for the chirp tool to request metadata from the chirp server without modifying the chirp protocol?

**Comment by dthain** [comment]
chirp_client_ticket_get gives back the ticket lifetime, yes?  You could just modify the tool to do an extra rock to get the desired info and display it.

**Comment by btovar** [comment]
It looks like `chirp_reli_ticket_modify` only allows changes to the acls, not the duration of the ticket, so we should be ok.
