### ISSUE TITLE
Resource Control Interface

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#50]
--- btovar commented at Wed, 06 Mar 2013 08:34:40 -0500 ---
Each task in the workflow will have a minimum and maximum rank, according to
where they appear in the dag. If the rank of two tasks overlap, that means that
there is a schedule where the tasks can be run concurrently. If the minimum rank
of a task is bigger than the maximum of the other, then the former task has to
always run first than the latter.

Once we have the tasks divided in ranks, it will be easier for makeflow to
report the range of resources, using the profile statistics from the logs
generated by resource_monitor.
--- btovar took bug at Tue, 29 Jan 2013 09:06:16 -0500 ---

--- dthain changed type to feature at Thu, 30 Aug 2012 13:41:19 -0400 ---

--- dthain submitted bug at Wed, 13 Jun 2012 15:02:35 -0400 ---
Develop a common method for a program to manage the resources of a (possibly
parallel) subprogram.  It should be possible to ask the subprogram how many
resources it could use, and also to tell it how many resources it may use.  The
mechanism should support hierarchy cleanly.

For example, it should be possible to ask a makeflow how many cores it needs. 
The makeflow would examine the dag and report back that it could use between 1
and 38 cores.  The parent looks at the possibilities, then decides to assign 10
cores to the makeflow, which then lives within that limit.

**Comment by dthain** [comment]
This is now encompassed by Nick's work on static dag measurement.
