### ISSUE TITLE
64 bit Parrot's 32 bit stat(64) is broken

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#511]
glibc `stat` returns garbage for 32 bit executable with 64 bit Parrot:

````
#define __USE_LARGEFILE64
#define _LARGEFILE_SOURCE
#define _LARGEFILE64_SOURCE

#include <sys/stat.h>
#include <stdio.h>
#include <stddef.h>

int main (int argc, char *argv[])
{
    struct stat64 foo = {0};
    stat64("/", &foo);
    printf("%p %zu %zu %d\n", &foo, __WORDSIZE, sizeof(foo), S_ISDIR(foo.st_mode));

    struct stat bar = {0};
    stat("/", &bar);
    printf("%p %zu %zu %d\n", &bar, __WORDSIZE, sizeof(bar), S_ISDIR(bar.st_mode));

    return 0;
}
````

In the time I've spent looking into this, I've found that glibc apparently passes `stat64` directly to the kernel. That is, the `struct stat64 *` that the application gives glibc is passed directly to the kernel. For this case, `struct stat64 foo` (above) is correct. However, `stat` is executed via the `stat64` syscall by glibc. So glibc uses its own `struct stat64` buffer and then copies it to the application's `struct stat` buffer. For the latter case, we end up with garbage in `struct stat bar` (above).

I've looked at the sources for `struct stat64` in the kernel, glibc, and strace. What we have in `pfs_sysdeps.h` appears to be correct. The size should be and is 96 (and strace even hard-codes that in its header without even using sizeof). I thought perhaps the order of some struct members is incorrect but we're consistent with the kernel and strace in that regard. The glibc headers apparently change the order of members based on the machine's word size, which is rather terrifying. That may be related to this bug but I can't see how.

There is no error running the above executable with strace.

**Comment by dthain** [comment]
I propose to close this bug: it only occurs on an old platform and does not seem to affect an active user.  Any objections?

**Comment by batrick** [comment]
Okay with me.
