### ISSUE TITLE
Balancing Workers Across Masters

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#569]
Note the distribution of workers here.  We have several masters, all with the same name.  A bunch of workers have connected to the first master and are waiting for work.  However, there is only one task remaining, so 1429 workers are idle.  When the first master exits, all the other workers will migrate over to other master.  Can we figure out a way to make this happen earlier?

PROJECT            HOST                   PORT WAITING RUNNING COMPLETE WORKERS 
asgroi_test        cvrl-c0-06.crc.nd.edu  9003       0       1     9999    1430 
asgroi_test        cvrl-c0-06.crc.nd.edu  9005    3682     636     5682     653 
asgroi_test        cvrl-c0-06.crc.nd.edu  9004    1821     214     7965     214 
asgroi_test        cvrl-c0-06.crc.nd.edu  9008    1083       6     8911       6 
asgroi_test        cvrl-c0-06.crc.nd.edu  9002    4302       1     5697       1

**Comment by btovar** [comment]
Fixed on 7fd9e5eb0a7ecc476c1eda9d857a3c97e0d6d526.

A worker will disconnect from a master if no task is received by --timeout.
