### ISSUE TITLE
Work Queue does not check for space of output.

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#576]
I do not believe that Work Queue is checking is there is enough space for the output that it is trying to receive. Can we more directly check if the master has space prior to sending the file and having it fail?
This may be related to an issue that Evan at Arizona is having.

**Comment by dthain** [comment]
@btovar says this is fixed...?

**Comment by nhazekam** [comment]
After discussing with @btovar this is checked at the worker, but not at the master. I am working on a fix for it now.

**Comment by nhazekam** [comment]
Addressed in pull-request #756.
