### ISSUE TITLE
Running bcl2fastq script in a virtul parrot mounted bash shell on gpfs in HPC

### ISSUE THREAD

**Issue by navyagit** [cooperative-computing-lab/cctools#585]
The bcl2fastq configure script uses parallelization and we use a cctools binary installation for parrot.
We notice an error while executing bcl2fastq script inside a parrot mounted shell:

prepare_bcl2fastq_Test.sh
./prepare_bcl2fastq_Test.sh: line 0: unalias: bbash8: not found
./prepare_bcl2fastq_Test.sh: line 0: unalias: bbash4: not found
./prepare_bcl2fastq_Test.sh: line 0: unalias: bbash: not found
./prepare_bcl2fastq_Test.sh: line 0: unalias: setfwpwd: not found
./prepare_bcl2fastq_Test.sh: line 0: unalias: bbash1: not found
./prepare_bcl2fastq_Test.sh: line 0: unalias: bxterm: not found
./prepare_bcl2fastq_Test.sh: line 0: unalias: hpc: not found
./prepare_bcl2fastq_Test.sh: line 0: unalias: bbash16: not found
Use of qw(...) as parentheses is deprecated at /gpfs/software/bcl2fastq/1.8.4/lib/bcl2fastq-1.8.4/perl/Casava/Alignment/Config.pm line 747.
Use of qw(...) as parentheses is deprecated at /gpfs/software/bcl2fastq/1.8.4/lib/bcl2fastq-1.8.4/perl/Casava/Alignment/Config.pm line 751.
[2014-10-24 11:44:07]   [configureBclToFastq.pl]        INFO: Running self tests: 'make self_test'
[2014-10-24 11:46:24]   [configureBclToFastq.pl]        INFO: Running self tests on /gpfs/test folder completed with no problems
[hpc test_parrot]$

	That worked, took approx.. 5 min
	Next:

Folder1/Sample_FR || ( sleep 5 && mkdir -p Temp/Folder2/Folder4/Sample_FR ); touch Temp/Folder2/Folder4/Sample_FR/.sentinel
mkdir -p TempFolder2/Folder4/Sample_MR || ( sleep 5 && mkdir -p Temp/Folder2/Folder4/Sample_MR ); touch Temp/Folder2/Folder4/Sample_MR/.sentinel
[2014-10-24 11:54:01]   [genomics-hpc]  [Folder2/Folder4/Sample_FR/.sentinel]    
make Cmd:       mkdir -p Temp/Folder2/Folder4/Sample_FR|| ( sleep 5 && mkdir -p Temp/Folder2/Folder4/Sample_FR); touch Temp/Folder2/Folder4/Sample_FR/.sentinel
make: *** wait: No child processes.  Stop.
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
[hpc test_parrot]$

	Stopped during processing

Any ideas?

**Comment by batrick** [comment]
Closing this because I think the original problem was resolved in the above mentioned PR/commits.

@navyagit if you have any further problems please open a new issue.
