### ISSUE TITLE
Makeflow and NFS latency

### ISSUE THREAD

**Issue by fescudie** [cooperative-computing-lab/cctools#614]
Hello,

I use makeflow on a web server and I have a problem with file system latency.
The master job is run on the web server. Slaves jobs are run on a cluster. Storages are mounted in GPFS on cluster but in NFS on the web server. When a slave job is ended the latency of the NFS triggers the error : '<cmd> did not create file <file>'. In fact the files are created but the file system of the web server is not synchronized when the end signal is received by the master job from the slave job.
To avoid this problem I have added a sleep in dag_node_complete just before the output files check (Makeflow.c) :

    void dag_node_complete(struct dag *d, struct dag_node *n, struct batch_job_info *info)
    {
        struct dag_file *f;
        int job_failed = 0;

        if(n->state != DAG_NODE_STATE_RUNNING)
            return;

        if(n->local_job && local_queue) {
            d->local_jobs_running--;
        } else {
            d->remote_jobs_running--;
        }

        if(info->exited_normally && info->exit_code == 0) {
            list_first_item(n->target_files);
            sleep(1); /* <............................................  patch here */
            while((f = list_next_item(n->target_files))) {
                struct stat buf;
                if(batch_fs_stat(remote_queue, f->filename, &buf) < 0) {
                    fprintf(stderr, "%s did not create file %s\n", n->command, f->filename);
                    job_failed = 1;
                } else {
                    if(output_len_check && buf.st_size <= 0) {
                        debug(D_DEBUG, "%s created a file of length %ld\n", n->command, (long) buf.st_size);
                        job_failed = 1;
                    }
                }
            }

What do you think about this problem ? Are there any other solutions ? Otherwise, is it possible to add this correction as an option to Makeflow ?

Best regards.

**Comment by dthain** [comment]
@fescudie I think this problem is solved, let us know if you have any further issues.
