### ISSUE TITLE
Send peak info to catalog

### ISSUE THREAD

**Issue by rampantmonkey** [cooperative-computing-lab/cctools#63]
--- dthain submitted bug at Wed, 13 Mar 2013 15:52:33 -0400 ---

The work queue master should keep track of the past peak values of workers
connected, tasks running, etc. and communicate those to the catalog.

This will preserve useful information even if some updates are lost, the
catalog information is stale etc.  Also useful for the WQ visualization that
kwern is working on.

**Comment by dthain** [comment]
This feature is largely superseded by the catalog history and query feature.
