### ISSUE TITLE
`Suspended (tty input)` error caused by parrot_run sets the foreground process group

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#650]
Peter Ivie tried to use `umbrella` in `prune` (as shown in the following snippet), and met the error of  `Suspended (tty input)` when trying to execute the last command `sys.stdin.readline()`. BTW, `umbrella` command is finished successfully.

    args = ['./umbrella','-T','local','-i','prune_function=NoOp', '-c','package.json', '-l','./tmp/', '-o','./final_output', 'run','/bin/bash prune_function']
    p = subprocess.Popen(args, stdout = subprocess.PIPE, cwd=sandbox_folder, shell = False)
    p.communicate()
    p_status = p.wait()
    sys.stdin.readline()

The reason for this problem is that `umbrella` currently uses `parrot` to redirect the input files and construct a sandbox, and `parrot` set the foreground process group of the session by default. Here is the illustration:
Before `umbrella` is called in Peter's code, the process information of Peter's code is as follows:

    PID: 62549, PGID: 62549, session ID: 39415; foreground PGID = 62549

After `umbrella` is executed successfully, the process information of Peter's code is as follows:

    PID: 62549, PGID: 62549, session ID: 39415; foreground PGID= 62569

**Comment by batrick** [comment]
Fixed in #651.
