### ISSUE TITLE
Parrot should hide reserved tracee file descriptors 

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#659]
Parrot currently has two "reserved" file descriptors for all tracees: the channel and the Parrot temporary directory. These file descriptors usually occupy descriptors just above the standard ones, e.g. 3 and 4. Applications sometimes have difficulty understanding why these descriptors are effectively off-limits; a `close` will fail and a `dup2` will also fail.

We might correct this by placing reserved descriptors elsewhere in the file descriptor table, out-of-reach of the application. One possibility is placing the descriptors at the end of the table but this only delays the appearance of the problem to when the application uses all of its file descriptors.

I suggest putting the descriptors at the beginning of the table, occupying descriptors 0 to (n-1). Currently n is 2. Then, all file descriptors given by the application for system calls are offset n before use. So we might have:

````
0 --> channel
1 --> Parrot temporary directory
2 --> stdin
3 --> stdout
4 --> stderr
...
````

A `dup2(0, 3)` syscall would be translated to `dup2(2, 5)`. We also need to appropriately modify the `/proc/pid/fd` directory (which we already change).

This change would require a bootstrap step of shifting all tracee file descriptors up by n.

One problem that we might encounter (during this bootstrap step) is Parrot run with file descriptors at the file descriptor open limit (i.e. if the open descriptor limit is 1024 and Parrot starts with file descriptor 1023 open). We may not be able to increase the limit (via `ulimit`) and we cannot shift the file descriptor up by n. I don't think there is a good solution for that except to complain and cowardly quit.

**Comment by dthain** [comment]
Hmm, I'm a little confused about the nature of the problem.

The basic idea is that the tracee has a virtual file table (pfs_table) which represents its virtualized file of the file descriptors.  The virtual fds represented by that table have a non-trivial relationship with the physical fds actually used to implement the tracing.  For example, virtual fd 1 could be implemented as a single local file (one fd) a remote file (possibly multiple fds) or as a memory buffer (no fds at all).  Whenever the tracee refers to an fd, that number has to be translated by passing it through the appropriate pfs_table to do the right thing.

That should leave Parrot free to do whatever it needs to do with file descriptors, since the tracee's view always goes through the table.  If a process does a close(1), it should affect entry 1 in the pfs_table, not the physical fd 1 directly.

Or am I missing something?

**Comment by dthain** [comment]
@batrick are we on the same page here?

**Comment by batrick** [comment]
No, sorry I meant to discuss this in your office sometime.

The relationship between Parrot's file descriptor table and the tracee's kernel file descriptor table changed in the native-fd branch. Now the two tables are completely in "sync". The only two discrepancies is (a) that Parrot does not actually have open the "native file descriptors" (i.e. the files the tracee has opened via the kernel, not Parrot) and (b) the kernel has dummy file descriptors open for "parrot file descriptors" (files Parrot has opened for the tracee, e.g. a /chirp file or a local directory).

The major reason for this change is so that we no longer need to remap file descriptors that the tracee uses in system calls. For example, if the tracee selects for reading file descriptors [0, 5] where 0 is a native tty and 5 is a chirp file, then we can allow this to be passed completely unmodified to the kernel. [In this instance, the kernel will always immediately return as a parrot file descriptor is an empty file, which is always ready for reading.] This is even more important for sending/receiving descriptors over a UNIX socket.

Admittedly, I *think* it may have been possible to keep the original structure where the pfs_table is the actual file descriptor table and native file descriptors within pfs_table refer to actual kernel descriptors. It would have been messy since Parrot no longer emulates socket send/recv and so the kernel would need real (i.e. dummy) descriptors to work with. We would also need to remap every file descriptor for every file I/O system call (causing PTRACE_SETREGS overhead).

**Comment by batrick** [comment]
> I suggest putting the descriptors at the beginning of the table, occupying descriptors 0 to (n-1). Currently n is 2. Then, all file descriptors given by the application for system calls are offset n before use.

I'm closing this because this is exactly what we wanted to avoid: changing every file descriptor used in a system call.

It's also not presently a problem for anyone.
