### ISSUE TITLE
domain_name module should retry transient failures of DNS lookups

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#662]
Anna Woodward reported that many of her workers were failing with:

````
2015/01/11 13:20:32.28 chirp_get[11380] dns: looking up name earth.crc.nd.edu
2015/01/11 13:20:40.32 chirp_get[11380] dns: couldn't look up earth.crc.nd.edu: Name or service not known
````

This error appeared along with other network related errors.

I believe the appropriate resolution for this is to retry the `getaddrinfo` request several times before failing, depending on the type of error.

**Comment by dthain** [comment]
Is there a robust way of distinguishing between "DNS not available" and "name not found" ?

**Comment by batrick** [comment]
I don't think that information is available but I could be wrong.

**Comment by batrick** [comment]
Found this:

https://bugzilla.redhat.com/show_bug.cgi?id=1044628

Our use of AF_UNSPEC causes the wrong error message to be displayed. I need to confirm this.

**Comment by batrick** [comment]
Seems this still exists even in glibc 2.20 (Arch). If the network is down or if packets get dropped, we still get EAI_NONAME. It seems to be the favorite catch-all for any problem by glibc. Unfortunately that means we can't do much intelligently except blindly retry.

**Comment by dthain** [comment]
In that case, I think the effort is not worth the trouble.  If the error code doesn't help use to decide whether to wait or return, the best default is to return so that higher level code can make a more informed decision about what to do next.

**Comment by batrick** [comment]
Perhaps chirp_reli should do the retry?

**Comment by dthain** [comment]
That would be the right place to do it, if chirp-reli can clearly distinguish between name-not-found and dns-down.  If it can't distinguish, then I think the right thing is to fail quickly.

**Comment by batrick** [comment]
chirp_reli can't distinguish either. I think we'll just keep the code as-is and have Anna adjust her code.

**Comment by annawoodard** [comment]
What would you recommend-- retrying my call? Can you remind me what exit
code will chirp return for this type of error? It looks like we were not
properly passing the exit code up or logging it.

On Mon, Jan 19, 2015 at 11:01 AM, Patrick Donnelly <notifications@github.com

**Comment by batrick** [comment]
Anna, `chirp_reli_*`/`chirp_client_connect` will set `errno` to `ENOENT` (No such file or directory).

I would suggest retrying the chirp operation, if that makes sense for the application. It could only require a few retries over the course of seconds or maybe minutes. You may also want to retry tasks at the Work Queue level.
