### ISSUE TITLE
WQ blacklist feature needs a section in the manual

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#664]
And it's missing Python/Perl bindings.

**Comment by annawoodard** [comment]
@batrick, @nhazekam 
From userland: we are excited about this feature (thanks, developers!), and looking forward to this issue being resolved (especially the python bindings), see [https://github.com/matz-e/lobster/issues/78](https://github.com/matz-e/lobster/issues/78).

**Comment by btovar** [comment]
On it.
