### ISSUE TITLE
There is no syntax for escaping $ in Makeflow

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#668]
So it is not possible to write a recipe with a literal "$".

I suggest this be fixed by adopting the Make escape syntax of "$$". The manual should be updated.

**Comment by btovar** [comment]
Backslash does not work?

**Comment by batrick** [comment]
`echo \$\$;` is changed to `echo  $;" (notice the extra space). Something isn't right...

**Comment by dthain** [comment]
I'm not seeing the problem, where is the extra space?
On master/head, I get the following output:

echo $ -> makeflow parse error
echo \$ -> "echo $" -> $
echo \$\$ -> "echo $$" -> 1126 (shell sees dollar dollar and yields the pid)
echo \\\$\$; -> "echo \$$;" -> $$

Am I missing something?

**Comment by batrick** [comment]
Apparently something recently (last ~6 months) changed in makeflow (or dttools) as this doesn't happen in the master branch. I'm closing this.

**Comment by btovar** [comment]
Yaaaaaaay!
