### ISSUE TITLE
putfile retry fails if client only has put permission

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#669]
So I ran into an interesting bug in Confuga where a transfer job is trying a `chirp_reli_putfile` operation. The issue it ran into was the first putfile attempt failing due to connection failures. Subsequent attempts failed because a file was partially written and the storage node (transfer job) only had put permission for the containing directory.

The problem put succinctly: a put operation cannot be retried on failure if the client only has put permissions.

I see a few potential solutions:

* Write your application in a way that it is not sensitive to this failure. [This one is hard because you can leave behind a lot of partially written files...]

* Don't give a client only put permission.

* Since the `putfile` RPC gives the length of the file being put, it's possible for the Chirp server to check if the operation did not put the entire file. If so, we could delete the partially written file.

* Another (very non-portable) option is to have an anonymous file that is linked in after it is fully written. From `open(2)`:

````
       O_TMPFILE (since Linux 3.11)
              Create  an  unnamed  temporary file.  The pathname argument specifies a
              directory; an  unnamed  inode  will  be  created  in  that  directory's
              filesystem.   Anything  written to the resulting file will be lost when
              the last file descriptor is closed, unless the file is given a name.

              O_TMPFILE must be specified with one of O_RDWR or O_WRONLY and, option‐
              ally,  O_EXCL.   If O_EXCL is not specified, then linkat(2) can be used
              to link the temporary file into the filesystem,  making  it  permanent,
              using code like the following:

                  char path[PATH_MAX];
                  fd = open("/path/to/dir", O_TMPFILE | O_RDWR,
                                          S_IRUSR | S_IWUSR);

                  /* File I/O on 'fd'... */

                  snprintf(path, PATH_MAX,  "/proc/self/fd/%d", fd);
                  linkat(AT_FDCWD, path, AT_FDCWD, "/path/for/file",
                                          AT_SYMLINK_FOLLOW);
````

I'm marking this as question since I'm not sure this can be reasonably fixed.

The fix I have now is to add write permission in addition to put permission.

**Comment by btovar** [comment]
What's wrong with option 3?

Since the putfile RPC gives the length of the file being put, it's possible
for the Chirp server to check if the operation did not put the entire file.
If so, we could delete the partially written file.

**Comment by batrick** [comment]
I'm not 100% fond of option 3 because deleting a partially written file seems at least somewhat surprising (to the user).

**Comment by dthain** [comment]
Since this is a very narrow case, let's find a quick fix and move ahead.

I think option three is the correct solution -- putfile is a single atomic operation, and if it fails, the user's only proper recourse is to start over again.  If the user wants restartability, they can use streaming or Unix-like I/O.
