### ISSUE TITLE
make cached name does not work with binary buffers

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#671]
The cached name is computed assuming the data is an ascii string. If there is a '\0' somewhere in the data, there might be a cache collision. I recommend using the remote_name instead.

**Comment by dthain** [comment]
Ah, I think we have made this mistake before, using the remote name to compute the unique cache name won't work, in the (common) case where a different file is delivered to the same remote name in many tasks.

You should be able to checksum the entire buffer in the case of a binary object, see md5.h

**Comment by batrick** [comment]
@btovar this was fixed in 3f99debb901b659b591148a103ef664072498fbb right?

**Comment by btovar** [comment]
Correct.

**Comment by batrick** [comment]
Closing this since I guess it's done.
