### ISSUE TITLE
Parrot and Python - Segmentation fault

### ISSUE THREAD

**Issue by QLeB** [cooperative-computing-lab/cctools#677]
Hi,
Im am having an error when executing a very simple Python script within Parrot :

#!/usr/bin/env python
import uuid

"parrot_run python parrot_python_test.py" returns :
sh: line 1: 17290 Segmentation fault      /sbin/ldconfig -p 2> /dev/null
sh: line 1: 17292 Segmentation fault      /sbin/ldconfig -p 2> /dev/null

The Parrot version is 4.4.0-TRUNK (released 03/05/2015). Note that the bug does not happen for version 4.3.2-RELEASE.

**Comment by batrick** [comment]
Hi @QLeB, thanks for the report. I'm looking into it.

**Comment by batrick** [comment]
@QLeB I have been able to reproduce this. It appears that ldconfig is experiencing a segfault when I/O buffers (stdout) are being flushed on `exit(3)`. I haven't yet been able to figure out why that's happening.

**Comment by batrick** [comment]
@QLeB, FYI 964b01fc1d6c65c28dd4be8ec23197d7ab49f1fc makes a small correction to 964b01fc1d6c65c28dd4be8ec23197d7ab49f1fc.
