### ISSUE TITLE
fast_abort v2.0 for hierarchical WQ

### ISSUE THREAD

**Issue by dpandiar** [cooperative-computing-lab/cctools#68]
--- malbrec2 submitted bug at Tue, 12 Mar 2013 17:09:24 -0400 ---
The semantics of fast_abort are unclear when work_queue_tasks may sit in worker
or foreman queues for a variable length of time.  For example, if half of the
workers are connected to a foreman and half are connected directly to the
master, there may be a (substantial) difference in the effective runtime the
master observes.

We may want to consider moving to an implementation where the master specifies
the allowed runtime when transmitting the task and allows the worker to handle
killing it, rather than having the master explicitly manage task cancelling
itself.

**Comment by dthain** [comment]
Issue now encompassed by #706
