### ISSUE TITLE
Parrot LHC Tests

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#689]
@jblomer writes:

Following the discussions at the CernVM workshop, I create a set of scripts that start the software frameworks of the four LHC experiments ALICE, ATLAS, CMS, and LHCb under parrot
https://github.com/jblomer/parrot-test

You can use the lhc.sh script like this:
```
./lhc.sh alice
PARROT_RUN=/path/to/parrot_run ./lhc.sh atlas
PARROT_OPTIONS="-d cvmfs" ./lhc.sh cms
HTTP_PROXY="http://my-proxy:3128" ./lhc.sh lhcb
```

The lhc.sh script sources ${TESTCASE_PATH}/setup.sh if it exists, changes into the workspace sub directory and executes the ${TESTCASE_PATH}/run.sh script.  The LHC applications are rather resource hungry, I gave them a few GB free disk space and 4G memory. The alice test case requires the compat-libgfortran-41 package.

I tested the latest released cctools as well as the development head from github against cvmfs 2.1.20 <https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.1.20/> both on Scientific Linux 6 and on CernVM, which is an SL6 on top of a vanilla 3.10 Linux kernel:

         HEAD, 3.10    release, 3.10    HEAD, SL6    release, SL6
atlas    no [1]        no [2]           yes          no [2]
alice    no [3]        no [3]           no [3]       no [3]
lhcb     no [4]        no [4]           no [4]       no [4]
cms      yes [5]       yes [5]          yes [5]      yes [5]

[1] The message "/tmp/asetup_dV7BNJ.sh: line 262: cd:
/home/atlas/parrot-test/workspace: Cannot allocate memory" appear, but
the test continues until at a later point the out-of-memory killer kicks in
[2] Segmentation fault in CMT, which is the tool to setup the
environment variables (PATH, LD_LIBRARY_PATH)
[3] symlink from the workspace into /cvmfs/alice-ocdb.cern.ch do not resolve
[4] CMT can’t setup the environment (SetupProject call)
[5] cms would benefit from the possibility to resolve a symlink
/cvmfs/cms.cern.ch/SITECONF/local —> /my/local/path

@batrick @btovar

**Comment by batrick** [comment]
Closing this since @jblomer reports all tests complete with master.
