### ISSUE TITLE
Incorrect exit code on external symlink

### ISSUE THREAD

**Issue by bbockelm** [cooperative-computing-lab/cctools#695]
CMS's CVMFS setup uses an off-CVMFS symlink (happens to point at /afs/cern.ch/something).

It's absolutely fine if the symlink is broken, but various tools check the errno for stat() -- and the errno set is wrong!  Currently, parrot returns EXDEV for a symlink that points at a different filesystem.  This is invalid - it should be ENOENT.

The errno checking is in various external packages (such as boost), so it's hard to change them to accept the invalid errno; we really need Parrot to return a valid value.

**Comment by dthain** [comment]
I believe @batrick already worked up a fix for this, so I'll let him chime in.

Also note that the simplest way to work around this issue is to use the -M option to parrot to explicitly redirect that symbolic link to the desired location.

**Comment by bbockelm** [comment]
Ah.  It seems that @batrick is a better person than I am.  I assumed that since I had mentioned it to someone in the hallway last week, it had already been forgotten by today.

Looks like it was fixed in PR #694.  Will go ahead and close.

**Comment by batrick** [comment]
@bbockelm This was fixed in:

https://github.com/cooperative-computing-lab/cctools/pull/694

Can you move discussion there. Marking this as duplicate.

**Comment by batrick** [comment]
@bbockelm Please chime in on #694, there is a question on whether EIO may be more appropriate.
