### ISSUE TITLE
cctools 4.1.3 fails to build against cvmfs 2.1.20

### ISSUE THREAD

**Issue by efajardo** [cooperative-computing-lab/cctools#702]
Dear CCtools devs,

The new cvmfs version (2.1.20) will be released in the OSG repos in April's release (April 14 2015). While trying to build cctools 4.1.3 against cvmfs-devel 2.1.20 we hit this error:

    COMPILE pfs_service_cvmfs.o
    pfs_service_cvmfs.cc: In member function 'bool cvmfs_dirent::lookup(pfs_name*, bool, bool)':
    pfs_service_cvmfs.cc:857: error: cannot convert 'char*' to 'cvmfs_context*' for argument '1' to 'int cvmfs_stat(cvmfs_context*, const char*, stat*)'
    pfs_service_cvmfs.cc:860: error: cannot convert 'char*' to 'cvmfs_context*' for argument '1' to 'int cvmfs_lstat(cvmfs_context*, const char*, stat*)'
    pfs_service_cvmfs.cc: In member function 'virtual int pfs_file_cvmfs::close()':
    pfs_service_cvmfs.cc:898: error: invalid conversion from 'int' to 'cvmfs_context*'
    /usr/include/libcvmfs.h:78: error: too few arguments to function 'int cvmfs_close(cvmfs_context*, int)'
    pfs_service_cvmfs.cc:898: error: at this point in file
    pfs_service_cvmfs.cc: In member function 'virtual pfs_file* pfs_service_cvmfs::open(pfs_name*, int, mode_t)':
    pfs_service_cvmfs.cc:970: error: cannot convert 'char*' to 'cvmfs_context*' for argument '1' to 'int cvmfs_open(cvmfs_context*, const char*)'
    pfs_service_cvmfs.cc: In member function 'virtual pfs_dir* pfs_service_cvmfs::getdir(pfs_name*)':
    pfs_service_cvmfs.cc:1026: error: cannot convert 'char*' to 'cvmfs_context*' for argument '1' to 'int  cvmfs_listdir(cvmfs_context*, const char*, char***, size_t*)'
    pfs_service_cvmfs.cc: In member function 'virtual int pfs_service_cvmfs::readlink(pfs_name*, char*, pfs_size_t)':
    pfs_service_cvmfs.cc:1185: error: cannot convert 'char*' to 'cvmfs_context*' for argument '1' to 'int cvmfs_readlink(cvmfs_context*, const char*, char*, size_t)'
    make[2]: Leaving directory `/builddir/build/BUILD/cctools-4.1.3/cctools-4.1.3-source/parrot/src'

I wonder if you have any plans to update it to be able to build against cvmfs 2.1.20

Thanks,

Edgar
OSG Software

**Comment by batrick** [comment]
Hi @efajardo, we plan to continue supporting cvmfs in CCTools. We will discuss what needs to be done to get this fixed.

**Comment by btovar** [comment]
Edgar,

The current cctools version (4.3.4) already has the changes necessary for the new cvmfs. You can get the source from here:

http://ccl.cse.nd.edu/software/downloadfiles.php

Could you tell us if the stable version works for you? Thanks.

**Comment by batrick** [comment]
@btovar CCTools master does build against libcvmfs 2.1.20.

I think @efajardo wants the changes backported to the 4.1 line though.

**Comment by btovar** [comment]
The current release candidate works too.

**Comment by jdost321** [comment]
Hi,

I'm continuing the cctools build for OSG that Edgar started. It looks like it's able to compile, but now we're getting a link error: 
```
COMPILE parrot_run.o
LINK parrot_run
/usr/lib/libcvmfs.a(libcvmfs.a_pub.o): In function `cvmfs::Uuid::MkUuid()':
/builddir/build/BUILD/cvmfs-2.1.20/cvmfs/uuid.cc:71: undefined reference to `uuid_generate'
collect2: ld returned 1 exit status
```
This was trying with cctools-4.3.4-source.tar.gz and cvmfs rpm:
cvmfs-devel-2.1.20-1.osg32.el6.x86_64

Any idea on what could be wrong?
Thanks,
Jeff
OSG Software

**Comment by batrick** [comment]
@jdost321 cvmfs 2.1.20 introduced a libuuid dependency. You need to install it: `yum install libuuid-devel`.

See also #686.

**Comment by jdost321** [comment]
Thanks @batrick however it looks like installing wasn't enough. I think the configure script needs to be modified to also add /usr/lib64/libuuid.a to CCTOOLS_EXTERNAL_LINKAGE. I tried manually adding it to ./config.mk and then everything in cctools was built fine.

**Comment by btovar** [comment]
Ok, I'll check this one. Thanks for the report.

**Comment by btovar** [comment]
@jdost321, with 4.4.0rc3 I do see libuuid.a listed in CCTOOLS_EXTERNAL_LINKAGE. Which version are you trying?

**Comment by jdost321** [comment]
4.3.4

Thanks,
Jeff

**Comment by btovar** [comment]
Jeff, 
Could you give 4.4.0rc3 a try, to see if it works for you? You can get it from here:

http://ccl.cse.nd.edu/software/downloadfiles.php

**Comment by jdost321** [comment]
Thank you @btovar I noticed you released 4.4.0 and indeed it builds fine. Before closing this however I have a related issue. Now that cctools requires libuuid-devel for cvmfs support, I'm unable to build in rhel5 because I can't find the libuuid-devel package anywhere (I searched rhel5 base, epel, and osg repos).

Do you guys have any advise on how to get the build working in rhel5?

**Comment by btovar** [comment]
Could you try the  util-linux-ng  rpm? uuid should be part of it.

**Comment by btovar** [comment]
Closing as 4.4.0 solves it.
