### ISSUE TITLE
Fixing Work Queue Foreman

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#706]
As per the discussion with @btovar and @dthain, this ticket should outline different areas of work to better model the interactions of the master<->foreman<->workers. The goal is to allow existing functionality to work with the foreman structure, and allow additional functionality to utilize foreman as it is added. To fix the foreman here are key areas to understand and model.
- Communication between master, foreman, and workers on task information
  - Currently, the master send task information out to foreman and workers, but the only information that is retrieved is the done status and the resulting files.
  - The end goal would allow information to move back and forth from master and worker through chains of foreman without losing important information about execution due to the encapsulating nature of foreman task management.
  - Initially, this may be addressed by passing a doc about task execution back to the master, using the same structure as exists for sending task information to workers.
- Management of policy attributes in the master
  - Currently, policies created and managed by the master are not communicated or enforced by the foreman. This causes some of the functionality to either not work function differently from expectations when foreman are used.
  - The end goal would be a standard way to communicated policies to foreman. This should work for chains of foreman and be clear how Work Queue refreshes these policies so behavior is understood.
- Revise structure to model internal structure as closely to API calls where appropriate
  - As we revise and add functionality to the master and foreman, to maintain clarity the API functions should be clearly related to the structures.
  - Though this is not an issue currently, this is included to help model the above work.

Let me know if I missed something substantial or if the direction is not quite right.

**Comment by dthain** [comment]
That's a good start.  Before we proceed any further, let's add add specific examples of where the foreman breaks existing functionality, so that when we consider changes, we can first consider whether the change fixes or breaks that particular aspect.

**Comment by nhazekam** [comment]
For specific examples of how foreman breaks existing functionality, there are two that come to mind.

1. Blacklist - Blacklisting workers if currently managed at the master. If there is a worker misbehaving or not executing properly, the master can blacklist the worker. However, if the worker is used by the foreman, the master does not know the name of the worker, and therefore can only blacklist the foreman losing all of its workers.

2. Fast Abort - To utilize fast abort currently both the master and the foreman must have fast abort turned on. However, in this case the statistics used to determine an aborted task are calculated separately at the master and all foreman, so the behavior is not as expected.

@btovar Please comment on other cases where foreman breaks existing functionality.

**Comment by btovar** [comment]
task.host used to describe the site on which the task executed. This is no longer true for foremen, as the task.host has the ip of the foreman, not of the worker.

**Comment by annawoodard** [comment]
Also, queue.stats.{total_workers_connected|total_workers_joined|total_workers_removed|workers_idle} all describe only the foremen and I don't know of a way to access it through the python API for the workers.

**Comment by btovar** [comment]
@annawoodard, I thought this was already covered with q.stats_hierarchy. Is q.stats_hierarchy not working for you anymore?

**Comment by annawoodard** [comment]
Hmm, I missed the memo on q.stats_hierarchy, we don't have it implemented in Lobster. I will try it out and report back. Thanks!

**Comment by annawoodard** [comment]
Just to close the loop on stats_hierarchy: I've tested with cctools build `cctools-010-c650f939-cvmfs-40cf5bba` and stats are being propagated through the foremen as expected (thanks, @btovar, and anyone else that implemented it!) I'll keep an eye on this thread, I'm happy to help test once there's a fix in place for propagating the hostname. In Lobster we find the blacklisting feature very useful, so we're excited about blacklisting + foremen.
