### ISSUE TITLE
work queue: rethink timeouts

### ISSUE THREAD

**Issue by dpandiar** [cooperative-computing-lab/cctools#71]
--- dthain commented at Mon, 18 Feb 2013 11:53:10 -0500 ---
Given the unusual things happening to Lee-Ping and biocompute workloads, we
need to take a serious look at this.

--- dthain changed title to 'work queue: rethink timeouts' at Mon, 18 Feb 2013
11:52:02 -0500 ---

--- btovar submitted bug at Thu, 07 Feb 2013 13:45:40 -0500 ---
Currently makeflow uses a conservative, static, time-out when transferring
files. A better alternative is to use the bandwidth information of previous
transfers to give a better bound. The bound should also depend on the size of
files already cached in a worker (the larger the cache, the more expensive is
to copy everything somewhere else, so the bound must be more forgiving).

**Comment by dthain** [comment]
Closing as wontfix -- not driven by user needs.
