### ISSUE TITLE
Stale dependency after changing ./configure --with-irods-path

### ISSUE THREAD

**Issue by mcast** [cooperative-computing-lab/cctools#710]
Hi again,

In 7796241 I noticed that re`./configuring` to change `$irods_path` does not mark dependent objects as stale.
```
mca@cgpfoo:~/build/src/cctools$ (./configure --debug --prefix ~/build --with-irods-path ~/build/src/irods-legacy/iRODS --without-system-{sand,allpairs,wavefront,makeflow,resource_monitor,doc} ; make clean; make) >/dev/null 2>&1; objdump -WL parrot/src/parrot_run| grep -E 'iRODS/.*/rcObjStat'
CU: /nfs/users/nfs_m/mca/build/src/irods-legacy/iRODS/lib/api/src/rcObjStat.c:

# change it.  build is rather fast, using the old irods API tree
mca@cgpfoo:~/build/src/cctools$ (./configure --debug --prefix ~/build --with-irods-path /usr/local/iRODS               --without-system-{sand,allpairs,wavefront,makeflow,resource_monitor,doc} ;             make) >/dev/null 2>&1; objdump -WL parrot/src/parrot_run| grep -E 'iRODS/.*/rcObjStat'
CU: /nfs/users/nfs_m/mca/build/src/irods-legacy/iRODS/lib/api/src/rcObjStat.c:

# ./configure needs a make clean to have effect
mca@cgpfoo:~/build/src/cctools$ make clean >/dev/null 2>&1
mca@cgpfoo:~/build/src/cctools$ (./configure --debug --prefix ~/build --with-irods-path /usr/local/iRODS               --without-system-{sand,allpairs,wavefront,makeflow,resource_monitor,doc} ;             make) >/dev/null 2>&1; objdump -WL parrot/src/parrot_run| grep -E 'iRODS/.*/rcObjStat'
CU: /usr/local/iRODS/lib/api/src/rcObjStat.c:
```
It's a minor issue but it could cause confusion when debugging other things and it's not obvious until you get a stacktrace or something.  I don't need it fixed, I'll probably remember next time.
Hope this is useful,

**Comment by batrick** [comment]
@mcast generally it's difficult to correctly detect configure changes and rebuild the right objects. I don't know of any projects that handle this. The usual advice is to do `make clean` anytime you reconfigure.

**Comment by batrick** [comment]
Also, since rebuilding can take a while, you might try using `make -jN` with `N` as your # of cores. For my workstation, that can cut the time to build by 66%.

**Comment by mcast** [comment]
I couldn't figure out a way to do it from `rules.mk`, which would seem like a useful benefit for a small change.
It is easy enough in the `*/src/Makefiles`, but maybe it's not worth the maintenance of ~20 copies in sub-Makefiles, presumably each subtly different.
```diff
diff --git a/parrot/src/Makefile b/parrot/src/Makefile
index d0112ef..a98afba 100644
--- a/parrot/src/Makefile
+++ b/parrot/src/Makefile
@@ -21,6 +21,9 @@ endif
 
 all: $(TARGETS)
 
+# rebuild after ./configure because $CCTOOLS_* have changed
+$(OBJECTS): ../../config.mk
+
 $(OBJECTS_PARROT_RUN): tracer.table.h tracer.table.c tracer.table64.h tracer.table64.c
 
 tracer.table.h tracer.table.c tracer.table64.h tracer.table64.c: tracer.table.pl syscall_parrot.tbl
```

**Comment by batrick** [comment]
Well, if we were to rebuild every object if `config.mk` changes, you might as well just do `make clean` first, right? It accomplishes the same thing. So, perhaps the better approach would be to run `make clean` in configure if `config.mk` already exists.

**Comment by mcast** [comment]
Yes, makes sense - PR offered.
