### ISSUE TITLE
make rpms for cctools

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#721]
While we still want to support user-level builds of cctools, it's time that we had rpms for installation.
This now seems to be feasible since our most important dependencies (cvmfs, globus, etc) are now available in rpm form.

Figure out how to write an rpm file.
Write an rpm file for cctools.
Figure out the complete set of rpm build dependencies.
Get the rpm file into our repository.
Make building rpms part of the auto build process.

**Comment by jblomer** [comment]
Hi Doug,

for CernVM I created a very simple RPM spec file a while ago: https://github.com/cernvm/renegade/blob/master/cctools/cctools.spec
Perhaps you can use it as a starting point.  

From experience with cvmfs, it is very easy to upset people with "wrong" packaging.  But it seems that the Fedora guidelines are widely accepted:
https://fedoraproject.org/wiki/How_to_create_an_RPM_package

Cheers,
Jakob

**Comment by dthain** [comment]
Excellent, thank you!

**Comment by hmeng-19** [comment]
I can take this one.

**Comment by hmeng-19** [comment]
I can take this one.

**Comment by dthain** [comment]
Go for it!

**Comment by hmeng-19** [comment]
I started working on the cctools rpm package, here are the problems about the structure of the cctools binary directory we need to concern for now:
(1) Add `README` and `LICENSE` files somewhere into our binary directory;
(2) Currently, `work_queue_example.py` and `work_queue_example.pl` are executables and should not be put into `cctools/doc`;
(3) `cctools/doc` and `cctools/etc` are not standard subdirectories, the standard directoreis are X11R6, X386, bin, games, include, lib, lib64, local, sbin, share, src, spool, tmp.
(4) We have several `*.so` files (`libparrot_helper.so`, `librmonitor_helper.so`) whose file naming are not under version control, like `libparrot_helper.so.0.n`. RPM recommends the naming all the upstream shared library dependencies should be under version control.
(5) The perl module in our cctools are put in `cctools/lib/perl5/site_perl`. However, `site_perl` is not a standard subdirectories. The standard directory should be `vendor_perl`.

As for these problems, we have two choices:
1) change the configuration of our cctools (Makefile) to follow the tradition of RPM;
2) Keep our Makefile, change the SPEC file of RPM.

**Comment by dthain** [comment]
1) Do it
2) The example code is part of the documentation, so it is in the right place.
3) Not necessary to install doc and etc as part of the RPM
4) Dig deeper to understand the library versioning and why it is required.  Note that we do not link any programs against these libraries, they are there solely for the purpose of modifying program behavior via LD_PRELOAD.
5) Again, dig deeper to understand the difference between site_perl and vendor_perl and why we should use one over the other.

For the moment, just modify the RPM to do the right thing, rather than our Makefile.

**Comment by hmeng-19** [comment]
@dthain , please check the pull request #736 which reorganized the binary directory of cctools.
Go back to the five questions mentioned above:
Now the problems (1) ~ (3) are solved by the pull request #736 .

As for the problem(4), if the *so files within our cctools binary dir are designed to modify program behavoir via LD_PRELOAD, then it is not necessary to follow the naming recommendations of shared libraries (http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html). 

As for the problem(5), site_perl is used to store the perl modules installed by the local system administrator; while vendor_perl is used to store the perl modules installed by package managers. Our usage case here (work queue modules) is a good fit to site_perl. So there is no necessary to change it.

**Comment by dthain** [comment]
Re site_perl/vendor_perl, what do other rpm packages do?

**Comment by hmeng-19** [comment]
As for the problem(5), I must admit that I did not really find lots of packages like `cctools` which creates new perl modules. 

The perl rpm package I saw (http://www.rpmseek.com/rpm-pl/perl.html?hl=com&cx=0) put all the stuff in the `site_perl` (it even does not include a `vendor_perl` subdir. However, on my own laptop (arch linux), everything is put into `vendor_perl` by the package manager, and the `site_perl` dir is empty. 

I doubt there is more clear recommendations about the usage of `vendor_perl` and `site_perl`. We may do not want to investigate our time on it. 

For now, I think we can keep our current perl module location. At least, it looks consistent with the perl rpm itself.

**Comment by btovar** [comment]
We want site_perl.

vendor_perl is for perl modules prepared by the distribution. site_perl for everyone else.

**Comment by dthain** [comment]
Please add this to our repo under `packaging/rpm/cctools.spec`

**Comment by hmeng-19** [comment]
@dthain , please check #766 .

**Comment by dthain** [comment]
Fixed by pr #766
