### ISSUE TITLE
Parrot with iRODS no longer asks for password

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#725]
If we try to use an iRODS server, we expect to see:

````
$ ./parrot_run -d all /bin/ls /irods/serv/
Enter your current iRODS password:
````

This no longer works as, by default, Parrot runs the application (`ls`) in its own **foreground** process group. So when the iRODS library tries to read the password from the terminal, it stops indefinitely due to `SIGTTIN`. (Actually, the library waits on a forked child that stops indefinitely.)

One way to fix this is to use the recently added `--no-set-foreground` option to Parrot. Then we can do:

````
$ ./parrot_run --no-set-foreground /bin/ls /irods/host:port/
Enter your current iRODS password:
tempZone
````

Unfortunately this isn't completely correct. As soon as we execute a shell that makes its own process groups, it fails again.

We need to inform the user that reading the password from the terminal might not work, and to suggest a workaround.

**Comment by dthain** [comment]
With the irods tools in general, it is usually assumed that the user runs `iinit` on the command line first, in order to log in, before running other i-commands.  So, it's ok to encourage `iinit; parrot_run` in the docs.

But,  what I don't want to see is parrot_run hanging silently just because rods is trying to access the terminal.

**Comment by dthain** [comment]
What we need here is a programmatic way to detect whether `iinit` has already been done.

**Comment by btovar** [comment]
iinit creates the file: ~/.irods/.irodsA. We could check for that. The ~/ I assume comes from the value of irods_home when running ienv. I would guess there is some API to get the values printed by ienv.
