### ISSUE TITLE
optimization of Allpairs in the symmetric case

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#731]
Currently, `Allpairs(setA,setB, Func)` applies `Func` on each pair of A[i] and B[j]. If the length of A is m, and the length of B is n, `Func` will execute `m x n` times totally.

Problem:
In the case of A=B (i.e., m=n, A[i] = B[i]), `Func(A[i], B[j])` and `Func(A[j], B[i])` are duplicate. Totally nearly half of the executions of Func are unnecessary. 
We need to optimize Allpairs to avoid doing the same computing twice.

Solution:
If i<=j, do Func(A[i], B[j]); if i>j, do nothing.

Potential Problem:
`allpairs_master` can set the width and height of one work unit. The modification of `allpairs_master` should try to avoid splitting work units unevenly.

**Comment by dthain** [comment]
For *some* functions F(x,y) = F(y,x), but not for all.  So, this should be an option that the user can turn on or off.

You are correct that the resulting work units near the diagonal will be smaller than the others.  Don't worry about this -- the complexity of equal-sized work units is not worth the trouble.

**Comment by hmeng-19** [comment]
Okay. I will add an option (something like `--symmetric`) to `allpairs_multicore` and `allpairs_master` for now without worrying about the size of work units.
