### ISSUE TITLE
parrot-cvmfs build and test

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#738]
Per @bbockelm commenting on the parrot-cvmfs interface
- It seems that the 4.4.0 release isn't tagged in github? Something break in the release process?
- It would be beneficial if "parrot_run -v" recorded the configure flags used for CVMFS.
- Can we get some unit test coverage for the various configuration options?  Particularly:
    Make sure alien cache can be specified; detect configuration key name changes.
    Validate that multiple instance of parrot can use alien cache at the same time.

@btovar please take a look

**Comment by btovar** [comment]
Closed with:
f5a3eea661e2921d056cd6949341b7f927ecdbed
and #741
