### ISSUE TITLE
"Text file busy" from parrot_run / CVMFS / alien_cache

### ISSUE THREAD

**Issue by bbockelm** [cooperative-computing-lab/cctools#742]
Hi,

When running parrot_run with CVMFS and alien_cache, I'm getting the following error message from our job scripts:

```
CRITICAL:root:Error running SCRAM
CRITICAL:root:
        Scram Command Diagnostic:
        Command : scramv1
        Architecture: slc5_amd64_gcc472
        Executed: eval `scramv1 ru -sh`
        Exit Status: 4
        Stdout:
        Stderr: /usr/bin/env: perl: Text file busy

```

This appears to occur when many jobs startup simultaneously - I'm guessing that either parrot or libcvmfs is opening files in the cache as writable?

Brian

**Comment by btovar** [comment]
Brian,

We have seen this before, but we are not able to reproduce it. Do you have an easy way to reproduce it?

Also, which version of cvmfs are you using?

**Comment by bbockelm** [comment]
Hi,

This is with 2.1.20.  I have found no easy way to reproduce this - only appears in production when about ~8 jobs are started simultaneously on a single host.

Brian

**Comment by bbockelm** [comment]
One thought - this is within the startup scripts for our jobs.  It's likely (maybe 80% confidence) that the file being accessed is already in the alien cache (cache hit).

**Comment by btovar** [comment]
Yes, I think so too. It is tricky to reproduce because we only get an error with executable files (hence the text file busy error), but most file accessed are not executable.

**Comment by dthain** [comment]
The `-d all` output would be useful to distinguish the system call and/or layer that is generating ETXTBSY.

**Comment by bbockelm** [comment]
:/ @dthain unfortunately, "-d all" is several hundred of MB so that already got squelched.

Let's ignore my last comment.  I think this is a perfectly possible sequence of events (assume an empty cache and 'foo' is an executable and glossing over details of filenames):
- Parrot process 1 tries to execute foo; file is not present in cache.
- Parrot process 2 tries to execute foo; file is not present in cache.
- Parrot process 1 starts downloading foo to temp file foo.1
- Parrot process 2 starts downloading foo to temp file foo.2
- Parrot process 1 finishes download of foo.1.
- Parrot process 1 renames foo.1 to foo inside the cache
- Parrot process 1 execs foo
- Parrot process 2 finishes download of foo.2.
- Parrot process 2 renames foo.2 to foo.  Gets ETXTBSY.  Boom.

A similar sequence of events can be done from within your shell:

$ cp /bin/sh /tmp/foo_sh
$ /tmp/foo_sh
$ echo "hi" >> /tmp/foo_sh
$ cp /bin/sh /tmp/foo_sh
cp: cannot create regular file `/tmp/foo_sh': Text file busy

I think libcvmfs ought to ignore this error on rename.  Can someone loop in the CVMFS folks?

**Comment by batrick** [comment]
Brian, that code should work if you use mv and not cp.

My instinct on this bug is that the rename is being done before close, so another process tries to exec the file before the writable handle is closed.

**Comment by bbockelm** [comment]
doh, yup, you're right.

That was my instinct too, but I can't see anything obvious in the cache code:

https://github.com/cvmfs/cvmfs/blob/c7c4179d6de3dac2b7f7dd6f7f97f3b731732f42/cvmfs/cache.cc

**Comment by dthain** [comment]
If the problem is related to executing programs, then the parrot file cache becomes involved, in addition to the cvmfs cache, because a locally accessible copy is needed to call exec. `decode_execve() -> pfs_get_local_name() -> pfs_open_cached()`

So, the possible culprit is in dttools/file_cache.c:file_cache_commit

@btovar suggest that you put in a check for ETXTBSY there and emit a big fat warning message there.  That way, we will know if that is the source of the bug.

**Comment by btovar** [comment]
That sounds like a good idea, thanks for the suggestion.

**Comment by bbockelm** [comment]
Ah - sure enough, file_cache_open in ddtools unconditionally opens the file as O_RDWR.  pfs_cache_open doesn't pass along the flags it wants:

https://github.com/cooperative-computing-lab/cctools/blob/8d9939530f5082de49478695d4ab0260414ace89/parrot/src/pfs_file_cache.cc#L207

So, in the case of a cache hit, a writable FD is held to the executable file here:

https://github.com/cooperative-computing-lab/cctools/blob/8d9939530f5082de49478695d4ab0260414ace89/parrot/src/pfs_sys.cc#L509

(and closed shortly thereafter).

The race condition is relatively small - if a process is already executing, the cache open will fail (and a new copy is made).  That's probably why we trigger this on startup (where we have many concurrent jobs starting short-lived perl scripts).

**Comment by bbockelm** [comment]
@btovar - any luck?

We'd like to ramp up scale tomorrow, so I have an opportunity to roll out a patch to our private build.

**Comment by btovar** [comment]
Not yet...

**Comment by bbockelm** [comment]
alright, I'll keep an eye out on the ticket!

**Comment by btovar** [comment]
Brian,

If you are going to test tomorrow, here is a branch with the debug message:

tag: release/4.4.1bbmsg 
(commit: e24330eeeb166a37bf798dc5bc027683785ef830)

**Comment by btovar** [comment]
@bbockelm, I added Patrick's commit to the current release base:
commit: 1739ef6cb35375fc6fa5577cdf68f38371bbc66d

**Comment by dthain** [comment]
@bbockelm if you have the time to do it, it would be helpful to first run the commit from @btovar that has just the added debug message, so that we can confirm that this is the source of your problems.  

The `O_RDWR` issue is definitely a bug, but it may not be the *only* bug!

**Comment by btovar** [comment]
Back-porting to the release version, there are the commits:

e24330eeeb166a37bf798dc5bc027683785ef830   debug message
db48309ea8672b6e62412567e1350780df4c3a08  Patrick's fix

**Comment by batrick** [comment]
@bbockelm is this fixed for you now?

**Comment by bbockelm** [comment]
So far so good!

I want to wait a by more before putting out the Mission Accomplished banner.  Can probably close the ticket for now.
