### ISSUE TITLE
Autobuild Platform Names

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#744]
The three docker-enabled platforms in autobuild should have more descritive names.
Instead of simply centos, debian, ubuntu, they should be x86_64-distro-version, like the other platforms.

**Comment by batrick** [comment]
We will need to add more Condor requirements for the docker builds as well. So x86_64-ubuntu-14.04 is actually run on an x86_64 machine.

I'll work on this one later this week.

**Comment by batrick** [comment]
Moved to autobuild issues.
