### ISSUE TITLE
Autobuild Docker Images

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#747]
Take a look at the docker images here:
https://registry.hub.docker.com/repos/cclnd/

Note that `ubuntu` is a base ubuntu image while `cctools-env-full-ubuntu` is derived from ubuntu, with all of the necessary cctools dependencies installed.  Same for `centos` and `debian`

Now, builds on those platforms are currently failing tests because the platforms do not have some essential tools installed: `curl ImageMagick python perl`.  So, we need to re-build those images with the missing packages.

@vhawley Please post (right here would be fine) the Dockerfiles that you used to generate these images.  We need to adjust them in order to generate new images...

**Comment by hmeng-19** [comment]
I downloaded the two centos images, the cctools-env-full-centos lookes a little large (1.7GB). What does `full` mean here?
 
    hmeng@hmeng ~$ docker images
    REPOSITORY                      TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
    cclnd/cctools-env-centos        latest              6a3eacc5f458        11 days ago         542.9 MB
    cclnd/cctools-env-full-centos   latest              138cdf5a2058        11 days ago         1.734 GB

**Comment by dthain** [comment]
@vhawley can you enlighten us?

**Comment by batrick** [comment]
Moved to autobuild issues.
