### ISSUE TITLE
Python + Work Queue = Segmentation Fault

### ISSUE THREAD

**Issue by pivie** [cooperative-computing-lab/cctools#755]
I am still having trouble with a segmentation fault running a work queue master inside of python. I was just going to try to figure things out on my own, but Anna Woodard is getting seg faults in Python also. They are trying to do a scale run this Friday, so I am hoping for some help to get it resolved more quickly. She is going to try to get a backtrace, but I have included mine below.

I think I am using the system version of work queue:
pivie@crcfe02> echo $PYTHONPATH
/afs/nd.edu/user37/ccl/software/cctools/lib/python2.6/site-packages:/afs/crc.nd.edu/user/p/pivie/cctools/lib/python2.6/site-packages:/afs/crc.nd.edu/user/p/pivie/local/lib/python2.7/site_packages

And here is the error I get.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff021c554 in fetch_output_from_worker (q=0xc382d0, w=0x0, taskid=59) at work_queue.c:1115
warning: Source file is more recent than executable.
1115		t = itable_lookup(w->current_tasks, taskid);
(gdb) backtrace
#0  0x00007ffff021c554 in fetch_output_from_worker (q=0xc382d0, w=0x0, taskid=59) at work_queue.c:1115
#1  0x00007ffff0221ecf in receive_one_task (q=0xc382d0) at work_queue.c:2827
#2  0x00007ffff0225805 in wait_loop_transfer_tasks (q=0xc382d0, stoptime=1431537255) at work_queue.c:4236
#3  0x00007ffff0225a3a in work_queue_wait_internal (q=0xc382d0, timeout=5, foreman_uplink=0x0, foreman_uplink_active=0x0) at work_queue.c:4335
#4  0x00007ffff0225432 in work_queue_wait (q=0xc382d0, timeout=5) at work_queue.c:4139
#5  0x00007ffff0213bc3 in _wrap_work_queue_wait (self=<value optimized out>, args=<value optimized out>) at work_queue_wrap.c:9442
#6  0x00000000004a8da0 in call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4033
#7  PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2679
#8  0x00000000004aa887 in PyEval_EvalCodeEx (co=0x7ffff1fcef30, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>,
    argcount=2, kws=0xbe0588, kwcount=0, defs=0x7ffff1f6c3a8, defcount=1, closure=0x0) at Python/ceval.c:3265
#9  0x00000000004a8a34 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4129
#10 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4054
#11 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2679
#12 0x00000000004a9d15 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4119
#13 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4054
#14 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2679
#15 0x00000000004a9d15 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4119
#16 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4054
#17 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2679
#18 0x00000000004a9d15 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4119
#19 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4054
#20 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2679
#21 0x00000000004a9d15 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4119
#22 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4054
#23 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2679
#24 0x00000000004aa887 in PyEval_EvalCodeEx (co=0x7ffff7ebe130, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>,
    argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3265
#25 0x00000000004aa992 in PyEval_EvalCode (co=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>) at Python/ceval.c:673
#26 0x00000000004cb0ae in run_mod (fp=0x86da60, filename=0x7fffffffde96 "/afs/crc.nd.edu/user/p/pivie/local/bin/prune", start=<value optimized out>,
    globals=0x7ffff7f73168, locals=0x7ffff7f73168, closeit=1, flags=0x7fffffffda00) at Python/pythonrun.c:1377
#27 PyRun_FileExFlags (fp=0x86da60, filename=0x7fffffffde96 "/afs/crc.nd.edu/user/p/pivie/local/bin/prune", start=<value optimized out>, globals=0x7ffff7f73168,
    locals=0x7ffff7f73168, closeit=1, flags=0x7fffffffda00) at Python/pythonrun.c:1363
#28 0x00000000004cb2d7 in PyRun_SimpleFileExFlags (fp=0x86da60, filename=0x7fffffffde96 "/afs/crc.nd.edu/user/p/pivie/local/bin/prune", closeit=1,
    flags=0x7fffffffda00) at Python/pythonrun.c:955
#29 0x0000000000414f72 in Py_Main (argc=<value optimized out>, argv=<value optimized out>) at Modules/main.c:640

**Comment by annawoodard** [comment]
Unfortunately I got disconnected and didn't get the whole thing, but here's the beginning of my trace:

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff07edd2c in fetch_output_from_worker (q=0x23b8ad0, w=0x0, taskid=287) at  work_queue.c:1114
    1114    work_queue.c: No such file or directory.

I'll try again. Please let me know if there's any other information I can provide that would be helpful.

**Comment by btovar** [comment]
On it.

**Comment by btovar** [comment]
Fixed in master.
