### ISSUE TITLE
Chirp Jobs need cleaned up on exit/signal

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#760]
Right now jobs are not killed when the Chirp server exits. This is partially a consequence of each job being in its own process group (so signals sent to the Chirp server are not passed along to jobs).

This will require the Chirp scheduler to periodically check for an abort condition and the kill all running jobs.

Related to #602.

**Comment by batrick** [comment]
@btovar I think this is your problem, right?

**Comment by btovar** [comment]
That's correct.

**Comment by dthain** [comment]
Closing old bugs without a driving use case.
