### ISSUE TITLE
No tilde expansion in `./configure --prefix=~/cctools`

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#764]
Problem:
Commit 2ed241214a58207175958e47efc3a34aebfdf16f tries to allow the `--prefix` option of `configure` to support `=`. However, if a user runs `configure` in the following way: `./configure --prefix=~/cctools`, it will not create the cctools binary directory under the home dirctory, instead, it creates a directory named `~` under the current directory and puts `cctools` under it like this:

    cp config.mk /afs/nd.edu/user20/hmeng/git-development/cctools/~/cctools/etc/
    mkdir -p /afs/nd.edu/user20/hmeng/git-development/cctools/~/cctools/doc
    cp COPYING /afs/nd.edu/user20/hmeng/git-development/cctools/~/cctools/doc/
    cp README /afs/nd.edu/user20/hmeng/git-development/cctools/~/cctools/doc/

The reason for this is:
Each shell command separates words by blanks. Tilde expansion only happens when the tilde itself is the first character of a word.
In the above case, `--prefix=~/cctools` is treated as a single word and there is no tilde expansion for `~/cctools` because it is not the first character of the whole word `--prefix=~/cctools`.

One Solution:
After positional parameters are separated using the new IFS (`<space>=`), forcefully do  tilde expansion on each positional parameter.

Potential Problem of the solution:
The tilde prefix can be used in multiple ways (http://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html
), the tilde expansion function should cover each case:
 
    ~
    ~/foo
    ~fred/foo
    ~+/foo
    ~-/foo
    ~N
    ~+N
    ~-N

**Comment by dthain** [comment]
This is creating more problems then it is solving.
Just use a space after --prefix and be done with it.
We have bigger fish to fry.

**Comment by hmeng-19** [comment]
@btovar , please check #769 .

**Comment by btovar** [comment]
See #784
