### ISSUE TITLE
'Command not found' from parrot_run accessing CVMFS with alien_cache enabled

### ISSUE THREAD

**Issue by annawoodard** [cooperative-computing-lab/cctools#770]
When starting many jobs simultaneously with WQ, many initial jobs fail because they can't find something they need in CVMFS, I see: ```scramv1: command not found```. It seems like it may be related to #742 (but I don't see 'text file busy.') The problem subsides after a while, but it gets worse as I scale up workers.

I'm using cctools from: ```/afs/crc.nd.edu/group/ccl/software/cctools-ndcms-after-scale-test/x86_64/redhat6/```.

I've put logs with debugging enabled for a job with this issue and a successful job, along with the script I'm running here:

    /afs/crc.nd.edu/user/a/awoodard/Public/error_code_173/failed.log
    /afs/crc.nd.edu/user/a/awoodard/Public/error_code_173/succeeded.log
    /afs/crc.nd.edu/user/a/awoodard/Public/error_code_173/wrapper.sh

**Comment by hmeng-19** [comment]
Hi Anna,
Thanks for your report. We will work on it.

Best,
Haiyan

**Comment by batrick** [comment]
@btovar does that branch have the latest parrot?

**Comment by btovar** [comment]
Yes, it is the parrot from master as of Monday.

**Comment by batrick** [comment]
@annawoodard I just got a chance to look at this more closely. It looks like in the failed test that it doesn't search `/cvmfs/cms.cern.ch/common/scramv1` after `lstat(/3.2.11-1/lcg/bin/scramv1)`. Instead it looks at `/opt/crc/gcc/4.6.2/gcc-4.4.7/bin/scramv1`.

I'm not really sure what that means... perhaps the bug is earlier in the program. Would it be feasible to get a full debug log (`-d all`) on a failed and successful run?

**Comment by annawoodard** [comment]
Sorry about the delay, @batrick. I've put the full debug logs for a failed and successful run here: ```/afs/crc.nd.edu/user/a/awoodard/Public/error_code_173/*.dall.log```. Please let me know if there's any other information I can help with.

**Comment by batrick** [comment]
I believe I located the source of the problem, early in the program:


````
2015/05/22 15:17:19.54 parrot_run[8453] <child:8497> syscall: open
2015/05/22 15:17:19.54 parrot_run[8453] <child:8497> libcall: open /cvmfs/cms.cern.ch/cmsset_default.sh 0 4404624
2015/05/22 15:17:19.54 parrot_run[8453] <child:8497> resolve: /cvmfs/cms.cern.ch/cmsset_default.sh = /cvmfs/cms.cern.ch/cmsset_default.sh
2015/05/22 15:17:19.54 parrot_run[8453] <child:8497> cvmfs: Using libcvmfs version: 2
2015/05/22 15:17:19.54 parrot_run[8453] <child:8497> cvmfs: setenv CERNVM_UUID=`parrot-4-6-0'
2015/05/22 15:17:19.54 parrot_run[8453] <child:8497> debug: Using CVMFS global options: cache_directory=/var/condor/execute/dir_8447/ex_parrot_awoodard/cvmfs,alien_cache,max_open_files=500,change_to_cache_directory,log_prefix=libcvmfs
2015/05/22 15:17:19.55 parrot_run[8453] <child:8497> cvmfs: filesystem configured *.cern.ch with repo path  and options repo_name=.cern.ch,timeout=3600,timeout_direct=3600,proxies=http://129.74.85.45:3128,pubkey=<BUILTIN-cern.ch.pub>,url=http://cvmfs.fnal.gov:8000/opt/
2015/05/22 15:17:19.55 parrot_run[8453] <child:8497> cvmfs: filesystem configured from pattern: cms.cern.ch with repo path  and options repo_name=cms.cern.ch,timeout=3600,timeout_direct=3600,proxies=http://129.74.85.45:3128,pubkey=<BUILTIN-cern.ch.pub>,url=http://cvmfs.fnal.gov:8000/opt/cms
2015/05/22 15:17:19.55 parrot_run[8453] <child:8497> cvmfs: activating repository cms.cern.ch
2015/05/22 15:17:19.55 parrot_run[8453] <child:8497> cvmfs: checking lock file /var/condor/execute/dir_8447/ex_parrot_awoodard/cvmfs/cms.cern.ch/lock.cms.cern.ch
2015/05/22 15:17:19.55 parrot_run[8453] <child:8497> cvmfs: cvmfs_attach_repo(repo_name=cms.cern.ch,timeout=3600,timeout_direct=3600,proxies=http://129.74.85.45:3128,pubkey=/var/condor/execute/dir_8447/ex_parrot_awoodard/parrot-instance.uRF6Gs/cvmfs_locks_w5SCBE/cvmfs/cern.ch.pub,url=http://cvmfs.fnal.gov:8000/opt/cms)
2015/05/22 15:17:19.55 parrot_run[8453] <child:8497> cvmfs: CernVM-FS: using public key(s) /var/condor/execute/dir_8447/ex_parrot_awoodard/parrot-instance.uRF6Gs/cvmfs_locks_w5SCBE/cvmfs/cern.ch.pub
2015/05/22 15:17:23.93 parrot_run[8453] <child:8497> cvmfs: CernVM-FS: linking /cvmfs/cms.cern.ch to repository cms.cern.ch
2015/05/22 15:17:23.95 parrot_run[8453] <child:8497> cvmfs: lstat(/cmsset_default.sh)
2015/05/22 15:17:23.95 parrot_run[8453] <child:8497> cvmfs: stat(/cmsset_default.sh)
2015/05/22 15:17:23.95 parrot_run[8453] <child:8497> cvmfs: open(/cmsset_default.sh)
2015/05/22 15:17:23.95 parrot_run[8453] <child:8497> cvmfs: open file descriptor limit exceeded
2015/05/22 15:17:23.95 parrot_run[8453] <child:8497> libcall: = -1 Too many open files [pfs_open]
2015/05/22 15:17:23.95 parrot_run[8453] <child:8497> syscall: = -24 Too many open files [open]
````

CVMFS is giving us the `EMFILE` error back. This happens here in cvmfs:

https://github.com/cvmfs/cvmfs/blob/a39a2a398a3e90afaf16f5800445da71debcd5bc/cvmfs/libcvmfs_int.cc#L609

This is the first point in the program where Parrot interacts with cvmfs so there are no other open cvmfs files (therefore, no reason for an EMFILE error). I think this is a bug in cvmfs. @dthain/@btovar, how do you want to proceed?

**Comment by btovar** [comment]
@jblomer, could we provide more information regarding this issue?

**Comment by jblomer** [comment]
Could the problem be the `max_open_files=500` mount option in conjunction with `static const int kNumReservedFd = 512;` in libcvmfs.h?  The `kNumReservedFd` is a safe guard to make sure there are enough internal file descriptors available to cvmfs for pipes, file catalog management and so on.  This probably makes more sense for the Fuse module that has to sustain multiple, possibly rouge clients.  Can you try setting this constant to 0 for the library and/or increasing the `max_open_files` mount option.

**Comment by btovar** [comment]
I'll try that. @batrick, I'll point to you such libcvmfs version.

**Comment by dthain** [comment]
Good catch, @batrick

**Comment by batrick** [comment]
@jblomer this seems to only happen when running these tests at scale, and only for a few runs of Parrot. It would seem to me that the possibility you describe would affect all of the executions of Parrot?

**Comment by btovar** [comment]
@annawoodard, could you try  /afs/crc.nd.edu/group/ccl/software/cctools-a078e9c9d-cvmfs-d3f0ac3f5
?

**Comment by jblomer** [comment]
@batrick True.  How exactly does the scaling work?  Is it more parrot processes with the same workload each or are there more threads that could consume more file descriptors of a single parrot process?

**Comment by btovar** [comment]
@batrick Since several parrot instances may run on the same machine, I would not discard the fd reservation as an issue.

@jblomer More parrot instances with the same workload.

**Comment by jblomer** [comment]
Let me check if the problem is actually an uninitialized variable that happens to by <500 in a few cases.

**Comment by jblomer** [comment]
Can you try with the latest libcvmfs-stable branch?  I think an uninitialized variable can explain it.  I removed the counting of open file descriptors altogether from libcvmfs.  The LIBCVMFS_REVISION is bumped to 15.

Anyway, the mount option `max_open_files=500` is probably not what you want.  It restricts the process from 1024 to 500 concurrently open files.  The idea of this option was rather to increase the limit in case you are allowed to.

**Comment by annawoodard** [comment]
@btovar: for completeness, I tried with cctools-a078e9c9d-cvmfs-d3f0ac3f5, and got the same error. I put the logs in ```/afs/crc.nd.edu/user/a/awoodard/Public/error_code_173/*.cctools-a078e9c9d-cvmfs-d3f0ac3f5.dall.log```. I can test now with @jblomer's updates.

**Comment by btovar** [comment]
@annawoodard: @jblomer changes are now in: cctools-a078e9c9d-cvmfs-f50d781c0

**Comment by annawoodard** [comment]
It looks to me like the problem is solved-- I do not see any jobs failing with this error, whereas before it was very consistent for this workflow. I think we are safe to close the issue. Thanks so much for all the help, @batrick, @btovar, @jblomer!
