### ISSUE TITLE
CVMFS on x86_64-redhat5

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#777]
FYI, builds are failing b/c `/afs/crc.nd.edu/group/ccl/software/cctools-dependencies/x86_64/redhat5/cvmfs` exists but is empty.  Perhaps someone started a rebuild there but didn't complete it?  To allow builds to go forward, I am renaming the directory to cvmfs.old.  @btovar please take a look when you return.

**Comment by btovar** [comment]
Should be fixed now.
