### ISSUE TITLE
links not found with cvmfs and Parrot

### ISSUE THREAD

**Issue by annawoodard** [cooperative-computing-lab/cctools#778]
@btovar recently reported an issue where links are not found with cvmfs and Parrot:

> For example:
> /cvmfs/oasis.opensciencegrid.org/osg-software/osg-wn-client
> is a link to
> /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client
>
> This one fails:
> parrot_run ls -l /cvmfs/oasis.opensciencegrid.org/osg-software/osg-wn-client/3.2
>
> But this one works:
> parrot_run ls -l /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.2

Jakob found and corrected an error in the expand_path function in libcvmfs and bumped up LIBCVMFS_REVISION to 14. @btovar updated ```/afs/crc.nd.edu/group/ccl/software/cctools-ndcms-after-scale-test/x86_64/redhat6/bin``` with the new patch. Now both of the commands above are successful, but it's still not quite right:

    parrot_run ls /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.1/3.1.46/el6-x86_64/etc/grid-security/certificates
    ls: cannot open directory /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.1/3.1.46/el6-x86_64/etc/grid-security/certificates: No such file or directory
    ls -l /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.1/3.1.46/el6-x86_64/etc/grid-security/certificates
    lrwxrwxrwx 1 1027 1027 49 May 22 08:02 /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.1/3.1.46/el6-x86_64/etc/grid-security/certificates -> /cvmfs/oasis.opensciencegrid.org/mis/certificates

**Comment by btovar** [comment]
Anna, thanks for the report.

**Comment by annawoodard** [comment]
@btovar and @jblomer have explained that this is working as expected; it is a 'variant symlink' which resolves at runtime to the contents of the environment variable OASIS_CERTIFICATES. Thanks for the help, I think we can close this issue.
