### ISSUE TITLE
'bad ELF interpreter: No such file or directory' when using Parrot + CVMFS

### ISSUE THREAD

**Issue by annawoodard** [cooperative-computing-lab/cctools#781]
When running some workflows which use Parrot to access CVMFS, we see the following error:

    bash: /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_3_5/bin/slc6_amd64_gcc491/cmsRun: /cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/glibc/2.12-2/lib64/ld.so: bad ELF interpreter: No such file or directory

@matz-e has made a script which reproduces the problem here: ```/afs/crc.nd.edu/user/m/mwolf3/parrot_test.sh```.

I've put a log with -d all enabled here: ```/afs/crc.nd.edu/user/a/awoodard/Public/elf_error.log``` (using cctools from ```/afs/crc.nd.edu/group/ccl/software/cctools-a078e9c9d-cvmfs-f50d781c0```.) Bypassing Parrot and running on a machine with cvmfs mounted (earth.crc.nd.edu, for example) works fine.

**Comment by matz-e** [comment]
See also [this gist](https://gist.github.com/matz-e/c20ed81601013685604e).

**Comment by btovar** [comment]
@batrick, sounds like 32bit libraries are missing?

**Comment by batrick** [comment]
Historically, we would see bad elf interpreter because of problems with the channel. I'm taking a look now.

**Comment by batrick** [comment]
Oh, I see the problem:

````
$ parrot_run ldd /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_3_5/bin/slc6_amd64_gcc491/cmsRun
[...]
        /cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/glibc/2.12-2/lib64/ld.so => /lib64/ld-linux-x86-64.so.2 (0x00000030ede00000)
````

The loader is in /cvmfs which the kernel can't find. This is something that would be difficult for Parrot to fix as we would need to rewrite the executable's ELF headers to use a local (i.e. not /cvmfs) ld-linux.

I wonder if whoever compiled cmsRun needed to bundle their own ld.so?

[This feels like #678 is haunting me, demanding to be fixed.]

**Comment by batrick** [comment]
@annawoodard @matz-e you can use the `-l` option for Parrot as a temporary workaround:

`parrot_run -l /lib64/ld-linux-x86-64.so.2`

You will need to search for the Linux loader (as its name may be different among Condor nodes). That should be as simple as:

````
parrot_run -l "$(find /lib64 /lib -name 'ld-linux*.so.*' -print -quit)"
````

**Comment by dthain** [comment]
@jblomer do you have any idea whether  `/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/glibc/2.12-2/lib64/ld.so` is actually used as the linker for cms software stacks, or is it just there as a side-effect of a complete `glibc` install?

**Comment by jblomer** [comment]
@dthain I think it is used but mostly in order to stay in control, in order to patch glibc problems quickly and independently of the worker nodes.  Let me contact a CMS expert and put you in 'cc.

**Comment by matz-e** [comment]
@batrick thanks, that works.

**Comment by annawoodard** [comment]
We tested this and it is working well for us. THANK YOU everyone, especially @batrick and @btovar!

**Comment by dthain** [comment]
Nice work on an ugly bug!

**Comment by jblomer** [comment]
Very nice fix!

I think there is still a little issue with statically linked binaries.  The debug messages show
    
    2015/06/02 21:34:12.13 parrot_run[29448] <child:29469> debug: prepare_exe: /home/atlas/ucvm-docker/UCVM/busybox PT_INTERP is
    2015/06/02 21:34:12.13 parrot_run[29448] <child:29469> process: prepare_exe: getting physical name of loader
    2015/06/02 21:34:12.13 parrot_run[29448] <child:29469> libcall: open  0 0
    2015/06/02 21:34:12.13 parrot_run[29448] <child:29469> libcall: = -1 No such file or directory [pfs_open_cached]

You can find a statically linked binary for testing in /afs/cern.ch/user/j/jblomer/public/busybox.  Please let me know if you need any other information.

**Comment by batrick** [comment]
Thanks @jblomer, I've got a fix incoming.

**Comment by davidlt** [comment]
Just a note. You have to understand that reverting dynamic loader, might break CMSSW, because it causes out-of-bounds write (damages memory) with standard system dynamic loader.

**Comment by bbockelm** [comment]
Hi @davidlt -

The patch in this branch switches back to the dynamic loader used by CMSSW.  See #786

Brian

**Comment by davidlt** [comment]
I looked at it. This is something we used to do in CMSSW. I had a bash wrapper, in which would exec dynamic loader <actual_path_to_cmsRUn> <args> that replace current bash process. Later this was changed to ELF patching at install time.

I copied from T3_US_Princeton_ARM parrot tarball to CERN on SLC6 machine without CVMFS and attempt to launch CMSSW:
```
bash-4.1$ cmsRun TTbar_8TeV_TuneCUETP8M1_cfi_GEN_SIM_RECOBEFMIX_DIGI_L1_L1Reco_RECO_EI_HLT_VALIDATION.py
bash: /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_0_pre5/bin/slc6_amd64_gcc491/cmsRun: /cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/glibc/2.17-78.el7_2.12-1.149.el6/lib64/ld.so: bad ELF interpreter: No such file or directory
```
So at least Parrot tarball is too old in factory.

**Comment by bbockelm** [comment]
Indeed - I haven't incorporated this patch yet.  I was going to fix the ARM issues first, verify it works with Justas, and then rebuild the tarball.

**Comment by batrick** [comment]
@davidlt please let us know if the newer version of Parrot doesn't work for you.
