### ISSUE TITLE
Broken symlink resolution in parrot + CVMFS?

### ISSUE THREAD

**Issue by matz-e** [cooperative-computing-lab/cctools#783]
Howdy,

I am trying to configure CVMFS as done within CMS, using an environment variable to set specify the target of a "variant?" symlink, that I think is also allowed to point outside CVMFS:

```
crcfe01: export CMS_LOCAL_SITE=$PWD/siteconfig
crcfe01: ls -l
total 4
drwxr-xr-x 4 mwolf3 campus 4096 May 27 07:25 siteconfig
crcfe01: parrot_run bash
[parrot] crcfe01: ls -l /cvmfs/cms.cern.ch/SITECONF/local
lrwxrwxrwx 1 root root 22 Jun 26  2013 /cvmfs/cms.cern.ch/SITECONF/local -> /tmp/mytest/siteconfig
[parrot] crcfe01: ls /cvmfs/cms.cern.ch/SITECONF/local
JobConfig  PhEDEx
[parrot] crcfe01: ls /cvmfs/cms.cern.ch/SITECONF/local/JobConfig
ls: cannot access /cvmfs/cms.cern.ch/SITECONF/local/JobConfig: No such file or directory
```

Shouldn't `JobConfig` be resolved to the symlinked directory?

**Comment by btovar** [comment]
@matz-e, in the current implementation of parrot, links cannot point outside cvmfs. For example, if you try CMS_LOCAL_SITE=T3_US_NotreDame, then the link works.

In the meantime, I would recommend using the mount options  as before (-m or -M).
