### ISSUE TITLE
Makeflow Docker Docs

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#787]
@charleszheng44 please add to `doc/makeflow.html` discussion of the docker support in Makeflow.

Add brief note about Docker support at the beginning of the manual, then add a section titled "Docker Support" just before the "Wrapper Commands" section.

Please expedite so this can be a part of the 5.0 release.

**Comment by charleszheng44** [comment]
I created a new pull request #791

**Comment by dthain** [comment]
Please make the changes to the Makeflow User Manual `doc/makeflow.html`

**Comment by dthain** [comment]
???
