### ISSUE TITLE
Parrot should have a system call to turn on debugging.

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#797]
We are increasingly seeing Parrot used as a wrapper for entire application frameworks (now even acting as an "init" process in Docker). It will become more important to be able to get debugging at choice moments. Editing the wrapper may not be feasible and may result log files that are too large.

I recommend we add a utility like `parrot_cp` which executes a new `parrot_debug` system call that sets flags, output file, etc.

**Comment by dthain** [comment]
That's an excellent idea.  You could go even farther and add `parrot_mount` to manipulate the namespace, unless the caller has locked it down as a sandbox.
