### ISSUE TITLE
wq_status foremen hierarchy with ssh tunnels does not work

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#817]
(per @matz-e)

If the foreman F connects to the master M via a tunnel, wq_status/pool does not show F as a foreman for M.

**Comment by btovar** [comment]
The problem here is that wq_status only knows about the catalog. When an anonymous foreman connects to a master (either directly or through an ssh-tunnel), the catalog does not know about it.

The solution would be for a master to report its hierarchy, rather than constructing it from the catalog.

**Comment by btovar** [comment]
@matz-e: is this still an issue? Do you have an example on when it occurs?

**Comment by matz-e** [comment]
I could re-produce that running distributed between CERN and ND again, but for me that's a fairly rare use-case by now. This is also more a graphical nit-pick than a hard issue…

**Comment by dthain** [comment]
Closing this issue b/c this is a design limitation; fixing it would be a very complex matter for a relatively small payoff.
