### ISSUE TITLE
Parrot's `getcwd` may return a path with a trailing slash, breaking some applications.

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#823]
UNIX makes no guarantees [1] about the form of paths returned by `getcwd`, only that it is an absolute path. However some applications [2] assume that the path returned by `getcwd` has no redundant trailing slashes.

Haiyan found this problem in a CMS application (made of Perl scripts) which would fail when a `getcwd` path had redundant terminating slashes. The Perl code is here [2]. The failing function is `verifypath`.

The fix for this problem is to simply strip trailing slashes in pfs_table::getcwd. PR incoming.

[1] http://pubs.opengroup.org/onlinepubs/009695399/functions/getcwd.html
[2] /cvmfs/cms.cern.ch/slc5_amd64_gcc434/cms/cmssw/CMSSW_4_2_8/bin/slc5_amd64_gcc434/SkelParser.pm

**Comment by batrick** [comment]
@btovar the fix for this should go in 5.0.

**Comment by hmeng-19** [comment]
@batrick , it solved the problem. Thanks.
