### ISSUE TITLE
Confuga should reclaim space used by deleted files

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#827]
A garbage collector needs to be written to remove replicas that are no longer referenced in the cluster (Confuga) namespace.

**Comment by dthain** [comment]
I'm a little confused between the bug title and the description.

Is the problem here that files deleted from the namespace are not deleted from the storage nodes?
Or that files still existing in the namespace may have too many replicas?

**Comment by batrick** [comment]
Both actually. But this issue is about the first one. I will improve the description.
