### ISSUE TITLE
Chirp error codes do not follow the protocol

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#835]
Several chirp operations return -1 on error. According to:

http://www.cse.nd.edu/~ccl/software/manuals/chirp_protocol.html

this should be interpreted as NOT_AUTHENTICATED, which is incorrect.

To fix it, no chirp_reli or chirp_client function should return -1, but the corresponding CHIRP_ERROR_*.

**Comment by batrick** [comment]
@btovar that protocol document is for the wire protocol. The client/reli interface is a library to operate over the Chirp wire protocol, without being sensitive to these details.

As I understand it, the protocol document was for standardizing the wire protocol so external projects like Condor could easily reimplement it for their own use.

**Comment by btovar** [comment]
I see. Is there a way to use chirp_reli and have informative error messages? (e.g. bad permissions v.s. bad path).

**Comment by batrick** [comment]
There's nothing like that presently.

**Comment by dthain** [comment]
I think you are both confused:

`chirp_client.c:convert_result()` converts the error on the wire to a global errno:
https://github.com/cooperative-computing-lab/cctools/blob/master/chirp/src/chirp_client.c#L71

This gets passed up through `chirp_client|chirp_reli|chirp_global|pfs_service_chirp|...` all the way back to the end user.

**Comment by btovar** [comment]
So, as a user of chirp_reli, I should just check errno?

**Comment by dthain** [comment]
Roger

**Comment by btovar** [comment]
Ah, sometimes the obvious answer...

Thanks!
