### ISSUE TITLE
Should cctools_python set PYTHONPATH?

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#847]
Right now to use Weaver and probably other tools we need the user to set `$PYTHONPATH` like so:

    env PYTHONPATH="$(dirname "$(which weaver)")/../lib/python2.6/site-packages/" weaver ...

which kinda stinks. Since we're already wrapping python to execute an appropriate version, we should set `PYTHONPATH` too since the location depends on the version selected. [In fact, the version on the system may be 2.6 but the library is in `lib/python2.7/`, yuck...]

Also, based on my recent experience using Weaver, the main drawback of `cctools_python` so far is that it must be in your path. Doing something like `./weaver` won't work anymore.

**Comment by batrick** [comment]
@dthain, comments?

**Comment by btovar** [comment]
I agree, PYTHONPATH should also be set in cctools_python.
