### ISSUE TITLE
Configuring with-system-path no does not disable that system.

### ISSUE THREAD

**Issue by nhazekam** [cooperative-computing-lab/cctools#855]
When trying to turn off Globus path for installing into Stampede, I used : 
./configure --with-globus-path=no

This then attempted to use the path no/... for globus configuration, when in reality it should turn it off. This may also be an issue on other --with-system-path configurations.

**Comment by dthain** [comment]
In general, simply omitting `--with-*-path` will leave the optional software unused.
Globus has a sepcial case in that `configure` looks for the environment variable `GLOBUS_LOCATION` and then automatically uses it.  Try unsetting the environment
variable, then run `configure` and see if that gives the desired result.

And perhaps we should just remove the automatic check for globus..

**Comment by nhazekam** [comment]
That worked to get cctools to compile correctly. Should we be concerned that modifying that path variable could break other programs, or should it just be advised to change it back after configuration?

**Comment by dthain** [comment]
Right, just change it for the build step.
And I think it's best to remove the check for GLOBUS_LOCATION from configure:219

**Comment by nhazekam** [comment]
Should I remove this and add it to my changes for batch system support?

**Comment by dthain** [comment]
yes
