### ISSUE TITLE
build out the test suite

### ISSUE THREAD

**Issue by psempoli** [cooperative-computing-lab/cctools#87]
--- dthain changed system to cctools at Thu, 24 Jan 2013 12:32:05 -0500 ---

--- dthain submitted bug at Thu, 13 Oct 2011 16:09:02 -0400 ---

Our current test suite is self-contained and designed to be portable, which is
good.  However, we really need it to test the hard, non-portable things, such
as testing the performance of chirp on hdfs, of parrot on root, of work queue
on azure, and so forth.  Put together a comprehensive test suite designed to
run only at Notre Dame, but to really exercise the system.

[Ported from prev. bugtracker]

**Comment by dthain** [comment]
Closing out low priority projects/bugs to avoid clutter.
