### ISSUE TITLE
Chirp putfile/getfile RPC stoptime is too coarse for aborting a failed transfer

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#882]
Chirp RPC uses a `time_t stoptime` to set a limit on the time the caller is willing to wait for an operation to take. The `chirp_reli` interface will also retry operations within this limit for failures like connection refused, connection reset, etc.

The problem with using a time limit is that it is too coarse to appropriately express the caller's wishes in this situation, especially for very large files (1GB+) . The caller necessarily picks a stoptime that is proportional to the size of the file, for example 60 seconds for a 60 KB file if the caller is willing to tolerate 1KB/s throughput. When the file is very large, this could easily lead to a timeout measured in weeks.

It's tempting to cap the maximum stoptime (or use a higher minimum bandwidth) but this is ultimately inflexible and I've hit artificial barriers like this before. Instead I propose that putfile/getfile have an added argument that limits the number of RPC (`chirp_client` calls) retries before giving up.

**Comment by dthain** [comment]
I can see how you run into this problem, but I'm not sure counting RPCs  is the right solution.

Time has a very clear interpretation for the end user and is set on the command line by most of our tools.  Under failure conditions, RPCs are delayed by a random exponential backoff.  How would you explain to the end user how to pick a good number for total RPC round trips?

**Comment by batrick** [comment]
Perhaps a better metric would be the number of seconds spent waiting to retry. e.g. don't exceed net 5 minutes of waiting to retry.

**Comment by dthain** [comment]
@batrick I don't see a clear way forward on this issue, do you?

**Comment by batrick** [comment]
I like the idea of adding "number of seconds spent waiting to retry". I was planning to implement something along those lines after the dissertation/slides are done.

**Comment by dthain** [comment]
Closing this as wontfix, in the absence of an end user driving the need.
