### ISSUE TITLE
Add support for multiple challenge directories for unix authentication

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#890]
I think all of our Chirp servers use the ND.EDU AFS space for the challenge directory which prevents clients operating in the CRC.ND.EDU AFS space from doing unix authentication. [In fact, CRC machines have kerberos configured so clients can't get ND.EDU kerberos tickets due to blacklisted ciphers.]  For this reason, it would be useful if we could extend the unix authentication mechanism to have multiple challenge directories depending on the network file system the client has access to.

In addition to having the two AFS realms, ND.EDU and CRC.ND.EDU, we could also use the pscratch (NFS) file system as a challenge directory. This would allow jobs run in SGE to also authenticate using unix.

This idea would probably require creating a new authentication method ("unix2"??) in order to maintain backwards compatibility.

**Comment by dthain** [comment]
Or it may just be time to bite the bullet and move to an assumption of crc credentials for everyone.
Do we have a use case for unix authentication of users that are *not* part of the crc?

**Comment by batrick** [comment]
I don't know of one.

**Comment by dthain** [comment]
Closing this as wontfix, since it's a very narrow use case with no immediate user.
