### ISSUE TITLE
follow up of issue #919

### ISSUE THREAD

**Issue by tommasoboccali** [cooperative-computing-lab/cctools#921]
Hi, Jacob prepared a uCERNVM with the fix as in issue 919.

the next problem is:

bash-4.1# voms-proxy-init 
/cvmfs/grid.cern.ch/emi-ui-3.15.3-1_sl6v1/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.35.x86_64/jre/lib/rt.jar: error reading zip file
/cvmfs/grid.cern.ch/emi-ui-3.15.3-1_sl6v1/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.35.x86_64/jre/lib/rt.jar: error reading zip file
/cvmfs/grid.cern.ch/emi-ui-3.15.3-1_sl6v1/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.35.x86_64/jre/lib/rt.jar: error reading zip file
Error occurred during initialization of VM
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:411)
	at java.lang.System.initProperties(Native Method)
	at java.lang.System.initializeSystemClass(System.java:1073)

I checked it is reproducible via

bash-4.1# unzip /cvmfs/grid.cern.ch/emi-ui-3.15.3-1_sl6v1/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.35.x86_64/jre/lib/rt.jar
Archive:  /cvmfs/grid.cern.ch/emi-ui-3.15.3-1_sl6v1/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.35.x86_64/jre/lib/rt.jar
  inflating: META-INF/MANIFEST.MF    
  inflating: com/sun/accessibility/internal/resources/accessibility.class  
  inflating: com/sun/accessibility/internal/resources/accessibility_de.class  
  inflating: com/sun/accessibility/internal/resources/accessibility_en.class  
  inflating: com/sun/accessibility/internal/resources/accessibility_es.class  error:  zipfile read error

if issued outside of parrot (for example on lxplus), it works correctly.

Checksum is the same inside and outside parrot:
e991e9cba35544f8a82327ee1232dacd

any Hint?

thanks

tom

**Comment by btovar** [comment]
Tom,

Thank you for your report. We will try to reproduce it shortly.

**Comment by jblomer** [comment]
Hi Ben,

strangely enough I couldn't reproduce it under plain parrot neither under the CernVM docker container with the fuse cvmfs bind-mounted inside.  It seems to occur only under the CernVM docker container when parrot not only serves grid.cern.ch but is also the init process of the docker container.

Cheers,
Jakob

**Comment by btovar** [comment]
Jakob,

I observed the same doing parrot_run bash. I was able to unzip the jar file with no issues. Thank you for pointing us to the docker container!

**Comment by jblomer** [comment]
The latest tar file of the container is here:
http://cernvm.cern.ch/releases/testing/cvm-docker.2.3-0.cernvm.x86_64.tar

It has the #920 fix in.

**Comment by jblomer** [comment]
I'm currently trying to pinpoint this a little further, in particular I'm trying to understand the difference in the two parrot environments (perhaps repository switching?).  I'm happy of course for any hints but just to let you know that I don't want to drop this problem with you just like that.

**Comment by btovar** [comment]
Jakob,

We were able to reproduce it using your docker image. Patrick is looking into it further.

**Comment by batrick** [comment]
@jblomer, I made some small fixes to Parrot in the master branch. I don't think it fixes the problem but it may give us a better idea of what's wrong (in the debug log). Can you update the cernvm image with the new parrot?

**Comment by jblomer** [comment]
Thanks, Patrick!  A new image is available here
http://cernvm.cern.ch/releases/testing/cvm-docker.2.3-1.cernvm.x86_64.tar

**Comment by batrick** [comment]
So here's the problem:

````
2015/09/22 17:14:02.42 parrot_run[1] <child:53> syscall: read
2015/09/22 17:14:02.42 parrot_run[1] <child:53> libcall: read 3 0x7ffdfea6e1c0 8192
2015/09/22 17:14:02.42 parrot_run[1] <child:53> cvmfs: read 1073741824 0x7ffdfea6e1c0 8192 8192
2015/09/22 17:14:02.42 parrot_run[1] <child:53> libcall: = -1 Bad file descriptor [pfs_read]
2015/09/22 17:14:02.42 parrot_run[1] <child:53> syscall: = -9 Bad file descriptor [read]
2015/09/22 17:14:02.42 parrot_run[1] <child:53> syscall: ioctl
2015/09/22 17:14:02.42 parrot_run[1] <child:53> syscall: = 0 [ioctl]
2015/09/22 17:14:02.42 parrot_run[1] <child:53> syscall: write
2015/09/22 17:14:02.42 parrot_run[1] <child:53> debug: fallthrough write(2, 4328448, 27)
2015/09/22 17:14:02.42 parrot_run[1] <child:53> syscall: = 27 [write]
2015/09/22 17:14:02.42 parrot_run[1] <child:53> syscall: exit_group
2015/09/22 17:14:02.42 parrot_run[1] debug: pid 53 received PTRACE_EVENT_EXIT
2015/09/22 17:14:02.42 parrot_run[1] process: pid 53 exited normally with code 3
2015/09/22 17:14:02.42 parrot_run[1] pstree: 53 exit status 3 (33366 syscalls)
````

The `cvmfs_pread` is returning EBADF to us. I don't see an obvious reason for that because the cvmfs fd was never closed. Any ideas?

**Comment by batrick** [comment]
Hmm, I see this between the open of the jar file and the error:

````
2015/09/22 17:14:02.41 parrot_run[1] <child:53> syscall: stat
2015/09/22 17:14:02.41 parrot_run[1] <child:53> libcall: stat /etc/localtime 0x7ffdfea7e170
2015/09/22 17:14:02.41 parrot_run[1] <child:53> resolve: /etc/localtime = /etc/localtime
2015/09/22 17:14:02.41 parrot_run[1] <child:53> local: readlink /etc/localtime 0x7ffdfea7b780 1023
2015/09/22 17:14:02.41 parrot_run[1] <child:53> local: = 29 [readlink]
2015/09/22 17:14:02.41 parrot_run[1] <child:53> resolve: /usr/share/zoneinfo/posix/GMT = /cvmfs/cernvm-prod.cern.ch/cvm3/usr/share/zoneinfo/posix/GMT
2015/09/22 17:14:02.41 parrot_run[1] <child:53> cvmfs: re-activating repository cernvm-prod.cern.ch
2015/09/22 17:14:02.41 parrot_run[1] <child:53> cvmfs: lstat(/cvm3/usr/share/zoneinfo/posix/GMT)
2015/09/22 17:14:02.41 parrot_run[1] <child:53> cvmfs: stat(/cvm3/usr/share/zoneinfo/posix/GMT)
2015/09/22 17:14:02.41 parrot_run[1] <child:53> libcall: = 0 [pfs_stat]
2015/09/22 17:14:02.41 parrot_run[1] <child:53> syscall: = 0 [stat]
````

Looks like that changes the global variable `cvmfs_active_filesystem` in `pfs_service_cvmfs.cc`. I suspect this is causing the problem since the cvmfs fd is associated with the other repository. @btovar?

**Comment by btovar** [comment]
@batrick,
If we do:
cp /cvmfs/grid.cern.ch/emi-ui-3.15.3-1_sl6v1/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.35.x86_64/jre/lib/rt.jar /
unzip rt.jar

Then it works. I think you are right that it is the switch of repositories.

**Comment by btovar** [comment]
Similarly, if I try to unzip a file on the same repository that unzip is. That is, the next works too:
unzip /cvmfs/cernvm-prod.cern.ch/cvm3/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.85.x86_64/lib/sa-jdi.jar

**Comment by btovar** [comment]
@batrick, as you said, it does seem we need to associate file descriptors with repositories. Support for libcmfs <= 1 would be more complicated, though. @jblomer, do you have any input on which version is being used by your users?

**Comment by btovar** [comment]
I was able to reproduce it outside docker:

parrot_run -dall -odebonlyparrot --cvmfs-repo-switching  -M/etc/localtime=/cvmfs/cernvm-prod.cern.ch/cvm3/usr/share/zoneinfo/posix/GMT /cvmfs/cernvm-prod.cern.ch/cvm3/usr/bin/unzip /cvmfs/grid.cern.ch/emi-ui-3.15.3-1_sl6v1/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.35.x86_64/jre/lib/rt.jar

**Comment by jblomer** [comment]
@btovar I don't think there is a need to fix this for libcvmfs 1, I think for repository switching we can require libcvmfs 2.
