### ISSUE TITLE
a tiny logic error of cctools python version check

### ISSUE THREAD

**Issue by hmeng-19** [cooperative-computing-lab/cctools#924]
`./configure` tries to check the python installed on a machine is corrected.
However, when the local machine's python version is 2.6.x, `./configure` still complains the python version is not correct.

    python version is 2.6.6
    checking for /usr/include/python2.6/Python.h...no
    *** skipping python support
    umbrella requires python >= 2.6

**Comment by btovar** [comment]
Mmm,
On opteron:
$ python --version
Python 2.6.6

$ ./configure | grep umbrella
package umbrella found
python version is suitable for umbrella

On which machine did this fail?

**Comment by btovar** [comment]
I think the problem is that the machine you were trying at did not have python-dev installed.

**Comment by btovar** [comment]
Why do we need Python.h though?
