### ISSUE TITLE
Incorrect check for Python.h

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#925]
For swig bindings we ask for python-dev.

umbrella, prune, and weaver use the same check for verifying the python version. If python-dev is not installed, ./configure fails for umbrella, etc., even when these packages do not need it.

Supersedes #924

**Comment by hmeng-19** [comment]
@ben, the failure happens on `vecnet-qa.crc.nd.edu`, (this is a private crc server used by Alex and Rob, two crc folks we recently started to collaborate.)
As you expected, this machine has no python-dev installed.

**Comment by hmeng-19** [comment]
@ben, is it possible to release the checking for `python-dev` if a user only wants to install `umbrella` without `swig`?

**Comment by hmeng-19** [comment]
BTW, it should be `python-devel`, not `python-dev`.
