### ISSUE TITLE
resource_monitor does not redirect > and < from command line.

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#942]
The following fails:

resource_monitor  --  gzip <  file > file.gz

The redirections are not sent to gzip.

**Comment by btovar** [comment]
@nhazekam fyi, this is why your example does not work. For now, try an example that does not use redirection.

**Comment by btovar** [comment]
Redirections from the command line work fine. It seems they only fail from inside work_queue. @nhazekam, can you confirm that --sh fixes the problem within makeflow/work_queue?

**Comment by nhazekam** [comment]
I'll take a look at this. Thanks @btovar

**Comment by btovar** [comment]
The monitor does work with redirection. It seems the problem is how we are internally constructing the command lines.
