### ISSUE TITLE
Project: Makeflow Support for RunC

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#949]
Add a new container mode that supports the `runc` container environment.  I believe this will be superior to docker execution, since the container image can then be a simple image specified as a regular input to makeflow, which is easily moved around via work queue.

**Comment by charleszheng44** [comment]
That is a good idea. running `runc` required `golang` installed. Can we install the `golang` on ccl cluster? I would like to implement `runc

**Comment by dthain** [comment]
See if you can build and install Go in your home directory.  That way you can use it everywhere at ND, not just a few machines.

**Comment by charleszheng44** [comment]
Yes. I have them installed in my $HOME.

**Comment by dthain** [comment]
Closing b/c It seems that singularity fits the use case that we were imagining for runc.
