### ISSUE TITLE
Parrot + Condor problems? 

### ISSUE THREAD

**Issue by tommasoboccali** [cooperative-computing-lab/cctools#951]
Ciao, 
I am trying to set up a uCERNVM image to work with condor.
Often (but not every time), as soon as I start condor, I get

2015/10/07 08:48:51.41 parrot_run[1] child:163 fatal: cannot execute program with personality 2359296
2015/10/07 08:48:51.41 parrot_run[1] child:163 notice: received signal 15 (Terminated), killing all my children...
2015/10/07 08:48:51.41 parrot_run[1] child:163 notice: sending myself 15 (Terminated), goodbye!

the error can be easily via reproduced (when it happens!) via

[root@cmstest ~]# docker run -e CMS_LOCAL_SITE=T2_IT_Pisa -ti tommasoboccali/cmsui_test /init

(it is just last version of Jakob's docker uCERNVM, I put it on dockerhub for faster accessibility)

and then

bash-4.1# mkdir -p /var/log/condor
bash-4.1# service condor start
Starting up Condor... done.
bash-4.1# 2015/10/07 08:54:34.99 parrot_run[1] child:115 fatal: cannot execute program with personality 2359296
2015/10/07 08:54:34.99 parrot_run[1] child:115 notice: received signal 15 (Terminated), killing all my children...
2015/10/07 08:54:34.99 parrot_run[1] child:115 notice: sending myself 15 (Terminated), goodbye!

at first approx, I would like to know what that error means....

thanks a lot!!

tom

**Comment by btovar** [comment]
Tom,

For some reason, parrot thinks that it landed in a machine with the wrong system call "personality" (e.g., a sun machine or bsd). Could this be the case?

@batrick: Checking sys/personality.h, it seems there are a couple of linux cases parrot does not accept (PER_LINUX32 and PER_LINUX32_3GB). Is there a reason for this?

**Comment by dthain** [comment]
It looks to me like we are handling personality too conservatively (or perhaps the system call has changed.)  Only the lower byte indicates the system call personality per se, and the upper bytes indication options.

So personality 2359296 is  0x240000, which is `ADDR_COMPAT_LAYOUT | ADDR_NO_RANDOMIZE | PER_LINUX`

Parrot should just pass that through transparently, since the lower byte is `PER_LINUX`.





Also note that the top byte of the personality toggles several bug-compatibility features without changing the core personality per se.  We should be able to pass those through transparently.

**Comment by tommasoboccali** [comment]
ciao, I could replicate the problem on
- a MAC, using docker tools. Not completely sure which machine the virtual box uses ...
- on a standard linux machine, with

[root@cmstest ~]# uname -a
Linux cmstest.pi.infn.it 2.6.32-431.1.2.el6.x86_64 #1 SMP Fri Dec 13 08:31:15 CET 2013 x86_64 x86_64 x86_64 GNU/Linux
[root@cmstest ~]# cat /etc/issue
Scientific Linux CERN SLC release 6.5 (Carbon)
Kernel \r on an \m

ciao ciao!

**Comment by btovar** [comment]
@batrick, since the solution seems simple, I am taking this one.

**Comment by btovar** [comment]
@tommasoboccali, can you give pr #953 a try?

**Comment by dthain** [comment]
Don't forget `pfs_dispatch64.cc`

**Comment by tommasoboccali** [comment]
ciao, thanks a lot
I need @jblomer  to produce a new image in order to test it, I am forwarding this to him

**Comment by jblomer** [comment]
No problem, is #953 ready for testing?

**Comment by btovar** [comment]
Yes @jblomer (two commits).

**Comment by jblomer** [comment]
[Here](http://cernvm.cern.ch/releases/testing/cvm-docker.2.3-4.cernvm.x86_64.tar) it is.

**Comment by tommasoboccali** [comment]
so, I did a fast test and was NOT able to get the error. As said before, I was not really getting it every time (even if "mostly").
I am optimistic, and I will do ore tests. If you do not hear back, just assume the fix .. fixed.

As always, thanks for the fast response and the patience to my usually very unclear reports ...

tom

**Comment by btovar** [comment]
Excellent, thanks for letting us know!

**Comment by batrick** [comment]
Fixed by #953.
