### ISSUE TITLE
Remove allpairs tpds tree

### ISSUE THREAD

**Issue by batrick** [cooperative-computing-lab/cctools#961]
This tree is kept around for the allpairs tpds paper:

https://github.com/cooperative-computing-lab/cctools/tree/master/allpairs/src.tpds

I think we can safely remove this and just tag an older commit, like 86a174edb6a6d5793f2f4b9f71ba5bdf4202349f.

I use a tag for confuga's ccgrid paper:

https://github.com/cooperative-computing-lab/cctools/tree/papers/confuga-ccgrid2015

**Comment by dthain** [comment]
Unless this is causing some problems, I would like to leave it in. If a paper says "you can find the source here", then we don't want to make it unusually difficult to find...

**Comment by batrick** [comment]
I think the main issue is that it's a maintenance burden. It made sense to keep it around when we were using subversion because users didn't have access to our repository. Now that they can look at the full history, it's easier to point them at a commit/tag. How about a README file in allpairs/src which documents where to look (commit/tag) for the paper's code?

**Comment by dthain** [comment]
Ok, that's acceptable to me.
