### ISSUE TITLE
makeflow does not warn about modes where remote renaming does not work

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#964]
For example, if remote renaming is used with -Tlocal, the rule fails. The rule should not even be tried, and makeflow should exit with an appropriate message.

Rules with remote renaming should only be tried with condor, work queue, and eventually, sandbox.

**Comment by dthain** [comment]
Easy enough to look for in the initial consistency check.

**Comment by btovar** [comment]
@nhazekam: I seem to remember this one to be fixed already?

**Comment by nhazekam** [comment]
@btovar: Yes, this has been addressed. This is addressed in the makeflow function makeflow_check_batch_consistency which primarily checks remote renaming support now.
