### ISSUE TITLE
Cannot Use Wildcard with Master Name in work_queue_pool Config File

### ISSUE THREAD

**Issue by klannon** [cooperative-computing-lab/cctools#971]
Originally noticed by @annawoodard (quoted below...):

>more feedback for @btovar: I might be missing something, but wildcards do not seem to be working for me

>I have two pools going and this one submits workers:
```"master-name": "lobster_resource_monitoring_v1",```
>while this one doesn't:
```"master-name": "lobster_resource_monitoring_v*",```

**Comment by btovar** [comment]
The patterns should be regular expressions. if you add a . before * does it work?

**Comment by klannon** [comment]
Sorry for not responding sooner.  You're right.  Adding a "." before the "*" makes this work.  Sorry if I missed this in the documentation.

**Comment by btovar** [comment]
Excellent, thanks for letting us know.
