### ISSUE TITLE
Should be automatically blacklist slow workers?

### ISSUE THREAD

**Issue by btovar** [cooperative-computing-lab/cctools#975]
That is, if fast abort activates for a worker, I would like to blacklist it too. 

@dthain, @matz-e, @klannon, @annawoodard, @nhazekam, thoughts?

**Comment by dthain** [comment]
No objection here, as long as the blacklist entry has a timeout.
You don't want an inherently-long task to wipe out the whole worker pool...

**Comment by nhazekam** [comment]
In that case, the max retries for the task limits the number of workers that can be blacklisted. I think an interesting way to approach this would be to have the task remember workers it blacklisted, and then if the task hits max retries we reinstate the blacklisted workers.

**Comment by btovar** [comment]
Implemented in #976
