### ISSUE TITLE
docker+ucernvm+parrot+condor

### ISSUE THREAD

**Issue by tommasoboccali** [cooperative-computing-lab/cctools#981]
Ciao, referring here to a htcondor thread (where I was adviced about opening an issue here: https://www-auth.cs.wisc.edu/lists/htcondor-users/2015-October/msg00067.shtml )

So this is the problem: I an trying to run condor inside a uCERNVM under docker, which gets /usr, /bin etc from CVMFS (the usual uno fro @jblomer ). Also condor is not in a local FS, but taken from cvmfs. There is nothing outisde parrot, since before parrot the system is not functional (no /usr, no /bin).

i can start condor, connect to a pool, be visible to external users, and accept jobs.
The problem (if we debugged the logs to a good level), is that at that point condor does not allow to run the payload as root, but wants to move to the user"nobody" (see logs below), using setuid().

In my understanding, that is not allowed by parrot, which traps it and the user remains root. at the next second, condor screams it is still root and closes the job.

I can reproduce the thing in a simplified way:

bash-4.1# su nobody
2015/10/22 13:10:45.68 parrot_run[1] <child:10616> notice: cannot execute the program /bin/su because it is setuid.
bash: /bin/su: Permission denied

even if I copy the /bin/su command to a non cvmfs disk (local), it still fails. I could not really test via the -M parrot option since /bin/su does not exist before parrot (and not even /bin), but I understood the effect is the same as my local test:

bash-4.1# cp /bin/su /root
bash-4.1# /root/su nobody
2015/10/22 13:21:51.96 parrot_run[1] <child:10664> notice: warning: system call 250 (keyctl) not supported for program /root/su

bash-4.1# chmod +s /root/su 
bash-4.1# /root/su nobody
2015/10/22 13:22:03.67 parrot_run[1] <child:10668> notice: cannot execute the program /root/su because it is setuid.
bash: /root/su: Permission denied

I think the basic question is: is there a way to have setuid () (and hence all the command using it, like su and sudo) working inside parrot?

Here is the log which shows how Condor gets the payload and tries to change user:

10/22/15 13:11:26 (fd:15) (pid:10651) (D_ALWAYS) Using wrapper /root/condor_job_wrapper.sh to exec /home/glidein_pilot/dir_10651/condor_exec.exe -a sandbox.tar.gz --sourceURL=https://cmsweb.cern.ch/crabcache --jobNumber=15 --cmsswVersion=CMSSW_7_3_5_patch2 --scramArch=slc6_amd64_gcc491 --inputFile=job_input_file_list_15.txt --runAndLumis=job_lumis_15.json --lheInputFiles=False --firstEvent=None --firstLumi=None --lastEvent=None --firstRun=None --seeding=AutomaticSeeding --scriptExe=None --eventsPerLumi=None --scriptArgs=[] -o {}
10/22/15 13:11:26 (fd:15) (pid:10651) (D_ALWAYS) Setting job's virtual memory rlimit to 0 megabytes
10/22/15 13:11:26 (fd:15) (pid:10651) (D_CONFIG) ENFORCE_CPU_AFFINITY is undefined, using default value of False
10/22/15 13:11:26 (fd:15) (pid:10651) (D_ALWAYS) Running job as user nobody
10/22/15 13:11:26 (fd:15) (pid:10651) (D_PRIV) PRIV_USER --> PRIV_CONDOR at /slots/01/dir_57518/userdir/src/condor_starter.V6.1/os_proc.cpp:529
10/22/15 13:11:26 (fd:15) (pid:10651) (D_DAEMONCORE) In DaemonCore::Create_Process(/root/condor_job_wrapper.sh,...)
10/22/15 13:11:26 (fd:17) (pid:10651) (D_PRIV) PRIV_CONDOR --> PRIV_USER at /slots/01/dir_57518/userdir/src/condor_daemon_core.V6/daemon_core.cpp:7260
10/22/15 13:11:26 (fd:17) (pid:10651) (D_PRIV) PRIV_USER --> PRIV_CONDOR at /slots/01/dir_57518/userdir/src/condor_daemon_core.V6/daemon_core.cpp:7282
10/22/15 13:11:26 (fd:17) (pid:10660) (D_DAEMONCORE) Create_Process: Arg: condor_exec.exe /home/glidein_pilot/dir_10651/condor_exec.exe -a sandbox.tar.gz --sourceURL=https://cmsweb.cern.ch/crabcache --jobNumber=15 --cmsswVersion=CMSSW_7_3_5_patch2 --scramArch=slc6_amd64_gcc491 --inputFile=job_input_file_list_15.txt --runAndLumis=job_lumis_15.json --lheInputFiles=False --firstEvent=None --firstLumi=None --lastEvent=None --firstRun=None --seeding=AutomaticSeeding --scriptExe=None --eventsPerLumi=None --scriptArgs=[] -o {}
10/22/15 13:11:26 (fd:17) (pid:10660) (D_PROCFAMILY) About to register family for PID 10660 with the ProcD
10/22/15 13:11:26 (fd:17) (pid:10660) (D_PROCFAMILY) Result of "register_subfamily" operation from ProcD: SUCCESS
10/22/15 13:11:26 (fd:17) (pid:10660) (D_PROCFAMILY) About to tell ProcD to track family with root 10660 via environment
10/22/15 13:11:26 (fd:17) (pid:10660) (D_PROCFAMILY) Result of "track_family_via_environment" operation from ProcD: SUCCESS
10/22/15 13:11:26 (fd:17) (pid:10660) (D_DAEMONCORE) Re-mapping std(in|out|err) in child.
10/22/15 13:11:26 (fd:17) (pid:10660) (D_DAEMONCORE) calling nice(10)
10/22/15 13:11:26 (fd:17) (pid:10660) (D_DAEMONCORE) Printing fds to inherit: 
10/22/15 13:11:26 (fd:17) (pid:10660) (D_DAEMONCORE) About to exec "/root/condor_job_wrapper.sh"
10/22/15 13:11:27 (fd:20) (pid:10651) (D_ALWAYS) Create_Process(/root/condor_job_wrapper.sh): child failed because PRIV_USER_FINAL process was still root before exec()
10/22/15 13:11:27 (fd:17) (pid:10651) (D_DAEMONCORE) Warning: cleanup from Create_Process took 0.693 sec, Create_Process took 0.693 sec overall
10/22/15 13:11:27 (fd:12) (pid:10651) (D_SYSCALLS) Doing CONDOR_ulog
10/22/15 13:11:27 (fd:12) (pid:10651) (D_NETWORK) condor_write(fd=9 <128.142.242.250:4080>,,size=755,timeout=300,flags=0)
10/22/15 13:11:27 (fd:12) (pid:10651) (D_ALWAYS) Create_Process(/root/condor_job_wrapper.sh,/home/glidein_pilot/dir_10651/condor_exec.exe -a sandbox.tar.gz --sourceURL=https://cmsweb.cern.ch/crabcache --jobNumber=15 --cmsswVersion=CMSSW_7_3_5_patch2 --scramArch=slc6_amd64_gcc491 --inputFile=job_input_file_list_15.txt --runAndLumis=job_lumis_15.json --lheInputFiles=False --firstEvent=None --firstLumi=None --lastEvent=None --firstRun=None --seeding=AutomaticSeeding --scriptExe=None --eventsPerLumi=None --scriptArgs=[] -o {}, ...) failed: (errno=666666: 'Unknown error 666666')
10/22/15 13:11:27 (fd:12) (pid:10651) (D_ALWAYS) Failed to start job, exiting

thanks a lot

tommaso

**Comment by batrick** [comment]
Parrot has always turned `setuid` into a no-op. So when HTCondor checks that `setuid` actually changed the uid, it fails.

One of the issues with allowing `setuid` is that it complicates signal handling and access control in Parrot (the tracee may no longer be the same uid as Parrot). I don't think the fix is as simple as turning the system call back on. What do you think @dthain?

**Comment by dthain** [comment]
Aha, I didn't understand that you were trying to run the whole condor stack on top of parrot.  This isn't what we recommend, and it may not work in the long run.  I would be more optimistic about an approach in which condor gets loaded and run first, and then uses parrot to run the job.

That said, I think there is a simple step that we can take that *might* address the setuid issue and get things working.  What we are going to do is add a`--fake-setuid` option to Parrot, such that when condor attempts to `setuid`, parrot will allow it, track the uid, and report it back to the application.  Of course, the application will not *actually* change userid, everything will still be running as root.  But, it might work just well enough to get a job running.

Let us know if that sounds ok.

@trshaffer please work on this one, what you need to do is adjust `pfs_dispatch.cc` and `pfs_dispatch64.cc` so that `setuid` and related calls modify `pfs_uid` and `pfs_gid`, then test it with some simple C applications to see how that goes.

**Comment by jblomer** [comment]
For this particular issue, do you think there is a chance to patch condor to optionally allow root for payload?

Btw, I think the `--fake-setuid` option would be very helpful anyway

**Comment by tommasoboccali** [comment]
ciao! Yes, condor lives in parrot, as all the rest.

I will be happy to test your fix (provided @jblomer builds a ucernvm from that, which I am sure he will!)

thanks a lot

tom

**Comment by dthain** [comment]
@jblomer the htcondor folks are not comfortable with jobs that run as root, and htcondor goes to great lengths to prevent that.  I think it's unlikely you will convince them otherwise.  However, htcondor can run itself (and the job) as an ordinary user, and I think that's likely to be a more fruitful approach.  (But it will still require the ability to su within parrot.)

**Comment by tommasoboccali** [comment]
i think generally they are correct (in not wanting that). In this precise case "root" is a "root" inside a parrot inside a docker ... so not much harm can be done. Still, I see their point in preventing me: I could run 2 payloads from 2 different users, and it is not nice one sees the other ...
So what we have here is a root--, but somehow still a root.

**Comment by bbockelm** [comment]
Root inside a docker container is widely considered to root outside a docker container (given the rate of CVE's on the subject).

Is there no ability to have a shim within the ucernvm that builds the environment then drops privs?  Can we revisit why parrot has to be run as root in the first place?

**Comment by tommasoboccali** [comment]
ciao Brian.
Since we want to use uCERNVM, there is no way NOT to be root.
/usr, /bin etc are linked to CVMFS, and hence the process preparing the system needs to run 
- under parrot (since it needs to copy/link from cvmfs to local fs)
- as root (in order to touch as said /usr etc)

the only way out I can see would be to have a completely different approach, in which /usr and the rest are in the container .... but that would be nome uCERNVM...

tom

**Comment by tommasoboccali** [comment]
ciao I see commits ;)
are we already at the point where @jblomer can try and build a container over them?

thanks

tom

**Comment by dthain** [comment]
Almost but not quite!  We will let you know...

**Comment by batrick** [comment]
@tommasoboccali have you resolved this problem? I think you ended up moving Condor out of Parrot in your stack right?

**Comment by tommasoboccali** [comment]
ciao @batrick , yes it works.
Still, that needs a container image @ 500 MB instead of the 30 MB of uCERNVM.
So I would still be interested in solving the issue described here.

ciao

**Comment by batrick** [comment]
@tommasoboccali well, #997 is merged so you can give that a try if you want.

**Comment by tommasoboccali** [comment]
thanks!
@jblomer , can you produce a tar with that?
I can take care on changing /init inside to use the new option, but I cannot produce a new tar :(

thanks a lot

tom

**Comment by jblomer** [comment]
@tom: please find a new tar here:
http://cernvm.cern.ch/releases/testing/ucernvm.2.4-5.cernvm.x86_64.tar

It comes with a new `parrot_run` binary but with an unmodified /init.  Could you send me the necessary modifications to the init script?

**Comment by tommasoboccali** [comment]
setting up the environment to check it now (I must confess I forgot a lot of stuff in the meantime ....)

**Comment by tommasoboccali** [comment]
@jblomer 
it does not seem correct tar file: it just contains kernel and initdr ... for example no /init ....

where am I wrong?

[root@cmstest ~]# tar xvf ucernvm.2.4-5.cernvm.x86_64.tar 
apply
initrd.2.4-5.cernvm.x86_64
vmlinuz-4.1.13-8.cernvm.x86_64.xz

**Comment by jblomer** [comment]
@tommasoboccali sorry, here's the correct link:
http://cernvm.cern.ch/releases/testing/cvm-docker.2.4-5.cernvm.x86_64.tar

**Comment by tommasoboccali** [comment]
uhm, not still completely sure, but
- a simple sleep jobs seem to work
- I get a 0 sized .err and a correct .ut on the submitting host

[tboccali@vocms058 out]$ cat sleep.out.54648.7
I slept for 300 seconds on:
6e66b50cf2ea
Tue Nov 24 15:32:08 GMT 2015

- condor seems to say the jobs are DONE:

[tboccali@vocms058 out]$ condor_history 54648.3
 ID     OWNER          SUBMITTED   RUN_TIME     ST COMPLETED   CMD            
54648.3   tboccali       11/24 16:16   0+00:05:27 C  11/24 16:26 /tmp/tboccali/sleep.sh 300

- still , the logs seem full of 

11/24/15 15:37:34 (pid:794) Job 54649.1 set to execute immediately
11/24/15 15:37:34 (pid:794) Starting a VANILLA universe job with ID: 54649.1
11/24/15 15:37:34 (pid:794) IWD: /home/glidein_pilot/dir_794
11/24/15 15:37:34 (pid:794) passwd_cache: initgroups() failed! errno=Operation not permitted
11/24/15 15:37:34 (pid:794) Failed to cache info for user nobody
11/24/15 15:37:34 (pid:794) passwd_cache: num_groups( nobody ) returned -1
11/24/15 15:37:34 (pid:794) set_user_egid - ERROR: initgroups(nobody, 99) failed, errno: Operation not permitted
11/24/15 15:37:34 (pid:794) Output file: /home/glidein_pilot/dir_794/_condor_stdout
11/24/15 15:37:34 (pid:794) Error file: /home/glidein_pilot/dir_794/_condor_stderr
11/24/15 15:37:34 (pid:794) Using wrapper /root/condor_job_wrapper.sh to exec /home/glidein_pilot/dir_794/condor_exec.exe 300
11/24/15 15:37:34 (pid:794) Setting job's virtual memory rlimit to 0 megabytes
11/24/15 15:37:34 (pid:794) Running job as user nobody
11/24/15 15:37:34 (pid:794) passwd_cache: initgroups() failed! errno=Operation not permitted
11/24/15 15:37:34 (pid:794) Failed to cache info for user nobody
11/24/15 15:37:34 (pid:794) passwd_cache: num_groups( nobody ) returned -1
11/24/15 15:37:34 (pid:794) set_user_egid - ERROR: initgroups(nobody, 99) failed, errno: Operation not permitted
11/24/15 15:37:35 (pid:794) Create_Process succeeded, pid=804
11/24/15 15:37:35 (pid:794) Unable to write into oom_adj file for the starter: (errno=13, Permission denied)
11/24/15 15:37:44 (pid:794) passwd_cache: initgroups() failed! errno=Operation not permitted
11/24/15 15:37:44 (pid:794) Failed to cache info for user nobody

does not seem really to harm..
So I would conclude first tests are fine, next step is to run a CMS job and see what happens

**Comment by tommasoboccali** [comment]
I am having an harder time with CMS jobs.
Are these errors expected when using fake-setuid?

bash-4.1# su - nobody
2015/11/24 17:32:07.89 parrot_run[1] <child:768> notice: warning: system call 250 (keyctl) not supported for program /bin/su
2015/11/24 17:32:07.89 parrot_run[1] <child:768> notice: warning: system call 250 (keyctl) not supported for program /bin/su
su: cannot set groups
bash-4.1# id
uid=0(root) gid=0(root)id: failed to get groups for the current process: Operation not permitted


I was assuming su would have "fakely worked", but does not seem the case

Parrot has been launched as:

 /UCVM/parrot_run --fake-setuid --mount=/bin=/cvmfs/cernvm-prod.cern.ch/cvm3/bin --mount=/lib=/cvmfs/cernvm-prod.cern.ch/cvm3/lib --mount=/lib64=/cvmfs/cernvm-prod.cern.ch/cvm3/lib64  .....

tom

**Comment by batrick** [comment]
Yes, supplemental groups are not supported in fake-setuid. We were not sure it would be necessary. It looks like Condor runs the job with some logged errors from `setgroups`. Do your CMS jobs fail because of `su`?

**Comment by tommasoboccali** [comment]
a good question, not easy to answer.
indeed, if i run the SAME script as plain root, it works. it does not when
inside the fake-setuid (so thinking it is another user). I need to debug
with crab experts, but i think the problem is there.
also i see a strange error which seems to be causing the crash when running
inside fake...

awk: fatal: could not find groups: Operation not permitted


does it help ? searching on google I could not find a lot, bue seems really
related to new id-gid ...

tom


On Tue, Nov 24, 2015 at 7:11 PM, Patrick Donnelly <notifications@github.com>
wrote:

> Yes, supplemental groups are not supported in fake-setuid. We were not
> sure it would be necessary. It looks like Condor runs the job with some
> logged errors from setgroups. Do your CMS jobs fail because of su?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cooperative-computing-lab/cctools/issues/981#issuecomment-159359715>
> .
>



-- 
Tommaso Boccali
INFN Pisa

**Comment by batrick** [comment]
@tommasoboccali, sorry for the delay in response. I have created an issue for this, #1063. We will try to solve this for you soon.

**Comment by batrick** [comment]
@tommasoboccali, @jblomer try the new master with #1067 at your leisure.

**Comment by jblomer** [comment]
@batrick: many thanks!
@tommasoboccali: new image is [here](http://cernvm.cern.ch/releases/testing/cvm-docker.2.4-6.cernvm.x86_64.tar)

**Comment by tommasoboccali** [comment]
on it asap (sorry, busy times :(
)

tom

On Tue, Dec 15, 2015 at 10:45 AM, jblomer <notifications@github.com> wrote:

> @batrick <https://github.com/batrick>: many thanks!
> @tommasoboccali <https://github.com/tommasoboccali>: new image is here
> <http://cernvm.cern.ch/releases/testing/cvm-docker.2.4-6.cernvm.x86_64.tar>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cooperative-computing-lab/cctools/issues/981#issuecomment-164704453>
> .
>



-- 
Tommaso Boccali
INFN Pisa

**Comment by tommasoboccali** [comment]
and the winner is ... US ;)
exec summary:

-rw-r--r--  1 root root 2075266 Dec 15 14:33 output.root and logs:

...
Begin processing the 3395th record. Run 1, Event 293845, LumiSection 672542 at 15-Dec-2015 14:46:18.861 GMT
...


if I get a root file produced by CMS everything must have been ok ....

Investigating more, but you probably did it!

tom

**Comment by batrick** [comment]
Great @tommasoboccali! I'll close this issue. Please make a new one if you have anymore trouble.

**Comment by dthain** [comment]
Great work, everyone!
