### ISSUE TITLE
Parrot dying due to file descriptors?

### ISSUE THREAD

**Issue by matz-e** [cooperative-computing-lab/cctools#986]
I'm currently seeing this error going by running parrot via WQ.  Haven't been able to easily reproduce it so far:
```
2015/10/23 10:13:27.87 parrot_run[4282] <child:5545> fatal: fd 24 is not an open parrotfd
2015/10/23 10:13:27.87 parrot_run[4282] <child:5545> notice: received signal 15 (Terminated), killing all my children...
2015/10/23 10:13:27.87 parrot_run[4282] <child:5545> notice: sending myself 15 (Terminated), goodbye!
```
and
```
2015/10/23 09:55:42.33 parrot_run[62014] <child:62504> fatal: fd 21 is not an open parrotfd
2015/10/23 09:55:42.33 parrot_run[62014] <child:62504> notice: received signal 15 (Terminated), killing all my children...
2015/10/23 09:55:42.33 parrot_run[62014] <child:62504> notice: sending myself 15 (Terminated), goodbye!
```
Any ideas why parrot crashes?

**Comment by batrick** [comment]
@matz-e, I will need to see more of the debug log (`-d all` would be most helpful) to diagnose this or a way to reproduce.

**Comment by batrick** [comment]
@matz-e I believe I figured out the problem. I'll make a patch and hopefully that will resolve this.

**Comment by batrick** [comment]
For the record, this is reproducible using `chromium --no-sandbox`. This can only occur with threaded applications.

**Comment by batrick** [comment]
@btovar can you get #989 into the branch @matz-e is using?

**Comment by matz-e** [comment]
Thanks!
