### ISSUE TITLE
batch_job in makeflow vs work_queue

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#995]
The more I work with the code, the more it seems to me that batch_job doesn't really fit within the work_queue module.  Would it make more sense to put it into makeflow?  is there a better way to disentangle our dependencies?

I think these are the essential parts:

```
batch_job -> batch_job_work_queue -> libwork_queue.a
work_queue_pool -> batch_job
makeflow -> batch_job
```

**Comment by btovar** [comment]
The nice thing of having it in libwork_queue is that allpairs and wavefront only get one dependency.

When I moved work_queue from dttools, I originally had a batch library, but at that time it seem overkill. Having batch as part of makeflow makes the dependencies for work_queue_pool ugly. 

I would leave it as it is, or create a new library. A better option would be to have batch as part of dttools, but this creates a circular dependency with work queue.

**Comment by dthain** [comment]
To summarize:
- keeping it in work_queue is awkward but works.
- moving it to dttools is out, since that would create a circular dependency.
- moving it to makeflow could work, but then work_queue_pool (though not the rest of wq) would depend upon makeflow
- moving it to a distinct module would work but would add a new dependency to some modules.

Did I get that right?

**Comment by btovar** [comment]
Correct.

Also, allpairs and wavefront would depend on makeflow.

**Comment by dthain** [comment]
See #1048
